### ISSUE TITLE
NTR: central conducting lymphatic anomaly 

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#1000]
Def: A lymphatic disease involved in dysfunction of the thoracic  duct (TD) or cisterna chyli, leading to a retrograde flux of lymphatic fluid or abnormal drainage of lymphatic fluid.   Symptoms can include fluid build-up in and around the lungs, around the heart, in the abdomen and in the feet and legs. CCLA can also affect the bones.  PMID:31263281  https://www.lgda.eu/complex-lymphatic-anomalies/central-conducting-lymphatic-anomaly/

Is_a DOID:75 lymphatic system disease

**Comment by lschriml** [comment]
I am working on this issue, doing a review of the terms in this area of the ontology.
Much appreciated,
Lynn

**Comment by lschriml** [comment]
Added to DO: DOID:0081030

Notes: 
CCLA, on the other hand, describes dysfunction of the thoracic duct (TD) or cisterna chyli, leading to a retrograde flux of lymphatic fluid or abnormal drainage of lymphatic fluid

- a lymphatic disease (DOID:75)

- Central conducting lymphatic anomaly (CCLA) is one of the complex lymphatic anomalies characterized by dilated lymphatic channels, lymphatic channel dysmotility and distal obstruction affecting lymphatic drainage.
- https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC7190898/
- 
- CCLA was classified as channel-type lymphatic malformation (17) by the International Society for the Study of Vascular Anomalies (ISSVA), 

this is OMIM:617300       LYMPHATIC MALFORMATION 7
       synonym: CENTRAL CONDUCTION LYMPHATIC ANOMALY

- heterozygous mutation in the EPHB4 gene (600011) on chromosome 7q22.
- an autosomal dominant disorder with variable expressivity. Some patients may develop severe nonimmune lymphatic-related hydrops fetalis (LRHF) in utero, resulting in early death, whereas others may have milder manifestations, such as atrial septal defect (ASD) or varicose veins as adults.
