### ISSUE TITLE
review neuronal ceroid lipofuscinosis terms

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#1001]
Recently OMIM is updating/ adding new terms for neuronal ceroid lipofuscinosis (NCL). Therefore existing NCL terms found in DO ontology start to differ more and more from OMIM. F.e. [neuronal ceroid lipofuscinosis 4A] (DOID:0110730) is now called at OMIM [Ceroid lipofuscinosis, neuronal, 6B (Kufs type)]  In OMIM:204300, OMIM cites a new paper from 2021: a review of NCLs. (PMID:34733232)

Please consider a review of NCL terms.

Thank you!

**Comment by lschriml** [comment]
Hello Marek,
Thank you foe sending the update request.
Yes, we will review the changes at OMIM and update the DO !!
Cheers,
Lynn

**Comment by lschriml** [comment]
PS256730 phenotypic series
DO has 1-11 and 13.

Changes:
DO:                                                        OMIM:
4A                           OMIM:204300. is now 6B
4B                           OMIM:162350, is now 4
6                              OMIM:601780, is now 6A

New term: 
CEROID LIPOFUSCINOSIS, NEURONAL, 14
in OMIM: progressive myoclonic epilepsy-3 with or without intracellular inclusions
OMIM:611726

**Comment by lschriml** [comment]
These terms have been updated in the DO. 
neuronal ceroid lipofuscinosis 
     4A.  DOID:0110730 was OMIM:204300.  --> 6B, the OMIM ID is representing the same gene, variant, phenotype
                 --> updating the name of the disease to 6B, editing definition of phenotypes

     4B DOID:0110720 OMIM:162350, is now 4, updated disease name, added synonym 
                          --> represents the same gene, variant

     6 DOID:0110729. OMIM:601780, is now 6A --> representing the same gene, variant, with revised phenotypes.
            --> updated the disease name and definition
