### ISSUE TITLE
review previous SNOMED releases, xrefs

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#1002]
To review xrefs from previous releases

**Comment by allenbaron** [comment]
There are 44 xrefs to previous releases of SNOMED. They are listed in their entirety below and in this file: [SNOMED_xrefs-pre_2021_09.csv](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/7810147/SNOMED_xrefs-pre_2021_09.csv)

## 2018_03_01
- [ ] DOID:0040098 | pemphigus gestationis | SNOMEDCT_US_2018_03_01:86081009
- [ ] DOID:0070314 | obstructive nephropathy | SNOMEDCT_US_2018_03_01:86249007
- [ ] DOID:0070315 | hypoplastic right heart syndrome | SNOMEDCT_US_2018_03_01:268180007
- [ ] DOID:0111833 | X-linked spinocerebellar ataxia 5 | SNOMEDCT_US_2018_03_01:766818009

## 2019_09_01
- [ ] DOID:0060135 | apraxia | SNOMEDCT_US_2019_09_01:68345001
- [ ] DOID:0060467 | humeroradial synostosis | SNOMEDCT_US_2019_09_01:205329008
- [ ] DOID:0070324 | systemic Epstein-Barr virus-positive T-cell lymphoma of childhood | SNOMEDCT_US_2019_09_01:450906003
- [ ] DOID:0070327 | melanoma in congenital melanocytic nevus | SNOMEDCT_US_2019_09_01:75931002
- [ ] DOID:0080316 | megalencephalic leukoencephalopathy with subcortical cysts 1 | SNOMEDCT_US_2019_09_01:703536004
- [ ] DOID:684 | hepatocellular carcinoma | SNOMEDCT_US_2019_09_01:109841003
- [ ] DOID:7234 | mucinous cystadenocarcinoma of the pancreas | SNOMEDCT_US_2019_09_01:785879009

## 2020_03_01
- [ ] DOID:0040085 | bacterial sepsis | SNOMEDCT_US_2020_03_01:10001005
- [ ] DOID:0050144 | Kartagener syndrome | SNOMEDCT_US_2020_03_01:42402006
- [ ] DOID:0050462 | Antley-Bixler syndrome | SNOMEDCT_US_2020_03_01:62964007
- [ ] DOID:0050741 | alcohol dependence | SNOMEDCT_US_2020_03_01:66590003
- [ ] DOID:0070167 | spermatogenic failure 6 | SNOMEDCT_US_2020_03_01:236818008
- [ ] DOID:0070183 | spermatogenic failure 5 | SNOMEDCT_US_2020_03_01:236806004
- [ ] DOID:0070230 | benign recurrent intrahepatic cholestasis | SNOMEDCT_US_2020_03_01:31155007
- [ ] DOID:0070313 | thiamine deficiency disease | SNOMEDCT_US_2020_03_01:399357009
- [ ] DOID:0070317 | wet beriberi | SNOMEDCT_US_2020_03_01:67360000
- [ ] DOID:0070319 | miliaria pustulosa | SNOMEDCT_US_2020_03_01:26988005
- [ ] DOID:0080617 | lymph node benign neoplasm | SNOMEDCT_US_2020_03_01:92197001
- [ ] DOID:0110827 | Usher syndrome type 2 | SNOMEDCT_US_2020_03_01:232058008
- [ ] DOID:0111572 | familial woolly hair syndrome | SNOMEDCT_US_2020_03_01:52564001
- [ ] DOID:0111594 | distal arthrogryposis type 5D | SNOMEDCT_US_2020_03_01:773396009
- [ ] DOID:0111596 | distal arthrogryposis type 1 | SNOMEDCT_US_2020_03_01:715314008
- [ ] DOID:0111599 | distal arthrogryposis type 2B | SNOMEDCT_US_2020_03_01:715216008
- [ ] DOID:0111603 | distal arthrogryposis type 7 | SNOMEDCT_US_2020_03_01:8757006
- [ ] DOID:0111604 | Freeman-Sheldon syndrome | SNOMEDCT_US_2020_03_01:205799002
- [ ] DOID:0111607 | distal arthrogryposis type 3 | SNOMEDCT_US_2020_03_01:237850008
- [ ] DOID:0111608 | distal arthrogryposis type 5 | SNOMEDCT_US_2020_03_01:715217004
- [ ] DOID:0111609 | distal arthrogryposis type 6 | SNOMEDCT_US_2020_03_01:720515009
- [ ] DOID:0111610 | distal arthrogryposis type 4 | SNOMEDCT_US_2020_03_01:715575001
- [ ] DOID:0111808 | linear skin defects with multiple congenital anomalies 1 | SNOMEDCT_US_2020_03_01:721879006
- [ ] DOID:0111831 | X-linked spinocerebellar ataxia 3 | SNOMEDCT_US_2020_03_01:719817002
- [ ] DOID:0111832 | X-linked spinocerebellar ataxia 4 | SNOMEDCT_US_2020_03_01:719818007
- [ ] DOID:0111947 | immunodeficiency 21 | SNOMEDCT_US_2020_03_01:778024005
- [ ] DOID:1339 | Diamond-Blackfan anemia | SNOMEDCT_US_2020_03_01:188588001
- [ ] DOID:2426 | gangliocytoma | SNOMEDCT_US_2020_03_01:78268004
- [ ] DOID:2632 | papillary serous adenocarcinoma | SNOMEDCT_US_2020_03_01:716649003
- [ ] DOID:2960 | photosensitive trichothiodystrophy | SNOMEDCT_US_2020_03_01:723551003
- [ ] DOID:3318 | epithelioid type angiomyolipoma | SNOMEDCT_US_2020_03_01:733836008

## 2020_09_01
- [ ] DOID:0070318 | dry beriberi | SNOMEDCT_US_2020_09_01:71021002
- [ ] DOID:0070321 | miliaria crystallina | SNOMEDCT_US_2020_09_01:44279002

**Comment by lschriml** [comment]
Review completed for:
2018_03_01, 2019_09_01 and 2020_09_01 --> updated IDs to the 2021_09_01 US version

**Comment by lschriml** [comment]
further review needed:
[no longer in SNOMED]
DOID:1339 | Diamond-Blackfan anemia | SNOMEDCT_US_2020_03_01:188588001
distal arthrogryposis type 7 
familial woolly hair syndrome
immunodeficiency 21.   
spermatogenic failure 6  --> also SNOMED has reassigned the ID

**Comment by lschriml** [comment]
removed SNOMED CT ID for:
Diamond-Blackfan anemia
distal arthrogryposis type 7
familial woolly hair syndrome
immunodeficiency 21
spermatogenic failure 6
