### ISSUE TITLE
Remove 'M' from ICDO xref codes

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1003]
14 ICD-O xrefs have codes that start with "M" (for morphology). These "M"s should probably be removed since they aren't part of the ICD-O codes.

- [ ] DOID:162 | cancer | ICDO:M8000/3
- [ ] DOID:0080531 | dedifferentiated liposarcoma | ICDO:M8858/3
- [ ] DOID:0070323 | childhood acute myeloid leukemia | ICDO:M9861/3
- [ ] DOID:769 | neuroblastoma | ICDO:M9500/3
- [ ] DOID:687 | hepatoblastoma | ICDO:M8970/3
- [ ] DOID:3070 | high grade glioma | ICDO:M9380/3
- [ ] DOID:3069 | malignant astrocytoma | ICDO:M9400/3
- [ ] DOID:3565 | meningioma | ICDO:M9530/3
- [ ] DOID:0070327 | melanoma in congenital melanocytic nevus | ICDO:M8761/3
- [ ] DOID:5016 | hepatocellular clear cell carcinoma | ICDO:M8174/3
- [ ] DOID:0080347 | malignant pheochromocytoma | ICDO:M8700/3
- [ ] DOID:5563 | malignant teratoma | ICDO:M9080/3
- [ ] DOID:2154 | nephroblastoma | ICDO:M8960/3
- [ ] DOID:684 | hepatocellular carcinoma | ICDO:M8170/3

**Comment by lschriml** [comment]
Loaded ICDO exact matches, had to do some cleanup of duplicate entries, so cleaned up the rest of the M cases. 
Cheers,
Lynn
