### ISSUE TITLE
Review synonyms that match a different term's label/synonym

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1010]
The following exact synonyms match a _different_ term's preferred label and need review:

- [ ] DOID:3565 (meningioma), exact synonym "supratentorial meningioma" **is the superclass of** DOID:0080843, preferred "supratentorial meningioma"
- [ ] DOID:3999 (Bartholin's gland carcinoma), exact synonym "Bartholin's gland cancer" **is an inferred subclass of** DOID:60003, preferred "Bartholin's gland cancer"
- [ ] DOID:4866 (salivary gland adenoid cystic carcinoma), exact synonym "adenoid cystic carcinoma" **matches but has no existing defined relationship with** DOID:0080202, preferred "adenoid cystic carcinoma"
- [ ] DOID:6726 (fibrillary astrocytoma), exact synonym "diffuse astrocytoma" **matches but has no existing defined relationship with** DOID:4857, preferred "diffuse astrocytoma"

</br>

These terms have the same exact synonym:

- [ ] DOID:9538 (multiple myeloma), exact synonym "plasma cell myeloma" **is the superclass of** DOID:9550 (indolent plasma cell myeloma), exact synonym "plasma cell myeloma"

</br>
If these synonyms are to be kept we should add them to a new document in this repository noting why they were retained for future reference and evaluation by others.

**Comment by lschriml** [comment]
I have removed the redundant synonyms

There is a not a direct way, as far as I can determine, to make an EQ for adenoid cystic carcinoma. 

Cheers,
Lynn
