### ISSUE TITLE
New Term Request: Frontonasal dysplasia 3 (FND3)

### ISSUE THREAD

**Issue by LeylaR** [DiseaseOntology/HumanDiseaseOntology#1014]
Could you please add Frontonasal dysplasia 3 (FND3) to the DO? 

OMIM ID : 613456

References associated with the OMIM Entry that describe the disease:
PMID 20451171
PMID 27324866
Additional references:
PMID 32914578 (includes zebrafish model)
PMID 35127681 (mouse model)

Review of Frontonasal Dysplasias:  
PMID 27920634

FND3 is associated with mutations in the ALX1 gene. There are 2 other frontonasal dysplasia terms involving ALX genes in OMIM:
FND1 (associated with ALX3) OMIM:136760
FND2 (associated with ALX4) OMIM:613451

**Comment by lschriml** [comment]
I have added the three disease terms to the DO.

Cheers,
Lynn
