### ISSUE TITLE
new Disease term: Hereditary alpha tryptasemia syndrome

### ISSUE THREAD

**Issue by Xenbase2** [DiseaseOntology/HumanDiseaseOntology#1015]
NEW DO term request: Hereditary alpha tryptasemia syndrome (HATS)
gene:TPSAB1 (https://www.ncbi.nlm.nih.gov/gtr/genes/7177/)

https://rarediseases.info.nih.gov/diseases/13193/hereditary-alpha-tryptasemia-syndrome

suggested Definition: a congenital mast cell disease caused by extra copies of the alpha tryptase gene, TPSAB1, which leads to increased blood levels of trypase, in turn effecting multiple organ systems including skin and connective tissues, the gastrointestinal and cardiovascular systems.

is caused by a gene duplication
is a mast cell disease

References
Hereditary Alpha Tryptasemia and Hereditary Alpha Tryptasemia Syndrome FAQ. National Institute of Allergy and Infectious Diseases. October 17, 2016; https://www.niaid.nih.gov/research/hereditary-alpha-tryptasemia-faq.

Lyons JJ & cols. Elevated basal serum tryptase identifies a multisystem disorder associated with increased TPSAB1 copy number. Nat Genet. December, 2016; 48(12):564-1569. https://www.ncbi.nlm.nih.gov/pubmed/27749843.

thanks

Christina James-Zorn
Xenbase
xenbase@cchmc.org

**Comment by lschriml** [comment]
Hello Christina,
Thank you for submitting this new term request !!
   I have added the new references to this term, DOID:0080714
   And added an axiom for : (derives_from some 'mast cell')

Cheers,
Lynn
