### ISSUE TITLE
tumor-associated endothelial cells (TECs)

### ISSUE THREAD

**Issue by ANiknejad** [DiseaseOntology/HumanDiseaseOntology#1016]
Hello DO team,

I am wondering if Disease Ontology may be the place where to have an identifier for these cells, because currently none ontology (as far as I can see) reports these cells. Even if those cells are not stricto sensu cancer cells, they are not normal, and I was somehow expecting TECs would be in the CCL, the cancer cell  ontology but again, as far as I can check, this is not the case
https://github.com/LucasSerra1/CCL

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6509834/

Tumor-associated endothelial cells may be described as part of the tumor-associated vasculature, available in NCI Thesaurus
https://ncithesaurus.nci.nih.gov/ncitbrowser/
Tumor-Associated Vasculature (Code C12968)
and also as part of Tumor Microenvironment (Code C94498)

here 2 recents articles involving TECs
https://pubmed.ncbi.nlm.nih.gov/31935371/

https://pubmed.ncbi.nlm.nih.gov/30800123/

Thank you in advance for your advice.
best regards,

Anne

https://orcid.org/0000-0003-3308-6245

Anne Niknejad

Senior biocurator
https://bgee.org/
SIB | Swiss Institute of Bioinformatics
Unil, Department of Ecology and Evolution - Quartier Sorge, bâtiment Biophore - 1015 Lausanne
t: +41 21 692 42 21 - f: +41 21 692 41 65
[Anne.Niknejad@sib.swiss](mailto:Anne.Niknejad@sib.swiss) - [https://www.sib.swiss](http://www.sib.swiss/)

**Comment by lschriml** [comment]
Hello Annie,
    I think these would belong to one of the Cell Ontologies. 
I am tagging the Cell Ontology PI, @addiehl (Alexander Diehl). 
[Alexander Diehl](mailto:addiehl@buffalo.edu)

Looking in the Ontology Lookup Service,
    The Ontology for MIRNA target (OMIT), has subtypes of endothelial cells:
https://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0023178

https://obofoundry.org/ontology/omit.html
       contact: [Jingshan Huang](mailto:huang@southalabama.edu)
                  
OMIT may be the best place to submit a term request to have this term added.

Cheers,
Lynn

**Comment by ANiknejad** [comment]
Thank you, Lynn, for quick reaction. Yes, very interested to have the feedback from Alexander Diehl, and from OMIT

**Comment by addiehl** [comment]
Hi Anne,

For the Cell Ontology, we have focused primarily on native cell types, i.e. the normal cells of a healthy organism. But we do have a small hierarchy under the term 'abnormal cell' ([CL:0001063](http://purl.obolibrary.org/obo/CL_0001063)), and have a specific subtype of 'neoplastic cell', 'CD25+ mast cell' ([CL:0011023](http://purl.obolibrary.org/obo/CL_0011023)), so there is precedent for adding a class like 'tumor-associated endothelial cell' as a subtype of 'abnormal cell'.

Logically we can specify the relationship between 'tumor-associated endothelial cell' and 'endothelial cell' (CL:0000115) as a subclass axiom:
'derives from' some 'endothelial cell'

I don't recommend the OMIT ontology as a location for this class because OMIT itself seems to have a poorly delineated scope and is built with little understanding or regard for best practices in ontology development.

Alex

**Comment by ANiknejad** [comment]
Thank you very much for your advices, Alex.
I can see in CL issues
 https://github.com/obophenotype/cell-ontology/issues/448

 that 'cancer cell' was already discussed, before its acceptation as a child of 'abonormal cell', and yes, here should be the case for 'tumor-associated endothelial cell' the same, I hope.
So I will create a term-request in CL, thank you again for your help.
Best regards,

Anne

**Comment by cmungall** [comment]
I agree with @addiehl's comments, especially re OMIT scope. It doesn't make sense to be requesting cancel cells from an ontology miRNAs.

I think CL is a better home than OMIT, however, I am wary of adding small numbers of terms in an ad-hoc as-needed fashion. It will lead to a hard to maintain ragged lattice. 

Our strategy here must encompass the NCIT abnormal cell hierarchy which has been built by experts. It does not yet connect to CL but it could.

**Comment by dosumis** [comment]
> Our strategy here must encompass the NCIT abnormal cell hierarchy which has been built by experts. It does not yet connect to CL but it could.

Is the action item here to start work on a bridge mapping from CL to NCIT?  Are there any semi-automated attempts at this we could use as a starting point?  Note - don't think this is a high priority right now given resources, but we could discuss priority/strategy on PF/Monarch calls.

**Comment by addiehl** [comment]
In any case, Anne's requested cell type, 'tumor-associated endothelial cell', does not appear in NCIT, so to facilitate her work I think we should proceed with her [CL request](https://github.com/obophenotype/cell-ontology/issues/1471), and sort out the NCIT abnormal cells later.
