### ISSUE TITLE
DOID:0081048 has inconsistent obo_namespace

### ISSUE THREAD

**Issue by chris-grove** [DiseaseOntology/HumanDiseaseOntology#1017]
Term ID: DOID:0081048
Term label: congenital limbs-face contractures-hypotonia-developmental delay syndrome

This is the only term that has_obo_namespace 'disease-ontology' (with a hyphen).

All other terms in the ontology have has_obo_namespace 'disease_ontology' (with an underscore). This is causing our (Alliance of Genome Resources) persistent store loader to fail to load this term. Can this be fixed to the standard underscore version?

**Comment by lschriml** [comment]
Thank you Chris for bringing this to our attention.
Apologies for the issues this caused.
I have fixed the file. 

Cheers,
Lynn

**Comment by chris-grove** [comment]
Thanks @lschriml !
