### ISSUE TITLE
review some OMIM:PSxxxxxx xrefs

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#1018]
In the newest release we noticed that several OMIM:PS assignments are controversial for us. Please kindly review the following list:

Lipodystrophy, familial partial - PS151660
IT IS:    lipoatrophic diabetes mellitus (DOID:11712)
PROPOSED: familial partial lipodystrophy (DOID:0050440)

Congenital disorders of glycosylation, type I - PS212065
IT IS:    congenital disorder of glycosylation (DOID:5212)
PROPOSED: congenital disorder of glycosylation type I (DOID:0050570)

Trichothiodystrophy - PS601675
IT IS:    photosensitive trichothiodystrophy (DOID:2960)
PROPOSED: trichothiodystrophy (DOID:0111866)

Seizures, familial febrile - PS121210 
IT IS:    generalized epilepsy with febrile seizures plus (DOID:0060170)
PROPOSED: familial febrile seizures (DOID:0111297)

Immunodeficiency (Select Examples) - PS300755
IT IS:    combined T cell and B cell immunodeficiency (DOID:628)
PROPOSED: primary immunodeficiency disease (DOID:612)

**Comment by lschriml** [comment]
Hello Marek,
   Happy to review these. 

How are these concontroversial for you ? 
Is it the name or the OMIM PS to DOID assignment ?

Cheers,
Lynn

**Comment by tutajm** [comment]
Hello Lynn,

The assignment.

 F.e. OMIM:PS151660 (Lipodystrophy, familial partial) groups a score of OMIM terms, all related to 'Lipodystrophy, familial partial'. 

However, currently OMIM:PS151660 is assigned to term DOID:11712 (lipoatrophic diabetes mellitus). But it looks to me, that DOID:0050440 (familial partial lipodystrophy) would be a better term to associate with OMIM:PS151660.

Thank you,
Marek

**Comment by lschriml** [comment]
Thank you Marek !! 
I will check these out and get them updated.
I'll post notes here.
Cheers,
Lynn

**Comment by sbello** [comment]
OMIM:PS151660 is currently attached to both DOID:11712 and DOID:0050440 
In OMIM lipoatrophic diabetes is a synonym for Lipodystrophy, familial partial, type 2. 
Agree that DO should remove the OMIM PS from DOID:11712

**Comment by sbello** [comment]
OMIM:PS212065 also assigned to both congenital disorder of glycosylation (DOID:5212) and congenital disorder of glycosylation type I (DOID:0050570)
agree we should remove the PS from DOID:5212
other xrefs (ORDO, NCI, MESH) are correct, these all refer to congenital disorder of glycosylation

**Comment by sbello** [comment]
OMIM: PS601675 only assigned to photosensitive trichothiodystrophy (DOID:2960) agree this should be moved to trichothiodystrophy (DOID:0111866). The OMIM series includes both photosensitive and non-photosensitive series.

**Comment by sbello** [comment]
Seizures, familial febrile - PS121210 assigned to both generalized epilepsy with febrile seizures plus (DOID:0060170) and familial febrile seizures (DOID:0111297)
agree this should be removed from generalized epilepsy with febrile seizures plus, most of the entries in the series do not have "generalized epilepsy"

**Comment by sbello** [comment]
Immunodeficiency (Select Examples) - PS300755 assigned to both combined T cell and B cell immunodeficiency (DOID:628) and primary immunodeficiency disease (DOID:612). Placement of select examples in DO and series name indicate this should only be assigned to DOID:612 

Also [NCI:C27871](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C27871) refers to Congenital Combined Immunodeficiency - based on the NCI definition this should be moved up to combined immunodeficiency ([DOID:0111962](http://www.disease-ontology.org/?id=DOID:0111962)) 

ORDO xref is correct where it is
