### ISSUE TITLE
DICER1 Syndrome, cancer syndromes, CIViC Mine

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#1020]
Jake Lever, CIViC Mine, has requested the addition of DICER1 syndrome.

-- reviewing this term request and the DO, I see the DO has pleuropulmonary blastoma
(DOID:4769). Several other sources combine pleuropulmonary blastoma with DICER 1.
However, DICER 1 is a syndrome

--> adding DICER 1 syndrome as a child of syndrome

DICER1 syndrome is an inherited disorder that increases the risk of different types of malignant and benign tumors. The syndrome is caused by mutations in the DICER1 gene, which is located on the long arm of chromosome 14, region q32.13. Patients with DICER1 syndrome commonly develop pleuropulmonary blastoma (PPB), multinodular goiter, ovarian Sertoli-Leydig cell tumors, and/or other types of tumors.

- a rare genetic disorder that predisposes individuals to multiple cancer types. Through mutations of the gene encoding the endoribonuclease, Dicer, DICER1 syndrome disrupts the biogenesis and processing of miRNAs with subsequent disruption in control of gene expression.

https://medlineplus.gov/genetics/condition/dicer1-syndrome/#resources
https://pubmed.ncbi.nlm.nih.gov/31409088/
https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC5977116/

**(DOID:4769)** 
[GARD:8757]. --> keep for pleuropulmonary blastoma
ICDO:8973/3
[MESH:C537516] --> keep for pleuropulmonary blastoma

[NCI:C5669]--> keep for pleuropulmonary blastoma

[OMIM:601200] --> Move to DICER 1

add: ORDO:64742 to pleuropulmonary blastoma
add: to DICER 1: 
    synonym: PPB familial tumor susceptibility syndrome
                     Pleuro-pulmonary blastoma familial tumor susceptibility 
                     Autosomal dominant inheritence

    ORDO: 284343

**Comment by lschriml** [comment]
DO has been updated, DICER1 syndrome added.

**Comment by lschriml** [comment]
Synonyms to add: 


Existing DOID | Name (and synonyms)
-- | --
DOID:13636 | Fanconi anemia
DOID:0050424 | Familial adenomatous polyposis\|Familial adenomatous polyposis (FAP)
DOID:5683 | hereditary breast ovarian cancer syndrome\|Hereditary breast and ovarian cancer
DOID:3883 | Hereditary non-polyposis colon cancer syndrome\|Hereditary non-polyposis colorectal cancer syndrome\|Hereditary nonpolyposis colon cancer syndrome\|Hereditary nonpolyposis colorectal cancer syndrome\|Hereditary non-polyposis colon cancer\|Hereditary non-polyposis colorectal cancer\|Hereditary nonpolyposis colon cancer\|Hereditary nonpolyposis colorectal cancer\|Lynch syndrome\|Lynch syndrome (hereditary non-polyposis colorectal cancer)
DOID:3012 | Li-Fraumeni syndrome
DOID:0080411 | MUTYH-associated polyposis
DOID:2512 | Nevoid basal cell carcinoma syndrome
DOID:14175 | Von Hippel-Lindau disease
DOID:0050427 | Xeroderma pigmentosum
DOID:2717 | Bloom syndrome
DOID:7400 | Nijmegen breakage syndrome
DOID:5688 | Werner syndrome
  | DICER1 syndrome\|PPB familial tumor susceptibility syndrome\|Pleuro-pulmonary blastoma familial tumor susceptibility syndrome\|Pleuropulmonary blastoma familial tumor susceptibility syndrome
DOID:6457 | Cowden Syndrome
DOID:3125 | Multiple endocrine neoplasia (MEN) syndrome\|Multiple endocrine neoplasia syndrome
DOID:5683 | Hereditary Breast and Ovarian Cancer (HBOC) syndrome\|Hereditary Breast and Ovarian Cancer syndrome\|Breast and Ovarian Cancer (HBOC) syndrome\|Breast and Ovarian Cancer syndrome\|HBOC syndrome
DOID:3852 | Peutz-Jeghers syndrome
DOID:2732 | Rothmund-Thomson syndrome

**Comment by allenbaron** [comment]
"MUTYH-associated polyposis" belongs to DOID:0080410 (familial adenomatous polyposis 2), not DOID:0080411 (familial adenomatous polyposis 3).
