### ISSUE TITLE
new disease: auditory neuropathy spectrum disorder 

### ISSUE THREAD

**Issue by LaurensWilming** [DiseaseOntology/HumanDiseaseOntology#1021]
Name: auditory neuropathy spectrum disorder 
Description: An autosomal dominant deafness characterized by preservation of outer hair cell function and abnormal or absent auditory brainstem responses that has_material_basis_in heterozygous mutation in the TMEM43 gene on chromosome 3p. 
Synonym: ANSD

Reference: PMID:34050020

Laurens Wilming wilmil@jax.org

**Comment by sbello** [comment]
Sent a comment to OMIM with the reference to request that they review and add the new disorder as well. They are usually pretty good about this and this way we get a check on the new disorder name before we add it.

**Comment by sbello** [comment]
OMIM has added this https://www.omim.org/entry/619832 I'll add this to the MGI ROBOT spreadsheet
