### ISSUE TITLE
Add "injection anthrax"

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1022]
A fourth type of anthrax (DOID:7427) is listed on Wikipedia and MedLine Plus which is not in the Disease Ontology, named "injection anthrax".

https://medlineplus.gov/ency/article/001325.htm
https://en.wikipedia.org/wiki/Anthrax#Injection

These web pages have all been updated since the sources were added to anthrax and its various types. They are succinct and well-organized so it might be worth a broader, quick review of all anthrax diseases.

For symptoms by type see: https://www.cdc.gov/anthrax/symptoms/index.html

**Comment by allenbaron** [comment]
Some of the definition source URLs for the anthrax types have been updated.

**Comment by lschriml** [comment]
add injection anthrax, DOID:0081239
