### ISSUE TITLE
Review and expand "acromesomelic dysplasia" (DOID:0080049)

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1023]
There is only one term for "acromesomelic dysplasia" in the DO but there are multiple subtypes (https://rarediseases.org/rare-diseases/acromesomelic-dysplasia/) and an OMIM phenotypic series (https://www.omim.org/phenotypicSeries/PS602875) for this term.

Saving this here for review.

**Comment by lschriml** [comment]
[bone development disease]
     [osteochondrodysplasia] 
acromesomelic dysplasia (DOID:0080049)
       GARD:6
       ORDO:93437

- OMIM synonyms added for:
     - acromesomelic dysplasia, Grebe type (DOID:0080052)
          OMIM:200700. (acromesomelic dysplasia-2A)
          ORDO:2098

    - acromesomelic dysplasia, Hunter-Thompson type (DOID:0080051)
         OMIM:201250. (acromesomelic dysplasia-2C)
         ORDO:968

       - acromesomelic dysplasia, Maroteaux type (DOID:0080050)
           OMIM:602875 (acromesomelic dysplasia-1 ), ORDO:440, MESH:C535661

Reviewing: 
acromesomelic dysplasia-2B (AMD2B), also known as Du Pan syndrome (OMIM:228900)
         --> this is: fibular hypoplasia and complex brachydactyly (DOID:0050790)
            -- a bone development disease

Added:
acromesomelic dysplasia-3 (AMD3), also known as Demirhan-type acromesomelic dysplasia (OMIM:609441)
acromesomelic dysplasia-4 (OMIM:619636)
