### ISSUE TITLE
Review gastritis (DOID:4029) subclasses

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1029]
[NIDDK](https://www.niddk.nih.gov/health-information/digestive-diseases/gastritis-gastropathy/definition-facts) lists a few gastritis/gastropathy subtypes that are not found in DO. An additional [review article](http://europepmc.org/article/MED/33179619) lists even more types of gastritis (see Table 1), as well as additional bacteria that can cause bacterial gastritis. It seems pretty exhaustive but may be too generous in what it includes as gastritis.

## Should these subclasses be added?

1. autoimmune gastritis: https://pubmed.ncbi.nlm.nih.gov/?term=%22autoimmune+gastritis%22&sort=date&size=200
2. reactive gastropathy (possibly the same as chemical gastropathy/gastritis)
    - "reactive gastropathy" appears to be most common with 41 [PubMed results](https://pubmed.ncbi.nlm.nih.gov/?term=%22reactive+gastropathy%22&sort=date&size=200) including recent use in last 2 years. There are instances where it is also shown as chemical gastritis, including the review linked above, but it's not clear on quick review whether they are exactly the same.
    -  "reactive gastritis" does not appear to be common usage (37 [PubMed results](https://pubmed.ncbi.nlm.nih.gov/?term=%22reactive+gastritis%22&sort=date&size=200) and none recent)
    -  "chemical gastritis" has 36 [PubMed results](https://pubmed.ncbi.nlm.nih.gov/?term=%22chemical+gastritis%22&sort=date&size=200).
    - "chemical gastropathy" is least common with only 16 [PubMed results](https://pubmed.ncbi.nlm.nih.gov/?term=%22chemical+gastropathy%22&sort=date&size=200).
3. erosive gastritis: https://pubmed.ncbi.nlm.nih.gov/?term=%22erosive+gastritis%22&sort=date&size=200

## Should bacterial gastritis be updated and/or split?

The number one cause of bacterial gastritis (DOID:4033) is _H. pylori_ -- a PubMed search for [human gastritis bacteria pylori](https://pubmed.ncbi.nlm.nih.gov/?term=human+gastritis+bacteria+pylori&sort=date&size=200) returns > 10,000 results while the search excluding "pylori" ([human bacteria gastritis NOT pylori](https://pubmed.ncbi.nlm.nih.gov/?term=human+gastritis+bacteria+NOT+pylori&sort=date&size=200)) returns < 1,000 results, many of which are not bacterial but other types of gastritis.

Should we rename bacterial gastritis to _H. pylori_ gastritis, add `has material basis in` axioms for _H. pylori_, or possibly create subclasses based on the different bacteria that cause gastritis?

Other potential bacterial causes:
1. Sarcina Ventriculi: https://pubmed.ncbi.nlm.nih.gov/34838720/
2. Campylobacter jejuni: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8406305/
3. Helicobacter heilmannii: https://pubmed.ncbi.nlm.nih.gov/34135148/

**Comment by lschriml** [comment]
autoimmune gastritis is : DOID:0040090
gastropathy is a more general term, in DO, we include it as a synonym of 'stomach disease'
For the various bacterial causes of gastritis, we do not create a new disease term, as they are all 'gastritis'
