### ISSUE TITLE
typo in term name for DOID:0070350)

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#1032]
it is: "spinal muscular atrophy with lower extremity predominante 2B" (DOID:0070350)

looks like a typo. proposed term name: "spinal muscular atrophy with lower extremity predominance 2B"?

please review

**Comment by allenbaron** [comment]
Marek,
Thank you for pointing out this typo. It has been fixed and will be included in the next release.
