### ISSUE TITLE
CRANIOFACIAL DYSMORPHISM, SKELETAL ANOMALIES, AND MENTAL RETARDATION SYNDROME

### ISSUE THREAD

**Issue by anna-anagnostop** [DiseaseOntology/HumanDiseaseOntology#1034]
Consider adding new DO term:

DO TERM NAME: Craniofacial dysmorphism, skeletal anomalies, and mental retardation syndrome
SUGGESTED DEF: A syndrome characterized by craniofacial dysmorphism, skeletal anomalies and mental retardation that has_material_basis_in homozygous mutation in the TMCO1 gene on chromosome 1q24.1 
SYN: Cerebrofaciothoracic dysplasia
SYN:  CFSMR 
SUGGESTED PARENT TERMS: is-a [autosomal recessive disease](http://www.informatics.jax.org/vocab/mmxvii_disease_ontology/DOID:0050737) and is-a [syndrome](http://www.informatics.jax.org/vocab/mmxvii_disease_ontology/DOID:225)
PubMed IDs: PMID: 20018682, PMID: 24194475
OMIM #: [213980](https://www.omim.org/entry/213980)

Thank you, 

Anna V. Anagnostopoulos https://orcid.org/0000-0002-6490-7723

**Comment by lschriml** [comment]
Thank you Anna !! 
Really appreciate all of the details you included in the ticket !! 
I have added this term to the DO.

Cheers,
Lynn
