### ISSUE TITLE
NTR 'ectodermal dysplasia and immune deficiency'

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#1035]
Please add the term 'Ectodermal dysplasia and immune deficiency'. Even better (if possible): please also add the child terms as found in OMIM phenotypic series PS300291: https://www.omim.org/phenotypicSeries/PS300291

Reason: currently OMIM:300291 is part of term 'hypohidrotic ectodermal dysplasia' (DOID:14793), but according to OMIM, this term is now named 'Ectodermal dysplasia and immunodeficiency 1' because of evidence of 'immunodeficiency' component.

**Comment by allenbaron** [comment]
Thank you Marek. We will review these records and update DO.

**Comment by lschriml** [comment]
The three Ectodermal dysplasia and immune deficiency terms have been added to the DO.
