### ISSUE TITLE
NTR: MARSILI SYNDROME

### ISSUE THREAD

**Issue by cindyJax** [DiseaseOntology/HumanDiseaseOntology#1036]
Include: 
- new disease terms or updates to DO's disease terms
- include the term name in the title of the request
- It is helpful to include a definition and PubMed reference for new terms
- It is useful to share information on the relevant project 
- include contact information along with your ORCID id, so that we can provide attribution for your contribution

New term request:

MARSILI SYNDROME

[OMIM Entry - # 147430 - MARSILI SYNDROME; MARSIS](https://www.omim.org/entry/147430)

 Habib AM, Matsuyama A, Okorokov AL, Santana-Varela S, Bras JT, Aloisi AM,
Emery EC, Bogdanov YD, Follenfant M, Gossage SJ, Gras M, Humphrey J, Kolesnikov
A, Le Cann K, Li S, Minett MS, Pereira V, Ponsolles C, Sikandar S, Torres JM,
Yamaoka K, Zhao J, Komine Y, Yamamori T, Maniatis N, Panov KI, Houlden H,
Ramirez JD, Bennett DLH, Marsili L, Bachiocco V, Wood JN, Cox JJ. A novel human
pain insensitivity disorder caused by a point mutation in ZFHX2. Brain. 2018 Feb
1;141(2):365-376. doi: 10.1093/brain/awx326. PMID: 29253101; PMCID: PMC5837393.

csmith@ MGI for mouse model curation

**Comment by lschriml** [comment]
Hello Cindy, @cindyJax 
Thank you for the new disease term !! 
 Apologies for the delayed response, as I was on travel. 

I have added Marsili Syndrome. 

Cheers,
Lynn
