### ISSUE TITLE
review use of disease has location axioms 

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1039]
Looking at the DO in MGI I noticed some odd relations under spinal disease (DOID:0060564)

1. bone structure disease is listed as a child of spinal disease 
- this is because bone structure disease has the subclass axiom 'disease has location' some 'vertebral column'
- Lynn has fixed this

2. brain ependymoma child of spinal disease which is a child of bone disease
- has the subclass axiom 'disease has location' some 'vertebral column'
- I think this should be 'disease has location' some 'spinal cord' or possibly not have the subclass axiom at all if the location in the spinal cord is only in children

3. lethal congenital contracture syndrome
- definition of the disease is that the disease can involve contractures in different locations
- may be better to have a subclass axiom using "skeletal joint" as the location rather than limb or vertebral column since this is always true

4. diffuse idiopathic skeletal hyperostosis
- disease involves hardening of the spinal ligaments not the vertebrae
- uberon has a term for ligament of vertebral column (UBERON:0011136) that would be a better fit.

I'll add any others I come across to the ticket

**Comment by lschriml** [comment]
Hello @sbello -- I have updated all of these examples and identified and fixed any other related ones that I could find. We'll keep this issue open for future examples.
Cheers,
Lynn

**Comment by sbello** [comment]
Thansks @lschriml !

**Comment by lschriml** [comment]
No new issues noted, will reopen ticket if needed.
