### ISSUE TITLE
doid.owl imports version 2022-05-10 of symp.owl, which does not exist

### ISSUE THREAD

**Issue by jamesaoverton** [DiseaseOntology/HumanDiseaseOntology#1043]
I can't load the latest `doid.owl` file into OWLAPI because of a failing import.

<http://purl.obolibrary.org/obo/doid.owl> resolves to <http://purl.obolibrary.org/obo/doid/releases/2022-06-06/doid.owl> which includes this import statement:

```
<owl:imports rdf:resource="http://purl.obolibrary.org/obo/symp/releases/2022-05-10/symp.owl"/>
```

This redirects to <https://raw.githubusercontent.com/DiseaseOntology/SymptomOntology/v2022-05-10/src/ontology/symp.owl> which returns a 404 error. I think this recent PURL PR <https://github.com/OBOFoundry/purl.obolibrary.org/pull/851> has the configuration that you want for SYMP, but for whatever reason there is no 2022-05-10 release of `symp.owl` in <https://github.com/DiseaseOntology/SymptomOntology/releases>.

**Comment by allenbaron** [comment]
Thanks for pointing this out James. We will get it fixed.

**Comment by allenbaron** [comment]
@jamesaoverton it should work now. Let us know if you experience any other issues.

**Comment by jamesaoverton** [comment]
Yes, <http://purl.obolibrary.org/obo/symp/releases/2022-05-10/symp.owl> now resolves. Thanks!
