### ISSUE TITLE
Repair obsolete terms in imports

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1047]
The count of `owl:deprecated` properties/classes from imports in doid-merged.owl, release v2022-06-07 is:

import | deprecated
-- | --
RO | 1
GENO | 2
HP | 147

These should be reviewed and removed or repaired as necessary.

The deprecated RO & GENO property/classes are:

- http://purl.obolibrary.org/obo/RO_0002218 (obsolete has active participant)           
- http://purl.obolibrary.org/obo/GENO_0000142 (obsolete dominant inheritance)           
- http://purl.obolibrary.org/obo/GENO_0000150 (obsolete autosomal recessive inheritance)

The deprecated HP classes are listed in the following file: [HP_deprecated_v2022-06-07.txt](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/8903503/HP_deprecated_v2022-06-07.txt)

**Comment by allenbaron** [comment]
The deprecated HP terms are all defined in the `src/ontology/ext.owl` file and do not exist in the `src/ontology/import/hp_import.owl` file.

**Comment by lschriml** [comment]
@allenbaron - Can we close this ticket ?

**Comment by allenbaron** [comment]
Not yet. None of these deprecated terms have been addressed.

**Comment by lschriml** [comment]
Can you add an estimate of when this will be addressed or time-frame for this resolution ?

**Comment by allenbaron** [comment]
`HP:0011007` has been merged into 'Onset' (`HP:0003674`) and the class has been completely removed from hp.owl, instead of deprecated, so it can be removed ext.owl.

**Comment by allenbaron** [comment]
The remaining HP deprecation statements have been removed. Closed by b691c5b4ee618c58dce75eb39321a13ef36a0372
