### ISSUE TITLE
Dump cross-references with each release

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1048]
xrefs in csv format were requested in discussion https://github.com/DiseaseOntology/HumanDiseaseOntology/discussions/1044 and would be easy to dump with each release to `DOreports`.

**Comment by allenbaron** [comment]
Two reports will now be issued with each release and can be found in [src/DOreports](https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/main/src/DOreports): 
1. HumanDO.tsv - the asserted disease hierarchy (subClassOf)
2. xrefs_in_DO.tsv - the complete set of mappings/cross-references between the DO's diseases and other clinical vocabularies.

**Comment by huerqiang** [comment]
Hi, I found the "xrefs_in_DO.tsv" file has been deleted in the release version, I want to ask where can I get the latest version of this file?

**Comment by allenbaron** [comment]
Oh sorry, they haven't been deleted, just moved. We still generate these files with each release. The [DOreports](https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/main/DOreports) folder was moved out of the src directory and is now in the top-level directory. We did also rename some of these reports. Hopefully the names are intuitive.
