### ISSUE TITLE
New term request: microcephaly-epilepsy-developmental delay syndrome

### ISSUE THREAD

**Issue by rankishore** [DiseaseOntology/HumanDiseaseOntology#1050]
Looks like we need a DO term that encapsulates clinical conditions associated with the PPP5C gene. This study has come from the Undiagnosed Diseases Network (we will get more of these types of studies). Trying to curate PMID: 35361529 and need a DO term to describe the clinical conditions associated with PPP5C and the engineered mutation in C. elegans.
I did a search looking for PPP5C with "definition" as the criterion and nothing comes up, as many of the similar definitions have the specific associated gene in them, so can't use them for PPP5C model studies. Thanks.

Ranjana Kishore (Orcid: 0000-0002-1478-7671)

**Comment by allenbaron** [comment]
Thank you Ranjana. We will review this and get back to you.

**Comment by lschriml** [comment]
Thank you Ranjana !! 
I would like to define a disease for this C. elegans gene.
 I noticed that there is also a mouse gene: http://www.informatics.jax.org/marker/MGI:102666

According to the paper and reviewing OMIM: I see that this gene has not yet been associated with disease, I am not sure how to add it to the DO. 
The phenotype from the paper  : microcephaly, developmental delay, and refractory epilepsy

One consideration on a name for this phenotype/disease, is that: 
       one of the 'developmental and epileptic encephalopathy' subtypes, DOID:0080457 is named microcephaly, seizures, and developmental delay,

Suggestions ?? 

Cheers,
Lynn

**Comment by sbello** [comment]
I contacted OMIM to get the paper prioritized for review. Usually they get back pretty quickly. 

I don't think anyone has picked this up yet.  I would agree that the term list is too close to the existing disease term to make a good name. If we do end up needing to create a term we could add "PPP5C-related" to the name to make it clearly distinct.

**Comment by lschriml** [comment]
Just checked, no new OMIM record for this one yet.

**Comment by lschriml** [comment]
OMIM Gene record:
https://omim.org/entry/600658?search=%22ppp5c%20gene%22&highlight=%22ppp5c%20gene%22

no phenotype record created yet.

**Comment by rankishore** [comment]
Thanks @lschriml @sbello on your comments. Any movement on this? This paper is stuck in our ACKnowledge pipeline (author flagged for disease model) without curation. 

I see that OMIM mentions this paper in their description on the PPP5 gene record https://omim.org/entry/600658: "[Fielder et al. (2022) showed that a C. elegans model harboring an A48T mutation in the pph5 gene, corresponding to the human PPP5C mutation A47T, on an mec15 mutant background, demonstrated abnormal neurite growth and abnormal GABA signaling compared to wildtype pph5 on an mec15 mutant background."

But no OMIM phenotype record yet. Do OMIM phenotype records have to exist to make a DO term?

The problem with annotating to existing DO term "DOID:0080457, microcephaly, seizures, and developmental delay" is that the definition relates this to human gene PNKP: "A developmental and epileptic encephalopathy characterized by microcephaly, infantile onset of seizures and developmental delay that has_material_basis_in homozygous or compound heterozygous mutation in the PNKP gene on chromosome 19q13."

Maybe we need another term similar to the above which relates the phenotypes to involvement of PPP5C.

**Comment by sbello** [comment]
OMIM has annotated the Fielder paper but called this a variant of unknown significance. If you go to the variant section of the PPP5C gene page you'll find
"In a 6-year-old girl with developmental and epileptic encephalopathy, [Fielder et al. (2022)](https://www.omim.org/entry/600658?search=ppp5c&highlight=ppp5c#2) identified a de novo heterozygous c.139G-A transition (c.139G-A, NM_006247.3) in the PPP5C gene, resulting in an ala47-to-thr (A47T) substitution. The mutation, which was identified by trio whole-exome sequencing and confirmed by Sanger sequencing, was not present in the gnomAD database (v2.1.1). The patient had epilepsy, nystagmus, congenital microcephaly, and developmental delay. A brain MRI at 4 years of age showed reduced cerebral white matter volume. Seizures, which began at 12 to 16 months of age, were refractory to treatment"

Looking at this I would suggest NOT adding a new DO term yet and instead annotating the C. elegans model to developmental and epileptic encephalopathy (DOID:0112202). I'm basing this suggestion on the first sentence of the OMIM description and that the DO term is the parent to DOID:0080457 which makes it likely that this is the correct branch of DO for the annotation.

**Comment by rankishore** [comment]
Okay, @sbello I see what you're saying, for now I think I'll just annotate it to the parent term "developmental and epileptic encephalopathy (DOID:0112202)" with the understanding that other nuances such as relating it to the PPP5C gene are lost.
