### ISSUE TITLE
Terms in so_terms.txt are lost during build with latest SO release

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1054]
The report during a full import refresh and test release conducted as part of testing in #1052, identified two SO terms as missing. Those are:

SO:1000044
SO:0000199

These are both in the `so_terms.txt` file and are in the source `so.owl` file but are NOT in the `so_import.owl` file built from them. Troubleshooting the command indicates they are removed by the `robot collapse` step while creating `build/so_feature.owl`.

This can be fixed by removing the `robot collapse` command or adding the `--precious-terms` argument to make sure all the terms in `so_terms.txt` are kept.

**Comment by lschriml** [comment]
@allenbaron -- please go ahead and use the 'precious-terms' command and rebuild this import.
Cheers,
Lynn

**Comment by allenbaron** [comment]
I will make this update after PR #1052 is merged.

**Comment by allenbaron** [comment]
This was fixed in 3064d41d32aede35f0b5e4d1b70479555a0c448c while updating SO in PR #1052.
