### ISSUE TITLE
Review chronic schizophrenia deprecation

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1055]
**Disease:** "obsolete chronic schizophrenia" (DOID:1231)

**Issue:** Term is showing as deprecated in DOID, but there's no replacement term – I was wondering why?  The new Alzheimer’s Ontology ended up using the NCIT "chronic schizophrenia" I think, so I was left not being able to suggest to them to submit the term to DOID!
 
**Submitter:** Damion Dooley, damion_dooley@sfu.ca

**Comment by lschriml** [comment]
Term reviewed. 
This term was removed more than a decade ago, as a result of schizophrenia nomenclature updates. 
       I researched this term, in DO, in literature and across vocabularies.
I found that this term was obsoleted quite awhile ago, when schizophrenia nomenclature was revised. 
Looking in various resources, including DSM, for 'chronic schizophrenia', I confirmed that this is an out of date name for 'schizophrenia' and that it is no longer in use.  
I would recommend usage of 'schizophrenia' for this use case.

**Comment by allenbaron** [comment]
A 'term replaced by' annotation has been added to "obsolete chronic schizophrenia" to indicate it's been replaced by "schizophrenia".

**Comment by allenbaron** [comment]
Just thought I'd note that the only subclass of "schizophrenia" (DOID:5419) that DO has is "paranoid schizophrenia" (DOID:1229), ignoring the subtypes from OMIM, while [ICD-10 schizophrenia](https://www.icd10data.com/ICD10CM/Codes/F01-F99/F20-F29/F20-) includes a few additional subcategories.
