### ISSUE TITLE
connect skin papilloma as a parent to common warts

### ISSUE THREAD

**Issue by shurjenw** [DiseaseOntology/HumanDiseaseOntology#1057]
**Is your request related to a specific disease? Please describe.**
common wart (DOID:11165) and skin papilloma (DOID:3178) 

**Describe the proposed **
make common wart (DOID:11165) a child of skin papilloma (DOID:3178)

**References**
 common wart has_material_basis_in human papillomavirus (types 2 and 4)  so should be connected to skin papilloma in Disease Ontology

**Comment by lschriml** [comment]
Thank you for the update request !! 
Looking at the definition of papilloma in NCI: 
A benign epithelial neoplasm that projects above the surrounding epithelial surface and consists of villous or arborescent outgrowths of fibrovascular stroma.

Although the root of the two words, papilloma and papillomavirus are similar, a wart is not a neoplasm (tissue growth resulting from uncontrolled cell proliferation), a wart is a type of skin infection. 

Histopathologic features is warts includes papillomatosis, which refers to the projection of dermal papillae above the surface of the skin, resulting in an irregular undulating configuration of the epidermis.

Cheers,
Lynn

**Comment by shurjenw** [comment]
Thank you Lynn for the explanation.
Shur-Jen
