### ISSUE TITLE
New term Request: Mandibuloacral dysplasia (MAD)

### ISSUE THREAD

**Issue by rankishore** [DiseaseOntology/HumanDiseaseOntology#1060]
Please create above term, for a paper that describes a C. elegans model for MAD, reference PMID: 32917887.

OMIM references: 
https://www.omim.org/entry/248370 for MANDIBULOACRAL DYSPLASIA WITH TYPE A LIPODYSTROPHY; MADA
 
https://www.omim.org/entry/608612 for MANDIBULOACRAL DYSPLASIA WITH TYPE B LIPODYSTROPHY; MADB

Useful review that describes Mandibuloacral dysplasia (MAD): https://www.sciencedirect.com/science/article/pii/S1568163717301757 

Thanks very much
Ranjana Kishore

**Comment by lschriml** [comment]
Thank you Ranjana !!

**Comment by lschriml** [comment]
@rankishore 
I have added the two subtypes along with a parent term.
Cheers,
Lynn

**Comment by rankishore** [comment]
Thank you Lynn, it's great that you've created the parent term as well.
