### ISSUE TITLE
review [arthrogryposis due to muscular dystrophy]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#1062]
'arthrogryposis due to muscular dystrophy' [DOID:0110631] references OMIM:253900 and ORDO:1155; these terms have been discontinued by both OMIM and ORDO

OMIM:
[^253900](https://www.omim.org/entry/253900)MOVED TO [618484](https://www.omim.org/entry/618484) AND [619334](https://www.omim.org/entry/619334)

ORDO:
This entity has been obsoleted from the Orphanet nomenclature of rare diseases.
Instead, consider using [Arthrogryposis multiplex congenita](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=1037)

Please review.

**Comment by allenbaron** [comment]
Thank you Marek. We will review and update.

**Comment by allenbaron** [comment]
The term has been obsoleted and an additional subtype has been added.

Thanks again Marek.
