### ISSUE TITLE
Fix duplicate_label_synonym WARNINGs

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1063]
Subject | Property | Value
-- | -- | --
non-alcoholic fatty liver disease | has exact synonym | non-alcoholic fatty liver disease@en
nonbacterial thrombotic endocarditis | has exact synonym | nonbacterial thrombotic endocarditis
familial hypertrophic cardiomyopathy | has exact synonym | familial hypertrophic cardiomyopathy@en
MECP2 duplication syndrome | has exact synonym | MECP2 duplication syndrome@en
acute necrotizing pancreatitis | has exact synonym | acute necrotizing pancreatitis@en
central diabetes insipidus | has exact synonym | central diabetes insipidus@en
MLS syndrome | has exact synonym | MLS syndrome
spondyloepimetaphyseal dysplasia with joint laxity type 2 | has exact synonym | spondyloepimetaphyseal dysplasia with joint laxity type 2

**Comment by allenbaron** [comment]
### Synonyms on the same term as the label
- 'non-alcoholic fatty liver disease' (DOID:0080208)
- 'spondyloepimetaphyseal dysplasia with joint laxity type 2' (DOID:0112199)

### Synonyms on a _different_ term than the label
Term w/synonym | Relationship | Term w/label | Note
-- | -- | -- | --
'Libman-Sacks endocarditis' (DOID:0080740) | sibling of | 'nonbacterial thrombotic endocarditis' (DOID:0060068) | same disease?
'hypertrophic cardiomyopathy' (DOID:11984) | superclass of | 'familial hypertrophic cardiomyopathy' (DOID:0080326) | 
'syndromic X-linked intellectual disability Lubs type' (DOID:0060799) | none apparent | 'MECP2 duplication syndrome' (DOID:0080713) | probably same disease: OMIM xref from DOID:0060799 has xref to GARD xref of DOID:0080713
'acute pancreatitis' (DOID:2913) |  superclass of | 'acute necrotizing pancreatitis' (DOID:0080998) |
'neurohypophyseal diabetes insipidus' (DOID:12388) |  subclass of | 'central diabetes insipidus' (DOID:0081055) | 
'linear skin defects with multiple congenital anomalies 1' (DOID:0111808) |  subclass of | 'MLS syndrome' (DOID:0111875) |

**Comment by allenbaron** [comment]
According to the recently updated [StatPearls article](https://www.ncbi.nlm.nih.gov/books/NBK532864/) used as a definition source for DOID:0060068, 'Libman-Sacks endocarditis' and 'nonbacterial thrombotic endocarditis' are the same. However, another [StatePearls article](https://www.ncbi.nlm.nih.gov/books/NBK542204/) appears to treat Libman-Sacks endocarditis as a _phenotype_ of systemic lupus erythematosus, perhaps making it a subtype of nonbacterial thrombotic endocarditis. MeSH appears to handle these separately, as well, with one entry for [Endocarditis, Non-Infective](https://meshb.nlm.nih.gov/record/ui?ui=D059905) and another for [Lupus Erythematosus, Systemic](https://meshb.nlm.nih.gov/record/ui?ui=D008180), which has 'Libman-Sacks Disease' as a synonym. PubMed articles appear to take both approaches.

@lschriml this case is more complicated than duplication of a synonym-label. Can you provide your opinion on whether to merge 'Libman-Sacks endocarditis' into 'nonbacterial thrombotic endocarditis'?

**Comment by allenbaron** [comment]
I'd also recommend merger of 'syndromic X-linked intellectual disability Lubs type' (DOID:0060799) into 'MECP2 duplication syndrome' (DOID:0080713) given the details on the [OMIM reference](https://www.omim.org/entry/300260) and a MedLine Plus article about [MECP2 duplication](https://medlineplus.gov/genetics/condition/mecp2-duplication-syndrome/#causes).

**Comment by lschriml** [comment]
reviewed and updated diid-edit.owl
 

**'Libman-Sacks endocarditis' (DOID:0080740) &  'nonbacterial thrombotic endocarditis'** (DOID:0060068) | same disease?
     -->  this is a case of a left over synonym when a new subtype was created 
     -->  two distinct diseases
 
**'hypertrophic cardiomyopathy' (DOID:11984) & 'familial hypertrophic cardiomyopathy'** (DOID:0080326) |  

--> this is a left over a previous split.
I also noticed that there were multiple NCI, MESH, etc. xrefs in the parent term, I check what they each represented (MESH, NCI thesaurus, UMLS, SNOMED CT) and moved the xrefs where needed

**'syndromic X-linked intellectual disability Lubs type'** (DOID:0060799) & '**MECP2 duplication syndrome'** (DOID:0080713) | 
    probably same disease: OMIM xref from DOID:0060799 has xref to GARD xref of DOID:0080713

--> Agreed, these should be merged. Done


**'acute pancreatitis'** (DOID:2913) & **'acute necrotizing pancreatitis'** (DOID:0080998) 

--> removed synonym from parent term 


**'neurohypophyseal diabetes insipidus'** (DOID:12388) & **'central diabetes insipidus'** (DOID:0081055) 

--> removed parent synonym from child term

'**linear skin defects with multiple congenital anomalies 1**' (DOID:0111808) & '**MLS syndrome'** (DOID:0111875)

--> removed parent synonym from child term
