### ISSUE TITLE
Two terms: BH4-deficient hyperphenylalanimemia C and D

### ISSUE THREAD

**Issue by DeniseSl22** [DiseaseOntology/HumanDiseaseOntology#1064]
Parent term: DOID:9252 (amino acid metabolic disorder)
Related siblings: DOID:0090106 (BH4-deficient hyperphenylalaninemia A) and DOID:0112225 (BH4-deficient hyperphenylalaninemia B).

BH4-deficient hyperphenylalanimemia C (alias: 'dihydropteridine reductase deficiency'):
OMIM: 261630
PMID:14705166
BH4-deficient hyperphenylalanimemia D (alias: 'pterin-4a-carbinolamine dehydratase deficiency'):
OMIM: 264070
PMID: 1405480

Relevant project: WikiPathways, https://www.wikipathways.org/index.php/Pathway:WP4156

**Comment by lschriml** [comment]
@DeniseSl22 Thank you for the term requests !! 
I have added the two subtypes and grouped the four subtypes under a parent class.
tetrahydrobiopterin (BH4)-deficient hyperphenylalaninemia

Cheers,
Lynn
