### ISSUE TITLE
dilated cardiomyopathy 2F

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1067]
Term: dilated cardiomyopathy 2F
Definition: A dilated cardiomyopathy that has_material_basis_in autosomal recessive mutation in the BAG5 gene on chromosome 14q32.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/35044787/  (PMID:35044787)
Parent DO: DOID:12930 dialted cardiomyopathy, DOID:0050737 autosomal recessive disease
DbXref: OMIM:619747
DbXref: ICD10CM:I42.0

For MGI mouse disease curation.
Thanks,
Monika Tomczuk

**Comment by lschriml** [comment]
Thank you Monika for the new term request.
I have added this new subtype, along with a few other dilated cardiomyopathy subtypes.
Cheers,
Lynn
