### ISSUE TITLE
3-hydroxy-3-methylglutaryl-CoA synthase-2 deficiency

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1068]
I'm not sure what the best name for this is: OMIM has it as 3-hydroxy-3-methylglutaryl-CoA synthase-2 deficiency, Orphanet has it as 3-hydroxy-3-methylglutaryl-CoA synthase deficiency (without the -2 after synthase), could also be HMG-CoA synthase deficiency.

Label: 3-hydroxy-3-methylglutaryl-CoA synthase-2 deficiency (OMIM) or 3-hydroxy-3-methylglutaryl-CoA synthase deficiency (Orphanet) – not sure if it should be synthase-2 or just synthase
Definition: An autosomal recessive disorder of ketone body metabolism that has_material_basis_in mutation in the HMGCS2 gene on chromosome 1p12.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/16601895/
Exact synonym: HMG-CoA synthase deficiency, HMGCS2 deficiency
DbXref: OMIM:605911
Dbxref: ORDO:35701
DbXref: MeSH:C567784
DbXref: UMLS_CUI:C2751532
DbXref: GARD:2712

For MGI mouse model curation (paper PMID: 35421611)

Thank you,
Monika Tomczuk

**Comment by sbello** [comment]
Since there is both HMGCS2 and HMGCS1 I think we need to include the -2 or create a more general disease term that covers both genes.
Currently there are no disease associated with HMGCS1 in OMIM
