### ISSUE TITLE
Leber congenital amaurosis 19

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1069]
Label: Leber congenital amaurosis 19
Definition: A Leber congenital amaurosis that has_material_basis_in mutation in the USP45 gene on chromosome 6q16.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/30573563/
Parent DO: DOID:14791 Leber congential amaurosis
Exact synonym: LCA19
DbXref: OMIM:618513
DbXref: ICD10CM:H35.5

Request for MGI mouse model paper PMID:30573563

Thank you,
Monika Tomczuk

**Comment by lschriml** [comment]
Thank you for the new term. Added to the DO.
Cheers,
Lynn
