### ISSUE TITLE
SHRF (short stature, hearing loss, retinitis pigmentosa, and distinctive facies)

### ISSUE THREAD

**Issue by srengel** [DiseaseOntology/HumanDiseaseOntology#1070]
Include: 
- new disease terms or updates to DO's disease terms
- include the term name in the title of the request
- It is helpful to include a definition and PubMed reference for new terms

https://pubmed.ncbi.nlm.nih.gov/34162742/

"While a number of mutations in RNA exosome genes cause pontocerebellar hypoplasia, mutations in the cap subunit gene EXOSC2 cause an apparently distinct clinical presentation that has been defined as a novel syndrome SHRF (short stature, hearing loss, retinitis pigmentosa, and distinctive facies)."

- It is useful to share information on the relevant project 
- include contact information along with your ORCID id, so that we can provide attribution for your contribution

Stacia Engel
Email
stacia@stanford.edu
ORCID iD
0000-0001-5472-917X

**Comment by lschriml** [comment]
Thank you Stacia !! 
I have added this new term to the DO.
DOID:0081175
It will be public in next week's release.
Cheers,
Lynn

**Comment by srengel** [comment]
nice, thanks Lynn!  next week i'll use the term to annotate that paper :)
