### ISSUE TITLE
spermatogenic failure vs azoospermia

### ISSUE THREAD

**Issue by shurjenw** [DiseaseOntology/HumanDiseaseOntology#1072]
**Is your request related to a specific disease? Please describe.**
spermatogenic failure and azoospermianeeded review.  

**Describe the proposed **
azoospermia (DOID:14227) has exact synonym of spermatogenic failure  and several child terms of spermatogenic failure n

**References**
![image](https://user-images.githubusercontent.com/12736813/187550626-1a4d2d0f-30e5-4ee4-9b3b-49ec552d0371.png)

**Comment by lschriml** [comment]
Thank you for pointing out this needed update.
The DO has been updated.
Cheers,
Lynn
