### ISSUE TITLE
Remove DO label/synonym capitalization duplicates

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1073]
Quite a few synonym duplicates exist in DO that differ only by capitalization (mostly) and/or whitespace. This issue is a placeholder for correcting this undesired duplication.

Lists of duplicates can be found on sheets in the [DO_synonym_capitalization_dups](https://docs.google.com/spreadsheets/d/1oIMi55zpShoWVyS509SHQCRZ-aasM-CO80adPtzbNxA/edit?usp=sharing) Google sheet.

There are 3 types of duplicates:
1. Label-synonym or synonym-synonym duplicates for the same disease.
2. Label-synonym or synonym-synonym duplicates for _different_ diseases.
3. Label-synonym or synonym-synonym duplicates between a DO disease and a SYMP synonym.

**Comment by allenbaron** [comment]
All duplicates within the same disease have been fixed.

Duplicates identified across diseases or between DO and SYMP still need to be reviewed.

**Comment by allenbaron** [comment]
Noting a related fact here that duplicate synonym scopes is are not allowed currently allowed for OBO (http://robot.obolibrary.org/report_queries/duplicate_scoped_synonym; e.g. where the same synonym on the same term has is both exact and related).

Also, a rich discussion about synonym duplication, scope, and format from others in the OBO community is ongoing at https://github.com/obophenotype/uberon/issues/2363.

**Comment by allenbaron** [comment]
@lschriml only the easiest set of duplicates have been addressed. The overlap of synonyms across diseases is something we should definitely address. I thought we'd assigned this to @csbjohnson?

**Comment by lschriml** [comment]
Sounds good.Let’s include the steps to take in the ticket.Sent from my iPhoneOn Nov 16, 2023, at 3:22 PM, J. Allen Baron ***@***.***> wrote:﻿
@lschriml only the easiest set of duplicates have been addressed. The overlap of synonyms across diseases is something we should definitely address. I thought we'd assigned this to @csbjohnson?
