### ISSUE TITLE
Requested term: RCDP type 4

### ISSUE THREAD

**Issue by DeniseSl22** [DiseaseOntology/HumanDiseaseOntology#1075]
Rhizomelic chondrodysplasia punctate ([DOID_2580](https://bioportal.bioontology.org/ontologies/DOID?p=classes&conceptid=http://purl.obolibrary.org/obo/DOID_2580)) now contains 4 subclasses (type 1,2,3, and 5), and could be extended with type 4. This disorder is described in [PMID: 28523433](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5818364/#CR54), and would be relevant to have for WikiPathways pathway model [WP5272](https://www.wikipathways.org/index.php/Pathway:WP5275).

"RCDP type 4 results from a mutation in FAR1, which is required for the conversion of fatty acyl-CoAs to fatty alcohols (Honsho et al., [2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5818364/#CR41); Buchert et al., [2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5818364/#CR16))."

Contact: [Github](https://github.com/DeniseSl22) ; [Orcid](https://orcid.org/0000-0001-8449-1318)

**Comment by lschriml** [comment]
Hello Denise,
  Thank you for identifying this disease to add !! 

Added: DOID:0081243

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9471318/

Inherited mutations in the FAR1 gene causing reduction or complete loss of FAR1 activity result in peroxisomal FAR1 deficiency (**MIM #616154,** also referred to as RCDP type 4), which can be clinically distinguished from the other forms of RCDP by the absence of chondrodysplasia punctata or rhizomelia ([Buchert et al., 2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9471318/#B25); [Alshenaifi et al., 2019](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9471318/#B5)).

Cheers,
Lynn
