### ISSUE TITLE
Requested term: Peroxisomal biogenesis disorder Type 1B

### ISSUE THREAD

**Issue by DeniseSl22** [DiseaseOntology/HumanDiseaseOntology#1076]
Peroxisomal biogenesis disorder ([DOID_0080377](http://purl.obolibrary.org/obo/DOID_0080377)) contains various subclasses, however, seems to be missing the subtype disorder 1B described in [PMID: 28523433](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5818364/#CR54), and would be relevant to have for WikiPathways pathway model [WP5272](https://www.wikipathways.org/index.php/Pathway:WP5275).

"Peroxisomal biogenesis disorders in the Zellweger spectrum are a heterogeneous group of genetic disorders encompassing Zellweger syndrome, neonatal adrenoleukodystrophy, and infantile Refsum disease."

These latter two disorder names are linked to one entry in [OMIM](https://www.omim.org/entry/601539) as aliasses.

Contact: [Github](https://github.com/DeniseSl22) ; [Orcid](https://orcid.org/0000-0001-8449-1318)

**Comment by lschriml** [comment]
Thank you Denise !! 
Added to DO: DOID:0081240

Cheers,
Lynn
