### ISSUE TITLE
COPA Syndrome

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1077]
Hi Lynn,
I'm not sure which name is the correct one for this syndrome. The paper I'm working on calls it COPA syndrome. OMIM has it as autoimmune interstitial lung, joint, and kidney disease and Orphanet has it as autoimmune interstitial lung disease-arthritis syndrome. A google search mostly shows COPA syndrome and there is a COPA syndrome foundation. Anyway, I don't know which one you would use. 

Label: COPA syndrome or autoimmune interstitial lung disease-arthritis syndrome or autoimmune interstitial lung, joint, and kidney disease 
Definition: An autoimmune interstitial lung, joint, and kidney disease characterized by interstitial lung disease, inflammatory arthritis, and immune complex-mediated renal disease that has_material_basis_in heterozygous mutation in the COPA gene on chromosome 1q23.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/25894502/
DbXref: OMIM:616414
Dbxref: ORDO:444092

MGI Reference for mouse disease model: https://pubmed.ncbi.nlm.nih.gov/32198142/

Thanks,
Monika

**Comment by lschriml** [comment]
Thank you Monika, 
I will review and get it added.
Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Monika,
   I am going to classify this one as a syndrome, as well as an autoimmune disease. 

autoimmune interstitial lung, joint, and kidney disease
DOID:0081242

Cheers,
Lynn
