### ISSUE TITLE
Review/New Term Request: 'low compliance bladder' & 'overactive bladder syndrome'

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1083]
Review whether 'low compliance bladder' should be considered a disease or moved to SYMP.

Also consider adding 'overactive bladder syndrome' even though 'overactive bladder' is not generally considered a disease (see https://github.com/DiseaseOntology/SymptomOntology/issues/15), since it is often used for diagnoses (see https://www.goldjournal.net/article/S0090-4295(02)02243-4/fulltext). 'overactive bladder syndrome' does appear in publications (see https://pubmed.ncbi.nlm.nih.gov/?term=%22overactive+bladder+syndrome%22&sort=date).

**Comment by lschriml** [comment]
Review:
  -- Let's keep 'low compliance bladder' as a disease, and add a definition.

Sources for the definition:

https://journals.lww.com/fpmrs/Abstract/2020/04000/Low_Bladder_Compliance_in_Women__A_Clinical.7.aspx

Bladder compliance refers to the ability of the bladder to accommodate large volumes of urine. Patients with low bladder compliance may present with persistent urinary incontinence and/or evidence of upper tract damage. Clinicians often may not consider low bladder compliance in their differential for patients complaining of bothersome lower urinary tract symptoms.

http://www.urocenterofnewyork.com/for-women/urinary-problems/low-bladder-compliance-women/

In patients with low bladder compliance, the bladder pressure rises considerably with only incimental increases in bladder volume. This rise in pressure may overcome the resistance offered by the urethra and cause [incontinence](http://www.urocenterofnewyork.com/for-women/urinary-problems/urinary-incontinence-women/).

Low bladder compliance is usually due to longstanding urethral obstruction or a rare neurologic condition such as spina bifida.

**Comment by lschriml** [comment]
'overactive bladder syndrome' - to be reviewed...

**Comment by allenbaron** [comment]
Abrams, et al 2002[^1] is a frequently cited source for Overactive Bladder and it clearly defines it as a syndrome and suggests additional possible synonyms, all of which are used less frequently in the literature. It should be added to DO and not SYMP.


<details>

<summary>Review Details</summary>

# Conclusions

- Overactive bladder is a syndrome.
- Overactive bladder (syndrome) is the most common name.
  - _Syndrome may or may not be included as part of the name in the literature but will be included as the primary name in DO for emphasis on the syndromic nature of the disease._
- Do not include “with or without urge incontinence” in definition.
- Include OAB as a synonym, along with other ICS-suggested names and "overactive bladder".
- Do not create subtypes at this time.
  - _None of the publications suggesting subtypes provide sufficient evidence to support their creation, especially given OAB itself is poorly described and likely to change/split._


## Relevant Details
“Overactive bladder (OAB) is the name for a group of urinary symptoms. It is not a disease.” 
described as a collection of symptoms = syndrome

### Sources:

- Most authoritative (Abrams et al., 2002) [^1] - frequently referenced and described as such
  - Provides 3 names: “overactive bladder syndrome”, “urge syndrome” or “urgency-frequency syndrome”
    - Based on PubMed searches:
      - "urge syndrome” was used but not commonly used now
      - “urgency-frequency syndrome” remains in use
      - “overactive bladder syndrome”, also commonly just “overactive bladder”, remains in use and is the most common
  - Definition: “Urgency, with or without urge incontinence, usually with frequency and nocturia”
    - _The “with or without urge incontinence” is useful for diagnosis but not incidental to the disease definition as it encompasses all possibilities._
  - Suggests “detrusor overactivity” may be a subtype
- Updated authoritative definition (Haylen et al., 2010)[^2]
  - Referenced directly by ICS: https://www.ics.org/glossary/symptom/overactivebladderoaburgencysyndrome
  - Definition: “urinary urgency, usually accompanied by frequency and nocturia, with or without urgency urinary incontinence, in the absence of urinary tract infection or other obvious pathology.”
  - _“in the absence of urinary tract infection or other obvious pathology” is of key importance in distinguishing this syndrome but needs to be standardized to avoid "in the absence of" which does not fit well with DO's style_
- [Overactive Bladder | Polyuria | MedlinePlus](https://medlineplus.gov/overactivebladder.html)
  - not very clear definition
- More recent clinical reviews - subtype info
  - (Peyronnet et al., 2019)[^3]
    - Suggests a spectrum of OAB
    - Supports “detrusor overactivity” as a subtype
  - (Gross et al., 2021)[^4]
    - Suggest two subtypes: “systemic” & “urinary”
- Paywalled but likely relevant:
  - [Inheritance in overactive bladder syndrome | Nature Reviews Urology](https://www.nature.com/articles/s41585-022-00667-1)

### OAB abbreviation
- all hits for OAB and OAB gene at google reference overactive bladder
- no HGNC hits
- no hits in DO

</details>

[^1]: Abrams, P., Cardozo, L., Fall, M., Griffiths, D., Rosier, P., Ulmsten, U., van Kerrebroeck, P., Victor, A., Wein, A., 2002. The standardisation of terminology of lower urinary tract function: Report from the standardisation sub-committee of the International Continence Society. Neurourol. Urodyn. 21, 167–178. https://doi.org/10.1002/nau.10052
[^2]: Haylen, B.T., de Ridder, D., Freeman, R.M., Swift, S.E., Berghmans, B., Lee, J., Monga, A., Petri, E., Rizk, D.E., Sand, P.K., Schaer, G.N., 2010. An International Urogynecological Association (IUGA)/International Continence Society (ICS) joint report on the terminology for female pelvic floor dysfunction. Int. Urogynecology J. 21, 5–26. https://doi.org/10.1007/s00192-009-0976-9
[^3]: Peyronnet, B., Mironska, E., Chapple, C., Cardozo, L., Oelke, M., Dmochowski, R., Amarenco, G., Gamé, X., Kirby, R., Van Der Aa, F., Cornu, J.-N., 2019. A Comprehensive Review of Overactive Bladder Pathophysiology: On the Way to Tailored Treatment. Eur. Urol. 75, 988–1000. https://doi.org/10.1016/j.eururo.2019.02.038
[^4]: Gross, J., Vetter, J.M., Lai, H.H., 2021. Clustering of patients with overactive bladder syndrome. BMC Urol. 21, 41. https://doi.org/10.1186/s12894-021-00812-9
