### ISSUE TITLE
NTR: Developmental delay, hypotrophy, and dysmorphic features without Moebius syndrome

### ISSUE THREAD

**Issue by srengel** [DiseaseOntology/HumanDiseaseOntology#1084]
Include: 
- new disease terms or updates to DO's disease terms
- include the term name in the title of the request

Developmental delay, hypotrophy, and dysmorphic features without Moebius syndrome

- It is helpful to include a definition and PubMed reference for new terms

PMID: 33474647

Human recessive disorder associated with a REV3L variant. 
First reported case of a REV3L associated disease different from Moebius syndrome both in terms of clinical manifestations and inheritance (autosomal recessive rather than dominant). 

- It is useful to share information on the relevant project 

SGD www.yeastgenome.org

- include contact information along with your ORCID id, so that we can provide attribution for your contribution

Stacia Engel
stacia@stanford.edu
SGD www.yeastgenome.org
ORCID 0000-0001-5472-917X

**Comment by lschriml** [comment]
Thank you Stacie,
 I have added this new disease to the DO.
Cheers,
Lynn
