### ISSUE TITLE
review DOID:0050976

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1086]
OMIM has merged OMIM:609307 into OMIM:193003 and renamed OMIM:193003 to the name that had been used for OMIM:609307

 OMIM:609307 is the sole xref for DOID:0050976 
OMIM:193003 is the sole xref for DOID:0111794

OMIM:193003 has been moved to be a member of the Spinocerebellar ataxia phenotypic series - [PS164400](https://www.omim.org/phenotypicSeries/PS164400)

Recommend we obsolete DOID:0111794 and change the OMIM xref for DOID:0050976 to OMIM:193003

Need to review the definition of DOID:0111794 as the OMIM record now has additional gene related information

**Comment by lschriml** [comment]
Done
Notes 

**in DO:** 

**OMIM:609307**       spinocerebellar ataxia type 27 (DOID:0050976)
       An autosomal dominant cerebellar ataxia that is characterized by slowly progressive ataxia, early-onset tremor and dyskinesia, and has_material_basis_in mutation in the FGF14 gene. 

**OMIM:193003**   congenital nystagmus 4. (DOID:0111794)
     A congenital nystagmus that has_material_basis_in heterozygous mutation in a region of chromosome 13q31-q33. 
       syn: autosomal dominant congenital nystagmus 4 


OMIM: 
   Merged OMIM:609307 into OMIM:193003, OMIM name:  SPINOCEREBELLAR ATAXIA 27

OMIM:193003 has been moved to be a member of the Spinocerebellar ataxia phenotypic series - [PS164400](https://www.omim.org/phenotypicSeries/PS164400)

Update: Merging  congenital nystagmus 4. (DOID:0111794) (& thus obsoleting) into spinocerebellar ataxia type 27 (DOID:0050976).
 
spinocerebellar ataxia type 27 (DOID:0050976)
      --> will be xref'd to: OMIM:193003
        --> will be removed
    --> [GARD:9603] is an empty record for autosomal dominant congenital nystagmus 4
