### ISSUE TITLE
Add non-Hodgkin lymphoma DOID:0060060 to the cancer slim file

### ISSUE THREAD

**Issue by kkrysiak** [DiseaseOntology/HumanDiseaseOntology#1099]
For CIViC, this doesn't appear in the cancer slim subset (according to the DO UI list).

**Comment by lschriml** [comment]
Thank you KK, we will add this to the slim.
Happy Holidays,
Lynn

**Comment by allenbaron** [comment]
Kilannin, it's been added and will be in the next release. If there are any other cancers needed by CIViC, please let us know.

Happy holidays!
