### ISSUE TITLE
Fix polyhierarchy

### ISSUE THREAD

**Issue by elviram** [DiseaseOntology/HumanDiseaseOntology#110]
_From @cmungall on June 13, 2014 12:43_

Short term: add links as required by users (no single inheritance constraint)

Medium term: infer polyhierarchy (depends on axiomatization)

_Copied from original issue: obophenotype/human-disease-ontology#9_

**Comment by lschriml** [comment]
DO's hierarchy: 
   Maintaining single inheritance constraint for is_a parents
  Adding in equivalencies for OWL file.
