### ISSUE TITLE
Replace standard Uberon labels with human-centric versions

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1114]
Opening this issue for continued discussion based on PR #1108.

**Comment by allenbaron** [comment]
Some human synonyms have been tagged with "human_preferred" but it's not consistent (https://github.com/obophenotype/uberon/issues/278).

**Comment by allenbaron** [comment]
Also it seems the need for human labels is on the Uberon teams radar (https://github.com/obophenotype/uberon/issues/1522#issuecomment-547575843).

**Comment by lschriml** [comment]
@allenbaron - have you submitted a ticket with Uberon for this issue ?

**Comment by allenbaron** [comment]
I reviewed relevant issues and pulled together background here to determine if progress has been made but it doesn't look like there has been any movement on this, so I've opened https://github.com/obophenotype/uberon/issues/2860.

**Comment by lschriml** [comment]
@allenbaron -- can we close this ticket ?

**Comment by allenbaron** [comment]
We did it for a handful of the most obvious non-human labels (e.g. pes) in a semi-automated way. There are still some that are not very human-like (e.g. 'paired limb/fin segment') but I don't think any of those are used in logical axioms. There's still no fully automated approach to use only human labels. I guess it depends on how far we want this to go.

It does seem like there have been some changes in how Uberon makes the human subset. No telling if that would be relevant to this particular issue. I would have to look into whether those changes include preferring human labels.

**Comment by lschriml** [comment]
Sounds good.For now, let’s close the ticket.Plan to revisit at a future date.Sent from my iPhoneOn Nov 16, 2023, at 4:06 PM, J. Allen Baron ***@***.***> wrote:﻿
We did it for a handful of the most obvious non-human labels (e.g. pes) in a semi-automated way. There are still some that are not very human-like (e.g. 'paired limb/fin segment') but I don't think any of those are used in logical axioms. There's still no fully automated approach to use only human labels. I guess it depends on how far we want this to go.
It does seem like there have been some changes in how Uberon makes the human subset. No telling if that would be relevant to this particular issue. I would have to look into whether those changes include preferring human labels.
