### ISSUE TITLE
chronic granulomatous disease location axiom problem

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#1115]
[chronic granulomatous disease](http://purl.obolibrary.org/obo/DOID_3265)
is defined as equivalent to
    'primary immunodeficiency disease'
     and ('disease has location' some 'zone of skin')
     and ('disease has location' some 'bone element')
     and ('disease has location' some lung)

I think the use of "and" is wrong here. There will be no intersection of "zone of skin" AND "bone element" AND "lung".
I think the proper is to use OR:
    'primary immunodeficiency disease'
     and ('disease has location' some ('zone of skin' or 'bone element' or lung))

**Comment by lschriml** [comment]
Thank you Asiyah !!

**Comment by allenbaron** [comment]
Thank you for pointing this out. I agree that 'AND' should not be used here.

I've noted that the locations in this axiom are also not all-inclusive for the possible locations of granuloma formation.
- https://www.ncbi.nlm.nih.gov/books/NBK99496/ states that granulomas form in the bladder and gastrointestinal tract
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5709447/ states that granulomas form in the GI tract, lungs, urogenital tract, and eyes.
- https://www.jacionline.org/article/S0091-6749(14)00589-2/fulltext expands 'inflammatory episodes' to those mentioned by others along with skin, central nervous system, and tympanum.

The location of inflammation is likely to be more widespread, particularly if the location of 'inflammatory episodes' related to infections are considered.

Given the wide array of potential locations affected by this disease, it might be best to remove this location-based axiom altogether.

One additional consideration is whether 'has phenotype' [Granuloma](http://purl.obolibrary.org/obo/HP_0032252)) might be appropriate. The sources listed indicate that a large proportion of patients develop granulomas, though this phenotype might not be universal.

**Comment by linikujp** [comment]
It seems that the anatomical position can not be the necessary condition to define this term, unless you list out every anatomical locations, which can be everywhere, because the manifestation of the disease is not restricted to certain locations. See https://en.wikipedia.org/wiki/Chronic_granulomatous_disease
**Chronic granulomatous disease** (CGD), also known as Bridges–Good syndrome, chronic granulomatous disorder, and Quie syndrome,[[1]](https://en.wikipedia.org/wiki/Chronic_granulomatous_disease#cite_note-Bolognia-1) is a diverse group of [hereditary diseases](https://en.wikipedia.org/wiki/Genetic_disorder) in which _**certain cells of the [immune system](https://en.wikipedia.org/wiki/Immune_system) have difficulty forming the reactive [oxygen](https://en.wikipedia.org/wiki/Oxygen) compounds (most importantly the [superoxide](https://en.wikipedia.org/wiki/Superoxide) radical due to defective phagocyte [NADPH oxidase](https://en.wikipedia.org/wiki/NADPH_oxidase))**_ used to kill certain ingested [pathogens](https://en.wikipedia.org/wiki/Pathogen).[[2]](https://en.wikipedia.org/wiki/Chronic_granulomatous_disease#cite_note-titleChronic_Granulomatous_Disease:_Immunodeficiency_Disorders:_Merck_Manual_Professional-2) This leads to the formation of [granulomas](https://en.wikipedia.org/wiki/Granuloma) in many organs.[[3]](https://en.wikipedia.org/wiki/Chronic_granulomatous_disease#cite_note-Heyworth-3)

The "certain cells of the immune system have difficulty forming the reactive oxygen compounds" seems a key condition of this disease that necessarily differentiate it from other disease.,

**Comment by allenbaron** [comment]
I've removed the location-based equivalent class axiom and added a weaker subclass axiom indicating this disease 'has phenotype' Granuloma (other diseases also have granulomas; see "Disorders with Similar Symptoms" from https://rarediseases.org/rare-diseases/chronic-granulomatous-disease/).

I think defects in the NADPH oxidase complex are more specific to this disease than difficulty producing ROS.

Thanks Asiyah.
