### ISSUE TITLE
conceptualisation and definitions surrounding major depressive disorder and related classes

### ISSUE THREAD

**Issue by reality** [DiseaseOntology/HumanDiseaseOntology#1116]
**Is your request related to a specific disease? Please describe.**
major depressive disorder/endogenous depression/melancholia

**Describe the proposed **

definition of "major depressive disorder" (DOID:1470) is currently:

```An endogenous depression that is characterized by an all-encompassing low mood accompanied by low self-esteem, and by loss of interest or pleasure in normally enjoyable activities. ```

This indicates it is a kind of endogenous depression (DOID:1595), however it is asserted as a superclass of endogenous depression[1]. 

"Endogenous depression" was the previous specifier for what is now known as melancholic depression or "Major Depressive Disorder with melancholic features." in DSM5 [2] So the current subsumption structure is correct, but the definition should not state that MDD is a kind of endogenous depression, and we should update the label of endogenous depression. The DSM-5 seems to de-emphasize characterisation by any particular biological basis (accordingly with the label change). I have suggested a new definition below based on the DSM item; we could also consider adding a sentence about a 'usually considered to have biological basis' or similar here, but it feels a little wooly to me.

Also of note is that we have a separate melancholia (DOID:2848) class; there is no definition here so I'm not sure if it's meant to be considered separate to melancholic depression. I suspect that it is meant in the more general sense e.g. low mood, in which case it would perhaps more correctly be considered as a phenotype, belonging in HPO, rather than a disease?

Also just for general consideration, some consider that melancholic depression should be considered a separate mood disorder [3]

Proposed changes: 

* Change definition of major depressive disorder (DOID:1470) to ```Mental depression that is characterized by an all-encompassing low mood accompanied by low self-esteem, and by loss of interest or pleasure in normally enjoyable activities. ```
* Change definition of endogenous depression (DOID:1595) to ```A major depressive disorder that is characterized by a severe loss of pleasure and prominent physical symptoms.```
* Change label of endogenous depression to melancholic depression, keeping endogenous depression as a synonym

If I can get some confirmation that these changes are sensible then I'm happy to submit a pull request!

Thanks a lot!

**References**
[1] https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_1470&lang=en&viewMode=PreferredRoots&siblings=false
[2] https://www.psychdb.com/mood/1-depression/melancholic
[3] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3733615/

**Comment by lschriml** [comment]
Thank you for submitting this review. 
We greatly appreciate your suggestions.
We will review and revise the DO, and will share the update via this ticket.
For changes to the DO, we process them via these tickets, rather than pull requests, 
as we will often need to make several types of updates. 
If you can share with us your name, ORCID ID, and the information on the project you are working on,
we would like to add you to our Contributors, and to recognize your contribution.
Cheers,
Lynn

**Comment by reality** [comment]
Hi,

Thanks a lot! My ORCID is https://orcid.org/0000-0001-9227-0670 . I'm using DO for quite a few projects but the context in which I discovered this issue was investigation into identification of disease-phenotype associations from text. I am in George Gkoutos' lab.

**Comment by lschriml** [comment]
Great !!
If your project's have website/publications, we would be happy to feature them on our website.

Cheers,
Lynn

**Comment by allenbaron** [comment]
The definition for 'major depressive disorder' (DOID:1470) has now been updated to "A depressive disorder that is characterized by at least two weeks of loss of interest or pleasure in normally enjoyable activities or depressed mood along with additional cognitive or somatic impairments such as appetite or weight changes, sleep difficulties, psychomotor agitation or retardation, fatigue or loss of energy, diminished ability to think or concentrate, feelings of worthlessness or excessive guilt, and suicidality."

As you suggested, 'endogenous depression' (DOID:1595) has been renamed to ‘melancholic depression’. We agree that melancholia should not be listed as a separate disease and have deprecated DOID:2848 and added a 'term replaced by' (IAO:0100001) tag to indicate DOID:1595 should be used instead. The definition for ‘melancholic depression’ has been updated to “A major depressive disorder characterized by near-complete absence of pleasure.”

After additional review of mental depression and its subtypes, prompted by your suggestions, numerous xrefs have been updated and 'mental depression' (DOID:1596) has been renamed to 'depressive disorder' with the following definition added: "A mood disorder characterized by persistent sadness, emptiness, or irritability and decreased ability to function."

All of these updates will be included in the next release. Thanks again for your input.
