### ISSUE TITLE
sickle cell anemia (DOID:10923)

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1118]
OMIM updated the label of 'sickle cell anemia' to 'sickle cell disease' (OMIM:603903).

ORDO has not made this change, looking at their definition for SCA: 

"A severe form of sickle cell disease (SCD) characterized by homozygosity for the sickle hemoglobin (HbS) gene and which acutely manifests with severe anemia, susceptibility to severe bacterial infections, and ischemic vasoocclusive accidents (VOA). It is a red cell disease of genetic origin which manifests with hemolytic disease and loss of red cell deformability leading to other occlusive events." 

I don't think they will.

Looking at ORDO they have "[Sickle cell disease and related diseases](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=20325&disease=Sickle-cell-disease-and-related-diseases&search=Disease_Search_Simple)" that groups SCA/SCD with other hemoglobin anomalies (not HBB) that produce a sickle shaped red blood cell but are not 'sickle cell disease'.

I'm not sure we want to mess with the label for DOID:10923. Poking in PubMed it seems like SCD is used both to mean a "group of genetic conditions that result from the inheritance of abnormal haemoglobin genes" (PMID: 33251574) and to mean "sickle cell disease (SCD) comprises a complex group of hematologic disorders that share a common genetic link - a missense mutation in the seventh codon of the β-globin gene that leads to adenine being replaced with thymine (GAG→GTG)". (PMID: 31413089)

We may want to add sickle cell disease as a broad synonym for sickle cell anemia.

We may also want to consider adding a grouping term for the various types of sickle cell diseases that can be produced by mutations in the different HB genes.

Sue

**Comment by lschriml** [comment]
Review: 
https://www.ncbi.nlm.nih.gov/books/NBK1377/


Notes: 
**Nomenclature**
Historically in the US the term **sickle cell anemia** has been used to describe persons homozygous for p.Glu6Val  (i.e., Hb S/S) or, at times, persons with Hb S/β0-thalassemia. 

With increased awareness of the broad spectrum of clinically significant sickle hemoglobinopathies with varying degrees of anemia, the trend has been to use the umbrella term **"sickle cell disease"** (SCD). The term SCD should be followed by a detailed genotypic description for the individual (e.g., Hb S/S, Hb S/C, Hb S/β0-thalassemia).

https://medlineplus.gov/genetics/condition/sickle-cell-disease

**Sickle cell disease** is a group of disorders that affects [hemoglobin](https://medlineplus.gov/images/PX000154_PRESENTATION.jpeg), the molecule in red blood cells that delivers oxygen to cells throughout the body. People with this disease have atypical hemoglobin molecules called hemoglobin S, which can distort red blood cells into a [sickle](https://medlineplus.gov/images/PX0000M0_PRESENTATION.jpeg) or crescent shape.

In people with **sickle cell disease,** at least one of the beta-globin subunits in hemoglobin is replaced with hemoglobin S. 
In **sickle cell anemia** (also called homozygous sickle cell disease or HbSS disease), which is the most common form of sickle cell disease, hemoglobin S replaces both beta-globin subunits.

The most common type are: Sickle Cell Anemia (SS), Sickle Hemoglobin-C Disease (SC), Sickle Beta-Plus Thalassemia and Sickle Beta-Zero Thalassemia.

https://en.wikipedia.org/wiki/Sickle_cell_disease

**Subtypes:**
**Sickle Cell Anaemia (HbSS)**
             -- Hemoglobin SS

**Sickle Cell Disease-SC (HbSC)** (aka: hemoglobin SC disease (HbSC))
              Synonyms; hemoglobin SC; haemoglobin C with sickling disease; HbSC
                   - S/C genotype and involves the inheritance of one sickle gene mutation and one HbC gene mutation.

**Sickle Beta Thalassaemia** (aka: hemoglobin sickle-beta-thalassemia (beta-thalassemia positive or 
                                                          beta-thalassemia negative).) 
                -  inherits a sickle gene mutation from one parent and a thalassemia gene mutation from the 
                 other parent, sickle beta thalassemia can present with characteristics of both blood diseases.

              --> Hemoglobin Sβ0 thalassemia - sickle beta zero thalassaemia (HbS/β0)
              --> Hemoglobin Sβ+ thalassemia - sickle beta plus thalassaemia (HbS/β+

 **rare types of sickle cell disease, which include:**

Haemoglobin-SD disease (HbSD)
Haemoglobin-SE disease (HbSE)
Haemoglobin-SO Arab disease (HbSO)
Hemoglobin SD
Hemoglobin SE

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2561539/

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7613509/
           Sickle Cell Anemia and Its Phenotypes

https://www.ncbi.nlm.nih.gov/books/NBK537130

**Sickle cell trait** (SCT) is a benign condition in which the affected individual has only one abnormal hemoglobin beta gene allele. 
              sickle cell trait (HbAS), which carries a heterozygous mutation and seldom presents clinical signs or symptoms.
                    - https://www.ncbi.nlm.nih.gov/books/NBK482164/

**Comment by lschriml** [comment]
- Added 'sickle cell disease' parent term
- Going to hold off on adding the genetic subtypes for now, not enough information that these are distinct diseases.
