### ISSUE TITLE
glycogen storage disease I

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1126]
Hi Lynn,

This is a confusing one

glycogen storage disease I ([DOID:2749](http://www.disease-ontology.org/?id=DOID:2749)) is defined as " A glycogen storage disease that has_material_basis_in deficiency of the glucose-6-phosphatase enzyme which impairs the ability of the liver to produce free glucose from glycogen and from gluconeogenesis and is characterized by accumulation of glycogen and fat in the liver and kidneys, resulting in hepatomegaly and renomegaly."

This term has 3 OMIM xrefs [OMIM:232200](http://www.omim.org/entry/232200), [OMIM:232220](http://www.omim.org/entry/232220), and [OMIM:232240](http://www.omim.org/entry/232240) for sub-types 1a, 1b, and 1c

I got an email this morning from another MGI curator wondering why we had association of both G6PC1 and SLC37A4 to this disease. Initially I read the definition in DO as referring to the gene but I think it is referring to deficiency of the gene product in the appropriate location. Looking in Orphanet in the etiology section I see "The disease is due to a dysfunction in the G6P system, a key step in glycemia regulation. Mutations in the G6PC gene (17q21) cause a deficit of the catalytic subunit G6P-alpha restricted to expression in the liver, kidney and intestine (type a), and mutations in the SLC37A4 gene (11q23) cause a deficit of the ubiquitously expressed G6P transporter (G6PT) or G6P translocase (type b)."  I think we may want to modify the DO definition to  make it clear that 
"has_material_basis_in deficiency of the glucose-6-phosphatase enzyme" does not mean there is a defect in the gene.

We could also consider adding separate terms for the 3 subtypes. 

Thanks,
Sue

**Comment by ukemi** [comment]
Hi Lynn! Hope all is well. 
I originally pinged @sbello  about this because the DO definition made it sound like the disease should only be a result of a mutation in the G-6-phosphatase. But we also had a transporter that transports the G-6-P to the ER associated with the disease. From @sbello 's analysis above, I think the definition of DOID:2749 only fits type a. The transporter should be associated with b and c (PMID:18337460).
-David

**Comment by sbello** [comment]
@ukemi That was my initial thought as well, DOID:2749 becomes 1a and new terms are entered for the parent and types 1b and 1c. The cross-references on the DO term made me wonder if the definition was just confusing G-6-P with the G-6-phosphatase enzyme.

**Comment by lschriml** [comment]
Thank you @sbello and @ukemi (David) !! 
   I can see from this disease record that the disease and definition were written prior to the three subtypes being defined, I will split the this out to the subtypes. 

I will rename : DOID:2749 from glycogen storage disease I to glycogen storage disease Ia
   -- will create a new parent term: glycogen storage disease I
      and add in type 1b and 1c 

Cheers,
Lynn
