### ISSUE TITLE
review DOID:3529 and DOID:0080991

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1131]
**Is your request related to a specific disease? Please describe.**
  
DOID:3529 and DOID:0080991

**Describe the proposed **
OMIM has changed these records

- OMIM:117000 | Central Core Disease of Muscle; CCD changed to Congenital Myopathy 1a, Autosomal Dominant, with Susceptibility to Malignant Hyperthermia; CMYP1A - xref to DOID:3529
- OMIM:255320 | Minicore Myopathy with External Ophthalmoplegia changed to Congenital Myopathy 1b, Autosomal Recessive; CMYP1B - xref to DOID:0080991

Currently these are in DO but only share the ancestor term myopathy. Based on the organization in OMIM it seems like these should share a common parent.

The DO term OMIM:117000 is defined as
 A congenital structural myopathy that is characterized by motor developmental delay and signs of mild proximal weakness most pronounced in the hip girdle musculature and that has_material_basis_in heterozygous, homozygous, or compound heterozygous mutation in the ryanodine receptor-1 gene (RYR1) on chromosome 19q13.

This does not match the revised definition of OMIM:117000 which is now specific for the dominant form

I think we need to review and revise these. MY inclination is to create a new child of DOID:3529 for the dominant disease and move the recessive DO term under here but need to make sure that the OMIM and DO terms really represent the same disease. Will try to add more notes later when I take a better look. 

**References**
Provide links to a database or a PubMed ID

**Comment by lschriml** [comment]
We are reviewing these terms and the nomenclature updates, which look to be ongoing.
Will have these figured out and updated for the next release in April.

**Comment by lschriml** [comment]
The classification has been updated, the definition revised, as noted above.
