### ISSUE TITLE
Review DOID:0110071 and DOID:0060675

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1138]
OMIM has merged 600996 into [604772](https://www.omim.org/entry/604772)

600996 is an xref for DOID:0110071 the only other xref for this is ICD10CM:I42.8  

604772 is an xref for DOID:0060675 the only other xref for this is ICD10CM:I47.2

Both involve mutations in RYR2 and heart

My inclination is to merge these two DO terms.

**Comment by lschriml** [comment]
-- Agreed, seeing the merge in OMIM, merging DOID:0110071 into DOID:0060675
 [DONE]

Notes: 

OMIM:600996 is arrhythmogenic right ventricular dysplasia 2 DOID:0110071
An arrhythmogenic right ventricular dysplasia that has_material_basis_in heterozygous mutation in the cardiac ryanodine receptor-2 gene (RYR2) on chromosome 1q43.

        definition ref:  https://pubmed.ncbi.nlm.nih.gov/11159936/
Identification of mutations in the cardiac ryanodine receptor gene in families affected with arrhythmogenic right ventricular cardiomyopathy type 2 (ARVD2)


OMIM:604772. catecholaminergic polymorphic ventricular tachycardia 1  - DOID:0060675
A catecholaminergic polymorphic ventricular tachycardia that is characterized by autosomal dominant inheritance and has_material_basis_in heterozygous mutation in the RYR2 gene on chromosome 1q43
