### ISSUE TITLE
New Term: Left Ventricular Noncompaction 1

### ISSUE THREAD

**Issue by ybradford** [DiseaseOntology/HumanDiseaseOntology#114]
Hi,

I would like to request a new term 'LEFT VENTRICULAR NONOMPACTION 1' , OMIM 604169; synonyms: LVNC1, LEFT VENTRICULAR NONCOMPACTION 1 WITH OR WITHOUT CONGENITAL HEART DEFECTS.

I  need it for annotation of PMID: 23768516.  Please let me know if you have any questions.
Thanks,
Yvonne

**Comment by elviram** [comment]
Hello Yvonne,

we will get back to you with an update on the term by the end of next week.

Best,
Elvira

**Comment by ybradford** [comment]
Hi Elvira,

Thanks - appreciate your help with it. 

Best,
Yvonne

**Comment by elviram** [comment]
Hi Yvonne,

the term will be added and will be in the new DO release on Monday.

Best,
Elvira
