### ISSUE TITLE
DOID_1727 IS-A DOID_8483 seems wrong

### ISSUE THREAD

**Issue by psiotwo** [DiseaseOntology/HumanDiseaseOntology#1142]
**Is your request related to a specific disease? Please describe.**
retinal vein occlusion (DOID_1727) is stated to be subClassOf retinal artery occlusion (DOID_8483).

**Describe the proposed **
Since veins are not arteries, this subclassof link seems incorrect

**Comment by lschriml** [comment]
Hello Petr,
   Thank you for pointing this out !! 
Agreed, this was an error which has now been fixed.
Cheers,
Lynn
