### ISSUE TITLE
Addition of Chlamydia

### ISSUE THREAD

**Issue by nkaramooz** [DiseaseOntology/HumanDiseaseOntology#115]
Hi I was wondering why all of the chlamydial diseases have been marked as obsolete. It seems like an entry for chlamydia would fit under "primary bacterial infectious disease" DOID:  0050338

Also if there is anything I can help with would be more than happy to contribute some time to this tremendously valuable project!

**Comment by elviram** [comment]
Hello nkaramooz,

we will get back to you after the holidays. Thank you so much for your willingness to contribute. We will be in contact to see how you could help.

Best,
Elvira

**Comment by nkaramooz** [comment]
Hi I just wanted to re-ping this thread as I'm curious why Chlamydia was removed (it seems like even having a group for sexually transmitted infections would be useful).

**Comment by elviram** [comment]
Hello,
the term was obsoleted a long time ago. Right now, 'Chlamydial conjunctivitis' can be found as a synonym to 'inclusion conjunctivitis' (DOID:13800). There is a discussion about maybe re-structuring the bacterial diseases, thus the delay. We will keep you informed.

Best,
Elvira

**Comment by lschriml** [comment]
chlamydia has been added back into DO. 
These edits will be in our public files this Friday.
Cheers,
Lynn
