### ISSUE TITLE
New term request: ACROCARDIOFACIAL SYNDROME; ACFS

### ISSUE THREAD

**Issue by Xenbase2** [DiseaseOntology/HumanDiseaseOntology#1177]
I'd like to request a term for ACROCARDIOFACIAL SYNDROME; ACFS

OMIM ID: 600460 
[https://omim.org/entry/600460?search=600460&highlight=600460]
CLEFT PALATE, CARDIAC DEFECT, GENITAL ANOMALIES, AND ECTRODACTYLY
perhaps more commonly referred to as ACROCARDIOFACIAL SYNDROME; ACFS

Potential parent terms: RASopathy, syndrome

Malacards entry CLF044: [https://www.malacards.org/card/cleft_palate_cardiac_defect_genital_anomalies_and_ectrodactyly?search=ACROCARDIOFACIAL%20SYNDROME%3B%20ACFS]

Definitions
GARD: A rare genetic disorder characterized by split-hand/split-foot malformation (SHFM), facial anomalies, cleft lip/palate, congenital heart defect (CHD), genital anomalies, and intellectual deficit.

Orphanet:A rare genetic disorder characterized by split-hand/split-foot malformation (SHFM), facial anomalies, cleft lip/palate, congenital heart defect (CHD), genital anomalies, and intellectual deficit.

Recent citations ( not in OMIM entry) using Xenopus as a model for ACFS,  identifies RAF1 as causal  gene involved in  this rare neonatal lethal syndrome.

XB-ART-59687: Wong et al 2023.  EMBO Mol Med (2023)e17078https://doi.org/10.15252/emmm.202217078

My contact information: Christina.James_Zorn@cchmc.org

Thanks!

**Comment by allenbaron** [comment]
Thank you for bringing this disease to our attention Christina. We're just coming back from the Biocuration conference and will be happy to review the information you've provided and add it to the ontology.

**Comment by lschriml** [comment]
Thank you for the new term !! 

We will add this disease, as a subtype of 'syndrome', as "Acrocardiofacial syndrome",
   we will include the exact synonym: 
          cleft palate-cardiac defect-genital anomalies-ectrodactyly syndrome
and 
     cleft palate, cardiac defect, genital anomalies, and ectrodactyly
 
Cheers,
Lynn

**Comment by Xenbase2** [comment]
thanks Lynn!

From: lschriml ***@***.***>
Date: Wednesday, May 24, 2023 at 4:28 PM
To: DiseaseOntology/HumanDiseaseOntology ***@***.***>
Cc: xenbase ***@***.***>, Author ***@***.***>
Subject: Re: [DiseaseOntology/HumanDiseaseOntology] New term request: ACROCARDIOFACIAL SYNDROME; ACFS (Issue #1177)

This email originated from an EXTERNAL sender to CCHMC. Proceed with caution when replying, opening attachments, or clicking links in this message.



Thank you for the new term !!

We will add this disease, as a subtype of 'syndrome', as "Acrocardiofacial syndrome",
we will include the exact synonym:
cleft palate-cardiac defect-genital anomalies-ectrodactyly syndrome
and
cleft palate, cardiac defect, genital anomalies, and ectrodactyly

Cheers,
Lynn

**Comment by allenbaron** [comment]
Added as DOID:0070419.
