### ISSUE TITLE
New Term Request: Pierpont syndrome 

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1182]
Hi Lynn, 
I'd like to request the term below for MGI, for the following paper which makes the mouse model: https://pubmed.ncbi.nlm.nih.gov/35416977/

Label: Pierpont syndrome
Definition: A rare multiple congenital anomaly syndrome characterized by developmental delay and learning disability, distinctive facial characteristics, plantar fat pads and other limb anomalies that has_material_basis_in heterozygous mutation in the TBL1XR1 gene on chromosome 3q26.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/21834056/
Exact synonym: Plantar lipomatosis-unusual facies-developmental delay syndrome
DbXref: OMIM:602342
Dbxref: ORDO:487825

Thank you,
Monika Tomczuk (MGI)

**Comment by csbjohnson** [comment]
Thank you very much for your term request for Pierpont syndrome, @MonikaTomczuk.

We'll review it, get back to you soon and update the DO for the next release.

**Comment by lschriml** [comment]
Hello Monika,
   Looking at the gene involved, I see that this gene defines another OMIM record, OMIM:616944;
autosomal dominant intellectual developmental disorder-41 (MRD41)
   which is DOID:0070071

Reading through the clinical synopsis, I am thinking that  Pierpont syndrome (OMIML602342) and  (MRD41) are representing the same disease.
What do you think ?

Cheers,
Lynn

**Comment by MonikaTomczuk** [comment]
Hi Lynn,
I think that they may be different based on the following report: https://pubmed.ncbi.nlm.nih.gov/36843287/ which differentiates Pierpont syndrome from MRD-41. According to OMIM, MRD-41 is associated with deletions, while Pierpont syndrome is due to heterozygous missense mutations. The following paper https://pubmed.ncbi.nlm.nih.gov/26769062/ also makes the distinction that autism is not present in individuals with Pierpont syndrome but is seen in MRD-41. So I think they are different diseases. Also see https://pubmed.ncbi.nlm.nih.gov/16007632/ which argues that Pierpont syndrome is a separate MR syndrome.

Best,
Monika

**Comment by lschriml** [comment]
Hello Monika,
   Thank you for the insight and the references !!
I have added Pierpont syndrome to the DO, DOID:0081362

Cheers,
Lynn
