### ISSUE TITLE
Determine disease(s) that should map to Orphanet's Ovarioleukodystrophy subtype

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1193]
**Is your request related to a specific disease? Please describe.**
[Ovarioleukodystrophy](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=14426&disease=Ovarioleukodystrophy&search=Disease_Search_Simple), ORDO:99853

**Describe the proposed change(s)**
Orphanet describes this disease as a subtype of CACH syndrome, which is equivalent to 'leukoencephalopathy with vanishing white matter', DOID:0060868). Like other subtypes of CACH syndrome at Orphanet this subtype is based on phenotype and does not match up with any of the etiological subtypes described in DO. It may be most appropriate as an Xref/skos:narrowMatch on DOID:0060868 but first there is a need to confirm that it is not a feature of other diseases.

On quick glance, results of a [PubMed search for ovarioleukodystrophy](https://pubmed.ncbi.nlm.nih.gov/?term=ovarioleukodystrophy&sort=date) suggest at least that it may be a feature of two of the CACH subtypes, in agreement with Orphanet's connection to two OMIM subtypes.

**References**
- [OMIM search for ovarioleukodystrophy](https://omim.org/search?index=entry&start=1&limit=10&sort=score+desc%2C+prefix_sort+desc&search=ovarioleukodystrophy): multiple matches.
- [CACH syndrome](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=3664&disease=CACH-syndrome&search=Disease_Search_Simple): Orphanet's description of disease including subtypes.

**Comment by lschriml** [comment]
Two Diseases:
**[1]** 
**leukoencephalopathy with vanishing white matter' (DOID:0060868)**
      OMIM: 603896
      ORDO: 135
      GARD:231
           synonym: CASH, CASH syndrome, childhood ataxia with central nervous system hypomyelination
[add synonyms to DOID:0060868]
      OMIM definition: 
         - homozygous or compound heterozygous mutation in the EIF2B1 gene on chromosome 12q24.
         - characterized by variable neurologic features, including progressive cerebellar ataxia, spasticity, and cognitive impairment associated with white matter lesions on brain imaging.

[2] 


    To do: add new term to DO:  (as a child of leukodystrophy)
           OMIM:615889  progressive leukoencephalopathy with ovarian failure
           OMIM definition: 
               - caused by compound heterozygous mutation in the AARS2 gene on chromosome 6p21.
               - characterized by loss of motor and cognitive skills, usually with onset in young adulthood. 

          synonym: ovarioleukodystrophy

           ORPHA:99853. Ovarioleukodystrophy
          -- includes mappings to both OMIM:603896 and OMIM:615889 (progressive leukoencephalopathy  
              (LKENP) with ovarian failure)

  ovarioleukodystrophy is no longer commonly used to describe this condition. I noticed that a number of sites (above) include a mixture of the nomenclature and conflate the two conditions. The conditions are caused by two different genes. 

An informative citation: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10047219/

**Comment by lschriml** [comment]
yes, add the Orphanet ID to both DO records.
