### ISSUE TITLE
New term requests: ARC syndrome has children

### ISSUE THREAD

**Issue by SianGramates** [DiseaseOntology/HumanDiseaseOntology#120]
ARC syndrome DOID:0050763 has a definition that explicitly describes only ARC syndrome 1 (OMIM:208085 ARTHROGRYPOSIS, RENAL DYSFUNCTION, AND CHOLESTASIS 1; ARCS1), as it mentions that ARC syndrome results from mutation in VPS33B.

ARC syndrome 2 (OMIM:613404 ARTHROGRYPOSIS, RENAL DYSFUNCTION, AND CHOLESTASIS 2; ARCS2) is genetically distinct, and caused by mutation in VIPAS39.
Both are part of (and completely comprise) OMIM phenotypic series PS208085, Arthrogryposis, renal dysfunction, and cholestasis

**Comment by elviram** [comment]
Hello Sian,

the definition of the term has been updated to include the VIPAR (VIPAS39) mutation.
Thank you for picking that up.

Best,
Elvira

**Comment by SianGramates** [comment]
Thanks!
(I assume you've figured out that I was siangramates on SourceForge)
