### ISSUE TITLE
Waardenburg syndrome type 2D (DOID:0110952)

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1207]
Waardenburg syndrome type 2D (DOID:0110952)

OMIM has merged the entry for type 2D into the description for type 2A with the comment:

"A form of WS2, designated WS2D, was thought to be caused by deletion of the SNAI2 gene ([602150.0001](https://www.omim.org/entry/602150#0001)), but the deletion has been reclassified as a variant of unknown significance."

Based on this I think DO should obsolete the 2D term

**Comment by allenbaron** [comment]
Makes sense to me. I'm going to add [Mirhadi et al. (2020)](https://pubmed.ncbi.nlm.nih.gov/32975012/) as a reference on the definition and add a comment explaining the obsoletion. That way if better evidence should arise to support SNAI2 as a pathogenic variant we can more easily find this and resurrect it.... though this seems unlikely.

I'll also update piebaldism (DOID:3263) so it no longer references SNAI2 in the definition. Perhaps I'll add a comment there as well.
