### ISSUE TITLE
Some ICD-10 mappings, mostly for cancers

### ISSUE THREAD

**Issue by reality** [DiseaseOntology/HumanDiseaseOntology#1209]
We developed these missing ICD10 xrefs as part of a research project and wanted to contribute them back to the ontology:

**Describe the proposed change(s)**
DOID:3451: ICD10:C44.9
DOID:4451: ICD10:C64.9
DOID:0080784: ICD10:N39.0
DOID:0070004: ICD10:C92
DOID:4001: ICD10:C56
DOID:0060060: ICD10:C85.9
DOID:0050861: ICD10:C18.9
DOID:1542: ICD10:C76.0
DOID:4667: ICD10:M40.209
DOID:10247: ICD10:R09.1
DOID:9909: ICD10:H00.019

My ORCID: https://orcid.org/0000-0001-9227-0670

Many thanks!

**Comment by csbjohnson** [comment]
Thank you for the ICD10 codes @reality!

The following changes have been made and will be in the next release:

DOID:3451 selected ICD10:C44.90 as best fitting
DOID:4451: ICD10:C64.9
DOID:0080784: ICD10:N39.0
DOID:0070004: ICD10:C92
DOID:4001: ICD10:C56
DOID:0060060: ICD10:C85.9
DOID:0050861: added ICD10:C18 and C20 as best fitting
DOID:1542: ICD10:C76.0
DOID:10247: ICD10:R09.1
DOID:9909: ICD10:H00.019"

Excluded DOID:4667: ICD10:M40.209 see details on the following ticket issue #1210
