### ISSUE TITLE
revisit GRID2-related spinocerebellar ataxia

### ISSUE THREAD

**Issue by SianGramates** [DiseaseOntology/HumanDiseaseOntology#121]
This partially references HumanDiseaseOntology/issues/57

I note that autosomal dominant cerebellar ataxia (renamed from spinocerebellar ataxia) DOID:1441, has a bunch of new children (yay!), one of which is GRID2-related spinocerebellar ataxia (DOID:0050988).  I think this disease may be both redundant, and in the wrong branch; I came to this conclusion by searching for that exact text string in OMIM, and finding among the top hits the gene GRID2 (OMIM:602368), which is the causative gene associated with autosomal recessive spinocerebellar ataxia 18 (OMIM:616204 and DOID:0080042). (I went looking because of the lack of xrefs).

http://www.ncbi.nlm.nih.gov/books/NBK1138/ (Thomas Bird's review) has big table (Table 1) that includes the exact term GRID2-related spinocerebellar ataxia, referencing Coutelier 2015 (PubMed:25841024); that paper does note the first identification of point mutations that appear to be semidominant.  So that adds some confusion, in that it looks to be genetically distinct from SCA18 (which is associated with deletions). 

Having written that, maybe the better course of action is leaving the term be, and wait to see if OMIM catches up with it.  I want to leave this here, though, in case DO revisits in the future, so you don't need to chase it down again.

**Comment by elviram** [comment]
Hi Sian,
we came to the same conclusion as you, but thank you for your comment. I am closing the ticket, for the reasons you mentioned. Thank you again, for writing it down, and we will revisit in the future.

Best,
Elvira
