### ISSUE TITLE
Ewing sarcoma

### ISSUE THREAD

**Issue by smockus** [DiseaseOntology/HumanDiseaseOntology#122]
peripheral primitive neuroectodermal tumor has been obsolete - this was a parent term for extraosseous Ewing's sarcoma and bone Ewing's sarcoma.  Now that the term has been made obsolete there is no good parent term for the Ewings sarcoma and often times it is unknown if the tumor is in the bone or outside of the bone.  Therefore a parent term of "Ewing sarcoma" is needed.

Tx - Susan Mockus, JAX

**Comment by elviram** [comment]
Hello Susan,
peripheral primitive neuroectodermal tumor (DOID:3369) has always had 'Ewing sarcoma' as an exact synonym. I have moved it from synonym to actual label.

Best,
Elvira
