### ISSUE TITLE
Kyphosis

### ISSUE THREAD

**Issue by csbjohnson** [DiseaseOntology/HumanDiseaseOntology#1222]
Refering #1210 

Term: Kyphosis

1. Need to determine the asserted (main) parent of Scheuermann disease. Potential: kyphosis or osteochondrosis.
Current DO definition for Scheuermann disease: An **osteochondrosis** that results_in abnormal bone growth and curvature located_in thoracic vertebral column.
2. Once established create an equivalent class statement for kyphosis to create inferred connections
3. Add postural and congenital kyphosis as subtypes of kyphosis (previously obsoleted)
4. Update Crossreferences:
https://www.ncbi.nlm.nih.gov/books/NBK558945/
https://www.hopkinsmedicine.org/health/conditions-and-diseases/kyphosis#:~:text=Postural%20kyphosis%3A%20the%20most%20common,used%20to%20help%20correct%20posture

[Additional curation notes](https://docs.google.com/document/d/1R3wVY8_vKF2DwQHDjT4Rk9cGvx1c5SErFBmifcaDy9g/edit)

**Comment by lschriml** [comment]
From NCBI books: 
Kyphosis is defined as an increase in the forward curvature of the spine that is seen along the sagittal plane, 

lordosis is an increase in the backward curvature seen along the sagittal plane. 

hyperkyphosis: When the forward curvature becomes excessive 

scoliosis, which is the curvature of the spine along the frontal plane. 

====================================================
To build the distinct EquivalentTo axiom, look at the description of the disease. 
the EQ has to be unique across the DO

create an axiom: 
    has_phenotype some 'Abnormality of the curvature of the vertebral column' and has_symptom some 'abnormal posture'

add this axioms as an EQ for kyphosis
    disease and (has_phenotype some 'Abnormality of the curvature of the vertebral column' and has_symptom some 'abnormal posture')

then add SubClass axioms to the terms that are to be inferred child terms: 
has_phenotype some 'Abnormality of the curvature of the vertebral column' and has_symptom some 'abnormal posture'

**Comment by allenbaron** [comment]
We would need to add directionality or the plane in which the curvature occurs to this equivalent class axiom to ensure that it doesn't also include scoliosis, which would require another import. I suggest we don't add an EQ axiom to kyphosis and, insteead, make kyphosis an asserted child of 'spinal disease' and add these attributes as subclass axioms.

**Comment by lschriml** [comment]
looked this one over, the needed changes have already been done. 
Closing this ticket.
