### ISSUE TITLE
Crossreference Update

### ISSUE THREAD

**Issue by csbjohnson** [DiseaseOntology/HumanDiseaseOntology#1225]
Email request by Shuya Ikeda:

The link from DOID:0080925 to NCI does not work.
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=131302

It seems the NCI ID lacks a "C". This works.
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C131302

Could you fix this?

**Comment by csbjohnson** [comment]
I just updated the crossreference in Protege yet it doesn't appear hyperlinked. Is there an additional step needed?

**Comment by lschriml** [comment]
The hyperlink is added when we load the o to loft file to the website. Sent from my iPhoneOn Jul 26, 2023, at 4:54 PM, Claudia Sánchez-Beato Johnson ***@***.***> wrote:﻿
I just updated the crossreference in Protege yet it doesn't appear hyperlinked. Is there an additional step needed?

**Comment by sh-ikeda** [comment]
Thank you for addressing the issue!

**Comment by csbjohnson** [comment]
Thank you for reaching out and letting us know @sh-ikeda. Greatly appreciated!
