### ISSUE TITLE
New digenic diseases

### ISSUE THREAD

**Issue by csbjohnson** [DiseaseOntology/HumanDiseaseOntology#1226]
- CRANIOSYNOSTOSIS 7; CRS7 | OMIM: 617439
- USHER SYNDROME, TYPE IIC; USH2C |  OMIM: 605472 / _Add sybtype to DO._
- PROTEASOME-ASSOCIATED AUTOINFLAMMATORY SYNDROME 1; PRAAS1 | _OMIM: 256040 /Why does (DOID:0090062) appear as a result when typing the disease? (not listed synonym) Is it the same? or interface error?_
- METHYLMALONIC ACIDURIA AND HOMOCYSTINURIA, cblC TYPE; MAHCC | OMIM: 277400 / _Add "METHYLMALONIC ACIDURIA AND HOMOCYSTINURIA" ("MAHCC" as synonym) to DO as parent term. Add "cblC " subtype to DO._ 
- BOMBAY PHENOTYPE | OMIM: 616754
- PROTEASOME-ASSOCIATED AUTOINFLAMMATORY SYNDROME 3; PRAAS3 | OMIM: 617591
- FACIOSCAPULOHUMERAL MUSCULAR DYSTROPHY 3, DIGENIC; FSHD3 | OMIM: 619477
- FACIOSCAPULOHUMERAL MUSCULAR DYSTROPHY 4, DIGENIC; FSHD4 | OMIM: 619478

**Comment by csbjohnson** [comment]
CRANIOSYNOSTOSIS 7; CRS7 | OMIM: 617439: Created in protege, need definition review

**Comment by csbjohnson** [comment]
Request to create an 'autoinflammatory disease' parent term

**Comment by csbjohnson** [comment]
Interface optimization suggestion:

PROTEASOME-ASSOCIATED AUTOINFLAMMATORY SYNDROME 1; PRAAS1 | OMIM: 256040 /Why does (DOID:0090062) appear as a result when typing the disease? (not listed synonym) Is it the same? or interface error?

**Comment by csbjohnson** [comment]
BOMBAY PHENOTYPE | OMIM: 616754

Should it be added to the DO if it's a phenotype?

**Comment by allenbaron** [comment]
Only diseases should be added to the DO. The inclusion of the word "phenotype" in the OMIM name doesn't necessarily mean it's not a disease.

In the case of "Bombay phenotype" specifically, it is a rare blood type and the OMIM entry uses wording that indicates it is like any other blood type and not a disease:

> Bombay and para-Bombay individuals display no apparent deleterious phenotype except in circumstances requiring blood transfusion, wherein they are cross-match incompatible with all donors except other H-deficient individuals

**Comment by csbjohnson** [comment]
METHYLMALONIC ACIDURIA AND HOMOCYSTINURIA remove parent term
