### ISSUE TITLE
NTR: 'Epstein-Barr virus infection'

### ISSUE THREAD

**Issue by sebastianduesing** [DiseaseOntology/HumanDiseaseOntology#1230]
Hello! I'd like to request the addition of a term for Epstein-Barr virus infection, for use by the Human Immune Project Consortium (HIPC) Coordinating Center (HCC). I've based the proposed definition on DO's '[human cytomegalovirus infection](http://purl.obolibrary.org/obo/DOID_0080827)' term.

**Definition:** A viral infectious disease that has_material_basis_in Human gammaherpesvirus 4.

**PubMed Source:** ([link](https://pubmed.ncbi.nlm.nih.gov/33533222/))

Thanks!

-- Sebastian Duesing

**Comment by allenbaron** [comment]
Thanks for reaching out Sebastian.

DO currently has 'Epstein-Barr virus hepatitis' ([DOID:0050204](http://purl.obolibrary.org/obo/DOID_0050204)). Would this disease be appropriate for your use?

**Comment by sebastianduesing** [comment]
Thanks for the quick response! We're looking for a more symptom-agnostic term to reflect all cases of EBV infection, rather than only those associated with particular manifestations of disease. Let me know if any clarification would be helpful.

**Comment by allenbaron** [comment]
Thanks for clarifying. The requested disease would have as children at least 'Epstein-Barr virus hepatitis' ([DOID:0050204](http://purl.obolibrary.org/obo/DOID_0050204)) and 'infectious mononucleosis' ([DOID:8568](http://purl.obolibrary.org/obo/DOID_8568)) which are currently in the DO.

**Comment by sebastianduesing** [comment]
Late Sept would be fine. That sounds great. Thanks for your help with this.

**Comment by lschriml** [comment]
@allenbaron -- agreed, add this new term, Epstein-Barr virus infection, as a child of viral infectious disease

add the axiom: has material basis in some 'Human gammaherpesvirus 4'

https://www.ncbi.nlm.nih.gov/books/NBK559285/

**Comment by allenbaron** [comment]
Epstein-Barr virus infection will be available in the next release as DOID:0070468.

**Comment by allenbaron** [comment]
It will be DOID:2938 (not DOID:0070468), my apologies.

**Comment by sebastianduesing** [comment]
Thank you very much! We appreciate it!
