### ISSUE TITLE
neurodevelopmental disorder with dysmorphic facies and distal limb anomalies (NEDDFL)

### ISSUE THREAD

**Issue by anna-anagnostop** [DiseaseOntology/HumanDiseaseOntology#1238]
Please consider adding new DO term:

DO TERM NAME: neurodevelopmental disorder with dysmorphic facies and distal limb anomalies

SUGGESTED DEF: An autosomal dominant neurodevelopmental disorder characterized by delayed psychomotor development and intellectual disability, poor growth with small head size, dysmorphic facial features, and mild abnormalities of the hands and feet that has_material_basis_in heterozygous mutation in the BPTF gene on chromosome 17q24.
SYN: NEDDFL

SUGGESTED PARENT TERMS: autosomal dominant intellectual developmental disorder DOID:0060307; syndromic intellectual disability DOID:0050888

PubMed IDs: [28942966](https://pubmed.ncbi.nlm.nih.gov/28942966/), [33522091](https://pubmed.ncbi.nlm.nih.gov/33522091/)

OMIM #: [617755](https://www.omim.org/entry/617755)

Thank you,

Anna V. Anagnostopoulos https://orcid.org/0000-0002-6490-7723

**Comment by allenbaron** [comment]
This disease will be in the December release as a child of 'autosomal dominant intellectual developmental disorder'. 
_My apologies for the delay, there was some Github-instigated confusion as to who was assigned to curate this disease._

I hope you have a happy holiday season!!
