### ISSUE TITLE
Ontology of Allergy

### ISSUE THREAD

**Issue by alanruttenberg** [DiseaseOntology/HumanDiseaseOntology#124]
http://purl.obolibrary.org/obo/DOID_4379

Class: nut allergic reaction

Term IRI: http://purl.obolibrary.org/obo/DOID_4379

has_exact_synonym: Allergy to nuts other than peanuts; Nut allergy; Allergy to nuts (disorder)

Parents:  immune system disease, hypersensitivity reaction disease, hypersensitivity reaction type I disease, food allergy

Minimally, the naming is confusing. Nut allergic reaction is a process. Nut allergy or Nut sensitivity is a disposition (disease). Furthermore an exact synonym is 'Allergy to nut (disorder)' which falls in yet another category (disorders).

If DO is to be based on OGMS then these terms should either be clarified in a way that is consistent with their parent terms, or reorganized to accomplish that.

**Comment by lschriml** [comment]
Hello Alan,
 Thank you for raising this point. 
The immune system diseases are organized by the type of hypersensitivity reaction. 
Food allergy is a hypersensitivity reaction type I disease.
  Taking a look at how IEDB is naming these diseases, 
I have updated these in DO.  

  Overall, 
    DO synonyms are imported from the other medical vocabularies. 
       We do remove redundant synonyms, but otherwise, they are included
          as they are presented in the source vocabulary. In this case, some of these synonyms
         are from IEDB. 
   DO disease terms follow community determined nomenclature, so there may be terms that seem odd and confusing. Some groups name diseases using 'disorder'. 
  Agreed, under the OGMS reaction is a process.
  To clarify, DO is not based on OGMS. We have agreed that we share the same top term, disease. 
  
Cheers,
Lynn

**Comment by phismith** [comment]
Lynn
It follows from the meaning of 'is-a' (and thus from the hierarchical  organization of a single-root ontology like DO) that all the terms beneath the root need to satisfy the definition of the root (Michael Ashburner called this the 'true path rule').  I appreciate that it is hard to deal with all the synonyms DO needs to take care of, but the strategy, surely, should be that all the preferred labels should, step-by-step be formulated in a way consistent with the definition of the root.
Barry
