### ISSUE TITLE
New Term Request: Renal Medullary Carcinoma

### ISSUE THREAD

**Issue by refu6enik** [DiseaseOntology/HumanDiseaseOntology#1240]
Name
renal medullary carcinoma

Definition
A rare aggressive subtype of renal cell carcinoma characterised by a large, white or tan, firm, infiltrative tumour with microabscess-like foci centred in the renal medulla, typically presenting with haematuria, abdominal/flank pain, weight loss and fever. It is associated with sickle cell trait and disease and metastasis to the bones and lungs is common at time of diagnosis.
https://en.wikipedia.org/wiki/Renal_medullary_carcinoma

XREFs
NCI:C7572
SNOMEDCT_US_2022_09_01:765094003
SNOMEDCT_US_2022_09_01:765095002
UMLS_CUI:C4049328

IS A
DOID:4450 ! renal cell carcinoma

**Comment by allenbaron** [comment]
Dylan, thanks for requesting this disease. It will be included in the next release.

_My apologies for the delayed response._
