### ISSUE TITLE
DOID:0080060 add SCAR synonyms

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#1253]
Email from wilmil@jax.org, 
 Comment for term: DOID:0080060

Could you add SCAR12 as synonym (like in many of the other SCARs). Also add similar SCAR# synonyms to other SCARs that don't yet have that synonym. Helps enormously with search.

**Comment by csbjohnson** [comment]
Of course, this additions have been implemented and pushed to main.

**Comment by allenbaron** [comment]
Thanks @LaurensWilming. That's a good reminder.

I just confirmed that we have all the diseases in the SCAR phenotypic series and they all have OMIM xrefs. We also have SCAR synonyms for diseases that have become part of other PS (i.e. SCAR1 & 9), except for 'Galloway-Mowat syndrome 1' (DOID:0060364) which was SCAR5 ([OMIM:251300](https://www.omim.org/entry/251300?highlight=scar5)).

@csbjohnson, can you add the appropriate SCAR synonyms to DOID:0060364 as well for completeness.

**Comment by csbjohnson** [comment]
Thank you all!

I added the appropriate SCAR synonyms to autosomal recessive spinocerebellar ataxia types.

DOID: 0060364 represents  Galloway-Mowat syndrome 1 which I don't believe would use SCAR as a synonym @allenbaron
