### ISSUE TITLE
NTR: Zaki Syndrome

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1254]
Hi Lynn. I would like to request a new term as below for MGI mouse model:

Label: Zaki syndrome 
Definition: A syndrome characterized by developmental delay, progressive microcephaly, and short stature, as well as dysmorphic features including sparse scalp hair, cupped ears, wide nose and mouth, short philtrum, and high-arched palate that has_material_basis_in homozygous mutation in the WLS gene on chromosome 1p31. 
Definition ref: https://pubmed.ncbi.nlm.nih.gov/34587386/| https://www.ncbi.nlm.nih.gov/medgen/1794247
Parent DO: syndrome DOID:225 
DbXref: OMIM:619648

The pubmed link above is also for the mouse model. 

Thank you,
Monika Tomczuk, Mouse Genome Informatics

**Comment by allenbaron** [comment]
Thanks Monika! Zaki syndrome will be in the November release.

_My apologies for the delayed response._
