### ISSUE TITLE
Typo in readme file

### ISSUE THREAD

**Issue by daulatojha17** [DiseaseOntology/HumanDiseaseOntology#1256]
There is a small typo in the readme file.
("activies" -> "activities")
fixed under pull request #1255

**Comment by lschriml** [comment]
Thank you !!We would love to learn more about your work and how you use the DO.Sent from my iPhoneOn Oct 21, 2023, at 10:29 PM, daulatojha17 ***@***.***> wrote:﻿
There is a small typo in the readme file.
("activies" -> "activities")
fixed under pull request #1255

**Comment by lschriml** [comment]
the readme has been updated.
