### ISSUE TITLE
Update to distal hereditary motor neuronopathy in OMIM

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1257]
**Is your request related to a specific disease? Please describe.**
distal hereditary motor neuronopathy
OMIM has done an update to distal hereditary motor neuronopathy that affects multiple sets of terms in DO falling under DOID:0111198 and DOID:0111197. Terms have been renames and renumbered in ways that I think alter the current organization. Also there are a some entries in OMIM that have not yet been added to DO. Terms are listed on the OMIM updates spreadsheet.

**Comment by lschriml** [comment]
Thank you Sue !!

**Comment by lschriml** [comment]
distal hereditary motor neuronopathy

DOID:0111198 and DOID:0111197




-- | --



**DOID:0111198 | autosomal dominant distal hereditary motor neuronopathy**

DOID:0111200 | distal hereditary motor neuronopathy type 1
DOID:0111206 | distal hereditary motor neuronopathy type 2
DOID:0111208 | distal hereditary motor neuronopathy type 2A
DOID:0111208 | distal hereditary motor neuronopathy type 2B
DOID:0111209 | distal hereditary motor neuronopathy type 2C
DOID:0111210 | distal hereditary motor neuronopathy type 2D

DOID:0111203 | distal hereditary motor neuronopathy type 5
DOID:0111204 | distal hereditary motor neuronopathy type 5A
DOID:0111205 | distal hereditary motor neuronopathy type 5B

DOID:0111199 | distal hereditary motor neuronopathy type 7
DOID:0111201 | distal hereditary motor neuronopathy type 7A
DOID:0111202 | distal hereditary motor neuronopathy type 7B
DOID:0111215 | distal hereditary motor neuronopathy type 8
DOID:0111212 | distal hereditary motor neuronopathy type 9

**DOID:0111197 | autosomal recessive distal hereditary motor neuronopathy**



-- | --
DOID:0111213 | distal spinal muscular atrophy type 4
DOID:0111211 | distal spinal muscular atrophy type 3

**Comment by lschriml** [comment]
Looking at: PS182960 DOID:0111198 | autosomal dominant distal hereditary motor neuronopathy
-- DO has subtypes 1-14: 
-- looking at OMIM: the OMIM IDs in the DO match the disease name and OMIM IDs in OMIM 
-- new subtypes were previously added.
DO has all of the OMIM subtypes now


Looking at:  PS604320
DOID:0111197 | autosomal recessive distal hereditary motor neuronopathy
   -- DO has 5 subtypes
-- checking alignment of DOID, OMIM ID, disease name 
    -- updating disease name to match OMIM names
-- adding in subtypes 6-10 

Updates for this ticket are now complete.
The new terms will be available in our January 2024 release this week.
Cheers,
Lynn
