### ISSUE TITLE
New term request: Schimke immunoosseous dysplasia

### ISSUE THREAD

**Issue by SianGramates** [DiseaseOntology/HumanDiseaseOntology#126]
Disease is  OMIM #242900
Might be a child of  	DOID:0080027 spondyloepimetaphyseal dysplasia. Or of DOID:10952 nephritis. Here's a review: http://www.ncbi.nlm.nih.gov/books/NBK1376/

**Comment by elviram** [comment]
Hello Sian, 
thank you for the term request. The term has been added to DO, as a child of DOID:0080027. It will be included in today's release.

Best,
Elvira
