### ISSUE TITLE
Need to revise the SCT Xrefs of DOID:10548 cardia cancer

### ISSUE THREAD

**Issue by linforestzhang** [DiseaseOntology/HumanDiseaseOntology#1262]
**Is your request related to a specific disease? Please describe.**
Disease name, needed review.  
DOID:10548 cardia cancer

**Describe the proposed change(s)**
For example, please include the terms to be split or merged, and the source of this change, e.g. the source xref * (e.g. OMIM) has been revised/updated.
Its current Xrefs SNOMEDCT_US_2023_03_01:93738008 (93738008 |Primary malignant neoplasm of cardia of stomach (disorder)|)  might need to be changed to 187732006 |Malignant tumor of cardia (disorder)|

**References**
Provide links to a database or a PubMed ID
SCTID 93738008 |Primary malignant neoplasm of cardia of stomach (disorder)|
https://browser.ihtsdotools.org/?perspective=full&conceptId1=93738008&edition=MAIN/2023-10-01&release=&languages=en
SCTID 187732006 |Malignant tumor of cardia (disorder)|
https://browser.ihtsdotools.org/?perspective=full&conceptId1=187732006&edition=MAIN/2023-10-01&release=&languages=en

**Comment by allenbaron** [comment]
Thanks for pointing this out. We'll get it updated shortly.
