### ISSUE TITLE
NTR: LIPHAK syndrome

### ISSUE THREAD

**Issue by srengel** [DiseaseOntology/HumanDiseaseOntology#1266]
Include: 
- new disease terms or updates to DO's disease terms

NTR: LIPHAK syndrome
- previously undescribed recessive dermatological condition named LIPHAK (LTV1-associated Inflammatory Poikiloderma with Hair abnormalities and Acral Keratoses)
-  affected locus: ribosome biogenesis factor gene LTV1

- include the term name in the title of the request
- It is helpful to include a definition and PubMed reference for new terms

https://pubmed.ncbi.nlm.nih.gov/34999892/

- It is useful to share information on the relevant project 

SGD is using DO to annotate S.cerevisiae homologs of human disease genes when used in experiments to study that disease https://www.yeastgenome.org/

- include contact information along with your ORCID id, so that we can provide attribution for your contribution

Stacia Engel, SGD
http://orcid.org/0000-0001-5472-917X

**Comment by allenbaron** [comment]
We're working to clear our request backlogs. If this doesn't get into this month's release. It will be in the next. Thanks Stacia for requesting this term!

**Comment by srengel** [comment]
Awesome @allenbaron thank you!

**Comment by allenbaron** [comment]
Stacia,
This disease will be in the Dec release as promised (DOID:0070510).

### Nomenclature notes (primarily for future reference)

The literature on this disease is currently limited to 2 publications (only one with patients). The authors seem to prefer 'LIPHAK syndrome', while the IPHAK acronym has not been used (only Europe PMC search hit is a typo of a similar acronym).

The label will be the name from OMIM (to [discourage use of genes in disease names](https://doi.org/10.1016/j.ajhg.2021.07.004)) and IPHAK, LIPHAK, and 'LIPHAK syndrome' will be added as synonyms. The full name proposed in [PMID:34999892](https://pubmed.ncbi.nlm.nih.gov/34999892/), 'LTV1-associated inflammatory poikiloderma with hair abnormalities and acral keratoses', will be excluded for the time-being given OMIM's name is unique and should suffice as a replacement in all circumstances. _Since the DO diligently works to align with clinical practice, the name used as the primary label may change, depending on how the literature plays out._
