### ISSUE TITLE
NTR: non-syndromic X-linked intellectual developmental disorder 111

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1269]
Hi,
I'd like to request the following term for MGI as mutant mice are a mouse model and OMIM has given this disorder number 111.

Label: non-syndromic X-linked intellectual developmental disorder 111
Definition: A non-syndromic X-linked intellectual disability characterized by different degrees of impaired intellectual development associated with motor, speech and behavioral impairments that has_material_basis_in hemizygous or heterozygous mutation in the SLITRK2 gene on chromosome Xq27.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/35840571/
Parent DO: non-syndromic X-linked intellectual disability ([DOID:0050776](http://www.disease-ontology.org/?id=DOID:0050776))
DbXref: OMIM:301107

Thanks so much,
Monika Tomczuk
MGI Scientific Curator

**Comment by lschriml** [comment]
Thank you Monika,
   we will get this added to the DO.

Cheers,
Lynn

**Comment by csbjohnson** [comment]
Hi Monika,

Thanks for reaching out! I've just included  non-syndromic X-linked intellectual developmental disorder 111 as requested. 

Happy Holidays!

Best,
Claudia Marie Sánchez-Beato Johnson
