### ISSUE TITLE
release Nov 30, 2023 issues

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#1272]
New term DOID:0060914 has xref: OMIM:109720 -- should not it be OMIM:618048

New term DOID:0060919 has xref: OMIM:619183 -- should not it be OMIM:619175

Please review. Thank you!

**Comment by allenbaron** [comment]
You are absolutely right, Marek. Thank you for catching those.

Do you need a new release to fix these or can it wait until the next one? Due to upcoming holidays, the next release will be public in mid-December.

**Comment by tutajm** [comment]
New release not needed: we fixed these OMIM issues on-the-fly while loading Nov 30 release into our database.

**Comment by allenbaron** [comment]
Great. They'll be in the December release.
