### ISSUE TITLE
New Term Request: Borrelia miyamotoi disease (BMD)

### ISSUE THREAD

**Issue by G-Molano-LA** [DiseaseOntology/HumanDiseaseOntology#1277]
Hi, 

Thanks for the amazing resource. New term suggestion: 

-  Name: Borrelia miyamotoi disease
-  synonym: 'BMD' scope=EXACT
-  synonym: 'hard tick-borne relapsing fever' scope=RELATED
-  definition: Human infection has_material_basis in Borrelia_miyamotoi (emerging tick-borne pathogen). Symptoms vary depending on the constitution of the patient. Immunocompetent, and otherwise healthy, patients present with milder, flu-like symptoms: fever, fatigue, sleepiness, chills, muscle and joint stiffness, aches and pains, and nausea (URL:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9967256/)
-  xrefs: [PMID: 36839539, https://www.cdc.gov/relapsing-fever/miyamotoi/index.html]
- is_a: DOID:0050338 ! primary bacterial infectious disease
-  my personal ORCID id: https://orcid.org/0000-0003-0069-6098

Best regards,

Alejandra

**Comment by csbjohnson** [comment]
Hi @G-Molano-LA, thank you very much for your request, we will review it and incorporate to the Disease Ontology promptly. Happy holidays!

**Comment by allenbaron** [comment]
In taxonomy, 'hard tick-borne relapsing fever' has begun to appear in describing a clade of _Borrrelia_ species but in the disease realm it has been used nearly exclusively to refer to BMD, so it's been added as an exact synonym.

This disease will be in this month's release as DOID:0070527.

Thanks for bringing this to our attention Alejandra!!
