### ISSUE TITLE
New Term Request: Cepacia syndrome (CS) 

### ISSUE THREAD

**Issue by G-Molano-LA** [DiseaseOntology/HumanDiseaseOntology#1278]
Hi,

Thanks for the amazing resource. New term suggestion:

-  name: Cepacia syndrome
-  synonym: 'CS' scope='EXACT' 
-  definition: Cepacia syndrome (CS) is an acute, necrotizing pneumonia with a high mortality rate, occurring in patients with cystic fibrosis (CF) has_material_basis in Burkholderia_cepacia (URL = https://pubmed.ncbi.nlm.nih.gov/36815622/)
- xrefs: [PMID: 36815622, https://www.cdc.gov/hai/organisms/bcepacia.html]
- is_a: DOID:552 ! pneumonia
- my personal ORCID id: https://orcid.org/0000-0003-0069-6098

Best regards,

Alejandra

**Comment by allenbaron** [comment]
Thank you for the requests! We will review them both after the winter holidays.

**Comment by allenbaron** [comment]
This disease will be in this month's release. Thanks again Alejandra!
