### ISSUE TITLE
Sifrim-Hitz-Weiss syndrome 

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1279]
Sifrim-Hitz-Weiss syndrome
OMIM:617159
ORPHA:653712 
See PMID:37738575 for the mouse model
Gene reviews - https://www.ncbi.nlm.nih.gov/books/NBK561516/

Synonyms:
SIHIWES
CHD4-related neurodevelopmental syndrome
CHD4-related neurodevelopmental disorder
SIFRIM-HITZ-WEISS MULTIPLE CONGENITAL ANOMALIES-MENTAL RETARDATION SYNDROME
CHD4 Neurodevelopmental Disorder

Definition
An autosomal dominant intellectual developmental disorder characterized by developmental delay, speech delay, usually mild-to-moderate intellectual disability, and variable congenital anomalies in other systems that has_material_basis_in an autosomal dominant mutation of the CHD4 gene on chromosome 12p13.31.
references: OMIM:617159, PMID:27479907, PMID:27616479, https://www.ncbi.nlm.nih.gov/books/NBK561516/

Parent
autosomal dominant intellectual developmental disorder (DOID:0060307)

**Comment by allenbaron** [comment]
Thanks Sue. I'll work to get this into the next release.
