### ISSUE TITLE
New Term Request: Spastic paraplegia, optic atrophy, and neuropathy; SPOAN

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#128]
I would like to request a new term for Spastic paraplegia, optic atrophy, and neuropathy; SPOAN syndrome (OMIM:609541). Also PubMed:26385635, 15852396.

**Comment by elviram** [comment]
Hello, 
thank you for the term request. The term has been added to DO. It will be included in today's release.

Best,
Elvira
