### ISSUE TITLE
Rename term renal medullary carcinoma (DOID: 0070475)

### ISSUE THREAD

**Issue by sumirp** [DiseaseOntology/HumanDiseaseOntology#1281]
Hi Team,

Can you please change the name renal medullary carcinoma (DOID: 0070475) to "SMARCB1-deficient renal medullary carcinoma" according to latest WHO classification of Urinary and Male Genital Tumours, 5th Edition. 

Pubmed ID: 36645398, 35853783

Best Regards,
Sumir

**Comment by csbjohnson** [comment]
Thank you very much for your request @sumirp , we'll review  the name change. Wishing you a great start of 2024!
