### ISSUE TITLE
Foveal hypoplasia 2 or FHONDA syndrome?

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1283]
Hi,
I'm requesting a new term for MGI, for the following publication: https://pubmed.ncbi.nlm.nih.gov/37862028/
This paper calls this "oveal hypoplasia, optic nerve decussation defects, and anterior segment dysgenesis" (FHONDA) or FHONDA syndrome. OMIM has it as Foveal hypoplasia 2 (FVH2) (OMIM:616502). It sounds like FHONDA syndrome may be a type of Foveal hypoplasia 2 (sounds like the optic nerve decussation defects and anterior segment dysgenesis can be seen in Foveal hypoplasia 2 but don't have to be there, so we at least need the FVH2 term). Orphanet call it "Foveal hypoplasia-optic nerve decussation defect-anterior segment dysgenesis syndrome". And if you enter the FVH2 term, then it might be a good idea to also enter the FVH1 term (which I have not looked at). 

Label: Foveal hypoplasia 2 (in OMIM), paper reports FHONDA Syndrome
Definition (for FVH2): An eye disease characterized by foveal hypoplasia, with or without optic nerve misrouting with an increased number of axons decussating at the optic chiasm and innervating the contralateral cortex, and with or without anterior segment dysgenesis, in the absence of albinism that has_material_basis_is homozygous or compound heterozygous mutation in the SLC38A8 gene on chromosome 16q23.
Definition (for FHONDA): An eye disease characterized by foveal hypoplasia, optic nerve misrouting with an increased number of axons decussating at the optic chiasm and innervating the contralateral cortex, and anterior segment dysgenesis, in the absence of albinism that has_material_basis_is homozygous or compound heterozygous mutation in the SLC38A8 gene on chromosome 16q23.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/24194637/ and/or https://pubmed.ncbi.nlm.nih.gov/24290379/
Exact synonym: oveal hypoplasia, optic nerve decussation defects, and anterior segment dysgenesis (for FHONDA)
DbXref: OMIM:609218
Dbxref: ORDO:397618

Thank you,
Monika Tomczuk
Scientific Curator, MGI

**Comment by allenbaron** [comment]
Thanks Monika. I'll review and get this added.
