### ISSUE TITLE
Developmental dysplasia of the hip

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1288]
In PMID:36067312 the authors report a new mouse model of developmental dysplasia of the hip that corresponds to a human variant in LRP1 associated with the disease.

The paper includes a reference to OMIM:142700 but this is now DDH1 that is associated with a locus on a different chromosome.

OMIM has a phenotypic series [PS142700](https://www.omim.org/phenotypicSeries/PS142700) with 2 entries for this disease. This appears to be a third. I'll ask OMIM to look at the paper and create a new record but in the meantime it would be helpful to have a new term for the general disease.

Term: developmental dysplasia of the hip
xref: OMIM:PS142700
child of bone development disease DOID:0080006
definition: A bone development disease characterized by abnormality of the seating of the femoral head in the acetabulum
PMID:11246461

This would have 2 subtypes from OMIM 
DDH1, 142700 - locus  chromosome 13q22
DDH2, 615612 - locus chromosome 3p21

**Comment by csbjohnson** [comment]
Hi Sue! Thank you very much for sharing. I added developmental dysplasia of the hip to the DO.  We can add the new OMIM record when available.
