### ISSUE TITLE
add subtypes for dystonia in OMIM PS128100

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#1289]
Review's DO's coverage and add in new subtypes.

https://omim.org/phenotypicSeries/PS128100

**Comment by csbjohnson** [comment]
More OMIM PS term sheet tracking: https://docs.google.com/spreadsheets/d/12qZvUng0FTUsAyhXekjXL2CfxD9LGTynkjBRz_eBwr4/edit#gid=0

**Comment by csbjohnson** [comment]
#1274

**Comment by csbjohnson** [comment]
All Dystonia PS Subtypes have been added. 

Next: add second inheritance to subtypes that require it.
