### ISSUE TITLE
DOID:4006 change to urinary bladder urothelial carcinoma

### ISSUE THREAD

**Issue by CarolBult** [DiseaseOntology/HumanDiseaseOntology#129]
DOID:4006 is currently bladder transitional cell carcinoma. 
The Xref is to NCI:C39851 which is "urinary bladder urothelial carcinoma"

We are using the DO as the vocabulary to annotate mouse models of human cancer.
We consulted our clinical collaborators they indicated that "transitional cell carcinoma" is the older term for this neoplasm.

I'm requesting that the name of DOID:4006 be changed to "urinary bladder urothelial carcinoma" and that "bladder transitional cell carcinoma" be moved to a synonym. 

This would also make DO consistent with the NCI thesaurus.

**Comment by elviram** [comment]
Hello Carol,
thank you for the update. The labels have been switched. It will be visible in today's release.

Best,
Elvira

**Comment by CarolBult** [comment]
Terrific. Thanks very much!

Sent from my iPhone

On Feb 19, 2016, at 3:59 PM, Elvira <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Carol,
thank you for the update. The labels have been switched. It will be visible in today's release.

Best,
Elvira

-
Reply to this email directly or view it on GitHub<https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/129#issuecomment-186405250>.

The information in this email, including attachments, may be confidential and is intended solely for the addressee(s). If you believe you received this email by mistake, please notify the sender by return email as soon as possible.
