### ISSUE TITLE
Add Foveal hypoplasia aka Foveal hypoplasia-presenile cataract syndrome to DO, rare syndrome

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#1290]
disease name: Foveal hypoplasia-presenile cataract syndrome. 

       synonym:  O'Donnell-Pappas syndrome.

see also: 
https://disorders.eyes.arizona.edu/category/alternate-names/odonnell-pappas-syndrome 

       ORDO:2253
       https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=2253

       OMIM:
             PS136520, with two subtypes
        -- in type 1 OMIM record: 
[O'Donnell and Pappas (1982)](https://omim.org/entry/136520#4) described a family in which 7 persons over 4 generations had mild foveal hypoplasia, presenile cataract (onset before age 40 years), and peripheral corneal pannus. There were 2 instances of male-to-male transmission, suggesting autosomal dominant inheritance. Corneal pannus was described as 'a small peripheral margin of pannus, about 1 mm in width, for 360 degrees.

2014 paper: 
https://pubmed.ncbi.nlm.nih.gov/23942204/

Foveal hypoplasia:   disease name in OMIM records
      -- see also: https://eyewiki.org/Foveal_Hypoplasia
       -- includes information on genetic variants

**Comment by allenbaron** [comment]
Foveal hypoplasia-presenile cataract syndrome/O'Donnell-Pappas syndrome is distinguished by the invariable presence of presenile cataracts everywhere that it is defined, while foveal hypoplasia 1 is defined by OMIM as a having a lack of aniridia. This suggests that O'Donnell-Pappas syndrome is a subset of FVH1, which idea is supported by Orphanets NTBT relationship to OMIM.

O'Donnell-Pappas syndrome isn't specific enough in my opinion to merit its own disease at this time (in the same way FHONDA syndrome is not sufficiently different from FVH2, #1283).

--> Add Foveal hypoplasia-presenile cataract syndrome & O'Donnell-Pappas syndrome as narrow synonyms
--> Add Orphanet and related xrefs as `skos:narrowMatch`
