### ISSUE TITLE
NTR: spastic tetraplegia, thin corpus callosum, and progressive microcephaly

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1291]
Hi,
Requesting the following for MGI for J:344184 (https://pubmed.ncbi.nlm.nih.gov/37642681/).

Label: spastic tetraplegia, thin corpus callosum, and progressive microcephaly
Definition: A neurodevelopmental disorder characterized by onset of spastic tetraplegia, thin corpus callosum, progressive microcephaly and severely impaired global development in early infancy that_has_material_basis_in homozygous or compound heterozygous mutation in the SLC1A4 gene on chromosome 2p14.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/25930971/ and https://pubmed.ncbi.nlm.nih.gov/26138499/  
Exact synonym: SPATCCM
DbXref: OMIM:616657
Dbxref: ORDO:447997

Thank you,
Monika Tomczuk
MGI curator

**Comment by allenbaron** [comment]
Thanks Monika. I'll work to get this out in the next release.
