### ISSUE TITLE
NTR: syndromic X-linked intellectual developmental disorder brain type

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1292]
Hi,

Requesting the following term for MGI for J:338313 (https://pubmed.ncbi.nlm.nih.gov/37463454/).

Label: syndromic X-linked intellectual developmental disorder brain type
Definition: A syndromic X-linked syndromic intellectual developmental disorder characterized by delayed psychomotor development, impaired intellectual development with behavioral abnormalities, dysmorphic facial features, and variable features such as musculoskeletal abnormalities, seizures, acquired microcephaly, and feeding problems with poor overall growth that has_material_basis_in heterozygous mutation in the HNRNPH2 gene on chromosome Xq22.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/27545675/
Parent DO: DOID:0060309 syndromic X-linked disability 
Exact synonym: MRXSB ?
DbXref: OMIM:300986

Thank you,
Monika Tomczuk
MGI curator

**Comment by allenbaron** [comment]
Thanks Monika. I'll work to get this out in the next release.
