### ISSUE TITLE
NTR: cone-rod dystrophy 22

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1294]
Requesting the following for MGI J:307901 (https://pubmed.ncbi.nlm.nih.gov/33077892/).

Label: cone-rod dystrophy 22
Definition: A cone-rod dystrophy that has_material_basis_in homozygous mutation in the TLCD3B gene on chromosome 16p11.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/33077892/ 
Parent DO: cone-rod dystrophy DOID:0050572
Exact synonym: CORD22
DbXref: OMIM:619531

Thank you,
Monika Tomczuk
MGI Curator

**Comment by lschriml** [comment]
added to DO
