### ISSUE TITLE
new term: X-linked hyper-IgM syndrome

### ISSUE THREAD

**Issue by KevinABurns137** [DiseaseOntology/HumanDiseaseOntology#1297]
Sorry if I failed to find this one if it already exists:

Include: 
- new disease terms or updates to DO's disease terms
-         X-Linked Hyper IgM Syndrome
- include the term name in the title of the request
-         done
- It is helpful to include a definition and PubMed reference for new terms
-         see OMIM: # 308230... I'm not an expert but PMID 14663287 defined it pretty well and talked about clinical presentations
- It is useful to share information on the relevant project 
-         part of an antibody/receptor knowledge base called AIRR
- include contact information along with your ORCID id, so that we can provide attribution for your contribution
-        I am Kevin Burns, Kevin.Burns@cchmc.org, ORCID = 0009-0003-6587-4809

**Comment by allenbaron** [comment]
I checked and this disease is in the Disease Ontology as 'X-linked hyper IgM syndrome' (DOID:6620), but it was missing the OMIM cross-reference. It actually looks like there are a number of updates to the cross-references needed. I'll make those and they'll be included in the February release.

Thanks for bringing this to our attention Kevin! We welcome and appreciate the contributions.
