### ISSUE TITLE
Need new term  "hepatoid adenocarcinoma"

### ISSUE THREAD

**Issue by CarolBult** [DiseaseOntology/HumanDiseaseOntology#130]
Hi DO team, 

I have a sample from a rare neoplasm for which I need the term, "hepatoid adenocarcinoma".

See https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20MetaThesaurus&code=C1266090

Thanks much for your help with this!

Carol Bult

**Comment by elviram** [comment]
Hello Carol,

the term will be included in the new release on Friday.

Best,
Elvira

**Comment by CarolBult** [comment]
Thanks so much Elvira. Really appreciate the help.

CB
__________________________________
Carol J. Bult, Ph.D.
Professor and Knowlton Family Chair
Deputy Director, The Jackson Laboratory Cancer Center
Scientific Director, PDX and Cancer Avatar Program
The Jackson Laboratory
600 Main Street
RL13
Bar Harbor, Maine 04609
(tel) 207-288-6324
