### ISSUE TITLE
Change prefix of OMIM cross-references to MIM

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1301]
OMIM made a request that we use MIM as a prefix instead of OMIM:
> We prefer that resources use MIM as the CURIE for our numbers.  The "O" stands for "online" which is redundant (see
sections 1.8 and 1.9 at https://omim.org/help/linking).  We are linking to the Alliance of Genome Resources and when we requested this change, they directed us to you as the source of MIM versus OMIM prefix.  Any chance you would change this?

I'm opening this issue so we can discuss and resolve this.

**Comment by allenbaron** [comment]
A few thoughts:
1. Their team has worked hard to consolidate prefixes for their resource to MIM, instead of OMIM.
    - This included setting up a PURL-like redirect that can handle both entry and phenotypic series (PS) terms that is currrently in production (examples: http://www.omim.org/MIM:102300, https://www.omim.org/MIM:PS102300). _Noting that it works with `http://` or `https://`._
    - Related issues elsewhere: 
         - https://github.com/biopragmatics/bioregistry/issues/497
         - https://github.com/identifiers-org/identifiers-org.github.io/issues/204
2. It would be easy to implement this change. The biggest issue is how it might affect downstream users of the DO.

### Here's my own personal opinion:
_TL;DR_ - I wholly support this change and doing whatever work is needed to make it happen. 

_Reasoning_ - The creator and maintainer of a resource should be the one to define it and it is best to ask that/those individual(s) when there is some decision on how their resource will be used. I believe some of the messiness in data and proliferation of competing resources exists because individuals do not think often enough about working together or are unwilling to do the work needed to discuss issues and come to a consensus. I see this as another unrecorded, aspect of FAIRness/TRUST-worthiness: users should communicate with the maintainers of a resource. If all OMIM users respected OMIM's desire to consolidate to the MIM prefix there would be only 1 prefix and no need for any programmatic efforts to correct them, making all data annotated with their identifiers more FAIR.

**Comment by allenbaron** [comment]
Tagging @fschiettecatte so he's aware of this discussion and can chime in if needed (I hope you don't mind).

**Comment by allenbaron** [comment]
@sbello what might the Alliance need to make this change?

@lschriml, the only thing I can think of that we need to change, beyond the data in the ontology, is the loader that supports the tree views of the DO at https://disease-ontology.org/do. Can you help me identify other resources beyond the Alliance who might benefit from a heads up and help me set a timeframe for this change?

**Comment by allenbaron** [comment]
@fschiettecatte does capitalization matter? Any preference for MIM vs mim?

**Comment by allenbaron** [comment]
Do we want to change all references from OMIM to MIM? I'm wondering about the name of some files, e.g. [DOreports/OMIMinDO.tsv](https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/main/DOreports/OMIMinDO.tsv), and references to OMIM in [src/ontology/README_DO_Files](https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/main/src/ontology/README_DO_Files).

**Comment by sbello** [comment]
@allenbaron MGI and the Alliance and I suspect most other DO users would need to modify our loaders to recognize the new prefix. I don't think this would break the loads but it would mean that we would fail to load any OMIM IDs until the loader was updated so early warning would be good.
I think once we did that we wouldn't need to change anything on the front end. 
Given that the OMIM website is called OMIM.org I don't know that you would need to change anything else.

**Comment by lschriml** [comment]
Items to change in the DO files: 
     -- only change the xref prefix from OMIM to MIM
    
On the DO website
      -- Advance Search
     -- SPARQL sandbox
     -- the loader that supports the tree views of the DO

Code: 
   -- SPARQL queries (src/sparql)
   -- make test/make release
   -- UMLS updating 

  OMIM susceptibility import

File names: 
    -- I would keep the file names OMIM

**Comment by allenbaron** [comment]
> -- I would keep the file names OMIM

I agree that it's probably best to change only the prefixes. 

>-- make test/make release

Nothing needs to be done for the DO build files/make rules since we aren't changing file names.

>OMIM susceptibility import

This is one I'd forgotten about and it probably presents the biggest challenge because both the IDs and URIs are based on "OMIM" (e.g. `OMIM:106300`, `http://purl.obolibrary.org/obo/OMIM_106300`). It seems like we should change the URIs along with the IDs. I guess that's one more place that users may need to update but maybe it's not as big a deal since the URIs are not currently resolvable anyway?

>On the DO website
-- Advance Search
-- SPARQL sandbox

Neither of these is dependent on prefixes, so we shouldn't need any updates for them. I'll only have to check the example SPARQL query examples we provide with the sandbox.

I decided to identify the use of "OMIM" for all non-OWL/OBO/JSON files in this repo (excluding files in the build, deprecated, and hidden directories). The files identified using this command are listed below along with the ontology edit/import files that need review/modification.
```zsh
find . ! -name "*.owl" ! -name "*.obo" ! -name "*.json*" ! -path "*build*" ! -path "*deprecated*" ! -path "./.*" -type f -print0 | 
xargs -0 grep -c "OMIM" | 
grep -E "[1-9]+$"
```

### Files in this repo:
- [ ] DOreports/allXREFinDO.tsv
- [ ] DOreports/OMIMinDO.tsv
- [ ] RELEASES.md
- [ ] example_issues/NTR-anna-anagnostop_1238.md
- [ ] example_issues/NTR-MonikaTomczuk_1254.md
- [ ] example_issues/NTR-sbello_1275
- [ ] example_issues/NTR-VJENKINS_1267.md
- [ ] example_issues/NTR-vjenkinsFB_1154
- [ ] CONTRIBUTING.md
- [ ] src/sparql/DOreports/OMIMinDO.rq
- [ ] src/ontology/README_DO_Files
- [ ] src/ontology/imports/omim_susceptibility.owl
- [ ] src/ontology/doid-edit.owl

### Files outside this repo
- [ ] disease-ontology.org OWL/OBO tree loader
- [ ] UMLS updater (this one we can probably do as part of planned improvements)

**Comment by fschiettecatte** [comment]
> @fschiettecatte does capitalization matter? Any preference for MIM vs mim?

Apologies for the slow reply, I was out through today. 

We want upper case of the 'MIM', see our [linking help](https://omim.org/help/linking) sections 1.8 and 1.9.

**Comment by lschriml** [comment]
I would prefer uppercase, as all other xrefs are uppercase.Sent from my iPhoneOn Feb 11, 2024, at 7:21 PM, François Schiettecatte ***@***.***> wrote:﻿

@fschiettecatte does capitalization matter? Any preference for MIM vs mim?

Apologies for the slow reply, I was out through today.
We want upper case of the 'MIM', see our linking help sections 1.8 and 1.9.

**Comment by allenbaron** [comment]
A test release, equivalent to official release `v2024-02-28`, with "OMIM:" prefixes replaced as "MIM:" has been created on the `mim_test_release` branch.

Test files are available at https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/mim_test_release/src/ontology

Please distribute this information as widely as possible so that all DO users are prepared for the April release in which this change will be implemented. Please reach out if you need any assistance.
