### ISSUE TITLE
Infantile hypotonia with psychomotor retardation and characteristic facies-3 (IHPRF3)

### ISSUE THREAD

**Issue by anna-anagnostop** [DiseaseOntology/HumanDiseaseOntology#1302]
Please consider adding new DO term:

DO TERM NAME: HYPOTONIA, INFANTILE, WITH PSYCHOMOTOR RETARDATION AND CHARACTERISTIC FACIES 3

SUGGESTED DEF: a severe autosomal recessive neurodevelopmental disorder characterized by very poor, if any, psychomotor development, poor speech, inability to walk independently and onset at birth or in early infancy that has_material_basis_in homozygous or compound heterozygous mutation in the TBCK gene ([616899](https://www.omim.org/entry/616899)) on chromosome 4q24.

SYN: IHPRF3 

PubMed IDs: PMID:[30103036](https://pubmed.ncbi.nlm.nih.gov/30103036/), PMID:[27040691](https://pubmed.ncbi.nlm.nih.gov/27040691), PMID:[27040692](https://pubmed.ncbi.nlm.nih.gov/27040692/)

OMIM #: [616900](https://www.omim.org/entry/616900) 

Thank you,

Anna V. Anagnostopoulos https://orcid.org/0000-0002-6490-7723

**Comment by csbjohnson** [comment]
Hi @anna-anagnostop, 

Thank you for your request for _Infantile hypotonia with psychomotor retardation and characteristic facies-3 (IHPRF3_). 

We'll review it and work on adding it to the Disease Ontology.

Best,
Claudia Marie Sánchez-Beato Johnson

**Comment by anna-anagnostop** [comment]
Thanks so much for adding this term to the DO.

**Comment by csbjohnson** [comment]
ou're most welcome! If you have any further requests, please don't hesitate to let us know. Happy to help!
