### ISSUE TITLE
NTR: Neurodevelopmental disorder with poor growth and behavioral abnormalities

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#1306]
Hi,
https://pubmed.ncbi.nlm.nih.gov/36604604/  is the paper that has a mouse model of the disorder reported in the paper that we would like to associate with a DO term. Not a whole lot of information on this new disorder.

Label: Neurodevelopmental disorder with poor growth and behavioral abnormalities
Definition: A neurodevelopmental disorder characterized by global developmental delay, moderately to severely impaired intellectual development, often with absent speech, and behavioral abnormalities, including hyperactivity, short attention span, and ADHD that has_material_basis_in homozygous or compound heterozygous mutation in the ATP9A gene on chromosome 10q13.
Definition ref: https://pubmed.ncbi.nlm.nih.gov/34379057/ and https://pubmed.ncbi.nlm.nih.gov/36604604/ 
Parent DO: 0060038 specific developmental disorder ? and DOID:0050737 autosomal recessive disease ?
DbXref: OMIM:620242

Thank you,
Monika Tomczuk
MGI Scientific Curator 
ORCID:0009-0005-7755-8314

**Comment by allenbaron** [comment]
I'll review this and add the disease after TAGC. Thanks Monika!

**Comment by lschriml** [comment]
added: 
DOID:0081444
