### ISSUE TITLE
New Term Request: Large B-cell lymphoma

### ISSUE THREAD

**Issue by cstatz78** [DiseaseOntology/HumanDiseaseOntology#1307]
Hello!

I was wondering if you could add Large B-cell lymphoma as a child term to B-cell lymphoma (DOID:707)? If yes, diffuse large B-cell lymphoma (DOID:0050745) would be a child term to Large B-cell lymphoma as well as intravascular large B-cell lymphoma (DOID:0081311) and high-grade B-cell lymphoma double-hit/triple-hit (DOID:0081004).

Here's the reference for this request: https://pubmed.ncbi.nlm.nih.gov/37190213/, which includes a general definition for large B-cell lymphomas.

If there are any questions, just let me know.

Thanks!
Cara

**Comment by csbjohnson** [comment]
Hi @vjenkinsFB,

Thank you for your request @cstatz78. We'll review your new term request for Large B-cell lymphoma.

Best,
Claudia Marie Sánchez-Beato Johnson

**Comment by lschriml** [comment]
Thank you Cara, Large B-cell lymphoma has been added to the DO and the parentage for those child terms have been revised. 
These updates will be included in our monthly release tomorrow.
Much appreciated !!
Cheers,
Lynn
