### ISSUE TITLE
DO cancer slim

### ISSUE THREAD

**Issue by wdduncan** [DiseaseOntology/HumanDiseaseOntology#131]
Hi all,

I recently read the article "Generating a focused view of disease ontology cancer terms for pan-cancer data integration and analysis".

In it, the authors state the DO_cancer_slim obo file is to be found in the src/ontology branch of this github site. However, I'm not seeing the file. 

Have the terms in DO slim already been incorporated in to the disease ontology? Or do I need to look somewhere else?

Thanks,
Bill

**Comment by elviram** [comment]
Hello Bill,

the terms are part the Disease Ontology. The DO_cancer_slim and all the slims haven been moved to the src/ontology/subsets folder.

Best,
Elvira

**Comment by wdduncan** [comment]
Thanks!
