### ISSUE TITLE
Lisch epithelial corneal dystrophy (DOID:0060450)

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1310]
**Is your request related to a specific disease? Please describe.**
Lisch epithelial corneal dystrophy (DOID:0060450)

**Describe the proposed change(s)**
OMIM has obsoleted MIM:300778 and merged this into MIM:620763 

MIM:620763 specifies a causal relationship to MCOLN1 on Chr. 19

The ORDO record also linked to DOID:0060450 specifies an X-linked dominant relationship.

The DO definition does not specify any gene relationship, only the phenotypic characterization of the disease.

Looking at the OMIM record it appears that the OMIM and ORDO records may be the same disease as the OMIM record describes an original association with the X chromosome and a more recent publication for the gene on chromosome 19.

I think we can just remove the existing OMIM xref and replace it with MIM:620763. Possibly the definition should be update to include the gene.

The publication for the new gene reference is PMID:[37972748](https://pubmed.ncbi.nlm.nih.gov/37972748/)

**Comment by csbjohnson** [comment]
Hi Sue! @sbello 

Thank you very much for the information, I implemented the changes and they will be reflected in the upcoming Disease Ontology Release.

Wishing you a lovely day!
