### ISSUE TITLE
New Term Request: Dimethylglycine dehydrogenase deficiency

### ISSUE THREAD

**Issue by rankishore** [DiseaseOntology/HumanDiseaseOntology#1315]
Model organisms have the human DMDH gene ortholog and it would be nice if DO had the "dimethylglycine dehydrogenase deficiency" term so that we can annotate them.  

Reference: https://pubmed.ncbi.nlm.nih.gov/11231903/

OMIM xref: https://omim.org/entry/605850 
OMIM xref: https://omim.org/entry/605849

Proposed definition:  A choline metabolic disorder that has material_basis_in deficiency of dimethylglycine dehydrogenase (DMDH).

Thanks for your consideration.
-Ranjana Kishore
WormBase and Alliance of Genome Resources

**Comment by lschriml** [comment]
-- adding this term as a child of amino acid metabolic disorder (DOID:9252)
DOID:0081446


Notes:

Choline and glycine are inter-related through their roles in methyl metabolism. 
Choline is metabolized to betaine, which donates a methyl group to homocysteine to form methionine, also generating dimethylglycine, which is further metabolized to glycine. Choline is transported across the placenta and is higher in fetal than maternal plasma.

 
Friesen RW, Novak EM, Hasman D, Innis SM. Relationship of dimethylglycine, choline, and betaine with oxoproline in plasma of pregnant women and their newborn infants. J Nutr. 2007 Dec;137(12):2641-6. doi: 10.1093/jn/137.12.2641. PMID: 18029477.
https://pubmed.ncbi.nlm.nih.gov/18029477/

**Dehydrogenases** are respiratory enzymes that transfer two hydrogen atoms from organic compounds to electron acceptors, thereby oxidizing the organic compounds and generating energy.

**dimethylglycine dehydrogenase** 
https://www.ncbi.nlm.nih.gov/gene/29958
- This gene encodes an enzyme involved in the catabolism of choline, catalyzing the oxidative demethylation of dimethylglycine to form sarcosine
- 
- --> Mutation in this gene causes **dimethylglycine dehydrogenase deficiency**, characterized by a fishlike body odor, chronic muscle fatigue, and elevated levels of the muscle form of creatine kinase in serum
