### ISSUE TITLE
Amelogenesis imperfecta subtypes

### ISSUE THREAD

**Issue by csbjohnson** [DiseaseOntology/HumanDiseaseOntology#1316]
PS104500

**Comment by lschriml** [comment]
Noticed the nomenclature uses numerals (e.g., 1 or 2) instead of the Roman Numerals (I, II)

**Comment by lschriml** [comment]
type IIA6 --> update disease name to : 
amelogenesis imperfecta hypomaturation type 2A6
 
== to do: review each subtype and update nomenclature, using the above format.

**Comment by csbjohnson** [comment]
Upon review, the amelogenesis imperfecta subtypes currently use the numerical format. ( For example: currently in the DO, the nomenclature is "amelogenesis imperfecta type 2A6" instead of "type IIA6", and the rest of the subtypes follow this pattern). If the desired format is to have the Disease Ontology nomenclature in numerals, all the subtypes currently abide by that format, with the exception of type "IK" that I updated to "1K".

The Disease Ontology is using numerals, while OMIM uses Roman numerals.
