### ISSUE TITLE
New Term Request: Warsaw Breakage Syndrome

### ISSUE THREAD

**Issue by ybradford** [DiseaseOntology/HumanDiseaseOntology#132]
Hi,

I would like to request a new term for OMIM #613398: WARSAW BREAKAGE SYNDROME.
Synonym: WABS

I need it for curation of PMID: 26089203 

Thank you,
Yvonne

**Comment by elviram** [comment]
Hello Yvonne,

the term will be included in today's release.

Best,
Elvira
