### ISSUE TITLE
review DOID:0111815

### ISSUE THREAD

**Issue by SianGramates** [DiseaseOntology/HumanDiseaseOntology#1326]
**Is your request related to a specific disease? Please describe.**
low molecular weight proteinuria with hypercalciuric nephrocalcinosis 

**Describe the proposed change(s)**
Definition has a typo; please correct 'elevted' to 'elevated'.

I'm also wondering if OMIM should be encouraged to merge this disease (MIM:308990) with the nearly identical Dent disease 1 (MIM:300009).

**References**
Provide links to a database or a PubMed ID

**Comment by lschriml** [comment]
Thank you Sian !! 
Fixed.
OMIM does note that 'low molecular weight proteinuria with hypercalciuric nephrocalcinosis' is a member of the Dent disease complex. 

Agreed, this is worth asking OMIM to review, to see if Dent 1 and 'low molecular weight proteinuria with hypercalciuric nephrocalcinosis' should be merged. 

Cheers,
Lynn
