### ISSUE TITLE
New Term Request: Need terminology for "healthy" or lack of a disease

### ISSUE THREAD

**Issue by schedlbau** [DiseaseOntology/HumanDiseaseOntology#1327]
Our organization frequently curates metadata associated with biological datasets. We have a disease entity in many of our data models and thus map disease terms to this concept. We use the Human Disease Ontology, but we commonly have biological samples coming from healthy tissue or healthy donors (e.g. as controls).  Would it be possible to add a term to capture this concept? It would greatly facilitate our ability to make data FAIR and completely map to a single common standard (as opposed to modifying or combining ontologies). Thank you!

Suggested defintion of "healthy" - Having no significant health-related issues

**Comment by lschriml** [comment]
Hello @schedlbau -- Thank you for contact the Human Disease Ontology. 
   We love that you are using the DO, and would be interesting in learning more about how you use the DO.

We would suggest a solution that has been devised and implemented by our collaborators at MGI. 
  That is to annotate using a qualifier like NOT or NONE or NORMAL to indicate the sample does not have any associated disease.
  Sharing here how MGI implements their solution:   
 MGI captures phenotype annotations where there are unexpected normal phenotypes in a system (using the NORMAL qualifier) and mice that don't model an expected human disease (NOT plus the DO term for the expected disease).

I hope this is of help. 
Thank you @sbello for sharing your process.

Cheers,
Lynn
