### ISSUE TITLE
Fix typos in ontology in bulk

### ISSUE THREAD

**Issue by cmdcolin** [DiseaseOntology/HumanDiseaseOntology#1328]
**Is your request related to a specific disease? Please describe.**
No

**Describe the proposed change(s)**
Use a typo detector tool to fix typos across repo

**References**
N/A

I used the typos-cli and ruplacer tools to create an example of this

I first created a similar PR to the mondo ontology, but i figured similar approaches can be added to others too

https://github.com/monarch-initiative/mondo/pull/7685

here is a quick test of using this same approach on the HumanDiseaseOntology repo. I focused on the src/ontology folder https://github.com/DiseaseOntology/HumanDiseaseOntology/compare/main...cmdcolin:HumanDiseaseOntology:main

**Comment by lschriml** [comment]
Thank you Colin for pointing out these typos. 
We will review and make updates.
We appreciate your sharing your work with us. 
We would like to acknowledge your contribution, can you share your ORCID ID with us ? 

Cheers,
Lynn

**Comment by cmdcolin** [comment]
sure thing, my ORCID is 0000-0003-2629-7570

I can also make the above branch into a pull request, and/or describe more about my approach. I used the tools "typos-cli" and "ruplacer" to make changes on a bulk scale.
