### ISSUE TITLE
Bug in the latest DO release? Related to inferred parents

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1329]
In the latest DO release a number of terms lost a path to an MGI DO slim term. Reviewing the issue this appears to be because the term 'hematological cancer' (DOID:2531) no longer has an inferred parent of 'hematopoietic system disease' (DOID:74)

Looking in MGI which is still displaying the last version on DO (at least for this week) I see the relations in the attached image (https://www.informatics.jax.org/disease/DOID:12603) where 'acute leukemia' has 2 ancestors since 'hematological cancer' is a child both 'hematopoietic system disease' and 'organ system cancer'. Since 'hematopoietic system disease' is in the MGI slim 'acute leukemia' had an ancestor in the MGI slim.

Looking in the current doid-merged.obo file 'hematological cancer' no longer has the parent 'hematopoietic system disease' it only has the 'organ system cancer' parent.

Looking in the doid-edit.owl file I still see that 'hematological cancer' has an eq that includes 'hematopoietic system' and that 'hematopoietic system disease' has an eq that includes 'hematopoietic system'

If I run the ELK reasoner on the current edit file I do not get the inference that 'hematological cancer' is a 'hematopoietic system disease' but I do get the inference that for example 'immune system cancer' is an 'immune system disease'.

Possibly the inclusion of the stanza  ('has material basis in' some 'hematopoietic cell') is causing an issue? Is this new?

The eq for hematopoietic system disease is 
disease and (('has material basis in' some 'hematopoietic cell') and ('disease has location' some 'hematopoietic system'))

The eq for immune system disease is 
disease and ('disease has location' some 'immune system')

![acuteLeukemia](https://github.com/DiseaseOntology/HumanDiseaseOntology/assets/10979793/47b54839-d679-4836-a755-f79e5e96266c)

**Comment by lschriml** [comment]
fixed, I split the EQs, checked and is working as expected.
Thank you for pointing this out Sue !!
Cheers,
Lynn
