### ISSUE TITLE
New term request: children of Hermansky-Pudlak syndrome

### ISSUE THREAD

**Issue by SianGramates** [DiseaseOntology/HumanDiseaseOntology#133]
Hermansky-Pudlak syndrome (DOID:3753) has 9 OMIM subtypes (phenotypic series Hermansky-Pudlak syndrome - PS203300), HPS1-9 (OMIM:203300, OMIM:608233, OMIM:614072, OMIM:614073, OMIM:614074, OMIM:614075, OMIM:614076, OMIM:614077, OMIM:614171), each linked to a different gene involved with lysosome structure/function/trafficking.

**Comment by elviram** [comment]
Hello Sian,
these terms will be included in today's release of DO.

Best,
Elvira

**Comment by SianGramates** [comment]
Thanks Elvira.

Cheers,
Sian
