### ISSUE TITLE
More subtypes of thyroid cancer

### ISSUE THREAD

**Issue by kkrysiak** [DiseaseOntology/HumanDiseaseOntology#1343]
Currently there is only the umbrella term for thyroid cancer in DO.

There are a number of subtypes that are missing. At a minimum supporting papillary thyroid carcinoma and medullary thyroid carcinoma would be very helpful.

NCIt has a number of child terms just for papillary thyroid carcinoma:
https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&version=24.04e&code=C4035&ns=ncit&type=relationship&key=1440863471&b=1&n=0&vse=null

The 2022 WHO guidelines outline several as well and this review helps highlight them:
https://erc.bioscientifica.com/view/journals/erc/30/2/ERC-22-0293.xml

This paper includes ICD-O terms as well:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9633223/

**Comment by allenbaron** [comment]
Thanks for your request Dr. Krysiak. We will work to add missing thyroid cancer subtypes.

**Comment by lschriml** [comment]
Hello KK,
Thank you for the references, very useful !! 
I also went through the WHO Blue Books for updates and reviewed NCI's representation.

    --> under thyroid cancer (DOID:1781), there are the: (upper nodes, with their subtypes)
      thyroid gland carcinoma
                --> thyroid gland papillary carcinoma  (DOID:3969)
                --> thyroid gland follicular carcinoma.  (DOID:3962)
                --> thyroid gland medullary carcinoma. (DOID:3973)
      thyroid lymphoma
      thyroid sarcoma 

This was super helpful for updating this branch !! 
     I am adding new terms, updating nomenclature, adding synonyms, e.g., for the terms
you mentioned in this ticket: 
                    papillary thyroid carcinoma and medullary thyroid carcinoma

 Would you prefer that all subtypes under 'thyroid carcinoma' be added to the DO cancer slim ? 

I am adding in the changes today, they will be public with our release at the end of this week.

Cheers,
Lynn

**Comment by lschriml** [comment]
Updates complete, will take another look at WHO new terms: Papillary thyroid carcinoma, before closing this ticket.

**Comment by lschriml** [comment]
done
