### ISSUE TITLE
Add xref to DOID:1440

### ISSUE THREAD

**Issue by nmah** [DiseaseOntology/HumanDiseaseOntology#1357]
Machado-Joseph disease, needed review.  

For the "Machado-Joseph disease", I would like to suggest to create a cross-reference between the DOID term and the ORDO term: 
Machado-Joseph disease [http://purl.obolibrary.org/obo/DOID_1440] and Spinocerebellar ataxia type 3 [http://www.orpha.net/ORDO/Orphanet_98757]

This is the same disease in both ontologies, and each ontology term is cross-referenced to UMLS_CUI:C0024408 and MESH:D017827. 
Both Orphanet [https://www.orpha.net/en/disease/detail/98757] and Wikipedia [https://en.wikipedia.org/wiki/Machado%E2%80%93Joseph_disease] state that "Spinocerebellar ataxia type 3" and "Machado-Joseph disease" are synonyms of the same disease.

**Comment by allenbaron** [comment]
You are absolutely right. Thanks for pointing this out and including details to speed up review.

The suggested xref and another to GARD:6801 will both be included on DOID:1440 in the next release.
