### ISSUE TITLE
GLUT1 DEFICIENCY SYNDROME 1

### ISSUE THREAD

**Issue by anna-anagnostop** [DiseaseOntology/HumanDiseaseOntology#1359]
Consider adding new DO term:

DO TERM NAME: GLUT1 DEFICIENCY SYNDROME 1
SUGGESTED DEF: a severe, infantile-onset neurologic disorder characterized by infantile seizures, ataxia, microcephaly, severe mental retardation with learning disabilities, delayed development, hypoglycorrhachia, and other varied symptoms, that has_material_basis_in heterozygous mutation in the solute carrier family 2 member 1 (SLC2A1) gene on chromosome 1p34.2. Rare cases caused by homozygous or compound heterozygous mutation in the SLC2A1 gene have been reported.
SYN: GLUT1DS1 
SUGGESTED PARENT TERMS: autosomal dominant disease ([DOID:0050736](http://www.disease-ontology.org/?id=DOID:0050736))
PubMed IDs: PMID: [1714544](https://pubmed.ncbi.nlm.nih.gov/1714544/), PMID: [9462754](https://pubmed.ncbi.nlm.nih.gov/9462754/), PMID: [23443458](https://pubmed.ncbi.nlm.nih.gov/23443458/)
OMIM #: [606777](https://www.omim.org/entry/606777) (Other entities represented in this entry: GLUT1 DEFICIENCY SYNDROME 1, AUTOSOMAL RECESSIVE, INCLUDED)

Thank you,

Anna V. Anagnostopoulos https://orcid.org/0000-0002-6490-7723

**Comment by allenbaron** [comment]
Thanks Anna. We will get this added before the next release.

**Comment by allenbaron** [comment]
This disease will be in the release today as 'glucose transporter type 1 deficiency syndrome 1' (DOID:0070561).
