### ISSUE TITLE
Proposal: make root of DOID a process

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#136]
I propose the entity of most utility to users and the most amenable to reasoning is the realization of the disposition, aka disease course.

By making the occurrent primary, it is far simpler to record when the disease starts and when it ends. It also removes a layer of unnecessary abstraction distancing us from unobservable hypothetical entities.

Note that groups that require a realization class can still use a class expression `realizedBy some D`

**Comment by lschriml** [comment]
Hello Chris,
    are you suggesting that our top node of DO, disease, be changed from a 'disposition' to a 'process' ?
Cheers,
Lynn

**Comment by cmungall** [comment]
Yes.

Just to clarify, there is no logical axiom change I am requested in DO, 
as there is no logical axiom in DO connecting to BFO.
