### ISSUE TITLE
Review and add carbohydrate transport diseases

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1362]
A glucose transporter disease was requested in #1359 and while attempting to determine where to classify it, I discovered the DO is missing a number of other glucose transporter diseases and that there is not currently a grouping term for carbohydrate/glucose transport diseases.

Please review glucose transport diseases (and possibly also the broader group of carbohydrate transport diseases) and determine which need to be added and what grouping term would be appropriate, if any.

Orphanet has the following [classification](https://www.orpha.net/en/disease/classification/group/158293?orphaCode=309001&firstParent=0&name=Disorder-of-carbohydrate-absorption-and-transport&mode=name) related to carbohydrate transport:
<img width="608" alt="image" src="https://github.com/user-attachments/assets/e10a8179-6c37-4ee1-ad04-602e11d27590">

With the glucose transport diseases:
<img width="584" alt="image" src="https://github.com/user-attachments/assets/e8c2e80b-0472-40f7-9bdd-38f64a0e04fa">
None of these glucose transport diseases appear to be in DO based on ORDO or MIM xref.

It's a bit surprising that Orphanet's glucose transporter diseases don't include 'Paroxysmal exertion-induced dyskinesia'. This disease is equivalent to DO's 'childhood-onset GLUT1 deficiency syndrome 2' (DOID:0090045), which is caused by mutations in the same glucose transporter gene (GLUT1, now officially [SLC2A1](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11005)) as the disease requested in #1359. 'childhood-onset GLUT1 deficiency syndrome 2' (DOID:0090045) is currently only classified as a child of dystonia (DOID:543) and not as a descendant of 'inherited metabolic disorder' (DOID:655) as it should be. 'childhood-onset GLUT1 deficiency syndrome 2' and its classification is also mentioned in #1361.

**Comment by lschriml** [comment]
I have reviewed the Glucose related terms, the terms to add or update are highlighted in blue, I added steps at the top of the sheet.
https://docs.google.com/spreadsheets/d/17SKWy4qNKOqNzJo63cKUimcC97u3uhXRyTyxTw6B2KE/edit?gid=0#gid=0

**Comment by allenbaron** [comment]
### Additions
- 'glucose transporter type 1 deficiency syndrome' (DOID:0070560)
- 'glucose transporter type 1 deficiency syndrome 1' (DOID:0070561)
- 'Fanconi-Bickel syndrome' (DOID:0070562)
- 'glucose-galactose malabsorption' (DOID:0070563)

### Revisions

**Now children of 'glucose transporter type 1 deficiency syndrome' (DOID:0070560):**
- 'glucose transporter type 1 deficiency syndrome 2' (DOID:0090045)
- 'dystonia 9' (DOID:0090044)

_These retained their previous parentage as well._

**Updated:**
- 'carbohydrate metabolic disorder' (DOID:2978) = added xrefs
- 'glucose metabolism disease' (DOID:4194) = added definition


**Still need to revise 'renal glycosuria' (DOID:9432).**

**Comment by allenbaron** [comment]
Currently, 'renal glycosuria' (DOID:9432) has a somewhat confusing status since it lacks a definition. From an ontology perspective, taking into account the whole of the information that's annotated to it, it would probably be considered an exact match to the currently linked OMIM ID ([MIM:233100](https://omim.org/entry/233100)). However, non-ontologists likely have been interpreting it differently based on the label (since they can't use the definition) and the current label suggests a broader meaning. There is, in fact, evidence from the Alliance that it has been used more broadly to annotate disease information to this term (HNRNPF gene was annotated to this term in mice, while the OMIM term and genetic cause in humans is limited to SLC5A2).

To avoid invalidating potential annotations, this disease will be more clearly defined to represent the broadest disease case (primary/isolated renal glycosuria without an inheritance requirement), and a child will be added that is equivalent to the OMIM xref. Xrefs & synonyms will be moved and updated as needed.
