### ISSUE TITLE
Consider merging DOID:0110578 and DOID:0110546

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1368]
OMIM has moved MIM:607683 to merge this with MIM:602459

MIM:607683 is an xref for autosomal dominant nonsyndromic deafness 52 DOID:0110578, 

MIM:602459 is an xref for autosomal dominant nonsyndromic deafness 15 DOID:0110546

The only other xref for both terms is ICD10CM:H90.3

OMIM has in the nomenclature section
[Xia et al. (2002)](https://www.omim.org/entry/602459#10) referred to the deafness locus that they located on 5q as DFNA42; however, the HUGO Nomenclature Committee assigned this deafness locus DFNA52. The family reported by [Xia et al. (2002)](https://www.omim.org/entry/602459#10) is incorporated into DFNA15 because mutation in the POU4F3 gene was later found to segregate with the disorder; see MOLECULAR GENETICS.

**Comment by allenbaron** [comment]
Without looking into it yet, it seems to make sense that these should be merged. I'll review this and get it updated before the next release. Thanks Sue.
