### ISSUE TITLE
anterior horn cell disease (DOID:4873)

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#1369]
**Is your request related to a specific disease? Please describe.**
anterior horn cell disease

**Describe the proposed change(s)**
This term does not have a definition in DOID. The MONDO_0003182(anterior horn disorder) reference this term via DbXref. Google shows an entry of [anterior horn disease in wiki](https://en.wikipedia.org/wiki/Anterior_horn_disease), which has the same definition with MONDO_0003182. The anterior horn cell disease seems a combination of a lot of diseases.
This is hard for us to determine if these two terms are equivalent or not. 
Please either add the definition for the term, or exam if it is intended the same as the MONDO term, and provide equivalent synonyms annotations or change your labels. 

**References**
***anterior horn cell disease resources***:
1. https://link.springer.com/referenceworkentry/10.1007/978-3-642-02202-9_370#:~:text=Disorders%20of%20the%20anterior%20horn,to%20enteroviruses%20other%20than%20poliovirus
2. https://www.sciencedirect.com/topics/medicine-and-dentistry/anterior-horn-cell-disease
***anterior horn disease resource***
1. https://en.wikipedia.org/wiki/Anterior_horn_disease

**Comment by allenbaron** [comment]
Hi @linikujp, thanks for reaching out. It sounds like this is part of an effort to compare diseases in the DO and Mondo, is that right?

Based on a quick review, it appears this is an older term in the ontology that may not be a true disease but might have been retained for the purpose of grouping other diseases (based on the definition at Wikipedia and the other links you've shared, as well as, the info at https://accesspediatrics.mhmedical.com/content.aspx?bookid=2126&sectionid=191302817.

Honestly, those definitions sort of imply it might be equivalent to 'motor neuron disease' (DOID:231). I'll assign Lynn to take a look at this since she's more familiar with term history and we'll get back to you.

**Comment by lschriml** [comment]
The mondo and DO terms are representing the same disease. 
I have added the definition. 

Cheers,
Lynn

Note:
Poliomyelitis, spinal muscular atrophy, amyotrophic lateral sclerosis and progressive muscular atrophy are diseases that frequently include problems within the anterior horn. 
  These diseases are not subtypes of 'anterior horn cell disease'


Taking a look at "anterior horn cell disease":

-->> anterior horn cell disease is a type of 'motor neuron disease'


**definitions:**
Anterior horn disease is a medical disorder affecting the anterior horn of the spinal cord that contains the motor neurons responsible for body muscles.
Anterior horn disease is characterized by selective involvement of muscles.
Anterior horn cell disease is characterized predominantly by lower motor neuron affection
--  lower motor neuron signs of weakness, wasting (atrophy), and fasciculations
-- characteristic lower motor neuron signs of wasting, weakness, and loss of reflexes

 Poliomyelitis, spinal muscular atrophy, amyotrophic lateral sclerosis and progressive muscular atrophy are diseases that frequently include problems within the anterior horn. 

sources: 
https://www.neurores.org/index.php/neurores/article/view/407/409
https://aimdrjournal.com/wp-content/uploads/2021/08/PE6_CR_PM.pdf

**Comment by lschriml** [comment]
The anterior horn cell is a motor neuron that projects from the anterior portion of the grey matter in the spinal cord to the skeletal muscle. 

synonyms:   (cell ontology):  
        anterior horn cell
       ventral horn of spinal cord spinal cord motor neuron
             (UBERON:0002257): ventral horn of spinal cord
