### ISSUE TITLE
purine-pyrimidine metabolic disorder (DOID:653)

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#1370]
**Is your request related to a specific disease? Please describe.**
purine-pyrimidine metabolic disorder (DOID:653)  

**Describe the proposed change(s)**
based on the wikipedia reference used for this term definition, the term refers to a union of purine or pyrimidine metabolism disorder. Therefore, the definition of this term should be "An inherited metabolic disorder involving dysfunction of purine **OR** pyrimidine metabolism" (suggested definition), instead of "An inherited metabolic disorder involving dysfunction of purine  and pyrimidine metabolism" (current definition).

**References**
http://en.wikipedia.org/wiki/Inborn_errors_of_purine-pyrimidine_metabolism

**Comment by csbjohnson** [comment]
Hi @linikujp ,

Thank you for your request . We'll review your definition review request for purine-pyrimidine metabolic disorder (DOID:653).

Best,
Claudia Marie Sánchez-Beato Johnson

**Comment by linikujp** [comment]
Hi Lynn,
Besides what you confirmed that the disease defines a condition of both purine metabolism disorder and pyrimidine metabolism disorder, what I want to know is if the disease also have either of the purine metabolism disorder (only) or the pyrimidine metabolism disorder (only) as its children terms. Or if purine metabolism and pyrimidine metabolism can not be separated condition exist independently. The former case, the disease will be "disorder of purine and/or pyrimidine metabolism", the latter, the disease will be "disorder of purine and pyrimidine metabolism".

Thanks,
Asiyah

**Comment by lschriml** [comment]
Thank you for the review suggestions. 
    By definition, the subtypes of the 'purine-pyrimidine metabolic disorder' branch include:
    purines: adenine or guanine
    pyrimidine: cytosine, thymine, and uracil

Reviewing our previous assignments to this disease category: 
     -- Some initial notes are below, I will be continuing this review of our classification, to update this area of the DO. 
Cheers,
Lynn

NOTES: 

**purine-pyrimidine metabolic disorders:**
-- The most common of purine and pyrimidine metabolism disorders is the deficiency of hypoxanthine phosphoribosyl transferase that also causes hyperuricaemia in childhood.
       https://blueprintgenetics.com/tests/panels/metabolic-disorders/purine-and-pyrimidine-metabolism-disorders-panel/


Merck:
https://www.merckmanuals.com/professional/pediatrics/inherited-disorders-of-metabolism/overview-of-purine-and-pyrimidine-metabolism-disorders

**Purine Metabolism Disorders:** 
disease (OMIM)
- Calcium pyrophosphate arthropathy (chondrocalcinosis-2; (118600)
- Lesch-Nyhan syndrome
             (https://www.merckmanuals.com/professional/pediatrics/inherited-disorders-of-metabolism/purine-salvage-disorders#v88762661) (300322)

- Increased activity of phosphoribosylpyrophosphate synthetase (311850)
- Phosphoribosylpyrophosphate synthetase I deficiency (311850)
- Hereditary xanthinuria
- Type I (278300)
- Type II (603592)
- Adenine phosphoribosyltransferase deficiency (102600)
- Type I
- Type II
- [Adenosine deaminase deficiency](https://www.merckmanuals.com/professional/pediatrics/inherited-disorders-of-metabolism/purine-catabolism-disorders#v88762622) (102700)
- Increased adenosine deaminase (102730)
- [Purine nucleoside phosphorylase deficiency](https://www.merckmanuals.com/professional/pediatrics/inherited-disorders-of-metabolism/purine-catabolism-disorders#v88762635) (164050)
- [Myoadenylate deaminase deficiency](https://www.merckmanuals.com/professional/pediatrics/inherited-disorders-of-metabolism/purine-catabolism-disorders#v88762617) (adenosine monophosphate deaminase I; 102770)
- Adenylate kinase deficiency (103000)
- Adenylosuccinase deficiency (103050)
Type I (severe form)
Type II (mild form)


Merck: Pyrimidine metabolic disorders
https://www.merckmanuals.com/professional/pediatrics/inherited-disorders-of-metabolism/pyrimidine-metabolism-disorders

- [Hereditary orotic aciduria](https://www.merckmanuals.com/professional/pediatrics/inherited-disorders-of-metabolism/pyrimidine-metabolism-disorders#v88762676) (258900)
- Dihydropyrimidine dehydrogenase deficiency (274270)
Inborn error form
Pharmacogenetic form
-- Dihydropyrimidinuria (222748)
-- Beta-ureidopropionase deficiency (613161)
-- Pyrimidine 5′ nucleotidase deficiency (266120)
-- Activation-induced cytidine deaminase deficiency (hyper IgM syndrome type II; 605257)
--
