### ISSUE TITLE
invalid KEGG Xrefs

### ISSUE THREAD

**Issue by need47** [DiseaseOntology/HumanDiseaseOntology#1374]
Dear DO team,

I have observed many invalid KEGG Xrefs, e.g. KEGG:05014 in,
[DOID:332](https://www.disease-ontology.org/?id=DOID:332)

The KEGG disease id **05014** doesn't follow the format of H number (e.g. H12345). Even you add the preceding H, [H05014](https://www.kegg.jp/entry/H05014) is still not a valid KEGG disease entry.

Do I misinterpret the KEGG xref? Thank you.

**Comment by csbjohnson** [comment]
Hi @need47  ,

Thank you for your request . We'll review your inquiry regarding KEGG xref in the DO  promptly.

Best,
Claudia Marie Sánchez-Beato Johnson

**Comment by allenbaron** [comment]
Hi @need47, thanks for reaching out. I can appreciate the confusion. The KEGG xrefs in DO are few (42 total) and somewhat varied, but they are all to real KEGG identifiers. The preference has been to reference KEGG pathways. Only when KEGG pathways did not exist in relation to a give disease, have KEGG diseases been referenced.

- 36 KEGG xrefs reference KEGG pathways (all those without the 'H' in the identifier).
    - Example: 'inflammatory bowel disease' (DOID:0050589) --> KEGG:05321
    - Accessible on KEGGs website by appending the number to `https://www.genome.jp/entry/hsa` --> https://www.genome.jp/entry/hsa05321
- 6 KEGG xrefs reference KEGG diseases. These have identifiers that include 'H'
    - Example: 'fibular hypoplasia and complex brachydactyly' (DOID:0050790) --> KEGG:H00467.
    - Accessible on KEGGs website by appending the H number to `https://www.genome.jp/entry/` --> https://www.genome.jp/entry/H00467

Admittedly, it would probably be less confusing if the pathway xrefs had `hsa` before the numbers. If we make any modifications, we will consider this but we have no plans currently to either add or update KEGG xrefs, as it is not clear to us that they are being/will be used.

For reference, here is a file with the whole list of KEGG diseases, pathways, their relationships to one another, and their relationships to DO diseases (via xrefs): [DO-KEGG-mapping.csv](https://github.com/user-attachments/files/16817842/DO-KEGG-mapping.csv).

If you have any other questions or comments concerning KEGG xrefs, feel free to post them on this issue (and reopen it if you want further assistance beyond discussion).

Thanks again!
