### ISSUE TITLE
nephroblastoma definition contains "located_in children"

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#1376]
**Is your request related to a specific disease? Please describe.**
nephroblastoma (DOID:2154)

**Describe the proposed change(s)**
A kidney cancer that affects the kidneys and typically *located_in children*. Is this the right use of the relation "located_in"?

**References**
N/A

**Comment by lschriml** [comment]
Hello Asiyah,  The relation here should be ‘existence starts during’   We will update this term for our next release.    Thank you for pointing out this update.Cheers,LynnOn Aug 30, 2024, at 11:49 AM, Asiyah Yu Lin ***@***.***> wrote:﻿
Is your request related to a specific disease? Please describe.
nephroblastoma (DOID:2154)
Describe the proposed change(s)
A kidney cancer that affects the kidneys and typically located_in children. Is this the right use of the relation "located_in"?
References
N/A

**Comment by linikujp** [comment]
I am glad that I made some contributions.  Additionally, perhaps add located_in Kidney?

**Comment by lschriml** [comment]
Thank you !We will review and update next week.Cheers,LynnOn Aug 30, 2024, at 2:07 PM, Asiyah Yu Lin ***@***.***> wrote:﻿
I am glad that I made some contributions.  Additionally, perhaps add located_in Kidney?

**Comment by lschriml** [comment]
The definition has been updated, this disease is a child of kidney cancer, so it's anatomical location is inferred from that relationship.
Cheers,
Lynn
