### ISSUE TITLE
	syndromic X-linked intellectual disability Cabezas type

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#1377]
**Is your request related to a specific disease? Please describe.**
syndromic X-linked intellectual disability Cabezas type (DOID:0060822)

**Describe the proposed change(s)**
The definition mentioned that the material base of this disease is "mutation in the CUL4B gene on chromosome Xq23". However, in the reference, the gene is located on Xq24-25. In MedGene, it is Xq24. The Xq23 seems a typo, and it should be Xq24.

**References**
https://pubmed.ncbi.nlm.nih.gov/10978355/
https://www.ncbi.nlm.nih.gov/medgen/337334

**Comment by allenbaron** [comment]
Yep, you're right. It's fixed and will be in the next release. Thanks.
