### ISSUE TITLE
Check the reference URL if broken or not

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#1378]
Some URLs are broken. 
For example: 
https://disease-ontology.org/?id=DOID:3982 the reference for this term ( http://www.ninds.nih.gov/disorders/dystonias/detail_dystonias.htm)  is leading to a 404 error.

As a QC process, it should be established to check all broken URLs in the file, to ensure no broken URLs.

**Comment by lschriml** [comment]
Fixed. 
We run these reviews approximately every 6 months.

Cheers,
Lynn
