### ISSUE TITLE
Add pediatric brain tumor terms

### ISSUE THREAD

**Issue by seandavi** [DiseaseOntology/HumanDiseaseOntology#138]
Perhaps this is a place to start?

http://www.aans.org/Media/Fact%20Sheets/Classification%20of%20Brain%20Tumors.aspx

**Comment by elviram** [comment]
Thank you, Sean. Will be very useful.

Best,
Elvira

**Comment by seandavi** [comment]
If you want a pediatric brain tumor person to work with, let me know and I'll try to find you one.

**Comment by lschriml** [comment]
Hello Sean, 
apologies for the lengthy delay. 
The DO contains a number of (72) pediatric and childhood brain tumors. 
If there is a specific tumor term you would like us to add, please let us know.
Cheers,
Lynn
