### ISSUE TITLE
Replace or remove inactive MeSH mappings

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1392]
A few mappings in DO are to inactive MeSH terms (aka obsoleted). An automated check for replacements did not find specific terms. We should check to see if there are active MeSH terms that might be added or probably remove these.

The terms can be found in the [QC-MeSH-inactive](https://docs.google.com/spreadsheets/d/1c2erpaeFO871neJ7gZSNdiA2qEdtbQD_3m-uGrbLKRE/edit) Google Sheet. There are only a few, so I'm listing them here as well. The `object_source_version` is the last active year of the term in MeSH.

subject_id | subject_label | predicate | object_id | object_label | subject_source_version | object_source_version
-- | -- | -- | -- | -- | -- | --
DOID:12118 | pulmonary hemosiderosis | oboInOwl:hasDbXref | MESH:C536281 | [OBSOLETE] idiopathic pulmonary hemosiderosis | 2024-09-27 | 2023
DOID:0080222 | pseudohypoparathyroidism type IB | oboInOwl:hasDbXref | MESH:C548075 | [OBSOLETE] Pseudohypoparathyroidism Type 1B | 2024-09-27 | 2023
DOID:0060479 | Shwachman-Diamond syndrome | oboInOwl:hasDbXref | MESH:C537330 | [OBSOLETE] Shwachman syndrome | 2024-09-27 | 2019
DOID:0112003 | immunodeficiency 33 | oboInOwl:hasDbXref | MESH:C567070 | [OBSOLETE] Atypical Mycobacteriosis, Familial, X-Linked 1 | 2024-09-27 | 2021
DOID:4905 | pancreatic carcinoma | oboInOwl:hasDbXref | MESH:C562463 | [OBSOLETE] Pancreatic Carcinoma | 2024-09-27 | 2023
DOID:0080053 | Albright's hereditary osteodystrophy | oboInOwl:hasDbXref | MESH:C537045 | [OBSOLETE] Albright's hereditary osteodystrophy | 2024-09-27 | 2020
DOID:8923 | skin melanoma | oboInOwl:hasDbXref | MESH:C562393 | [OBSOLETE] Melanoma, Cutaneous Malignant | 2024-09-27 | 2023
DOID:0111799 | syndromic microphthalmia 1 | skos:exactMatch | MESH:C564457 | [OBSOLETE] Microphthalmia, Syndromic 4 | 2024-09-27 | 2021

**Comment by lschriml** [comment]
MeSH term updated for: 
pulmonary hemosiderosis --> added new MeSH ID
Shwachman-Diamond syndrome --> added new MeSH ID

MeSH term removed for:
pseudohypoparathyroidism type IB
immunodeficiency 33 --> removed
        Orphaned has a new name: X-linked mendelian susceptibility to mycobacterial diseases due to IKBKG deficiency
        No name change in OMIM
pancreatic carcinoma

**Comment by lschriml** [comment]
--> Nomenclature, xrefs and definitions updated: 
Notes: 

DOID:0080053
Albright's hereditary osteodystrophy
    --> nomenclature update 

parent term: pseudohypoparathyroidism
        --> in OMIM: nomenclature change to : pseudohypoparathyroidism type 1A
                         defn: 
                                 Pseudohypoparathyroidism is a term applied to a heterogeneous group of disorders whose common feature is end-organ resistance to parathyroid hormone (PTH; [168450](https://omim.org/entry/168450)). In addition to PTH resistance, PHP Ia is characterized by resistance to other hormones, including thyroid-stimulating hormone (TSH; see TSHB, [188540](https://omim.org/entry/188540)) and gonadotropins. PHP Ia is associated with a constellation of clinical features referred to as Albright hereditary osteodystrophy (AHO), which includes short stature, obesity, round facies, subcutaneous ossifications, brachydactyly, and other skeletal anomalies.

        ==> GARD:5770 is gone
                    new GARD ID: 7486
                         https://rarediseases.info.nih.gov/diseases/7486/pseudohypoparathyroidism-type-1a
        --> in MeSH: subtypes are grouped under this parent term

         --> Orphanet: was ORDO:665. --> removed, 
https://www.orpha.net/en/disease/detail/665
This entity has been excluded from the Orphanet nomenclature of rare diseases and moved to [Pseudohypoparathyroidism with Albright hereditary osteodystrophy](https://www.orpha.net/en/disease/detail/457059)
             new ID: ORDO:79443

Gene Reviews: 
       - nomenclature: Disorders of GNAS Inactivation
       - https://www.ncbi.nlm.nih.gov/books/NBK459117/
       - dated 2017:
       - Disorders of GNAS inactivation include the phenotypes pseudohypoparathyroidism Ia, Ib, and Ic (PHP-Ia, -Ib, -Ic), pseudopseudohypoparathyroidism (PPHP), progressive osseous heteroplasia (POH), and osteoma cutis (OC).

**Comment by lschriml** [comment]
skin melanoma - MeSH term obsoleted
        new MeSH term: D000096142.  Cutaneous Malignant Melanoma


DOID:0111799.  syndromic microphthalmia 1
      Mesh term for type 4 was obsoleted

Task complete

**Comment by allenbaron** [comment]
The definition of DOID:0080053 (PHP-Ia) may need to be revised since it does not appear to have a genetic basis currently.

**Comment by lschriml** [comment]
Please review and revise the definition.Sent from my iPhoneOn Dec 18, 2024, at 1:47 PM, J. Allen Baron ***@***.***> wrote:﻿
The definition of DOID:0080053 (PHP-Ia) may need to be revised since it does not appear to have a genetic basis currently.
