### ISSUE TITLE
Consider reclassifying CAMRQ3 (DOID:0070558)

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1397]
**Is your request related to a specific disease? Please describe.**
'cerebellar ataxia, impaired intellectual development, and dysequilibrium syndrome 3'

**Describe the proposed change(s)**
Consider reclassifying this disease as a child of 'autosomal recessive cerebellar ataxia' (DOID:0050950) and possibly renaming it as OMIM has.

**References**
OMIM has renamed this disease "SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 34; SCAR34" ([MIM:613227](https://omim.org/entry/613227)) in light of a new study by Kaiyrzhanov R, et al[^1].

[^1]: Kaiyrzhanov R, Ortigoza-Escobar JD, Stringer BW, Ganieva M, Gowda VK, Srinivasan VM, Macaya A, Laner A, Onbool E, Al-Shammari R, Al-Owain M, Deconinck N, Vilain C, Dontaine P, Self E, Akram R, Hussain G, Baig SM, Iqbal J, Salpietro V, Neshatdoust M, Kasiri M, Yesil G, Uygur T, Pysden K, Berry IR, Alves CA, Giacomotto J, Houlden H, Maroofian R. Clinical and Molecular Spectrum of Autosomal Recessive CA8-Related Cerebellar Ataxia. Mov Disord. 2024 Jun;39(6):983-995. doi: 10.1002/mds.29754. Epub 2024 Apr 6. PMID: [38581205](https://pubmed.ncbi.nlm.nih.gov/38581205/).

**Comment by lschriml** [comment]
nomenclature and reclassification done.
