### ISSUE TITLE
revise congenital nonspherocytic hemolytic anemia

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1399]
**Is your request related to a specific disease? Please describe.**
congenital nonspherocytic hemolytic anemia and descendants  

**Describe the proposed change(s)**
OMIM has revised this set of terms, renaming several. Some of these are in DO others are not. Also both hemolytic anemia and congenital nonspherocytic hemolytic anemia have multiple OMIM xrefs that could use to be split out into child terms.

The full set is on the OMIM update spreadsheet lines 1710-1724 (ignore the couple that are not part of this branch) https://docs.google.com/spreadsheets/d/1SUiFOMGeO3QJfnevpXAPFN90UmAaeoIHF7u0X5lvgc4/edit?usp=sharing 

**References**
Provide links to a database or a PubMed ID

**Comment by allenbaron** [comment]
Thanks Sue. I'll take a look and revise these... possibly by the release scheduled for Oct 30.

**Comment by lschriml** [comment]
I am working on the reclassification here: 
https://docs.google.com/spreadsheets/d/1IxQz0CSXaKcwKKaBt4UW09cS8wMPTouM2Q_mDpKArdA/edit?gid=0#gid=0

**Comment by lschriml** [comment]
Updates complete.
