### ISSUE TITLE
Consider adding 'autoinflammatory disease' as a grouping term & revising diseases accordingly

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#1400]
'autoinflammatory disease' has been suggested as a grouping term in multiple prior issues and has not been addressed directly. There are a number of immune system diseases that might be re-classified under 'autoinflammatory disease'.

This issue has been opened to consolidate previous comments and to address the need for autoinflammatory disease as a term directly.

The most extensive look at this so far has been in https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/1387#issuecomment-2391393420 but it was also briefly considered as part of https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/1226#issuecomment-1656084090. In neither case, was a definitive decision made.

Other issues that identify autoinflammatory diseases but are only weakly relevant to this topic as a whole include:
- https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/435
- https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/1150

**Comment by allenbaron** [comment]
We might also consider adding a parent for diseases that have both autoinflammatory and autoimmune components.

Sue noted in https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/1387#issue-2546457121 about adding 'autoinflammation, antibody deficiency, and immune dysregulation syndrome':
>The Orphanet parent is Mixed autoinflammatory and autoimmune syndrome

**Comment by lschriml** [comment]
Updates made: 
https://www.autoimmuneinstitute.org/articles/autoimmune-vs-autoinflammatory-disease/
          Autoimmune vs Autoinflammatory Disease

-- Autoimmune disease (AD) and autoinflammatory disease (AIF) are two categories of illnesses that occur when the immune system mistakenly damages healthy cells.

For the classification: 
       autoimmune disease and autoinflammatory disease --- are sibling terms

      for: autoinflammatory disease: 
              --> create a new term, as a child of primary immunodeficiency disease
                       revise this branch to be: 

          autoinflammatory disease 
                 [child terms]: all 'auto inflammatory diseases' 
                 familial Mediterranean fever    [DOID:2987]
                 TNF receptor–associated periodic syndrome 
                              -->  this is: DOID:0090018 [autosomal dominant familial periodic fever]
