### ISSUE TITLE
Add Wieacker-Wolff syndrome subtypes

### ISSUE THREAD

**Issue by csbjohnson** [DiseaseOntology/HumanDiseaseOntology#1401]
MIM:PS314580

[Curation notes on Wieacker-Wolff syndrome subtypes.](https://docs.google.com/document/d/1dYHQXUAG1dTmaiwcKOV0t6hVU9vWqhd42FgNRWo_A5o/edit?tab=t.0)

**Comment by lschriml** [comment]
I searched DO, by the synonyms in the OMIM record
MIM:314580. (Wieacker-Wolff syndrome).
    Also good to start by searching DO for the OMIM ID.
    We have this OMIM ID in the DO,  Miles-Carpenter syndrome
        -- I see OMIM has a different name for this disease
     Next: 
        look for both names in PubMed/other resources
     -- Google both names 

--> the most currently used name for this disease is: 
          Wieacker-Wolff syndrome

I noted that Wieacker-Wolff syndrome. is X-linked recessive and that 
female-restricted Wieacker-Wolff syndrome is X-linked dominant
       MIM:301041. -- is not in the DO

-- Noticed the phenotypic series is called the same name as the 
one disease: 
       Wieacker-Wolff syndrome - PS314580
            Wieacker-Wolff syndrome    MIM:314580
            female-restricted Wieacker-Wolff syndrome     MIM:301041)

-- I would keep the two records as sibling terms, would not create the parent class.
I would add the PS # as a comment: disease and PS have same label

--> let's preserve OMIM's representation of these diseases.
