### ISSUE TITLE
both cancer and benign

### ISSUE THREAD

**Issue by alanruttenberg** [DiseaseOntology/HumanDiseaseOntology#141]
The following come up as inconsistent when I make 'benign neoplasm' disjoint from cancer

'Bartholin's gland adenoma'
'Bartholin's gland adenomyoma'
'Bartholin's gland neoplasm'
'basophil adenoma'
'C-P angle neurinoma'
'central nervous system chondroma'
'central nervous system hemangioma'
'central nervous system lipoma'
'childhood kidney angiomyolipoma'
'chromophobe adenoma'
'epidural spinal canal angiolipoma'
'mature gastric teratoma'
'mediastinal melanocytic neurilemmoma'
'mediastinal neurilemmoma'
'minor vestibular glands adenoma'
'neurilemmoma of the fifth cranial nerve'
'ovarian papillary cystadenoma'
'retinal hemangioblastoma'
'schwannoma of twelfth cranial nerve'
'spleen angiosarcoma'
'sympathetic neurilemmoma'
'vagina squamous papilloma'
insulinoma
prolactinoma

**Comment by lschriml** [comment]
Hello Alan,
 can you please explain a bit further what you are asking/identifying ?

Thank you,
Lynn

**Comment by alanruttenberg** [comment]
Step 1:  Benign neoplasm and cancer are disjoint classes.
Assuming we agree,
Step 2: I said so in the ontology by asserting DisjointClasses(benign neoplasm, cancer)
Step 3: Run the reasoner 
Step 4: Observe that a bunch of classes are now marked as being inconsistent (actually unsatisfiable - red)
Step 5: Conclude that something in DO either says directly, or implies, that there is some type of cancer which is not disjoint from some type of benign neoplasm. 

A quality control step I frequently use is to add a logical assertion that matches what be believe to the case. If the reasoner subsequently complains, one concludes some error in the ontology needs to be addressed.

**Comment by lschriml** [comment]
Hello Alan,
 I've reviewed the terms, and am not finding any errors. 
Lynn

**Comment by alanruttenberg** [comment]
Hi Lynn.
Which of the 5 steps in my report do you disagree with? Did you fail to reproduce the reasoner error?
