### ISSUE TITLE
Add subtypes of B-lymphoblastic leukaemia/lymphoma & Acute myeloid leukemia

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#1411]
The Pediatric Cancer Taskforce has been focused on curating evidence related to B-lymphoblastic leukemias with known underlying genetic alterations. We are trying to be as specific as possible with naming of the disease based on the WHO blue books. An odd hiccup in the blue books is a number of diseases with specific alterations are listed under the same ICDO code. 

Would it be possible to add those above as their own terms in the DO or would they needed to be added as synoyms for B-lymphoblastic leukaemia/lymphoma (the preferred ICDO term)

9811/3 B-lymphoblastic leukaemia/lymphoma with other defined genetic alterations
9811/3 B-lymphoblastic leukaemia with DUX4 rearrangement
          DOID:0081412
9811/3 B-lymphoblastic leukaemia with MEF2D rearrangement
9811/3 B-lymphoblastic leukaemia with ZNF384 rearrangement
9811/3 B-lymphoblastic leukaemia with PAX5alt
9811/3 B-lymphoblastic leukaemia with PAX5 p.P80R
        DOID:0081411
9811/3 B-lymphoblastic leukaemia with NUTM1 rearrangement
9811/3 B-lymphoblastic leukaemia with MYC rearrangement

From DO: 
we have added a number of these subtypes, happy to add in the others as additional subtypes.  And their ICDO codes.     

Cheers,
Lynn

**Comment by allenbaron** [comment]
Just noting that the disease term "B-lymphoblastic leukemia/lymphoma" (DOID:0080630) has the xref ICDO:9836/3, which corresponds to [Precursor B-cell lymphoblastic leukemia](https://seer.cancer.gov/seertools/hemelymph/51f6cf58e3e27c3994bd540e/). A number of subtypes have specific codes in the 9812/3-9819/3 range. These are all already in DO.

It makes sense to add the rest of these subtypes and seems like they should all be skos:broadMatch to ICDO:9811/3 ([B-lymphoblastic leukemia/lymphoma, NOS](https://seer.cancer.gov/seertools/hemelymph/51f6cf59e3e27c3994bd5468/?q=9811/3)). Should we also add them as xrefs?

**Comment by allenbaron** [comment]
Do we really want to add "B-lymphoblastic leukaemia/lymphoma with other defined genetic alterations"? That looks like an NOS by another name.

**Comment by lschriml** [comment]
yes as xrefs, yes as broad match

B-lymphoblastic leukaemia/lymphoma with other defined genetic alterations"? That looks like an NOS by another name.
--> agreed, but CIViC needs that term, so lets add it

**Comment by allenbaron** [comment]
Okay. Thanks.

**Comment by jsaliba10** [comment]
A Few others in B-ALL and AML 

B-lymphoblastic leukemia with TCF3::HLF fusion

9861/3 Acute myeloid leukemia with CBFA2T3::GLIS2 fusion
9861/3 Acute myeloid leukemia with KAT6A::CREBBP fusion
9861/3 Acute myeloid leukemia with FUS::ERG fusion
9861/3 Acute myeloid leukemia with MNX1::ETV6 fusion
9861/3 Acute myeloid leukemia with NPM1::MLF1 fusion

**Comment by jsaliba10** [comment]
The way things are listed in the WHO "B-lymphoblastic leukaemia/lymphoma with other defined genetic alterations" is the heading which all of the terms with actual genetic subtypes fall.  I think it would be ok to leave "B-lymphoblastic leukaemia/lymphoma with other defined genetic alterations" out. Those could simply be put in as NOS

**Comment by lschriml** [comment]
Thank you Jason 
      --> leave out: B-lymphoblastic leukaemia/lymphoma with other defined genetic alterations"

**Comment by allenbaron** [comment]
I added all the requested diseases with the following IDs and labels:

## B-ALL
ID | label
-- | --
DOID:0070623 | B-lymphoblastic leukemia with MEF2D rearrangement
DOID:0070624 | B-lymphoblastic leukemia with MYC rearrangement
DOID:0070625 | B-lymphoblastic leukemia with NUTM1 rearrangement
DOID:0070626 | B-lymphoblastic leukemia with PAX5alt
DOID:0070627 | B-lymphoblastic leukemia with TCF3::HLF fusion
DOID:0070628 | B-lymphoblastic leukemia with ZNF384 rearrangement
DOID:0081411 | B-lymphoblastic leukemia with PAX5 p.P80R
DOID:0081412 | B-lymphoblastic leukemia with DUX4 rearrangement

## AML

ID | label
-- | --
DOID:0070629 | acute myeloid leukemia with CBFA2T3-GLIS2 fusion
DOID:0070630 | acute myeloid leukemia with KAT6A-CREBBP fusion
DOID:0070631 | acute myeloid leukemia with FUS-ERG fusion
DOID:0070632 | acute myeloid leukemia with MNX1-ETV6 fusion
DOID:0070633 | acute myeloid leukemia with NPM1-MLF1 fusion

@jsaliba10 One more thing to note. The WHO blue book suggests using ICD-O code 9818/3 for 'B-lymphoblastic leukemia with TCF3::HLF fusion' (DOID:0070627), which is the code that exactly matches 'B-lymphoblastic leukemia/lymphoma with TCF3-PBX1' (DOID:0080649). I added it with 9811/3 but if you think it should be switched to 9818/3 let me know.
