### ISSUE TITLE
NTR: Bryant-Li-Bhoj syndrome

### ISSUE THREAD

**Issue by srengel** [DiseaseOntology/HumanDiseaseOntology#1413]
Include: 

- NTR: Bryant-Li-Bhoj syndrome

Bryant-Li-Bhoj syndrome (BLBS; OMIM # 619720, 619721), caused by germline H3F3A and H3F3B variants encoding histone H3.3, is characterized by mild to severe developmental delay, intellectual disability, failure to thrive, muscle tone abnormalities, and dysmorphic facial features. 

- It is helpful to include a definition and PubMed reference for new terms
PMID: 36867246|PMID: 37782742|PMID: 38678163|PMID: 39525290|PMID: 39627236

- It is useful to share information on the relevant project 
SGD is using DO to annotate yeast genes used to study human diseases

- include contact information along with your ORCID id, so that we can provide attribution for your contribution
Stacia Engel, SGD
0000-0001-5472-917X

**Comment by allenbaron** [comment]
Thanks Stacia. We'll review and get new disease(s) ready for this month's release.

**Comment by lschriml** [comment]
--> add three new DOIDs:
[1] Bryant-Li-Bhoj neurodevelopmental syndrome 
       PS619720
 definition: 
      A syndrome that is characterized by developmental delay / intellectual disability (typically in the severe range) and nonspecific craniofacial abnormalities.
           xref: url:https://www.ncbi.nlm.nih.gov/books/NBK595206/

[2] Bryant-Li-Bhoj neurodevelopmental syndrome 1

definition. 
A Bryant-Li-Bhoj neurodevelopmental syndrome that is characterized predominantly by moderate to severe global developmental delay with impaired intellectual development, poor or absent speech, and delayed motor milestones and that has_material_basis_in heterozygous mutation in the H3F3A gene on chromosome 1q42.
      xref: url:https://www.ncbi.nlm.nih.gov/books/NBK595206/
               url: https://pubmed.ncbi.nlm.nih.gov/38678163/
              

xrefs:
MIM:619720
autosomal dominant inheritance

[3]:
MIM:619721
Bryant-Li-Bhoj neurodevelopmental syndrome 2
A Bryant-Li-Bhoj neurodevelopmental syndrome that is characterized predominantly by moderate to severe global developmental delay with impaired intellectual development, poor or absent speech, and delayed motor milestones nd that has_material_basis_in heterozygous mutation in the H3F3B gene on chromosome 17q25.

**Comment by lschriml** [comment]
The new terms have been added and will be in the DO's December release.
Cheers,
Lynn
