### ISSUE TITLE
not necessarily pre-malignant

### ISSUE THREAD

**Issue by alanruttenberg** [DiseaseOntology/HumanDiseaseOntology#142]
'conjunctival intraepithelial neoplasm'

Reference
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1772848/

**Comment by alanruttenberg** [comment]
Also corneal intraepithelial neoplasm.
From http://www.aao.org/focalpointssnippetdetail.aspx?id=588b7319-056a-4fc6-b5ff-9550083b9965

Conjunctival and Corneal Intraepithelial Neoplasia/Squamous Cell Carcinoma
A spectrum of lesions can arise from the squamous epithelium of the conjunctiva and cornea, varying along a continuum from benign to malignant.

**Comment by lschriml** [comment]
Hello Alan,
   Looking into these terms: 
I agree, there is the pre-malignancy form and the malignant. I have added definitions to DO to clarify this etiology. 
Details: 
**conjunctival intraepithelial neoplasia** (CIN)
   The most common tumor of the ocular surface,
   CIN is a precursor of **squamous cell carcinoma**, the most common conjunctival malignant      neoplasm 
   If CIN invades the epithelial basement membrane, the lesion is termed invasive squamous cell carcinoma of the conjunctiva.

**conjunctival squamous cell carcinoma** (CSCC) (synonym: ocular surface squamous neoplasia (OSSN))  is considered “in situ” if it is restricted within the epithelium, and “invasive” if it is infiltrating beyond the confines of the epithelial basement membrane

References: 
(1) 
http://ac.els-cdn.com/S0161642001009915/1-s2.0-S0161642001009915-main.pdf?_tid=23eed9a8-bd7a-11e6-b5c2-00000aab0f6b&acdnat=1481224476_6b22e4d7937f9961b55bc29a906a0554
(2) http://www.sciencedirect.com/science/article/pii/S0161642009010963
(3) https://www.ncbi.nlm.nih.gov/pubmed/27584160

Cheers,
Lynn
