### ISSUE TITLE
New Term Request: Barber-Say syndrome

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#143]
Hi,
I wanted to request this new term for the ontology: Barber-Say syndrome
(MIM:209885),  MeSH (C537908) and Orphanet (ORPHA1231). Thanks

Sridhar

**Comment by elviram** [comment]
Hello, 
thank you for the term request. It will be reviewed and it should be in the DO release of next week.

Best,
Elvira
