### ISSUE TITLE
New Term Request:Ablepharon-Macrostomia syndrome

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#144]
Hi,
I wanted to request this new term for the ontology: Ablepharon-Macrostomia syndrome
(MIM:200110), MeSH (C535557 ) and Orphanet (ORPHA920). Thanks

Sridhar

**Comment by elviram** [comment]
Hello, 
thank you for the term request. It will be reviewed and it should be in the DO release of next week.

Best,
Elvira
