### ISSUE TITLE
DOID:3458 is_a DOID:299?

### ISSUE THREAD

**Issue by mbernste** [DiseaseOntology/HumanDiseaseOntology#145]
Perhaps I am mistaken, but shouldn't there be an "is_a" edge between "breast adenocarcinoma" (DOID:3458) and "adenocarcinoma" (DOID:299)?

**Comment by elviram** [comment]
Hello,
if you look at the inferred tree view of the ontology you will see that there is a link between 'breast adenocarcinoma' and 'adenocarcinoma'.

Best,
Elvira

**Comment by mbernste** [comment]
Thanks, I had been looking at the release at the OBO Foundry.
