### ISSUE TITLE
New Term Request:poikiloderma with neutropenia

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#146]
Hi,
I wanted to request this new term for the ontology: poikiloderma with neutropenia
(MIM:604173)  and Orphanet (ORPHA221046). Thanks

Sridhar

**Comment by elviram** [comment]
Hello, 
thank you for the term request. It will be reviewed and it should be in the DO release of next week.

Best,
Elvira
