### ISSUE TITLE
Synonym or term for "tumor" and/or "neoplasm"?

### ISSUE THREAD

**Issue by mbernste** [DiseaseOntology/HumanDiseaseOntology#147]
Is there a reason why "tumor" or "neoplasm" does not exist as a stand-alone term or synonym in the ontology? This term can be found here: MSH:D009369 and here: EFO:0000616.  It seems that such a term might be a synonym of "disease of cellular proliferation" (DOID:14566) or be a separate term that is a child of DOID:14566.

**Comment by lschriml** [comment]
Hello Matt, 
  Thank you for bringing up these points. 
I have added neoplasm as a synonym as you suggest. 
I am not adding tumor as a synonym as not all 'disease of cellular proliferation' form a mass. 

Cheers,
Lynn
