### ISSUE TITLE
New term request: lethal congenital contracture syndrome

### ISSUE THREAD

**Issue by sabrinatoro** [DiseaseOntology/HumanDiseaseOntology#148]
Hello, 
I would like to request 2 new terms: 
1) lethal congenital contracture syndrome 1 
synonym: LCCS1
reference: OMIM: 253310

2) lethal congenital contracture syndrome 2 
synonym: LCCS2
reference: OMIM: 607598 

Thank you
Sabrina

**Comment by elviram** [comment]
Hello Sabrina,
the requests will be reviewed and should be in the new release of the ontology on Friday.

Thank you,
Elvira

**Comment by sabrinatoro** [comment]
Thank you Elvira!

**Comment by sabrinatoro** [comment]
@elviram 
I cannot find the terms above in the ontology. They should have been in one of the releases last month. 
Can you help, please? 
Thank you! 
Sabrina

**Comment by elviram** [comment]
@sabrinatoro I looked through my logs. Protege crashed that day and looks like the changes were not saved. I will add them today and they will be in Friday's release. I apologize for the confusion. If you need them sooner I will do a release today.

**Comment by sabrinatoro** [comment]
@elviram 
no worries, I can wait until Friday. 
I am glad the problem was easily found! 
Thanks!

**Comment by elviram** [comment]
@sabrinatoro triple checked. LCCS1 -> DOID:0060559 and LCCS2 -> DOID:0060560

**Comment by sabrinatoro** [comment]
@elviram I was able to use the terms. I confirm that they are in the ontology! Thank you very much!
