### ISSUE TITLE
Revise synonym for DOID_4464 collecting duct carcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [DiseaseOntology/HumanDiseaseOntology#149]
I think the synonym for 'collecting duct carcinoma' is incorrect. I believe 'renal medullary carcinoma' is not an exact synonym. The collecting duct system of the kidney consists of tubules and ducts (https://en.wikipedia.org/wiki/Collecting_duct_system). There is the renal medulla collecting duct, but I am uncertain if the 'renal medullary' is the same.

Could you consider removing the 'renal Medullary carcinoma' synonym or weakening it from 'exact'

id: DOID:4464
name: collecting duct carcinoma
synonym: "renal Medullary carcinoma" EXACT [NCI2004_11_17:C7572]

cc @cmungall

**Comment by elviram** [comment]
Hi Nicole, we will look into it.
Thank you,
Elvira

**Comment by elviram** [comment]
Hi Nicole, 
the synonym has been removed and has been added as a subclass of 'collecting duct carcinoma'.

**Comment by nicolevasilevsky** [comment]
Thanks Elvira!
