### ISSUE TITLE
Revise synonyms for DOID:4468 clear cell adenocarcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [DiseaseOntology/HumanDiseaseOntology#150]
I believe these synonyms are incorrect for DOID:4468 clear cell adenocarcinoma, could you review and consider removing them?

synonym: "Mesonephroid Clear cell carcinoma" EXACT [NCI2004_11_17:C3766]
synonym: "Mesonephroma NOS (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189861007]
synonym: "Mesonephroma, malignant (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:2221008]
synonym: "malignant Mesonephroma" EXACT [NCI2004_11_17:C4072]
synonym: "mesonephroma" EXACT []

See info about of clear cell carcinoma: https://en.wikipedia.org/wiki/Clear-cell_adenocarcinoma 

cc @cmungall

**Comment by elviram** [comment]
Hi Nicole,
according to NCI 'mesonephroma' is a synonym for 'clear cell (adeno)carcinoma', see: http://www.cancer.gov/publications/dictionaries/cancer-terms?cdrid=335092 
It is pretty much an obsoleted term by now. We will look further into it.
