### ISSUE TITLE
Update release pipeline

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#153]
In the [OBO registry entry](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/doid.md) you have your build tag pointing to doid-non-classified.obo

Is this intentional? Generally the protocol is to always release the pre-reasoned version. For DO, it may not matter right now, as it looks like you aren't doing any reasoning, but it may in future. Also, I don't know if you even intend to release equivalence axioms or inter-ontology axioms, but this strategy will prevent you from ever doing this.

Note that the build tag should not be necessary for ontologies like DO that are capable of managing their own release. See http://obofoundry.org/faq/what-is-the-build-field.html

Note in particular that you are relying on an OBO central/Berkeley build of doid.owl from the non-classified obo file in order to generate your main http://purl.obolibrary.org/obo/doid.owl

I recommend that you manage your releases directly from github, and have http://purl.obolibrary.org/obo/doid.owl and http://purl.obolibrary.org/obo/doid.obo point directly at GitHub. To do this, you will want at publish at least two files directly in github:
- doid.owl
- doid.obo

It's important the file names are the same.

I believe it was set up this way when this GitHub repo was created, but things seemed to have morphed in an odd direction.

You might also want to look at replacing Oort with ROBOT

**Comment by elviram** [comment]
The registry entry is because the DO was build in OBO, way back, and most users have been using the HumanDO.obo file (from the svn repo) that is equivalent to doid-non-classified.obo.

The main doid.owl is generated from the doid-edit.owl using ROBOT

doid.owl and doid.obo are both available here in github.

Am I not getting something?

**Comment by cmungall** [comment]
In general, I suggest recommend reducing the number of files you have, and standardizing on the content.

I understand the needs of users who want the obo file in general. Are there documented specific requirements for your users? Is there not a single obo file that can serve the needs of all obo file consumers?

I'm trying to reverse engineer your requirements by looking at the files you produce. I can see two broad differences between doid-nonclassified (which is your release file) and doid.obo (which as far as I can tell is not consumed anywhere further downstream).

 1. doid.obo includes extra is_a relationships, missing from the release doid-non-classified.obo
 2. doid.obo uses MSH instead of MESH

I do not understand why you wouldn't want to release the inferred is_a relationships, if they are biologically correct (some are not correct, but the problem here is in your equivalence axioms, and the fix is easy). Is it the case that some of your users of HumanDO have an assumption of single inheritance?

As for the second, you are just inviting confusion by having two different ways to write the same ID. I strongly recommend standardizing on MESH.

If you follow this advice, you can eliminate the weirdly named doid-non-classified, and point the OBO registry at doid.obo. That will go a long way to simplifying in the short term.

After that we can discussion how to release your doid.owl (note that your doid.owl isn't the one at the end of the PURL, for the reasons I mention above).

The first difference is in the classification

doid-non-classified.obo (release):

```
[Term]
id: DOID:0050612
name: gall bladder carcinoma in situ
is_a: DOID:8719 ! in situ carcinoma
```

doid.obo:

```
[Term]
id: DOID:0050612
name: gall bladder carcinoma in situ
is_a: DOID:0060262 ! gallbladder disease
is_a: DOID:9053 ! bladder carcinoma in situ
```

Note the former is the one that percolates through the berkeley release pipeline into OWL and into all browsers, e.g.

**Comment by cmungall** [comment]
Also, I didn't notice you had switched part of the pipeline to using ROBOT as it's not in the Makefile, or in the README-editors.md file.

If you aren't using the Makefile, then you can delete it.

I do strongly recommend having some kind of automated way to run your pipeline and having the script checked in to github. Ideally something like a shell script or makefile that can be executed by anyone, run on travis, etc. Failing that at least a script a human can follow.

**Comment by cmungall** [comment]
Here is an example of a difference between the two

```
 [Term]
 id: DOID:9733
 name: renal tuberculosis
 def: "An urogenital tuberculosis that results_in formation of granulomas located_in kidney." [url:http\://emedicine.medscape.com/article/450651-overview]
 subset: gram-positive_bacterial_infectious_disease
 synonym: "Tuberculosis of kidney" EXACT [ICD9CM_2006:016.0]
 xref: ICD9CM:016.0
 xref: ICD9CM:016.00
-xref: MESH:D014398
+xref: MSH:D014398
 xref: SNOMEDCT_US_2015_03_01:186236001
 xref: SNOMEDCT_US_2015_03_01:44323002
 xref: UMLS_CUI:C0041328
 is_a: DOID:2149 ! urogenital tuberculosis
-is_a: DOID:557 ! kidney disease
```

The `-` shows things that get lost in the doid-non-classified (released version)

**Comment by elviram** [comment]
I agree that things get lost in the non-classified version, but it is a file that has to remain.
I will look into cleaning things up.

**Comment by cmungall** [comment]
On 14 Jun 2016, at 13:18, Elvira wrote:

> I agree that things get lost in the non-classified version, but it is 
> a file that has to remain.

Do you mean the file itself has to remain (ie someone has hardcoded a 
non-PURL path)

Or do you mean there is some property or properties of the current file 
that need preserved? If so, can we document what these are?

You can refer to the OBO-Basic subset of OBO format, which was designed 
for these purposes:
http://owlcollab.github.io/oboformat/doc/obo-syntax.html#6.1

**Comment by elviram** [comment]
As far as I know, the file itself, but thanks for the link.

**Comment by cmungall** [comment]
> As far as I know, the file itself, but thanks for the link.

Sorry to harp on about this one, but if you have a handful of users (and 
it must only be a handful) who have a hardcoded dependency on having a 
file called doid-non-classified.obo, then I suggest deprecating the file 
after giving sufficient notice. The dependency should never have been 
introduced in the first place.

I don't see a link to doid-non-classified.obo here:
http://disease-ontology.org/downloads/

However, you do provide a link to a file HumanDO.obo. However, this file 
has not been updated in 6 months. The last update was a cp from 
doid-non-classified.obo

It looks like you have a manual step to do this:
https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/README-editors.md#checklist

I see you're also providing links to SVN from the main DO page. This is 
not a good idea. What if SF ends up freezing these? You will have a 
large user base who will be pulling stale files.

I think you are making things complicated for yourselves and your users. 
If you stick to the standard way of doing things it all becomes much 
easier.

  - point your users to PURLs. The point of the OBO PURLs is that you 
have control over where they point, and you can change the underlying 
system without affecting your users
  - make the doid.obo purl point to a file that is geared towards your 
obo users, with documented conventions
  - make the doid.owl purl point to a complete version of the ontology, 
with arbitrary axiomatization, imports etc. This is what all modern 
browsers like OLS and OntoBee consume, and all non-legacy computational 
frameworks.
  - include PURLs for subsets if you need them
  - make all release files pre-reasoned
  - deprecate all SVN URLs, give a few months for people to change
  - deprecate any non-standard path, give a few months for people to 
change

**Comment by elviram** [comment]
I will have to get back to you on this on a later date, after more discussion.

Thank you.

**Comment by cmungall** [comment]
@elviram I see you merged https://github.com/OBOFoundry/purl.obolibrary.org/pull/269

This resolves many of the issues here. The useless file doid-non-classified is never seen, except by people poking around this repo (you may as well `git rm` it).

Note however, we never resolved the MSH vs MESH issue. Note that your public releases now uses the highly non-standard MSH. Can you fix this?

**Comment by elviram** [comment]
That can be fixed, but I have to ask for a revert for the doid-non-classified. Explanation on [https://github.com/OBOFoundry/purl.obolibrary.org/pull/269](url)

**Comment by sbello** [comment]
If you do change the MESH prefix please give us (MGI) a heads up before you
do as we will need to change things on our end to make sure the MESH IDs
are still loaded.
Thanks,
Sue

**Comment by elviram** [comment]
No changes for the MESH prefix planned. It won't revert back to MSH.

Cheers,
Elvira
