### ISSUE TITLE
Clarifying whether this is the official Disease Ontology repo

### ISSUE THREAD

**Issue by dhimmel** [DiseaseOntology/HumanDiseaseOntology#158]
I've previously filed issues in both:

+ [`IGS/disease-ontology`](https://github.com/IGS/disease-ontology)
+ [`obophenotype/human-disease-ontology`](https://github.com/obophenotype/human-disease-ontology)

Now it looks like this repository ([`DiseaseOntology/HumanDiseaseOntology`](https://github.com/DiseaseOntology/HumanDiseaseOntology)) is the official repo where ontology requests should be filed? Anyways I suggest clearly specifying which repo is official. The deprecated repos should state their deprecation and link to the active one. Note that the two outdated repos appear first on Google for me.

**Comment by elviram** [comment]
Hi Daniel,
yes, this is the official repo. The IGS one was a stop-gap measure when SVN went down for quite a few days. And the obophenotype one was the repo when DO was developed in OBO format.
We will get that sorted out.

Thank you.

**Comment by dhimmel** [comment]
Great thanks -- I realize I've been confused for a while as evidenced by IGS/disease-ontology#1. I unstarred the `IGS` and `obophenotype` and starred this repo to do my part.
