### ISSUE TITLE
Renaming epilepsy syndrome to epilepsy

### ISSUE THREAD

**Issue by dhimmel** [DiseaseOntology/HumanDiseaseOntology#159]
Project Rephetio uses the Disease Ontology to identify our diseases. Chrissy Hessler, one of the physicians involved in the project, [commented that](https://thinklab.com/discussion/predictions-of-whether-a-compound-treats-a-disease/203#5):

> A small point- i think we should use the term "epilepsy" rather than "epilepsy syndrome"- the word syndrome implies that the epilepsy is part of a constellation of associated features. Perhaps Ari and Pouya can weigh in.

Hence, I thought I should relay her concern upstream. Does it make sense to rename epilepsy syndrome ([`DOID:1826`](http://www.disease-ontology.org/?id=DOID:1826)) to epilepsy?

**Comment by elviram** [comment]
Hi Daniel,
'epilepsy' is an exact synonym for 'epilepsy syndrome'. It will be changed from synonym to label on our next commit.
