### ISSUE TITLE
Improving the the depression hierarchy

### ISSUE THREAD

**Issue by dhimmel** [DiseaseOntology/HumanDiseaseOntology#160]
Currently depression is expressed with the following hierarchy:
- mental depression (`DOID:1596`) >
  - endogenous depression (`DOID:1595`) >
    - major depressive disorder (`DOID:1470`)

However, wikipedia [defines](https://en.wikipedia.org/wiki/Endogenous_depression) endogenous depression as:

> an atypical sub-class of the mood disorder, [major depressive disorder](https://en.wikipedia.org/wiki/Major_depressive_disorder) (clinical depression). Endogenous depression includes patients with treatment-resistant, non-psychotic, major depressive disorder, characterized by abnormal behavior of the endogenous opioid system but not the monoaminergic system.

This appears contradictory. Perhaps the depression section of the ontology should be reviewed by an expert.

---

Note this issue was migrated from IGS/disease-ontology#2

**Comment by elviram** [comment]
Hi Daniel, this will require more time, as for now it seems that this term (endogenous depression) is no longer recommended for use. It is a terms that goes way back to the debate of if unitary or a binary model is better suited for the disease representation.
For now the terms will be rearranged.

**Comment by melodyswen** [comment]
Issue reviewed and closed!
