### ISSUE TITLE
Reclassify DOID_1686 Glaucoma?

### ISSUE THREAD

**Issue by nicolevasilevsky** [DiseaseOntology/HumanDiseaseOntology#164]
We have a question about the classification of DOID_1686 Glaucoma:

```
   is_a DOID:5679 ! retinal disease [DEF: "An eye disease that is located_in the retina."]
    is_a DOID:8466 ! retinal degeneration
     is_a DOID:1686 ! glaucoma
      is_a DOID:9283 ! borderline glaucoma
       is_a DOID:9282 ! ocular hypertension *** 
```

'borderline glaucoma' seems to be a temporal phase of glaucoma (early stage)? Ocular hypertension can give rise to this condition and is a risk factor, but I don't think it is a subclass of glaucoma. 

In MESH, glaucoma is a subclass of ocular hypertension.

cc @cmungall

**Comment by elviram** [comment]
In [ICD10](http://www.icd10data.com/ICD10CM/Codes/H00-H59/H40-H42/H40-) ocular hypertension is a "subclass" of glaucoma.
According to AAO (American Academy of Ophthalmology) patients with ocular hypertension are at risk to develop glaucoma, but not necessarily ([PMID:1867550](https://www.ncbi.nlm.nih.gov/pubmed/1867550)).  There is also the fact that 'Normal-Tension Glaucoma' exists. Hence this classification.
Glaucoma will stay where it is, and 'ocular hypertension' will be reviewed.

**Comment by lschriml** [comment]
Hello Nicole, 
looking at this again, I am moving ocular hypertension to is_a eye disease. 
It is not a type of glaucoma.
Glaucoma is also being moved to is_a eye disease. 
Definitions have been added. 
Thank you for pointing these issues out to us !! 
Cheers,
Lynn
