### ISSUE TITLE
Add DOID from WHO 2016 revision of myeloid neoplasms + acute leukemia

### ISSUE THREAD

**Issue by ahwagner** [DiseaseOntology/HumanDiseaseOntology#165]
[Arber, et al.](http://www.bloodjournal.org/content/127/20/2391) describe the addition of a new diagnostic category of hematological cancers: 

> **Myeloid/lymphoid neoplasms associated with eosinophilia and rearrangement of _PDGFRA_, _PDGFRB_, or _FGFR1_ or with _PCM1-JAK2_** The criteria for the diagnosis of the eosinophilia-related proliferations associated with specific molecular genetic changes are retained in the classification, although it is noted that eosinophilia may be absent in a subset cases. In the 2016 revision (Table 10), this disease group will incorporate the myeloid neoplasm with t(8;9)(p22;p24.1);PCM1-JAK2 as a new provisional entity. This rare entity is characterized by a combination of eosinophilia with BM findings of left-shifted erythroid predominance, lymphoid aggregates, and often myelofibrosis, at times mimicking PMF. It can also rarely present as T- or B-lymphoblastic leukemia (acute lymphoblastic leukemia [ALL]) and responds to JAK inhibition. Other JAK2-rearranged neoplasms, for example, t(9;12)(p24.1;p13.2);ETV6-JAK2 and t(9;22)(p24.1;q11.2);BCR-JAK2 may have similar features, but are uncommon and are not currently included as distinct entities. Moreover, ETV6-JAK2 and BCR-JAK2–rearranged neoplasms present primarily as B-cell ALL (B-ALL), and these are best considered as BCR-ABL1–like B-ALL, a new provisional category of B-lymphoblastic leukemia/lymphoma.

This has also led to the diagnostic exclusion of other related diseases (such as CMML) when these mutations are present. I propose that a new DOID is made to capture this specific type of cancer, and placed under DOID 2531: Hematologic Cancer in the ontology.

**Comment by elviram** [comment]
Hello, to make sure I understand correctly. You are proposing the creation of the term: Myeloid/lymphoid neoplasms associated with eosinophilia ?
Thank you for the link to the article, we will review the WHO classification.

**Comment by ahwagner** [comment]
It's unfortunate that they did not provide a more concise name for this category. Their full title for the group was **Myeloid/lymphoid neoplasms associated with eosinophilia and rearrangement of PDGFRA, PDGFRB, or FGFR1 or with PCM1-JAK2**. However, a parent term with your suggested name--**Myeloid/lymphoid neoplasms associated with eosinophilia**--would probably suffice, perhaps with four new subterms as outlined in Table 1 of the paper:
- **Myeloid/lymphoid neoplasms with _PDGFRA_ rearrangement**
- **Myeloid/lymphoid neoplasms with _PDGFRB_ rearrangement**
- **Myeloid/lymphoid neoplasms with _FGFR1_ rearrangement**
- **Myeloid/lymphoid neoplasms with _PCM1-JAK2_**

**Comment by elviram** [comment]
Yes, the naming seems a bit lacking, but we will work with it.
Thank you, again.

**Comment by ahwagner** [comment]
It looks like there are NCI codes for this: [NCI Code C84270](https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&version=16.07d&code=C84270&ns=NCI_Thesaurus&type=properties&key=1708502852&b=1&n=0&vse=null) describes **Myeloid and Lymphoid Neoplasms with Eosinophilia and Abnormalities of PDGFRA, PDGFRB, or FGFR1**, with three child concepts:

- Myeloid and Lymphoid Neoplasms with FGFR1 Rearrangement [(C84277)](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.07d&ns=NCI_Thesaurus&code=C84277)
- Myeloid and Lymphoid Neoplasms with PDGFRA Rearrangement [(Code C84275)](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.07d&ns=NCI_Thesaurus&code=C84275)
- Myeloid Neoplasms with PDGFRB Rearrangement [(Code C84276)](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.07d&ns=NCI_Thesaurus&code=C84276)

I hope that this helps. Thanks.

**Comment by elviram** [comment]
That definitely helps.
Thank you, Alex.

**Comment by lschriml** [comment]
I have added these terms. 
Lynn

**Comment by ahwagner** [comment]
Great, thanks @lschriml. What are the new DOIDs for these terms?
