### ISSUE TITLE
Inappropriate capitalization

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#166]
See https://github.com/cmungall/capital-offence/issues/1

There are various cases where DO capitalizes non-proper nouns in a query. I have run this report for all DO labels (not when I do this with synonyms I get very many hits, as there is excess capitalization in synonyms, resulting from derivation from other sources. We can handle this separately).

## Disease

 * [DOID:0050398](http://purl.obolibrary.org/obo/DOID_0050398) ! Carrion's  __Disease__ 
 * [DOID:14415](http://purl.obolibrary.org/obo/DOID_14415) ! Legg-Calve-Perthes  __Disease__ 

## Syndrome

 * [DOID:0050470](http://purl.obolibrary.org/obo/DOID_0050470) ! Donohue  __Syndrome__ 
 * [DOID:0050782](http://purl.obolibrary.org/obo/DOID_0050782) ! Zollinger-Ellison  __Syndrome__ 
 * [DOID:0060171](http://purl.obolibrary.org/obo/DOID_0060171) ! Dravet  __Syndrome__ 
 * [DOID:11599](http://purl.obolibrary.org/obo/DOID_11599) ! Frey  __Syndrome__ 
 * [DOID:14796](http://purl.obolibrary.org/obo/DOID_14796) ! Dubowitz  __Syndrome__ 

## Related/Lesion

double offence here:

 * [DOID:7962](http://purl.obolibrary.org/obo/DOID_7962) ! tamoxifen- __Related__  endometrial __Lesion__

## Sclerosing Liposarcoma

 * [DOID:5704](http://purl.obolibrary.org/obo/DOID_5704) !  __Sclerosing__  liposarcoma

 * [DOID:5705](http://purl.obolibrary.org/obo/DOID_5705) ! spindle cell  __Liposarcoma__ 

## In

 * [DOID:6938](http://purl.obolibrary.org/obo/DOID_6938) ! pediatric  __In__ traocular retinoblastoma
 * [DOID:7512](http://purl.obolibrary.org/obo/DOID_7512) ! localized  __In__ traductal papillomatosis

## Species common names

 * [DOID:526](http://purl.obolibrary.org/obo/DOID_526) !  __Human__  immunodeficiency virus infectious disease

even though HIV is capitalized, the label here should have no leading capital. See https://en.wikipedia.org/wiki/HIV

# Debatable ones

 * [DOID:11888](http://purl.obolibrary.org/obo/DOID_11888) !  __Schwannoma__  of ureter

WP uses lowercase form (when not title): https://en.wikipedia.org/wiki/Schwannoma

But HP always uppercases...

# Inappropriate lowercase

This is the converse. Proper names here should be capitalized

 * [DOID:0050791](http://purl.obolibrary.org/obo/DOID_0050791) ! persistent  __mullerian__  duct syndrome
 * [DOID:133](http://purl.obolibrary.org/obo/DOID_133) ! vaginal  __mullerian__  papilloma
 * [DOID:9442](http://purl.obolibrary.org/obo/DOID_9442) ! cervical  __mullerian__  papilloma

also consider Müllerian, but as a synonym, but ensure UTF-16 (keep primary labels ASCII however)

 * [DOID:0050444](http://purl.obolibrary.org/obo/DOID_0050444) ! infantile  __refsum__  disease

Some other tokens in labels that should be capitalized:

 * achilles
 * cowper
 * ehrlich
 * fordyce
 * gasserian
 * hurthle
 * langerhans
 * leber
 * littre
 * meibomian
 * skene
 * vater
 * von

If we also look at synonyms we see many cases where words should be capitalized: african, aspergillus, ...

**Comment by elviram** [comment]
Nice report. The synonyms should be handled separately. 
Will handle those mentioned here.
