### ISSUE TITLE
ovarian carcinoma classification (and broader DO strategy for cancer)

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#167]
This part of DO struck as as odd:

```
        is_a DOID:2394 ! ovarian cancer // xref: NCIT:C4984, NCIT:C7431
         is_a DOID:2152 ! ovary epithelial cancer* // xref: NCIT:C4381
          is_a DOID:2151 ! malignant ovarian surface epithelial-stromal neoplasm // xref: NCIT:C40026
           is_a DOID:4001 ! ovarian carcinoma* // xref: NCIT:C4908
```

At first based on names, we expected the two marked `*` terms to be equivalent - as a carcinoma is defined as cancer derived from epithelial cell.

If these two are equivalent, then the intermediate term would be equivalent too.

The defs don't help much:

```
       is_a DOID:2394 ! ovarian cancer [DEF: "A female reproductive organ cancer that is located_in the ovary."]
        is_a DOID:2152 ! ovary epithelial cancer [DEF: "An ovarian cancer that is derived_from ovarian surface epithelium."]
         is_a DOID:2151 ! malignant ovarian surface epithelial-stromal neoplasm
          is_a DOID:4001 ! ovarian carcinoma 
```

At least this is consistent with NCIT. Althogh it seems that the DO was built from an earlier version of NCIT, and the labels have changed:

```
     is_a C4984 ! Ovarian Neoplasm
        is_a C4381 ! Ovarian Epithelial Tumor
         is_a C40026 ! Malignant Ovarian Epithelial Tumor <--- used to be "malignant ovarian surface epithelial-stromal neoplasm"
          is_a C4908 ! Ovarian Carcinoma ***
```

It would be useful to see the DO's plans regarding cancer. Is the strategy is defer to NCIT? If so, then a pipeline should be established to sync content (or even better: MIREOT). At the moment it seems the cancer part of DO is a stale copy of NCIT?

Or is the strategy to use OBO principles, apply logical defs to terms and infer the hierarchy?

Or some mixture?

**Comment by lschriml** [comment]
We are in the process of revising DO's cancer hierarchy and definition of subtypes. This is an ongoing effort with NCIt, CIViC and others. This work will continue through early 2017.
