### ISSUE TITLE
Disagreement with spinal muscular atrophy tree (DOID:12377 and children)

### ISSUE THREAD

**Issue by SianGramates** [DiseaseOntology/HumanDiseaseOntology#168]
I think the children of spinal muscular atrophy need a bit of rearrangement. OMIM lists 4 spinal muscular atrophies, all caused by the gene SMN1, that differ by severity and age of onset; all of these are also represented in DO (each DO currently linked to exactly one OMIM by XREF):
OMIM:253300 spinal muscular atrophy 1 = DOID:13137 Werdnig-Hoffman disease
OMIM:253550 spinal muscular atrophy 2 = DOID:0050530 intermediate spinal muscular atrophy
OMIM:253400 spinal muscular atrophy 3 = DOID:12376 juvenile spinal muscular atrophy
OMIM:271150 spinal muscular atrophy 4 = DOID:005029 adult spinal muscular atrophy

The OMIM diseases were classified prior to the identification of the common genetic basis, then later assigned to the same gene.

One of the children of DOID:12377 is DOID:0060160 survival motor neuron spinal muscular atrophy, which is defined as "A spinal muscular atrophy that is associated with the survival of motor neuron protein" (i.e., SMN1).  DOID:13137 and DOID:12376 are children of this term, while DOID:005029 and 
DOID:0050530 are siblings.  I think it would make more sense for DOID:005029 and DOID:0050530 to be children of DOID:0060160, and grandchildren of DOID:12377.

The other children of DOID:12377, DOID:0060161 (Kennedy's disease, caused by a different gene) and DOID:4873 (anterior horn cell disease) should stay where they are.

**Comment by elviram** [comment]
Hello Sian,

we will review that branch and it should be updated sometime next week.

Best,
Elvira

**Comment by SianGramates** [comment]
Thanks Elvira.

Sian
