### ISSUE TITLE
Add adult B-lymphoblastic leukemia term

### ISSUE THREAD

**Issue by kkrysiak** [DiseaseOntology/HumanDiseaseOntology#169]
Currently no B-cell child term exists for DOID:5604 adult acute lymphocytic leukemia.

I would like to propose adult B-lymphoblastic leukemia (NCI Code C9143) which is a child of NCI Code C4967.

**Comment by elviram** [comment]
Hello Kilannin,

the term will be included in the next release.

Thank you,
Elvira

**Comment by kkrysiak** [comment]
Wonderful. Thanks!
