### ISSUE TITLE
Question about obsoleted term: delayed puberty (DOID:5575)

### ISSUE THREAD

**Issue by sabrinatoro** [DiseaseOntology/HumanDiseaseOntology#170]
The term "delayed puberty (DOID:5575)" has been obsoleted. 
Is there another term that replaces it?
 
In general, is there a place where we could see why a term has been obsoleted? 
Thank you! 

Sabrina

**Comment by elviram** [comment]
Hello Sabrina,

that was an old term, and back then there was no policy in place on how to deal with obsoleted terms. So the short answer is, no such a place does not exist.
Most of the terms deleted from that period were considered outside DO's scope.

Nowadays we try not to obsolete terms, but merge them (where necessary). Would such a list be useful to you?

Cheers,
Elvira

**Comment by sabrinatoro** [comment]
Hello Elvira. 
Thank you for your answer. 
We use DO in ZFIN to associate disease to a publication or to a zebrafish model. Sometimes, the disease reported in publications corresponds to an obsolete term in DO. In this case, it is not always obvious which term should be used. 
So yes, a list of merged terms would be very useful, thanks. Note that if the merged terms are shown as synonyms, we should be able to find them easily. So I guess the list would be most useful for the terms which are not shown as synonyms. 
Thank you! 
Sabrina

**Comment by elviram** [comment]
Thank you Sabrina.
We will start a list like that if a term is obsoleted or merged.

Best,
Elvira
