### ISSUE TITLE
Definition of Rett syndrome is inconsistent with OMIM assignment

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#174]
Def is:

A pervasive developmental disease that is a neurological and developmental disorder that mostly occurs in females and __is caused_by a mutation on the MECP2 gene on the X chromosome__. Infants with Rett syndrome seem to grow and develop normally at first, but then stop developing and even lose skills and abilities http://www.nichd.nih.gov/health/topics/rett_syndrome.cfm

The xrefs say:

```
comment: OMIM mapping confirmed by DO. [SN].
xref: OMIM:312750
xref: OMIM:613454 <-- congenital variant, caused by FOXG1
```

So unless we interpret xref very weakly as something like 'has similar phenotypes to' either the xref or definition is wrong.

For a detailed discussion of this syndrome and how DO compares to Orphanet and DC, see https://github.com/monarch-initiative/monarch-disease-ontology/issues/141

**Comment by cmungall** [comment]
Two others to consider (have not looked in details):

DOID:0060247 ! Smith-McCort dysplasia   An osteochondrodysplasia characterized by short limbs and a short trunk with a barrel-shaped chest and caused_by homozygous or compound heterozygous mutation in the DYM gene on chromosome 18q.  OMIM:607326     OMIM:615222     NCBIGene:54808  NCBIGene:83452

DOID:0060294 ! cold-induced sweating syndrome   An autosomal dominant disease characterized by problems with regulating body temperature and other abnormalities affecting many parts of the body; caused_by mutations in the CRLF1 gene. OMIM:272430     OMIM:610313     NCBIGene:9244   NCBIGene:23529

**Comment by lschriml** [comment]
Definitions for these three diseases have been updated.
