### ISSUE TITLE
Merge: DOID:1442 ! Alpers syndrome + DOID:0080122 ! mitochondrial DNA depletion syndrome 4a

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#177]
![alp](https://cloud.githubusercontent.com/assets/50745/17972779/cc14a92a-6a94-11e6-9ac9-65d92ea3077f.png)

I believe these two are the same. They both xref [OMIM:203700 mitochondrial DNA depletion syndrome 4a](http://omim.org/entry/203700). Various authoritative references seem to treat this as a synonym

You may also want to consider adding a grouping class as per the grouping file @sbello creates:
DC:0000284 ! Mitochondrial DNA Depletion Syndrome

**Comment by lschriml** [comment]
Hello Chris, thank you for pointing this out.
Agreed: Alpers is_a parent should be changed. 

Looking at Alpers Syndrome and mitochondrial DNA depletion syndrome 4a
According to Genetics Home Reference: 
   Alpers syndrome --> name updated to Alpers-Huttenlocher syndrome (AHS)
Genetics Home Reference, Orphanet and NORD all concur: 
     AHS is a rare and severe form of mitochondrial DNA (mtDNA) depletion syndrome 

Another reference: PMID: 27555780

**OMIM: 203700  mitochondrial DNA depletion syndrome 4a**

--> I see that OMIM has both mitochondrial DNA (mtDNA) depletion syndrome and Alpers under this OMIM ID. 
--> DO will keep these as two disease terms, so in this situation, the OMIM ID belongs to both. 

Checked other refs: all OK 

I have made all of the changes.
The will be available in DO's next data release.
Cheers,
Lynn

**Comment by sbello** [comment]
@lschriml I think we might want to review the decision to keep these as separate entries. OMIM has Alpers Syndrome as a synonym for 'mitochondrial DNA depletion syndrome 4a' and all the OMIM and Orphanet cross-references indicate to me these are now the same disease.
I'm submitting a separate ticket for the missing definitions for the 'mitochondrial DNA depletion syndrome' terms.
Thanks,
Sue

**Comment by msinclair2** [comment]
I have merged Alpers syndrome (DOID:1442) into mitochondrial DNA depletion syndrome 4a (DOID:0080122) as per the discussion on issue #692.
