### ISSUE TITLE
doid.obo corrupted when fetching from OBO Foundry

### ISSUE THREAD

**Issue by jogoodma** [DiseaseOntology/HumanDiseaseOntology#181]
When pulling doid.obo from http://purl.obolibrary.org/obo/doid.obo, the resulting file fails to load when parsed by the BioPerl OBO parser.

The error received states 

> ------------- EXCEPTION: Bio::Root::Exception -------------
> MSG: OBO File Format Error on line 41574 
> The term does not have a id/name tag. This term will be ignored.
> 
> STACK: Error::throw
> STACK: Bio::Root::Root::throw /usr/share/perl5/Bio/Root/Root.pm:449
> STACK: Bio::OntologyIO::obo::parse /usr/share/perl5/Bio/OntologyIO/obo.pm:241
> STACK: Bio::OntologyIO::obo::next_ontology /usr/share/perl5/Bio/OntologyIO/obo.pm:341
> STACK: /g2f/bin/load_DO.pl:147
> 

Parsing dies at this point and nothing gets processed.  The offending term in the file is

> [Term]
> id: DOID:13628
> is_a: DOID:2862 ! glucosephosphate dehydrogenase deficiency
> 

Note the lack of a name attribute.

This term appears to be fine in the github [doid.obo file](https://github.com/DiseaseOntology/HumanDiseaseOntology/raw/master/src/ontology/doid.obo).

 @FlyBase had been using the OBO Foundary URL since the beginning of this year and only started seeing problems within the last few months.  We thought it might be a short term issue, but it has persisted for nearly two months now.

**Comment by elviram** [comment]
Hello John,
as you say, the doid.obo file in github, as well as the one in our old repo in sourceforge.
We will look further into it. In the meantime you could switch to load the file directly from github.

Best,
Elvira

**Comment by elviram** [comment]
Hello John,
we think we have found the cause for this issue. A new release will be pushed today and we will check again tomorrow to make sure.

Best,
Elvira

**Comment by elviram** [comment]
Fixed.
