### ISSUE TITLE
DOID:13628 no term name 

### ISSUE THREAD

**Issue by ybradford** [DiseaseOntology/HumanDiseaseOntology#185]
Hi,

Loading the DO file this morning ZFIN finds that DOID:13628 has no term name or information other than is_a relationship:
[Term]
id: DOID:13628
is_a: DOID:2862 ! glucosephosphate dehydrogenase deficiency

from ontology version:
data-version: releases/2016-09-01
date: 09:01:2016 16:27

Can you please add a term name and the cross references back?  In the DO browser the term name is 'favism'.

Thanks,
Yvonne

**Comment by elviram** [comment]
Hello Yvonne,

we have been made aware of this issue (see #181). It is something going on with OBO file from the OBO foundry. Our files in github and sourceforge do not have that issue. We will post a new release this Friday.

Best,
Elvira

**Comment by ybradford** [comment]
Hi Elvira,
Thanks for the speedy reply. Sorry I didn't notice that this was previously reported. Thanks for fixing the OBO foundry file.

-Yvonne

**Comment by elviram** [comment]
Hello Yvonne,
we think we have found the cause for this issue. A new release will be pushed today and we will check again tomorrow to make sure.

Best,
Elvira

**Comment by elviram** [comment]
Fixed.
