### ISSUE TITLE
DOID:8484 synonym missing end quote and synonym type

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#186]
Hi Elvira,
Lori is starting to look at the DO file in anicipation of our next project. She found the error below.
Thanks,
Sue

http://bhmgiapp14ld.jax.org/data/downloads/raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid.obo

[Term]
id: DOID:8484
name: maple bark strippers' lung
def: "An opportunistic mycosis that is located_in lungs caused by inhalation of fungal spores while stripping the bark from maple logs, has_material_basis_in Cryptostroma corticale." [url:http\://nt.ars-grin.gov/fungaldatabases/, url:http\://www.ncbi.nlm.nih.gov/pubmed/2735559]
synonym: "alveolitis due to cryptostroma corticale" EXACT []
synonym: "maple bark disease" EXACT []

***This symbol is missing it’s ending quote and synonym type.***
I can fix it in my version…but this needs to be fixed upstream.

synonym: "maple bark stripper

synonym: "maple bark stripper's lung" EXACT []
synonym: "Maple bark-strippers' lung" EXACT [ICD9CM_2006:495.6]
synonym: "Maple-bark strippers' lung (disorder)" EXACT [SNOMEDCT_2005_07_31:86638007]
xref: ICD10CM:J67.6
xref: ICD9CM:495.6
xref: SNOMEDCT_US_2016_03_01:86638007
xref: UMLS_CUI:C0155890
is_a: DOID:2473 ! opportunistic mycosis

**Comment by elviram** [comment]
Fixed in today's release.

Best,
Elvira
