### ISSUE TITLE
OMIM terms mapped to more than 1 DO term

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#196]
Hi Elvira,
I've created a spreadsheet of OMIM terms mapped to multiple DO terms, https://docs.google.com/spreadsheets/d/1y87hjHwcpM8OJUkolkMpcH0FsUYreoQLUb-ibAjB46g/edit?usp=sharing
I'll work on reviewing these and indicating if I think one of the mappings should be removed. I've looked at a few and for the most part I don't think the primary entity in the OMIM record actually represents 2 diseases.
Sue

**Comment by elviram** [comment]
Thank you Sue!
