### ISSUE TITLE
central nervous system leukemia should be classified as a subtypes of leukemia

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#198]
[DOID:12969](http://purl.obolibrary.org/obo/DOID_12969) ! central nervous system leukemia

should be a subclass of

 [DOID:1240](http://purl.obolibrary.org/obo/DOID_1240) ! leukemia

instead the hierarchy looks like this:

![l](https://cloud.githubusercontent.com/assets/50745/19094969/015cfdda-8a48-11e6-8596-0371b5d7a78a.png)

**Comment by cmungall** [comment]
Fixing this ticket would fix this issue: #153

**Comment by cmungall** [comment]
Can I just reiterate: this is high priority. If a group is using DO in their system, and they have data/genes/samples annotated to CNS leukemia or children, and a user queries using the DOID for leukemia, __they will not find the data__

Also: __this is a simple problem to fix__ (see ticket above) I am available to help if you need it.

**Comment by lschriml** [comment]
Looking at this request: 
the term, CNS leukemia, was created (and later included in DO) for the disease where there are neurological consequences of leukemic infiltration. 
This term is not describing a type of leukemia. 

check out this [reference]): http://link.springer.com/article/10.1007%2Fs11912-005-0028-7
Leukemia and the nervous system 

It would be incorrect to classify CNS leukemia as a type of leukemia.

**Comment by cmungall** [comment]
I disagree with the statement "It would be incorrect to classify CNS leukemia as a type of leukemia", and I note that this statement doesn't follow from either textual or OWL definitions in the DO right now.

But for now I will just note that many browsers, such as the MGI browser are showing the OWL version of DO, and are consequently showing the parent I hold to be correct, yet DO holds to be incorrect!

http://www.informatics.jax.org/disease/DOID:12969

![image](https://cloud.githubusercontent.com/assets/50745/23861254/bb6b25ca-07c6-11e7-8232-54cf2cf09d0e.png)


cc-ing @sbello to check about the intent of the MGI browser.

**Comment by cmungall** [comment]
Note the default obo version of the DO lacks this parentage. So the obo version is in line with the DO's stated intent that CNS leukemia is not a type of leukemia, and the owl version is in line with what myself and most other people would hold to be correct. I think it's most important for DO to document its intent clearly and put out consistent releases, then we can discuss the modeling. But the current situation is confusing for everyone.
