### ISSUE TITLE
DOID:627 SCID definition

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#200]
The current definition of DOID:627 (severe combined immunodeficiency) specifies defects in both T and B cell but multiple sources refer to T cell defects with or without B cell and NK cell defects. See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3196791/ 
http://omim.org/entry/601457 
A few child terms of this term are specified to be B cell + types of SCID
DOID:0060016
DOID:0060015

Consider reviewing this term and subterms.
Sue

**Comment by elviram** [comment]
Looking into it. Thank you Sue.

**Comment by lschriml** [comment]
SCID is T & B - look at revising definitions

**Comment by melodyswen** [comment]
Definition now changed to "A combined T cell and B cell immunodeficiency that is caused by a defect in infection=fighting immune cells resulting in individuals with non-functional immune systems."
