### ISSUE TITLE
Strange xref lines in do_id.obo (causing problems with ontology update in FlyBase)

### ISSUE THREAD

**Issue by gm119** [DiseaseOntology/HumanDiseaseOntology#203]
Hi DO folks,

we've come across some oddly formatted xref lines in the following version of doid.obo:

data-version: releases/2016-09-26
date: 26:09:2016 15:27

They are causing problems with us trying to update the DO in FlyBase.

In each case, the text of the line after the 'xref: ' at the beginning starts with a '\\:' ie. backslash followed by a colon.

It looks like there are two kinds of problem:

Three cases look like a definition has somehow ended up as an xref - they are bolded in the term info below.

These three are also causing issues when using the DO browser at [http://disease-ontology.org/] - in each case when I try to click on the term after searching I get a message like so:

'Server Error (500)

There's been an error. It's been reported to the site administrators via e-mail and should be fixed shortly. Thanks for your patience.'

Here are the three terms:

id: DOID:0060599
name: Nance-Horan syndrome
**xref: \\:An X-linked disease that has_material_basis_in mutation in the NHS gene on chromosome Xp22. It is characterized by congenital cataract leading to profound vision loss\, characteristic dysmorphic features and dental anomalies. {xref="url:https://en.wikipedia.org/wiki/Nance-Horan_syndrome", xref="url:https://www.ncbi.nlm.nih.gov/pubmed/6467651", xref="url:https://www.ncbi.nlm.nih.gov/pubmed/2246772"}**
xref: ICD10CM:Q87.0
xref: MSH:C538336
xref: OMIM:302350
xref: ORDO:627
xref: UMLS_CUI:C0796085
is_a: DOID:0050735 ! X-linked disease

id: DOID:0110076
name: arrhythmogenic right ventricular dysplasia 8
synonym: "arrhythmogenic right ventricular cardiomyopathy 8" EXACT []
synonym: "ARVC8" EXACT []
synonym: "ARVD8" EXACT []
synonym: "familial arrhythmogenic right ventricular dysplasia 8" EXACT []
**xref: \\:An arrhythmogenic right ventricular dysplasia that has material basis in heterozygous mutation in the gene encoding desmoplakin (DSP) on chromosome 6p24. {xref="url:http://www.ncbi.nlm.nih.gov/pubmed/?term=12373648"}**
xref: ICD10CM:I42.8
xref: OMIM:607450
is_a: DOID:0050431 ! arrhythmogenic right ventricular cardiomyopathy

id: DOID:0110081
name: arrhythmogenic right ventricular dysplasia 10
synonym: "arrhythmogenic right ventricular cardiomyopathy 10" EXACT []
synonym: "ARVC10" EXACT []
synonym: "ARVD10" EXACT []
synonym: "familial arrhythmogenic right ventricular dysplasia 10" EXACT []
**xref: \\:An arrhythmogenic right ventricular dysplasia that has material basis in heterozygous mutation in the desmoglein-2 gene (DSG2) on chromosome 18q12. {xref="url:http://www.ncbi.nlm.nih.gov/pubmed/?term=16505173", xref="url:http://www.ncbi.nlm.nih.gov/pubmed/?term=17105751"}**
xref: ICD10CM:I42.8
xref: OMIM:610193
is_a: DOID:0050431 ! arrhythmogenic right ventricular cardiomyopathy

The second case looks like maybe the odd xref is a dbxref (as its a number) but is missing the part that says what database it comes from.  Again, bolded below.

[Term]
id: DOID:10487
name: Hirschsprung's disease
def: "A megacolon that is characterized by a blockage of the large intestine due to improper muscle movement in the bowel." [url:http\://digestive.niddk.nih.gov/ddiseases/pubs/hirschsprungs_ez/, url:http\://en.wikipedia.org/wiki/Hirschsprung%27s_disease, url:http\://www.nlm.nih.gov/medlineplus/ency/article/001140.htm, url:http\://www.uptodate.com/contents/congenital-aganglionic-megacolon-hirschsprung-disease]
comment: Xref MGI.\nOMIM mapping confirmed by DO. [SN].
subset: DO_MGI_slim
subset: DO_rare_slim
synonym: "aganglionic megacolon" EXACT [NCI2004_11_17:C34700]
synonym: "congenital megacolon" EXACT []
synonym: "Hirschsprung disease" EXACT []
synonym: "macrocolon" EXACT [SNOMEDCT_2005_07_31:204744001]
synonym: "pelvirectal achalasia" EXACT [CSP2005:0724-7702]
synonym: "total intestinal aganglionosis" EXACT []
**xref: \\:611644**
xref: EFOpat_id:647
xref: ICD10CM:Q43.1
xref: MSH:D006627
xref: NCI:C34700
xref: OMIM:142623
xref: OMIM:600155
xref: OMIM:600156
xref: OMIM:606874
xref: OMIM:606875
xref: OMIM:608462
xref: OMIM:613711
xref: OMIM:613712
xref: ORDO:388
xref: SNOMEDCT_US_2016_03_01:156957008
xref: SNOMEDCT_US_2016_03_01:204738000
xref: SNOMEDCT_US_2016_03_01:204739008
xref: SNOMEDCT_US_2016_03_01:204742002
xref: SNOMEDCT_US_2016_03_01:204744001
xref: SNOMEDCT_US_2016_03_01:360436002
xref: SNOMEDCT_US_2016_03_01:367495003
xref: SNOMEDCT_US_2016_03_01:6687001
xref: UMLS_CUI:C0019569
is_a: DOID:11372 ! megacolon

**Comment by elviram** [comment]
Hello,

thank you for pointing that out. Protege was acting up. Has been fixed with today's release.

Best,
Elvira

**Comment by gm119** [comment]
thanks for fixing ! Gillian
