### ISSUE TITLE
NTR: thrombosis

### ISSUE THREAD

**Issue by ybradford** [DiseaseOntology/HumanDiseaseOntology#206]
Hi,
I would like to request the term 'thrombosis' MeSH: D013927. I believe this term would also be an additional parent term for DOID:11512, DOID:11695, DOID:11847, DOID:3410, DOID:3572, DOID:3572, DOID:3575, DOID:3576, DOID:4193

I need the term to annotate zebrafish thrombosis model as described in PMID:27333081.

Thanks,
Yvonne

**Comment by elviram** [comment]
Hi Yvonne,

I apologize for the delay. The term 'thrombosis' has been added under 'vascular disease'.

Best,
Elvira

**Comment by ybradford** [comment]
@elviram thank you very much for adding!

Best,
Yvonne
