### ISSUE TITLE
Replace 'Microsporum gypseum' with 'Nannizzia gypsea'

### ISSUE THREAD

**Issue by jamesaoverton** [DiseaseOntology/HumanDiseaseOntology#210]
[NCBITaxon:489714 'Microsporum gypseum'](http://purl.obolibrary.org/obo/NCBITaxon_489714) has been merged into [NCBITaxon:63402 'Nannizzia gypsea'](http://purl.obolibrary.org/obo/NCBITaxon_63402) upstream in the NCBI Taxonomy. I think that DO can just make the replacement, but the textual definition for [DOID:0050097 'ectothrix infectious disease'](http://purl.obolibrary.org/obo/DOID_0050097) should probably be updated.

**Comment by elviram** [comment]
Will be updated with the new release.

Thank you James.
