### ISSUE TITLE
Website down http://www.disease-ontology.org/

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#213]
2:59pm PST Monday 12/5/2016  http://www.disease-ontology.org/ 
Gives error :
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by elviram** [comment]
We are looking into it. 

Thank you!

**Comment by elviram** [comment]
Fixed. Website is live again.
