### ISSUE TITLE
DO terms with self ID as synonym

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#214]
We have come across 2 DO terms with their own ID listed as an exact synonym in the OBO file. Please remove these.

[Term]
id: DOID:0060504
name: apple allergy
def: "A fruit allergy triggered by Malus domestica plant fruit food product." []
synonym: "DOID:0060504" EXACT []
synonym: "Malus domestica fruit allergy" EXACT []
is_a: DOID:0060503 ! fruit allergy
 
[Term]
id: DOID:0110357
name: retinitis pigmentosa 35
def: "A retinitis pigmentosa that has_material_basis_in mutation in the SEMA4A gene on chromosome 1q22." [https://www.ncbi.nlm.nih.gov/pubmed/16199541]
synonym: "DOID:0110357" EXACT []
synonym: "RP35" EXACT []
xref: ICD10CM:H35.5
xref: OMIM:610282
xref: ORDO:791
is_a: DOID:10584 ! retinitis pigmentosa

**Comment by elviram** [comment]
Fixed. OBO files will be update on the next release.
