### ISSUE TITLE
Changes to DOID:0050865

### ISSUE THREAD

**Issue by mbernste** [DiseaseOntology/HumanDiseaseOntology#219]
I found two issues with the term for DOID:0050865 ("tongue squamous cell carcinoma"):

1.The term has an EXACT synonym "squamous-cell carcinoma". I think this synonym should be labelled BROAD at the very least.  Not all squamous-cell carcinomas are located at the tongue. 
2. Rather, the term should have an "is_a" relationship to DOID:5520 ("head and neck squamous cell carcinoma"). This would take care of the first issue.

Thanks!

**Comment by elviram** [comment]
Thank you for pointing out the issue. We are looking at it.

**Comment by lschriml** [comment]
Hello Matthew,
  thank you for pointing this out. 
  I have removed the synonym, and updated the parentage to head and neck squamous cell carcinoma. 
Cheers,
Lynn
