### ISSUE TITLE
immune system cancer - nervous system cancer

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#224]
In the DOID-merged.obo file and the DOID.obo file nervous system cancer (DOID:3093) is an is_a child of immune system cancer DOID:0060083. This is not an accurate relationship. This relationship does not exist in the OWL file so I'm guessing this is a problem in the conversion from OWL to OBO. Please review the files to remove this relationship.
Thanks,
Sue

**Comment by elviram** [comment]
Just saw it. Wires got crossed with an axiom. New DOID-merged.obo file should be up in a bit. Still working out the kinks with that file.

Cheers,
Elvira
