### ISSUE TITLE
brain disease - bone marrow disease

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#225]
Another odd relationship has cropped up in the DOID.OBO and DOID-merged.OBO files. The term brain disease (DOID:936) is showing up as a child of bone marrow disease (DOID:936). Please review this relationship.
Thanks,
Sue

**Comment by elviram** [comment]
Fixed in the owl file with the latest commit. Will be visible in the obo files with the new release.

Thanks,
Elvira
