### ISSUE TITLE
hematopoietic system - immune system relationship

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#229]
Currently hematopoietic system disease is a child of immune system disease in the DO. These terms should be siblings. There are many hematopoietic system diseases (anemias, blood cooagulation diseases) that are not immune system diseases. Please alter this relationship and use inferred relationships for diseases that would belong under both parents.
Thanks,
Sue

**Comment by elviram** [comment]
Hematopoietic system disease is now a sibling to immune system disease. Leaving the ticket open to check if any other subclasses need to be moved still.

**Comment by melodyswen** [comment]
Reviewed November 2019 - hematopoietic system disease is a sibling to immune system disease.
