### ISSUE TITLE
autosomal recessive congenital ichthyosis 4A

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#230]
The ICD10 ID 'ICD10CM:Q80.2' was accidentally entered as a synonym instead of an xref. Please modify this association.

**Comment by elviram** [comment]
Hi Sue,

which file are you talking about? I cannot see it anywhere. The ICD10 code is an xref on the term you mention.

Best,
Elvira

**Comment by sbello** [comment]
Odd, I found this in the MGI dev environment when I was doing a search but I don't see the issue in either the current doid-edit or doid-merged files. So, I guess this got fixed sometime between our last upload of the file and now. Sorry for the confusion.

**Comment by elviram** [comment]
No problem!
