### ISSUE TITLE
Lack of a grouping for benign lung neoplasm and lung cancer

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#231]
This in itself is problematic: there is no grouping:

![image](https://cloud.githubusercontent.com/assets/50745/22177740/52a92448-dfd9-11e6-9a3a-bf4e2ca190f4.png)

There is an additional problem with the xrefs for benign:

```
[Term]
id: DOID:3683
name: lung benign neoplasm
namespace: disease_ontology
synonym: "tumor of the lung" EXACT [NCI2004_11_17:C3200]
***xref: MESH:D008175 ! Lung Neoplasms
***xref: NCIT:C3200 ! Lung Neoplasm
xref: NCIT:C4454 ! Benign Lung Neoplasm
xref: SCTID:126713003
xref: UMLS:C0024121
is_a: DOID:0050621  ! respiratory system benign neoplasm
```

While there should be no assumption that xrefs are 1:1, ones such as the marked are particularly problematic.

For reference, here is NCIT (why not just adopt NCIT directly for neoplasm and below??)

![image](https://cloud.githubusercontent.com/assets/50745/22177791/2b367aea-dfda-11e6-9b5d-efa3957c506b.png)

**Comment by elviram** [comment]
Hi Chris, 
will look into it and see what we can do. There is the Cancer-DO workshop coming up.

Best,
Elvira

**Comment by lschriml** [comment]
The DO follows the WHO classification, and classifies separately benign tumors and cancers. 
It would be incorrect to classify them together. 
The use of the word neoplasm has been used for both benign tumors and cancers in many resources. The DO purposely made these distinctions, which is essential when annotation cancer datasets. When the NCI groups benign and cancer terms under one NCIt ID, the DO will link to that ID.

**Comment by cmungall** [comment]
OK, let's tackle the straightforward part first - in my initial comment I noted a problem with the xref to NCIT:

```
[Term]
id: DOID:3683
name: lung benign neoplasm
synonym: "tumor of the lung" EXACT [NCI2004_11_17:C3200]
xref: MSH:D008175
***xref: NCI:C3200 ! Lung Neoplasm
xref: SNOMEDCT_US_2015_03_01:126713003
xref: UMLS_CUI:C0024121
is_a: DOID:0050621 ! respiratory system benign neoplasm
```

As can be seen in the diagram above, NCI:C3200 is a malignancy-neutral grouping, and that there is a more specific concept  NCIT:C4454 Benign Lung Neoplasm.

It would be more accurate to xref this, as it is more closely aligned with (or in fact equivalent to)  DOID:3683.

I would also recommend changing the synonym scope of the NCIT-derived synonym to BROAD, as NCIT is clearly using the term "tumor" in a broad malignancy-neutral fashion.

Next:

please note that I am not suggesting DO collapse the distinction between benign and malignant neoplasms/tumors. As you say, this is necessary for the annotation of cancer data. I am requesting the addition of a grouping class, or at least for some connections between these classes. One of the main purposes of an ontology rather than a flat list is to create grouping classes that may be useful for different purposes. I think NCIT is a better model than ICD-0 here, because NCIT is an ontology. You can still be consistent with the ICD-0 hierarchy of course, but it should not prevent you from making the kinds of groupings that people use OBO ontologies for.
