### ISSUE TITLE
organ system cancer terms

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#236]
Several of the organ system cancer terms lack relationships to the organ system disease terms in DO. These are:
endocrine gland cancer (DOID:170) - endocrine system disease (DOID:28)
gastrointestinal system cancer (DOID:3119) - gastrointestinal system disease (DOID:77)
nervous system cancer (DOID:3093) - nervous system disease (DOID:863)
reproductive organ cancer (DOID:193) - reproductive system disease (DOID:15)
thoracic cancer (DOID:5093) - thoracic disease (DOID:0060118)

Please add located_in relationships for these cancer terms so that the correct inferred relationship will be created.
endocrine system (UBERON:0000949)
gastrointestinal system (UBERON:0005409)
nervous system  (UBERON:0001016) please also add this for the nervous system disease term
reproductive system (UBERON:0000990)
thoracic segment of trunk (UBERON:0000915) please also add this for the thoracic disease term

**Comment by elviram** [comment]
Will start working on them.

**Comment by lschriml** [comment]
DONE
