### ISSUE TITLE
NCI links no longer valid

### ISSUE THREAD

**Issue by kkrysiak** [DiseaseOntology/HumanDiseaseOntology#237]
I'm assuming since they have updated their thesaurus version they are no longer supporting older versions, leading to broken links. See DOID:12689 example below.

DOID Link:
http://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=14.10d&code=C3276

Current NCI Link:
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.12d&ns=NCI_Thesaurus&code=C3276

**Comment by elviram** [comment]
Hi Kilannin,

thank you for the heads up. We will update the links on our next database update of the website.

Best,
Elvira

**Comment by elviram** [comment]
Hi Kilannin,

as of today's database update, the links redirect to the correct page.

Thank you,
Elvira
