### ISSUE TITLE
NTR:  epileptic encephalopaty, early infantile, female-limited

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#240]
EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE 
synonyms: EPILEPSY, FEMALE-RESTRICTED, JUBERG-HELLMAN SYNDROME, female-limited infant onset epilepsy
OMIM # 300088

**Comment by elviram** [comment]
Thank you for the request. The term has been added.

Best,
Elvira
