### ISSUE TITLE
McKusick type metaphyseal dysplasia AND cartilage-hair hypoplasia

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#243]
Are these the same?

http://purl.obolibrary.org/obo/DOID_0080022
McKusick type metaphyseal dysplasia

http://purl.obolibrary.org/obo/DOID_14773
cartilage-hair hypoplasia

https://en.wikipedia.org/wiki/Cartilage%E2%80%93hair_hypoplasia

**Comment by elviram** [comment]
Yes they are. Terms have been merged. McKusick type metaphyseal dysplasia is now an exact synonym for cartilage-hair hypoplasia.
