### ISSUE TITLE
familial hypertriglyceridemia AND hyperlipoproteinemia type IV

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#244]
According to mesh, these are synonyms:

http://purl.obolibrary.org/obo/DOID_0050527
familial hypertriglyceridemia

http://purl.obolibrary.org/obo/DOID_1172
hyperlipoproteinemia type IV

https://www.nlm.nih.gov/cgi/mesh/2011/MB_cgi?exact&field=uid&term=D006953

**Comment by elviram** [comment]
Terms have been merged.
