### ISSUE TITLE
Add logical relationships to herpes simplex #51 (from obophenotype)

### ISSUE THREAD

**Issue by elviram** [DiseaseOntology/HumanDiseaseOntology#251]
[https://github.com/obophenotype/human-disease-ontology/issues/51](url)
@mcourtot

Moving issue here: 

http://purl.obolibrary.org/obo/DOID_8566

Could the relations described in the text be formalized, e.g. located_in etc?

reported by lidia.ryabova@um.edu.mt - please include her in any reply

**Comment by cmungall** [comment]
A first pass at all these should be in the ext.owl file I made

**Comment by lschriml** [comment]
I have added logical definitions for anatomical locations, where the anatomical term is present in UBERON. 
missing terms: genitalia (UBERON has more specific external/internal genitalia, we need the more general term)
, hand (UBERON:manus, foot (UBERON: pes)

The human anatomical terms need to be added a terms, not synonyms, for DO to be able to use them. 

These updates will be available in our next weekly release.

**Comment by mcourtot** [comment]
Thanks; do you want to let Lidia know? (her email is above) IIRC, she had other DO requests, so may be useful to link with her directly.

**Comment by elviram** [comment]
Thank you Melanie, I'll forward it to Lidia.

**Comment by cmungall** [comment]
On 16 Feb 2017, at 9:15, lschriml wrote:

> I have added logical definitions for anatomical locations, where the 
> anatomical term is present in UBERON.
> missing terms: genitalia (UBERON has more specific external/internal 
> genitalia, we need the more general term)

Which term specifically? Uberon has sex-neutral superclasses for these.

> , hand (UBERON:manus, foot (UBERON: pes)
> The human anatomical terms need to be added a terms, not synonyms, for 
> DO to be able to use them.

hand is an exact synonym of manus (same for pes/foot).

note you're using the classes, not the labels.

> These updates will be available in our next weekly release.

Thanks!
