### ISSUE TITLE
SITraN terms

### ISSUE THREAD

**Issue by elviram** [DiseaseOntology/HumanDiseaseOntology#252]
List of requested terms from Vivien Junker, in Hide lab, Sheffield Institute for Translational Neuroscience (SITraN), University of Sheffield.

Spastic paralysis    
Spastic paraplegia    
Upper Motor Neuron-Dominant Amyotrophic Lateral Sclerosis    
Frontotemporal Dementia Chromosome 3-linked    
Corticobasal Degeneration    
Primary Lateral Sclerosis     
Flail Arm    
Juvenile Amyotrophic Lateral Sclerosis    
Multisystem proteinopathy    
Primary open angle glaucoma    
Frontotemporal Lobar Degeneration with Motor Neuron type inclusions but without Motor Neuron Disease (FTLD-U)    
Early-onset Alzheimer’s disease    
Apraxia of Speech    
Semantic Dementia

and:

Amyotrophic Lateral Sclerosis-Frontotemporal Dementia 
Frontotemporal Lobar Degeneration - Corticobasal Degeneration
Amyotrophic Lateral Sclerosis-Motor Neuron Disease, Parkinson's disease
Frontotemporal Lobar Degeneration - Semantic Dementia
Amyotrophic Lateral Sclerosis - Parkinson's disease
Frontotemporal Lobar Degeneration - Motor Neuron Disease

**Comment by melodyswen** [comment]
Terms have been added to team drive for further review

**Comment by melodyswen** [comment]
A number of these terms are already in the DO as a synonym or a term. 

Terms to be added for review: 
- Corticobasal Degneration
- Flail Arm Syndrome
- Multisystem Proteinopathy (MSP)
- Frontotemporal Lobar Degneration with Motor Neuron type inclusions but without Motor Neuron Disease (FTLD-U)

**Comment by melodyswen** [comment]
MSP has been added
