### ISSUE TITLE
Missing link between 'malignant ovarian Brenner tumor' and 'ovarian Brenner tumor'

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#253]
![obt](https://cloud.githubusercontent.com/assets/50745/22806071/2dec12b8-eed5-11e6-839f-71700e09d110.png)

**Comment by lschriml** [comment]
Hello Chris,
These two diseases represent a benign and a malignant form of the same tumor type. 

  What connection do you expect to see ? 

      Oddly, UBERON does not include ovary as a term, but as an exact synonym for female gonad.
         I cannot include female gonad in DO, it is not how this organ is referred to clinically. 
     
       Would you consider changing female gonad to ovary ? 

 I am adding their anatomical location and cell of origin. 
     I have added definitions to clarify these terms. 

Cheers,
Lynn

**Comment by cmungall** [comment]
> These two diseases represent a benign and a malignant form of the same tumor type

Yes, aware of that (although the labels in DO are misleading here)

> What connection do you expect to see

I'd expect these to be grouped, for example as they are in NCIT

```
      is_a NCIT:C3872 ! Ovarian Brenner Tumor *** 
          is_a NCIT:C4270 ! Malignant Ovarian Brenner Tumor
          is_a NCIT:C4746 ! Benign Ovarian Brenner Tumor
          is_a NCIT:C9459 ! Borderline Ovarian Brenner Tumor
```

I also recommend using the same design patterns and labels and NCIT where the malignancy status is clearer, and benign forms are clearly indicated.

**Comment by cmungall** [comment]
Re: uberon species-neutral terminology. Note that you are not compelled to follow the terminology of either uberon or go (which are species-neutral) in GO. You can import an uberon module without any concerns for clinical users.
