### ISSUE TITLE
NTR: two terms

### ISSUE THREAD

**Issue by zhengj2007** [DiseaseOntology/HumanDiseaseOntology#254]
@elviram Hi, Elvira,

Two disease terms are needed for defining some assays in BAO.
   Hypotonia-Cystinuria syndrome (a syndrome)
   Salmonellosis (a primary bacterial infectious disease)

Could you please help on it? Please feel free to contact me if more information are needed.

Thanks!

Jie

**Comment by elviram** [comment]
Hi Jie,

I will add them in. They should be in our next release.

Cheers,
Elvira

**Comment by zhengj2007** [comment]
Hi Elvira,

Thanks a lot! Please let me know if you need more information.

Jie

**Comment by linikujp** [comment]
Hi Elvira,

When will be the next release?

Thanks,
Asiyah

**Comment by elviram** [comment]
Hi Asiyah,

that would be this Friday, February 17.

Cheers,
Elvira

**Comment by zhengj2007** [comment]
It's great! 
Thanks, Elvira.
- Jie
