### ISSUE TITLE
New MeSH xrefs or new terms

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#257]
I am trying to match up a couple hundred MeSH terms with DO or HPO and have a bunch that I couldn't match. So I retrieved the MeSH broader term (one up the tree) and attempted to xref those. Here is a list of those where the broader term has an xref to DO. 
I think some of these either 

1. exist but don't have mesh xrefs (guillain-barre: http://purl.obolibrary.org/obo/DOID_12842)
2. have incorrect xrefs (diphtheria has xref to the broader term Corynebacterium Infections
3. don't exist but should
4. may be too specific to be useful ("hepatitis c, chronic" vs. "hepatitis c" ??)
5. are really phenotypes and should be in HPO, so can be ignored here ("iron overload" ?)

I will try to categorize them when I get a chance (1-5)

| Mesh  | Mesh Name | Mesh Broader | Mesh Broader Name | DO Broader xref | HP Broader xref | category
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|D020275| guillain-barre syndrome| D011129| polyradiculoneuropathy| DOID:4308| None|
|D057135| wet macular degeneration| D008268| macular degeneration| DOID:10871| HP:0007868|
|D016908| gram-positive bacterial infections| D001424| bacterial infections| DOID:104| None|
|D008224| lymphoma, follicular| D008228| lymphoma, non-hodgkin| DOID:8675| HP:0012539|
|D003865| depressive disorder, major| D003866| depressive disorder| DOID:1595| HP:0000716|
|D004165| diphtheria| D003354| corynebacterium infections| DOID:11405| None|
|D008286| malabsorption syndromes| D007410| intestinal diseases| DOID:5295| HP:0002242|
|D017681| hypereosinophilic syndrome| D004802| eosinophilia| DOID:999| HP:0001880|
|D016891| polycystic kidney, autosomal dominant| D007690| polycystic kidney diseases| DOID:898| HP:0000113|
|D008585| meningitis, meningococcal| D016920| meningitis, bacterial| DOID:9470| None|
|D019190| iron overload| D019189| iron metabolism disorders| DOID:2351| None|
|D048909| diabetes complications| D003920| diabetes mellitus| DOID:9351| HP:0000819|
|D001171| arthritis, juvenile| D001168| arthritis| DOID:848| HP:0001369|
|D020522| lymphoma, mantle-cell| D008228| lymphoma, non-hodgkin| DOID:8675| HP:0012539|
|D009371| neoplasms by site| D009369| neoplasms| DOID:162| HP:0002664|
|D054058| acute coronary syndrome| D017202| myocardial ischemia| DOID:3393| None|
|D014883| water-electrolyte imbalance| D008659| metabolic diseases| DOID:0014667| None|
|D054198| precursor cell lymphoblastic leukemia-lymphoma| D007945| leukemia, lymphoid| DOID:1037| HP:0005526|
|D006504| hepatic veno-occlusive disease| D008107| liver diseases| DOID:409| HP:0001392|
|D012735| sexual dysfunction, physiological| D005832| genital diseases, male| DOID:48| None|
|D001862| bone resorption| D001847| bone diseases| DOID:0080001| None|
|D019973| alcohol-related disorders| D019966| substance-related disorders| DOID:302| None|
|D053201| urinary bladder, overactive| D001745| urinary bladder diseases| DOID:365| None|
|D052016| mucositis| D005759| gastroenteritis| DOID:2326| None|
|D009385| neoplastic processes| D009369| neoplasms| DOID:162| HP:0002664|
|D008583| meningitis, haemophilus| D016920| meningitis, bacterial| DOID:9470| None|
|D016470| bacteremia| D001424| bacterial infections| DOID:104| None|
|D019698| hepatitis c, chronic| D006526| hepatitis c| DOID:1883| None|
|D015663| osteoporosis, postmenopausal| D010024| osteoporosis| DOID:11476| HP:0000939|
|D019694| hepatitis b, chronic| D006509| hepatitis b| DOID:2043| None|
|D016905| gram-negative bacterial infections| D001424| bacterial infections| DOID:104| None|

**Comment by lschriml** [comment]
Hello Gregory,
Thank you for your interest in the Disease Ontology. 
We greatly appreciate your identifying how we can improve the DO. 
I have gone through your list. (attached).
And noted where these MeSH terms could be added to DO. 
We will update the DO, based on your list. 
Cheers,
Lynn
[MeSH review_Feb_2017.xlsx](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/788577/MeSH.review_Feb_2017.xlsx)

**Comment by lschriml** [comment]
These MESH IDs have been added to DO. 
Lynn
