### ISSUE TITLE
New Term Request: Exstrophy of Bladder

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#261]
Hi,

I wanted to request this new term for the ontology: Exstrophy of Bladder
(MIM:600057) and Orphanet (ORPHA:93930). Thanks

Sridhar

**Comment by lschriml** [comment]
Hello Sridhar,
  Thank you for suggesting this new term. 
I am adding it to DO, under physical disorder. 
I have added, as a parent term, bladder exstrophy-epispadias-cloacal exstrophy complex.
 
Cheers,
Lynn
