### ISSUE TITLE
septooptic dysplasia

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#262]
Please consider moving this to be a child of autosomal genetic disease (currently a child of monogenic disease). 
Also update the definition to: 
An autosomal genetic disease characterized by the classical triad of optic nerve hypoplasia, pituitary gland hypoplasia and midline brain defects that has_material_basis_in mutation in the HESX1 gene on chromosome 3p14.

**Comment by elviram** [comment]
The suggested changes are accepted.
