### ISSUE TITLE
Create new subtype of lymphoplasmacytic lymphoma

### ISSUE THREAD

**Issue by kkrysiak** [DiseaseOntology/HumanDiseaseOntology#264]
Waldenström's macroglobulinemia is currently considered an exact match for lymphoplasmacytic lymphoma when it is a subtype. Lymphoplasmacytic lymphoma with IgM gammopathy.

**Comment by elviram** [comment]
Thank you for the term request Kilannin. Waldenstroem's macroglobulinemia will become a child of lymphoplasmacytic lymphoma.
