### ISSUE TITLE
STR:  histiocytoid cardiomyopathy

### ISSUE THREAD

**Issue by sabrinatoro** [DiseaseOntology/HumanDiseaseOntology#265]
I would like request a new term: 
name: histiocytoid cardiomyopathy
Xref: MIM  500000 

This term would be a child of cardiomyopathy (DOID:0050700)
I believe it would actually be a child of intrinsic cardiomyopathy (DOID:0060036)

Thank you, 
Sabrina

**Comment by lschriml** [comment]
Thank you Sabrina for this term request. 
We will review this term for inclusion in DO.
Cheers,
Lynn

**Comment by lschriml** [comment]
done, apologies for the delay.
