### ISSUE TITLE
duplicate term in DO: Timothy syndrome

### ISSUE THREAD

**Issue by gm119** [DiseaseOntology/HumanDiseaseOntology#267]
Hi DO folks,

we discovered a duplication in DO while trying to load the latest version of the obo file into FlyBase, which is preventing us loading the latest version of DO into the database.

There are two terms that have the same name, but they have different DOID numbers:

[Term]
id: DOID:0060173
name: Timothy syndrome
def: "An autosomal dominant disease that is characterized by cardiac, hand/foot, facial, and neurodevelopmental features. The two forms are type 1 (classic) and type 2, a rare form that has material basis in mutations in a transcript variant of CACNA1C." [url:http\://www.ncbi.nlm.nih.gov/books/NBK1403/]
is_a: DOID:0050736 ! autosomal dominant disease
created_by: lschriml
creation_date: 2011-11-08T12:52:33Z

and

[Term]
id: DOID:0110649
name: Timothy syndrome
def: "A long QT syndrome that has_material_basis_in dominant inheritance of mutation in the CACNA1C gene on chromosome 12p13.33. " [url:https\://www.ncbi.nlm.nih.gov/pubmed/15863612]
synonym: "long QT syndrome 8" EXACT []
synonym: "long QT syndrome with syndactyly" EXACT []
synonym: "LQT8" EXACT []
synonym: "TS" EXACT []
xref: ICD10CM:G72.3
xref: OMIM:601005
xref: ORDO:65283
xref: ORDO:768
is_a: DOID:2843 ! long QT syndrome

The version of the file that has this issue is:

format-version: 1.2
data-version: releases/2017-02-17
date: 02:17:2017 17:00

(we get this file by using the purl http://purl.obolibrary.org/obo/doid.obo)

Thanks,

Gillian

**Comment by elviram** [comment]
Hello Gillian,

thank you for catching that. The terms will be merged. The new DO release is scheduled for this Friday, does that work for you?

**Comment by gm119** [comment]
Hi Elvira, thanks !

**Comment by lschriml** [comment]
The terms have been merged.
