### ISSUE TITLE
xref with no db/accession: MEHMO syndrome

### ISSUE THREAD

**Issue by gm119** [DiseaseOntology/HumanDiseaseOntology#268]
Hi,

minor issue spotted while trying to load latest DO into FlyBase.

There is a xref with no db/accession to indicate where it came from:

id: DOID:0060801
name: MEHMO syndrome

xref: C53745

Thanks,

Gillian

**Comment by elviram** [comment]
Hello Gillian,

thank you for finding that. The working file has been updated. The new DO release is scheduled for this Friday.

**Comment by lschriml** [comment]
Fixed.
