### ISSUE TITLE
intrinsic vs extrinsic blood disorders

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#271]
Ticket submitted to phenotype GitHub by @nlwashington 

There seems to be consideration of platelet/blood disorders into extrinsic vs intrinsic. Can you add these grouping classes? Here's some materials:

http://www.allaboutbleeding.com/hcp/platelet-dysfunction.aspx
https://en.wikipedia.org/wiki/Coagulation#Tissue_factor_pathway_.28extrinsic.29

**Comment by melodyswen** [comment]
Are blood disorders separated into extrinsic vs intrinsic - is it a pathway or does it distinguish disease? Need further look into the literature.

**Comment by melodyswen** [comment]
https://www.chop.edu/conditions-diseases/hemolytic-anemia

**Comment by melodyswen** [comment]
The intrinsic and extrinsic pathways are part of the coagulation pathway - a cascade of events that leads to hemostasis (the first stage of wound healing). The two paths originate separately but converge at a specific point, leading to fibrin activation. Given that these are characteristics of blood coagulation, I think that they are not pertinent as grouping classes.

**Comment by melodyswen** [comment]
Source: https://www.ncbi.nlm.nih.gov/books/NBK482253/
