### ISSUE TITLE
Add grouping for classic and atypical forms of multiminicore

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#274]
you recently added

```
    is_a DOID:66 ! muscle tissue disease
      is_a DOID:423 ! myopathy
       is_a DOID:9884 ! muscular dystrophy
        is_a DOID:0050557 ! congenital muscular dystrophy
         is_a DOID:0110633 ! rigid spine muscular dystrophy 1 *** 
```

RSMD aka 'classic' multiminicore seems to be often grouped with 'atypical' forms caused by RYR1, e.g. https://ghr.nlm.nih.gov/condition/multiminicore-disease#

Would DO consider a term for the RYR1 form? And would also DO consider a grouping 'multiminicore disease' for both?

Arises from: https://github.com/monarch-initiative/monarch-disease-ontology/issues/211

**Comment by lschriml** [comment]
Thank you Chris !!
We will take a look.
Cheers,
Lynn
