### ISSUE TITLE
glycoproteinosis: specific vs generic

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#276]
```
[Term]
id: DOID:3343
name: glycoproteinosis
namespace: disease_ontology
def: "A lysosomal storage disease that is characterized by a deficiency of the enzyme alpha-N -acetyl neuraminidase (sialidase)." [url:http://en.wikipedia.org/wiki/Sialidosis, url:https://en.wikipedia.org/wiki/Glycoproteinosis, url:https://www.rarediseases.org/rare-disease-information/rare-diseases/byID/302/viewAbstract]
comment: OMIM mapping submitted by NeuroDevNet. [LS].
subset: DO_FlyBase_slim  ! DO_FlyBase_slim
synonym: "Mucolipidosis type I" EXACT []
synonym: "sialidosis" EXACT []
xref: ICD10:E77.1
xref: MESH:D009081
xref: NCI:C61267
xref: OMIM:256550
xref: SNOMEDCT_US_2016_03_01:70528007
xref: UMLS_CUI:C0026697
is_a: DOID:3211  ! lysosomal storage disease
```

The referenced wikipedia article talks of a generic grouping " lysosomal storage diseases[1] affecting glycoproteins, resulting from defects in lysosomal function". Such a generic grouping brings together many OMIMs, including sialidosis.

The DO definition is for a specific form, sialidosis. The rarediseases.org ref is also for this, as is the other wikipedia link. The two synonyms should not be exact.

Consider using the Orphanet classification:

![glycoproteinosis](https://cloud.githubusercontent.com/assets/50745/24263258/de0b05dc-0fb9-11e7-99a2-acc638508ff3.png)

**Comment by cmungall** [comment]
I don't know whether you will retain the ID for the specific form, or for the generic form. OBO guidelines suggest obsoletion in this case, as the concepts have become mixed.

**Comment by cmungall** [comment]
The above figure included the genes. Just the disease classification:

![glycoproteinosis](https://cloud.githubusercontent.com/assets/50745/24263348/24ba52e4-0fba-11e7-9a4c-dcef8925606d.png)

**Comment by elviram** [comment]
Thank you Chris. We will discuss this issue.
