### ISSUE TITLE
ectodermal dysplasia grouping term

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#277]
consider adding a new grouping term of: 
ectodermal dysplasia syndrome
see Orphanet entry  http://www.orpha.net/ORDO/Orphanet_79373 
text of GHR https://ghr.nlm.nih.gov/condition/ankyloblepharon-ectodermal-defects-cleft-lip-palate-syndrome "Ankyloblepharon-ectodermal defects-cleft lip/palate (AEC) syndrome is a form of ectodermal dysplasia, a group of about 150 conditions characterized by abnormal development of ectodermal tissues including the skin, hair, nails, teeth, and sweat glands."
For a review see:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4155886/
Seems like this would be a useful term to group a broad class of syndromes currently placed under either syndrome or genetic disease.
We may also want to consider adding a relationship for tissue of origin for a disease but I think we might need a new relation type fore this. Basically some way to tag all diseases that develop as a result of a developmental defect in a particular embryonic tissue, something like arising_from ectoderm (UBERON:0000924).

**Comment by sbello** [comment]
See also:
https://meshb.nlm.nih.gov/record/ui?ui=D004476

**Comment by lschriml** [comment]
Thank you Sue, 
agreed, this should be added. 
For this relationship, we can use : 

the relation derives_from
def: "Type of tissue or cell/the source of the material. 
and we link these to the Cell Ontology or UBERON. 
Cheers,
Lynn

**Comment by melodyswen** [comment]
Moved AEC syndrome to child of ectodermal dysplasia.

**Comment by melodyswen** [comment]
https://ghr.nlm.nih.gov/search?query=ectodermal+dysplasia&tab=condition

117 terms related to ectodermal dysplasia
