### ISSUE TITLE
Convert license to CC0

### ISSUE THREAD

**Issue by andrewsu** [DiseaseOntology/HumanDiseaseOntology#278]
Not sure what the best mechanism to accomplish the license change is, but just creating the issue so we can make good on the promise that was made at Biocuration 2017.  ;)

For reference, here are how CIVIC and wikipathways handled their CC-BY to CC0 transition:
* https://github.com/genome/civic-client/issues/493
* http://www.wikipathways.org/index.php/WikiPathways:CC0_Announcement

**Comment by lschriml** [comment]
Hello Andrew,
  Here are the steps we are taking for update the content license to Creative Commons CC0
CC0 license: https://creativecommons.org/publicdomain/zero/1.0/
full license text: https://creativecommons.org/publicdomain/zero/1.0/legalcode

Changes made: 
(1) in the DO's production file: 
   adding refs:comment for licensing:   --> (in diid-edit.owl), the DO production files will be updated next week, as part of our bi-monthly data release. 

The Disease Ontology content is available via the Creative Commons Public Domain Dedication CC0 1.0 Universal license. 
(2) DO Github: License.txt updated to CC0
(3) DO website
      - News item added 
     DO downloads page updated 
     DO resources page: DO License
     DO's FAQ
    DO's About
(4) OBO Foundry
(5) DO Social Media: twitter, Facebook, google groups, DO list-serv


Disease Ontology CC0 licensing update announcement: 
To encourage broad and open usage of the DO's content (data), for example in projects such as Wikidata and CIViC, as of April 5, 2017, the DO data and content licensing will be updated to CC0. While we will continue to encourage users of the DO to cite our publications (available on our DO website: www.disease-ontology.org), broader licensing will encourage greater usage of this biomedical ontology. Additionally, on the practical side, we recognize that we are not able to enforce CCBY licensing. The DO has been created and shared for it to be used, thus open content licensing is appropriate for this project. The DO's updated CC0 license will apply to all of our data and content. Notices regarding licensing of art, branding materials, etc. are unchanged.

Cheers,
Lynn
