### ISSUE TITLE
synonyms that start with whitespace

### ISSUE THREAD

**Issue by dan2097** [DiseaseOntology/HumanDiseaseOntology#283]
Not a major issue, but simple to fix. The following synonyms appear to start with an erroneous space.

synonym: " X-linked intellectual disability-choreoathetosis-abnormal behavior syndrome" EXACT []
synonym: " X-linked mental retardation with seizures, hypogammaglobinemia, and gait disturbance" EXACT []
synonym: " MEGCANN" EXACT []
synonym: " ARMD10" EXACT []
synonym: " short rib-polydactyly syndrome, type I" EXACT []
synonym: " CMT2D" EXACT []
synonym: " RI-CMTB" EXACT []
synonym: " INAD1" EXACT []
synonym: " Polycystic Kidney Disease, Adult, Type II" EXACT []
synonym: " Poland sequence" RELATED []
synonym: " hypoprothrombinemia" EXACT []
synonym: " small cell osteosarcoma (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189882001]
synonym: " Smooth muscle tumor NOS (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189799007]
synonym: " Clear cell sarcoma of kidney (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189813000]
synonym: " Eccrine papillary adenoma (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189674003]
synonym: " Myxoid chondrosarcoma (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189881008]
synonym: " osmotic demyelination syndrome" EXACT []

**Comment by lschriml** [comment]
Dan,
  Thank you for pointing these out. 
All fixed. 
Much appreciated,
Lynn
