### ISSUE TITLE
add a relationship for DOID:0050156

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#290]
It seems odd that the term idiopathic pulmonary fibrosis (DOID:0050156) is not a child of pulmonary fibrosis (DOID:3770). Currently this is a child of only idiopathic interstitial pneumonia (DOID:2797). Please consider adding a relationship so that we can infer that idiopathic pulmonary fibrosis is a type of pulmonary fibrosis in the OBO version of the DO.

**Comment by melodyswen** [comment]
We are fine with this relationship, but need a unique logical definition for pulmonary fibrosis.

**Comment by melodyswen** [comment]
added unique logical definition 'has material basis in' some ('Interstitial pulmonary abnormality' and 'has material basis in' some Scarring and 'located in' some lung)
