### ISSUE TITLE
familial adenomatous polyposis - review needed

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#292]
Not all OMIM subtypes of familial adenomatous polyposis (DOID:0050424) are autosomal dominant therefore this term may need a new parent and a change in definition. See OMIM:608456 (currently an xref to DOID:0050424) for an example of an autosomal recessive form. Possible locations for this term could be as a child of:
* disease of cellular proliferation (DOID:14566) - key features include development of  intestinal polyps and predisposition for cancer. For 3 of the 4 subtypes these are the only features listed on the OMIM clinical synopsis but the clinical synopsis for FAP1 includes symptoms in a range of other systems
* intestinal disease DOID:5295 - polyps are confined to the intestines although neoplasia may be widespread

However the use of FAP to group adenomatous polyposis syndromes is not consistent between sources.

See https://www.ncbi.nlm.nih.gov/pubmed/28331556 for a recent review This review does not lump the OMIM series PS175100 under the FAP name instead FAP is used only for FAP1 (175100). The others are given different names and collected under the term "adenomatous polyposis syndromes"  

The use of "Attenuated familial adenomatous polyposis" is also inconsistent between the review above and Orphanet as Orphanet does not restrict AFAP to only those with mutations in APC. See ORDO:220460

GHR uses FAP in a similar manner to OMIM https://ghr.nlm.nih.gov/condition/familial-adenomatous-polyposis#genes In that it includes both APC and MUTYH mutations, but it is missing NTHL1 and MSH3

GeneReviews groups FAP and attenuated FAP under APC-Associated Polyposis Conditions https://www.ncbi.nlm.nih.gov/books/NBK1345/ similar to the way the review handled these. There is a separate entry for MUTYH-Associated Polyposis https://www.ncbi.nlm.nih.gov/books/NBK107219/ The entries for both of these also mention NTHL1 and MSH3.

**Comment by lschriml** [comment]
subtypes added, add PS:

Familial adenomatous polyposis - PS175100
--
