### ISSUE TITLE
has_exact_synonym: malignant melanoma; Naevocarcinoma

### ISSUE THREAD

**Issue by alanruttenberg** [DiseaseOntology/HumanDiseaseOntology#293]
Could these please be split into two annotation values. That's generally how the property is used.

**Comment by elviram** [comment]
Hello Alan,

could you tell me which term you are referring to? 'melanoma' (DOID:1909) has malignant melanoma and Naevocarcinoma as two separate exact synonyms.

**Comment by alanruttenberg** [comment]
By separate I mean each in its own synonym axiom. Instead they are both in the same property value , separated by a semicolon

**Comment by elviram** [comment]
Hi Alan,
can you tell me which file you are looking at? I am attaching a Protege screenshot. Those synonyms are not separated by a semicolon.
<img width="723" alt="screen shot 2017-05-08 at 9 47 33 am" src="https://cloud.githubusercontent.com/assets/8419912/25807062/90be0a84-33d3-11e7-9aac-cac6b450610d.png">

**Comment by alanruttenberg** [comment]
Very strange. Can't replicate now, so closing. Sorry for the distraction.
