### ISSUE TITLE
Disease names seen in the wild

### ISSUE THREAD

**Issue by alanruttenberg** [DiseaseOntology/HumanDiseaseOntology#294]
Hi,

In mapping a data set: http://www.bio-bigdata.com/lnc2cancer/down.jsp,
I found a number of labels that were neither label nor exact synonym
in DO. Consider these as candidates for new terms or synonyms of
existing terms, as you see fit.

A table listing of the labels. Format is: name as seen, ICD code, ICD code, chosen DO term ;; guess what should be done or "unsure"

* "parotid cancer" "C07.9" "" "Parotid gland cancer" ;; exact
* "B-lymphoblastic leukemia" "" "M9811/3" "lymphoblastic leukemia"  ;;unsure
* "B cell acute lymphoblastic leukemia" "" "M9826/3" "lymphoblastic leukemia"  ;; unsure
* "serous ovarian cancer" "C56.9" "M8441/3" "ovarian cancer" ;; subclass 
* "esophageal squamous cell carcinoma" "C15" "M8070/3" "esophagus squamous cell carcinoma"  ;; subclass 
* "esophageal adenocarcinoma" "C15" "M8140/3" "adenocarcinoma"  ;; subclass
* "non-small cell lung cancer" "C34" "M8046/3" "non-small cell lung carcinoma"  ;; exact
* "urothelial carcinoma of the bladder" "C67" "M8120/3" "Transitional cell carcinoma"  ;; exact
* "hypopharyngeal squamous cell carcinoma" "C13" "M8070/3" "hypopharynx cancer"  ;; unsure
* "gastric cancer" "C16" "" "stomach cancer" ;; unsure

**Comment by elviram** [comment]
Hi Alan,

thank you for the list.
Added 'parotid cancer', 'gastric cancer' as exact synonyms. 'non-small cell lung cancer' was already listed.

Working our way through the rest of the list.

Best,
Elvira
