### ISSUE TITLE
DOID:0060810 OMIM xref

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#297]
The OMIM term OMIM:300220 has been moved to OMIM:300438. OMIM:300438 is not currently in DO. From looking at the OMIM record and the information in DO it appears that OMIM has combined typical and atypical HSD10 deficiency into a single record. I suggest removing the obsolete OMIM ID and reviewing the DO term to see if we should just have a single entry for  HSD10 deficiency.
Thanks,
Sue

**Comment by lschriml** [comment]
moved to google doc for review: 
https://docs.google.com/spreadsheets/d/1SUiFOMGeO3QJfnevpXAPFN90UmAaeoIHF7u0X5lvgc4/edit#gid=686803456
