### ISSUE TITLE
mucoepidermoid carcinoma 

### ISSUE THREAD

**Issue by simonjupp** [DiseaseOntology/HumanDiseaseOntology#298]
"mucoepidermoid carcinoma" is asserted to be a child of  "salivary gland carcinoma" whilst also being a parent of organ specific mucoepidermoid carcinomas like "lung mucoepidermoid carcinoma" (http://purl.obolibrary.org/obo/DOID_0050932).

**Comment by melodyswen** [comment]
This issue has been resolved - lung mucoepidermoid carcinoma is now a child of lung carcinoma, while mucoepidermoid carcinoma is a child of salivary gland carcinoma.
