### ISSUE TITLE
polycystic kidney disease

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#301]
MGI has a number of mouse models of 'polycystic kidney disease' where the mutation is recessive and the gene does not match one of the known autosomal dominant or recessive PKD human genes. Please consider adding a new term for:
polycystic kidney disease
def: A cystic kidney disease characterized by the uncontrolled growth of multiple cysts in the kidneys eventually resulting in kidney failure

ref: https://pkdcure.org/what-is-pkd/
ref:http://www.kidneyfund.org/kidney-disease/other-kidney-conditions/polycystic-kidney-disease.html?gclid=CjwKEAjw3pTJBRChgZ3e7s_YhAkSJAASG9Vr2f5p9_x82LwFZy5F8Vm6jeP1-yI9a1iHk69WfLIepBoCQ2_w_wcB

child of DOID:2975 cystic kidney disease

parent of: 
 	DOID:0110861
 	DOID:898

**Comment by lschriml** [comment]
To complete the work on this request:

DO is lacking a term for polycystic kidney disease.
I have added this term, 
  re-classified the current DO polycystic kidney disease subtypes,
  revised definitions and added logical definitions. 

Cheers,
Lynn
