### ISSUE TITLE
placement of DOID:5331

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#304]
The DO term testicular granulosa cell tumor (DOID:5331) is currently a child of granulosa cell tumor (DOID:2999) but this means that a testes specific tumor is showing up under female reproductive organ benign neoplasm (DOID:0060086). I think this is because granulosa cell tumor is asserted to be a child of both ovarian cancer and sec cord-gonadal stromal tumor.

Please review these relationships.

Thanks,
Sue

**Comment by mikelivstone** [comment]
Update: OLS now [shows](https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_5331) DOID:5331 as a child of "ovarian benign neoplasm."  Essentially the same problem as Sue noted above.

-Mike

**Comment by lschriml** [comment]
Thank you Mike !!
I will take a look and update DO.

Cheers,
Lynn

**Comment by lschriml** [comment]
Updated in DO.
