### ISSUE TITLE
new term: hypoplastic right heart syndrome

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#305]
Please consider adding the term:
hypoplastic right heart syndrome
def: A congenital heart disease characterized by underdevelopment of the structures on the right side of the heart commonly associated with atrial septal defect.
def. ref: url:https://www.ncbi.nlm.nih.gov/pubmed/28009100
xref: ORDO:98723
parent: congenital heart disease (DOID:1682)

**Comment by Apujar** [comment]
Hello,

The new term has created in DO. 

Cheers
anu
