### ISSUE TITLE
clean up synonyms for DOID:14679

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#306]
The synonyms for DOID:14679 are currently:
VACTERL/VATER association; vater ASSOCIATION; vater association (disorder); vater association [dup] (disorder); VATER syndrome 
I would suggest removing "vater ASSOCIATION" and "vater association [dup] (disorder)" as these do not appear to add any value and are mostly duplicates of "vater association (disorder)".

Thanks,
Sue

**Comment by lschriml** [comment]
Agreed, 
I work to remove these types of redundant synonyms.
Fixed.
