### ISSUE TITLE
Beta-thalassemia

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#309]
Consider adding child terms for beta-thalassemia: 
beta-thalassemia major - transfusion dependent, severe anemia, ORDO:231214 
beta-thalassemia intermedia -mild to moderate anemia,  ORDO:231222
beta-thalassemia minor - asymptomatic, carrier state

ref: url:https://www.ncbi.nlm.nih.gov/pubmed/10395635
mouse model: url:https://www.ncbi.nlm.nih.gov/pubmed/19258591

**Comment by lschriml** [comment]
**beta thalassemia**
        - https://ghr.nlm.nih.gov/condition/beta-thalassemia
         https://www.ncbi.nlm.nih.gov/books/NBK1426/
         https://www.ncbi.nlm.nih.gov/pubmed/10395635

ICD10CM:D56.1
NCI:C34375
OMIM:613985
GARD:871

MESH:D017086. - beta thalasimia, includes all types of beta thalassemia
            [skos narrower match]

ORDO:848
       
       UMLS_CUI:C0005283
       ICD9CM:282.44. --> no longer in ICD19CM, 282.49 is 'other thalassemia' 
        
        

**autosomal dominant  beta thalassemia**
        - Very rarely, the inheritance of beta-thalassemia may be dominant. In this case, a person has only one mutated HBB gene, but has signs and symptoms of beta-thalassemia major or beta-thalassemia intermedia
     xref: OMIM:603902
             ORDO:231226

        Dominant beta-thalassemia is a form of beta-thalassemia (see this term) resulting in moderate to severe anemia.
 In a small percentage of families, the HBB gene mutation is inherited in an autosomal dominant manner. In these cases, one copy of the altered gene in each cell is sufficient to cause the signs and symptoms of beta thalassemia.
 

**beta-thalassemia major** - transfusion dependent, severe anemia
      xref: ORDO:231214
   - AR inheritance
         https://www.ncbi.nlm.nih.gov/pubmed/19258591

        thalassemia major (also known as Cooley's anemia)
       - signs and symptoms of thalassemia major appear within the first 2 years of life. 
       - Children develop life-threatening anemia. They do not gain weight and grow at the expected rate (failure to thrive) and may develop yellowing of the skin and whites of the eyes (jaundice). Affected individuals may have an enlarged spleen, liver, and heart, and their bones may be misshapen.

Thalassemia major (also called Cooley's anemia) - the more severe form, causing severe anemia and enlarged liver and spleen (hepatosplenomegaly). This form usually becomes apparent before 2 years of age. If not treated, it causes failure to thrive and a shortened life expectancy. Treatment involves regular transfusions and chelation therapy to reduce iron overload. Treatment allows for normal growth and development. Bone marrow transplantation or cord blood transplantation may eliminate the need for regular treatment. 

   xref:  NCI:C129699


       -https://pubmed.ncbi.nlm.nih.gov/12480689/
       - https://ghr.nlm.nih.gov/condition/beta-thalassemia

**beta-thalassemia intermedia** -mild to moderate anemia, 

    xrefs: 
          ORDO:231222


       - https://ghr.nlm.nih.gov/condition/beta-thalassemia
   - AR inheritance

     - Thalassemia intermedia is milder than thalassemia major. The signs and symptoms of thalassemia intermedia appear in early childhood or later in life. Affected individuals have mild to moderate anemia and may also have slow growth and bone abnormalities.

      Thalassemia intermedia - the less severe form, becoming apparent later and causing milder anemia that does not require regular blood transfusions. People with this form are also at risk for iron overload.

**Delta-Beta Thalassemia**
NCI:C172823
A form of beta thalassemia characterized by decreased or absent synthesis of both the delta- and beta-globin chains, which leads to a compensatory increase in fetal gamma-chain synthesis. This disorder results in a microcytic anemia that is clinically mild.

**thalassemia minor** 
  xref: 
OMIM:187550

People who have only one HBB gene mutation (carriers) typically are said to have thalassemia minor (or trait) and usually do not have symptoms, but may have some symptoms of anemia.[1][2][3] In some cases, anemia is worsened if there is a nutritional deficiency such as with iron, folic acid or vitamin B12.[4]

Sometimes, however, people with only one HBB gene mutation in each cell develop mild anemia. These mildly affected people are said to have thalassemia minor.

https://ghr.nlm.nih.gov/condition/beta-thalassemia#inheritance

**Comment by lschriml** [comment]
added to DO. 
Lynn
