### ISSUE TITLE
chromosome deletion syndromes

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#310]
I have a paper dealing with a model for partial monosomy 21. It is not clear which precise chromosome 21 deletion syndrome this is modeling based on OMIM and Orphanet entries. Looking at the children of chromosomal deletion syndrome (DOID:0060388) it seems like it would be helpful to add children of chromosome deletion syndrome for each of the human chromosomes. This would both help to group the existing children of the term and provide a place for these less specific models that is more precise than chromosome deletion syndrome. 
The mouse model reference is url:https://www.ncbi.nlm.nih.gov/pubmed/20512340

**Comment by lschriml** [comment]
Done
