### ISSUE TITLE
new OMIM terms and changes for 6/12/17

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#311]
OMIM 611705 was Myopathy, Early-Onset, with Fatal Cardiomyopathy; EOMFC this is now Salih Myopathy; SALMY; this appears to be just a preferred name change, the disease described does not appear to have changed and the old name is a synonym for the disease

New terms:
OMIM:617516	Stankiewicz-Isidor Syndrome; STISS                               	      
OMIM:617514	Immunodeficiency 52; IMD52                                       	       
OMIM:617519	Myopathy, Congenital, with Neuropathy and Deafness; CMND         	        
OMIM:617520	Microcephaly 18, Primary, Autosomal Dominant; MCPH18

**Comment by lschriml** [comment]
moved to google doc for review: 
https://docs.google.com/spreadsheets/d/1SUiFOMGeO3QJfnevpXAPFN90UmAaeoIHF7u0X5lvgc4/edit#gid=686803456
