### ISSUE TITLE
new term - Reifenstein syndrome

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#318]
Hello,
I'd like to request that Reifenstein syndrome (http://www.omim.org/entry/312300) be added as a new term.
Thanks,
Cara

**Comment by lschriml** [comment]
Need to split, one DOID for partial one for complete

**Comment by sbello** [comment]
added to OMIM spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
parent term: disorders of sexual development (DOID:1923)

**androgen insensitivity syndrome (DOID:4674)**

     OMIM:300068
     https://www.ncbi.nlm.nih.gov/books/NBK1429/ 
            https://ghr.nlm.nih.gov/condition/androgen-insensitivity-syndrome
     ORDO:754
     MESH:D013734. [skos narrow] DO splits the subtypes, MESH does not

- Androgen insensitivity syndrome is a condition that affects sexual development before birth and during puberty. People with this condition are genetically male, with one X chromosome and one Y chromosome in each cell. Because their bodies are unable to respond to certain male sex hormones (called androgens), they may have mostly female external sex characteristics or signs of both male and female sexual development.
  
    GARD:5803
ICD10CM:E34.5
  NCI:C27226
  UMLS_CUI:C0039585
ICD9CM:259.51

 **Complete androgen insensitivity syndrome**
    - ORDO:99429.  
       NCI:C120191
        UMLS_CUI:C0936016
   ICD10CM:ICD10CM:E34.51
ICD9CM:259.51

- Complete androgen insensitivity syndrome occurs when the body cannot use androgens at all. People with this form of the condition have the external sex characteristics of females, but do not have a uterus and therefore do not menstruate and are unable to conceive a child (infertile).

- Affected individuals have male internal sex organs (testes) that are undescended,


 **Partial androgen insensitivity syndrome** (orphanet)
Reifenstein syndrome 
  in OMIM: partial androgen insensitivity

             https://ghr.nlm.nih.gov/condition/androgen-insensitivity-syndrome
- The partial and mild forms of androgen insensitivity syndrome result when the body's tissues are partially sensitive to the effects of androgens. People with partial androgen insensitivity (also called Reifenstein syndrome) can have genitalia that look typically female, genitalia that have both male and female characteristics, or genitalia that look typically male




A disorder of sex development (DSD) distinct from complete AIS (CAIS) characterized by the presence of abnormal genital development in a 46,XY individual with normal testis development and partial responsiveness to age-appropriate levels of androgens.

GARD:5692
