### ISSUE TITLE
Oligomeganephronia

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#321]
Please consider adding the term:
oligomeganephronia
syn: Oligomeganephronic renal hypoplasia
def: A kidney disease characterized by bilateral reduced kidney size with a marked decrease in the total number of nephrons
ref: url:https://www.ncbi.nlm.nih.gov/pubmed/9794553
xref: ORDO:2260; ICD10CM:Q60.4; GARD:4066
child of: kidney disease

**Comment by sbello** [comment]
transferred to MGI DO ROBOT template

**Comment by lschriml** [comment]
DONE
