### ISSUE TITLE
umlaut in DOID:4258

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#323]
There is an umlaut in the disease term label for DOID:4258 "Weissenbacher-Zweymüller syndrome" This is causing issues in the MGI web display. Would you please remove the umlaut.
Thanks,
Sue

**Comment by lschriml** [comment]
Fixed in the diid-edit.owl file, this fix will be public in our next DO release. 
Double checked, no other umlauts in DO.
