### ISSUE TITLE
New term request: "Relapsed/Refractory Diffuse Large B-Cell Lymphoma"

### ISSUE THREAD

**Issue by mikelivstone** [DiseaseOntology/HumanDiseaseOntology#330]
Citation: 489 [studies](https://clinicaltrials.gov/ct2/results?cond=Relapsed%2FRefractory+Diffuse+Large+B-Cell+Lymphoma&term=&cntry1=&state1=&SearchAll=Search+all+studies&recrs=) at clinicaltrials.gov

**Comment by lschriml** [comment]
Thank you for the term request. I will review and add to DO.

Cheers,
Lynn

**Comment by lschriml** [comment]
done.
