### ISSUE TITLE
New MGI terms for week of 6/29 and 7/3

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#332]
Added Prinzmetal angina to MGI DO ROBOT template. But I'm uncertain about the correct parent for this term. I'm trying to decide between coronary artery disease (DOID:3393) and its child coronary artery vasospasm (DOID:11840). The child term lacks a definition so it is unclear if this would be a better parent. The MESH xref is not a parent to the MESH term for Prinzmetal angina (MESH:D000788) so I'm inclined to go with coronary artery disease. 
Also the definition of coronary artery disease 'plaque building up along the inner walls' but it is not clear that Prinzmetal angina involves plaque build up. It may be that the definition of coronary artery disease is too narrow as it currently stands.

**Comment by sbello** [comment]
Link to MGI DO ROBOT template https://docs.google.com/spreadsheets/d/1m_Skq97c4HwuRlClYe30ZuZqF6rboCl7RbigOFLS70U/edit?usp=sharing

**Comment by sbello** [comment]
Added multicentric Castleman disease to the ROBOT template

**Comment by sbello** [comment]
added congenital mirror movement disorder to the ROBOT template

**Comment by sbello** [comment]
Please add synonyms to DOID:0060282
persistent fetal vasculature syndrome
PFVS
see url:https://www.ncbi.nlm.nih.gov/pubmed/22880002 for a reference

**Comment by lschriml** [comment]
DONE
