### ISSUE TITLE
New OMIM terms 7/2/17

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#335]
New OMIM terms for this week:
OMIM:617532	Intellectual Developmental Disorder with Neuropsychiatric Features        
OMIM:617537	Rahman Syndrome; RMNS

**Comment by lschriml** [comment]
moved to google doc for review: 
https://docs.google.com/spreadsheets/d/1SUiFOMGeO3QJfnevpXAPFN90UmAaeoIHF7u0X5lvgc4/edit#gid=686803456
