### ISSUE TITLE
Duplicate? "aspiration pneumonia" and "aspiration pneumonitis"

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#336]
These items have different descriptions but all the same xrefs:
http://www.disease-ontology.org/?id=DOID:3240
http://www.disease-ontology.org/?id=DOID:0050152

**Comment by lschriml** [comment]
Thank you for finding this. 
the pneumonitis is an inflammation, the pneumonia (bacterial infection).

Two distinct diseases.
