### ISSUE TITLE
ghrelinoma

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#340]
Hi Lynn,
I have a paper https://www.ncbi.nlm.nih.gov/pubmed/19602582 describing a mouse model of ghrelinoma. I'm unable to fit this in the DO structure as they are using this as a model of ghrelinomas in general and this includes both malignant and non-malignant tumors. I'm uncertain how we want to handle this. Ideally I'd want to have a cell type tumor class that was independent of malignancy.
See also:
https://www.ncbi.nlm.nih.gov/pubmed/15292299
http://www.endocrine-abstracts.org/ea/0016/ea0016P340.htm
Thanks,
Sue

**Comment by lschriml** [comment]
Latest paper: https://www.ncbi.nlm.nih.gov/books/NBK279169/

Still keeping this ticket on hold, as there is not yet sufficient data to make a DO disease term.
Lynn

**Comment by lschriml** [comment]
In 2020 literature, referred to as a 'theoretical syndrome' 
  https://www.ncbi.nlm.nih.gov/books/NBK279169/

Closing this ticket for now. Will reopen when new information becomes available.
Lynn
