### ISSUE TITLE
Fanconi anemia OMIM xref

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#352]
The omim xref shouldn't start with PS?
OMIM:PS227650
http://purl.obolibrary.org/obo/DOID_13636

Also, it looks like it specifically refers to complementation group A

**Comment by sbello** [comment]
The xref is for the OMIM phenotypic series. See https://omim.org/phenotypicSeries/PS227650

**Comment by lschriml** [comment]
Some of the OMIM xrefs do start with PS, we associate these OMIM ID's to the parent term, when we have a number of child terms.
