### ISSUE TITLE
New OMIM terms for 7/17/17

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#355]
New OMIM terms this week:

OMIM:617562	Meckel Syndrome 13; MKS13                                        	        
OMIM:617563	Orofaciodigital Syndrome Xvi; OFD16                     
OMIM:617561	Cohen-Gibson Syndrome; COGIS                                   
OMIM:617564	Meier-Gorlin Syndrome 8; MGORS8                              
OMIM:617565	Perrault Syndrome 6; PRLTS6                                      	      
OMIM:601188	Suppression of Tumorigenicity 12; ST12                        
OMIM:617574	Ichthyosis, Congenital, Autosomal Recessive 13; ARCI13           	       
OMIM:617571	Ichthyosis, Congenital, Autosomal Recessive 14; ARCI14           	        
OMIM:617572	Exudative Vitreoretinopathy 7; EVR7

**Comment by lschriml** [comment]
moved to google doc for review: 
https://docs.google.com/spreadsheets/d/1SUiFOMGeO3QJfnevpXAPFN90UmAaeoIHF7u0X5lvgc4/edit#gid=686803456
