### ISSUE TITLE
hypochondroplasia cross-references

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#357]
Please add the cross-references:
ORDO:429 - Hypochondroplasia
OMIM:146000 - Hypochondroplasia 
UMLS_CUI:C0410529
ICD10CM:Q77.4
to the disease term hypochondroplasia (DOID:0080041)

Thanks,
Sue

**Comment by cmungall** [comment]
kboom results:

 * __Pr(G)__=0.6987917989276029 CONFIDENCE=23.88095238095238 Success:true
 * __SIZE__=4 (4 new axioms) 
[img](target/img-MESH_C562937.png)
 * MEMBER: MESH_C562937 Hypochondroplasia
 * MEMBER: DOID_0080041 hypochondroplasia
 * MEMBER: Orphanet_429 Hypochondroplasia
 * MEMBER: OMIM_146000 Hypochondroplasia
 * DOID_0080041 hypochondroplasia EquivalentTo MESH_C562937 Hypochondroplasia Pr= 0.6875
 * MESH_C562937 Hypochondroplasia EquivalentTo OMIM_146000 Hypochondroplasia Pr= 0.75
 * OMIM_146000 Hypochondroplasia EquivalentTo Orphanet_429 Hypochondroplasia Pr= 0.7142857142857143
 * DOID_0080041 hypochondroplasia EquivalentTo Orphanet_429 Hypochondroplasia Pr= 0.75

These high-confidence transitive equivalence assignments could easily be incorporated into the DO

**Comment by lschriml** [comment]
Thank you for the updates, the DO record has been updated. 
Cheers,
Lynn
