### ISSUE TITLE
new MGI terms on ROBOT spreadsheet

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#358]
Added:
camptodactyly-tall stature-scoliosis-hearing loss syndrome
Crouzon syndrome-acanthosis nigricans syndrome
epidermal nevus

to the ROBOT spreadsheet

**Comment by sbello** [comment]
Added OMIM:PS252150 (MOCOD) and child terms to ROBOT spreadsheet

**Comment by sbello** [comment]
added Dyggve-Melchior-Clausen disease to the ROBOT spreadsheet

**Comment by sbello** [comment]
added dopa-responsive dystonia due to sepiapterin reductase deficiency to the ROBOT spreadsheet

**Comment by sbello** [comment]
added subcortical band heterotopia to the ROBOT spreadsheet

**Comment by sbello** [comment]
https://docs.google.com/spreadsheets/d/1m_Skq97c4HwuRlClYe30ZuZqF6rboCl7RbigOFLS70U/edit?usp=sharing

**Comment by lschriml** [comment]
These terms have been reviewed, curated, added to DO file via ROBOT. 
Closing this ticket.
