### ISSUE TITLE
New Term Request: Marinesco-Sjogren syndrome (MSS)

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#359]
Hi,

I would like to request this term: Marinesco-Sjogren syndrome (MSS). OMIM: 248800. Thanks

Sridhar

**Comment by lschriml** [comment]
Hello Sridhar,
Thank you for your term request. I will review this term for DO.
Regards,
Lynn

**Comment by lschriml** [comment]
done
