### ISSUE TITLE
New OMIM terms and changes for week of 7/24/17

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#360]
OMIM:184840 was Stickler Syndrome, Type III; STL3 changed to Otospondylomegaepiphyseal Dysplasia, Autosomal Dominant; OSMEDA  and made part of a new phenotypic series. This is currently mapped to DOID:0080046.

OMIM:215150 was Otospondylomegaepiphyseal Dysplasia; OSMED changed to Otospondylomegaepiphyseal Dysplasia, Autosomal Recessive; OSMEDB and made part of a new series. This is currently mapped to DOID:0080026.

New terms:
OMIM:617575	Nephrotic Syndrome 14; NPHS14                                          
OMIM:617577	Ciliary Dyskinesia, Primary, 37; CILD37                          	       
OMIM:617576	Spermatogenic Failure 18; SPGF18

**Comment by lschriml** [comment]
moved to google doc for review: 
https://docs.google.com/spreadsheets/d/1SUiFOMGeO3QJfnevpXAPFN90UmAaeoIHF7u0X5lvgc4/edit#gid=686803456
