### ISSUE TITLE
New OMIM terms and changes for week of 7/31/17

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#361]
Obsolete - OMIM:216411 - We spoke with Ada and they reviewed the Cockayne syndrome entries resulting this entry being obsoleted. 

New terms:
OMIM:617584	Spinocerebellar Ataxia, Autosomal Recessive 25; SCAR25           	       
OMIM:617585	Immunodeficiency 53; IMD53                                                                                                     
OMIM:617598	Mosaic Variegated Aneuploidy Syndrome 3; MVA3                    	       
OMIM:617596	Maleylacetoacetate Isomerase Deficiency; MAAID                    
OMIM:617595	Birk-Landau-Perez Syndrome; BILAPES                                     
OMIM:617593	Spermatogenic Failure 20; SPGF20                                
OMIM:617592	Spermatogenic Failure 19; SPGF19

**Comment by lschriml** [comment]
Thank you Sue,
I will get this updated when I am back in the office.
Much appreciated,
Lynn

**Comment by lschriml** [comment]
moved to google doc for review:
https://docs.google.com/spreadsheets/d/1SUiFOMGeO3QJfnevpXAPFN90UmAaeoIHF7u0X5lvgc4/edit#gid=686803456
