### ISSUE TITLE
New term request: "RELAPSED/REFRACTORY ACUTE MYELOID LEUKEMIA"

### ISSUE THREAD

**Issue by mikelivstone** [DiseaseOntology/HumanDiseaseOntology#362]
synonym: "R/R ACUTE MYELOID LEUKEMIA"
synonym: "R/R AML"
synonym: "relapsed or refractory acute myeloid leukemia"

reference: https://www.fda.gov/newsevents/newsroom/pressannouncements/ucm569421.htm

**Comment by lschriml** [comment]
Thank you Mike !!
I will take a look.
Much appreciated,
Lynn

**Comment by lschriml** [comment]
Closing this ticket for now, as relapsed does not define a new disease.
