### ISSUE TITLE
tumor of exocrine pancreas: does this include benign tumors?

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#367]
```
id: DOID:1795
name: tumor of exocrine pancreas
namespace: disease_ontology
alt_id: DOID:1794
synonym: "malignant neoplasm of the Exocrine pancreas" EXACT [NCI2004_11_17:C7430]
synonym: "malignant tumor of exocrine pancreas" EXACT []
synonym: "malignant tumor of exocrine pancreas (disorder)" EXACT [SNOMEDCT_2005_07_31:255088001]
synonym: "pancreatic Exocrine tumor" EXACT [NCI2004_11_17:C4445]
synonym: "tumor of exocrine pancreas (disorder)" EXACT [SNOMEDCT_2005_07_31:254604005]
***xref: NCI:C4445
xref: NCI:C7430
xref: SNOMEDCT_US_2016_03_01:254604005
xref: SNOMEDCT_US_2016_03_01:255088001
xref: UMLS_CUI:C0345920
xref: UMLS_CUI:C0346648
is_a: DOID:1793  ! pancreatic cancer
```

no def

the label leads one to believe this could include benign tumors. And the xref to NCI:C4445 which in NCIT includes benign neoplasms confirms this.

However, there is exact syns to "malignant..." and the graph placement under cancer forces an interpretation that excludes benign.

I recommend DO makes a more explicit commitment here about inclusion or exclusion of benign, adds a def, and selects whichever of the two NCIT xrefs to whatever is equivalent.

A broader recommendation would be to scrap the cancer subset in DO and start with NCIT

**Comment by cmungall** [comment]
For the kboom analysis that lead to this ticket see: https://github.com/monarch-initiative/monarch-disease-ontology/issues/283#issuecomment-321069412

**Comment by lschriml** [comment]
benign term added to DO, xrefs updated, definitions added.
