### ISSUE TITLE
Remove xref to NCIT on DOID:2426 gangliocytoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [DiseaseOntology/HumanDiseaseOntology#368]
Based on some analysis in MonDO, we believe that NCIT_C6934 gangliocytoma is a sibling of NCIT_C0349 ganglioneuroma.

DO currently xrefs NCIT_C0349 (and UMLS:C0017075), and I'd like to ask that these xrefs be removed.

See the kboom analysis that led to this ticket: https://github.com/monarch-initiative/monarch-disease-ontology/issues/314

cc @cmungall

**Comment by lschriml** [comment]
Thank you for pointing out the updates for the xrefs for these two DOIDs.
I will update them as follows. 

Cheers,
Lynn


gangliocytoma
    DOID:2426
    is_a cell type cancer

--> we will remove this NCI:C3049
         Ganglioneuroma
        A benign neuroblastic tumor of the sympathetic nervous system that occurs in childhood

NCI:C6934
Gangliocytoma
A well differentiated, slow growing neuroepithelial neoplasm composed of neoplastic, mature ganglion cells.

https://rarediseases.info.nih.gov/diseases/10638/gangliocytoma
Gangliocytoma is a rare type of central nervous system (CNS) tumor made up of mature neurons.

https://radiopaedia.org/articles/gangliocytoma
Gangliocytomas are rare indolent CNS tumours (WHO grade I), primarily encountered in children, and frequently discovered as the cause of epilepsy. They differ from gangliogliomas by the absence of neoplastic glial cells, although both tumours are defined by the presence of displaced ganglion cells (large mature neurones that show cytological or architectural abnormalities).


ganglioneuroma
DOID:4817
is_a autonomic nervous system neoplasm

--> We current have this NCI ID linked to this DOID.
NCI:C42065
      Mature Ganglioneuroma
     A ganglioneuroma characterized by the presence of mature ganglion cells and a mature Schwannian stroma.

--> This mapping will be updated to C3049,  Ganglioneuroma
--> parentage will be updated, based on the (below) NCI definition

A benign neuroblastic tumor of the sympathetic nervous system that occurs in childhood. Ganglioneuroma typically arises from the sympathetic trunk in the mediastinum. Histologic features include spindle cell proliferation (resembling a neurofibroma) and the presence of large ganglion cells. Common presenting features include a palpable abdominal mass, hepatomegaly, and a thoracic mass detected on routine chest X-ray.

https://en.wikipedia.org/wiki/Ganglioneuroma

**Comment by lschriml** [comment]
terms and parentage updated.
Cheers,
Lynn
