### ISSUE TITLE
Cockayne syndrome and COFS

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#369]
Cockayne syndrome
There appear to be 2 competing classification systems for Cockayne syndrome - CSA/CSB are referred to as "complementation groups" and CS1/CS2/CS3 appear to vary based on phenotypic severity. See PMID:27507608 OMIM had records for CSA, CSB and CS3. Orphanet has CS1, CS2, CS3. OMIM has since removed the CS3 record.

Orphanet and OMIM split COFS from Cockayne syndrome although Orphanet calls this a "prenatal extreme form of Cockayne syndrome" GHR states " Cockayne syndrome type II is also known as cerebro-oculo-facio-skeletal (COFS) syndrome, and while some researchers consider it to be a separate but similar condition, others classify it as part of the Cockayne syndrome disease spectrum." https://ghr.nlm.nih.gov/condition/cockayne-syndrome GeneReviews states "CS type II, a more severe form with symptoms present at birth; this form overlaps with cerebrooculofacioskeletal syndrome (COFS) or Pena-Shokeir syndrome type II; " Orphanet has COFS as a child of Cockayne This 2013 review https://www.ncbi.nlm.nih.gov/pubmed/23428416 refers to COFS as overlapping with Cockayne but does limit Cockayne to just ERCC8 and EFCC6. 

Discussion with Ada and Joanna from OMIM: CS3 is gone from OMIM, Ada stated that the split between Cockayne and COFS is based on when symptoms develop. Cockayne is postnatal, COFS is prenatal/neonatal. She would map the phenotypic series in ORDO to the OMIM records this way: CSA= CS1 or CS3; CSB= CS1 or CS3; CS2=COFS. So CSA and CSB are both postnatal and may be more (CS1) or less severe (CS3). COFS is neonatal and is severe (CS2?). Orphanet has separate entries for CS2 and COFS and refers to COFS as "the prenatal extreme form of Cockayne syndrome".

DO currently has a term for Cockayne syndrome (DOID:2962) with xrefs to OMIM and ORDO:
OMIM:133540
OMIM:216400
OMIM:216411 (obsolete in OMIM)

ORDO:191
ORDO:90321
ORDO:90322
ORDO:90324

DO has no entry for COFS syndrome (ORDO:1466, OMIM:214150  278780  610756  610758  616570). If we want to have COFS under Cockayne syndrome, in keeping with this being an extreme neonatal form of Cockayne we would need to modify Cockayne in DO as this is currently defined as being caused by either ERCC8 and ERCC6 and COFS is caused by the ERCC1, ERCC2, ERCC5 and ERCC6 genes (see https://www.omim.org/phenotypicSeries/PS214150)

**Comment by lschriml** [comment]
Thank you Sue for this thorough review. 

Looking over these resources and the notes above:
I will update Cockayne syndrome definition and refs,
and then create some new DOIDs for the subtypes. 

Cheers,
Lynn

DOID:2962 (Cockayne syndrome) (post natal)
                    ORPHA:191 
type I
           Cockayne syndrome A 
           OMIM:216400, GARD:1415    
           CSA, due to a mutation on ERCC8 on chromosome 5q12-q31
    
type II
           cerebro-oculo-facio-skeletal (COFS) syndrome  (prenatal/neonatal)
          (OMIM:PS214150, GARD:1420)
      COFS1 (OMIM:214150)
      COFS2 (OMIM:616570)
      COFS3 (OMIM:610756)
      COFS4 (OMIM:610758)

type III  
            Cockayne syndrome B
            (OMIM:133540)
            CSB, due to a mutation on ERCC6 on chromosome 10q11. CSB

**Comment by lschriml** [comment]
added to DO.
