### ISSUE TITLE
MERS Middle East Respiratory Syndrome

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#370]
Please add MERS-CoV to the DO

**Comment by lschriml** [comment]
https://www.cdc.gov/coronavirus/mers/index.html
http://www.who.int/mediacentre/factsheets/mers-cov/en/Middle East respiratory syndrome (MERS) is a viral respiratory disease caused by a novel coronavirus (Middle East respiratory syndrome coronavirus.

Typical MERS symptoms include fever, cough and shortness of breath. 

https://en.wikipedia.org/wiki/Middle_East_respiratory_syndrome

Middle East respiratory syndrome (MERS), also known as camel flu,[1] is a viral respiratory infection caused by the MERS-coronavirus (MERS-CoV).[2] Symptoms may range from mild to severe.[3] They include fever, cough, diarrhea, and shortness of breath.[2] 

https://www.ncbi.nlm.nih.gov/pubmed/26049252

Middle East respiratory syndrome (MERS) is a highly lethal respiratory disease caused by a novel single-stranded, positive-sense RNA betacoronavirus (MERS-CoV). Dromedary camels, hosts for MERS-CoV, are implicated in direct or indirect transmission to human beings, although the exact mode of transmission is unknown

**Comment by sbello** [comment]
Hi Lynn,
Could we try to get this added soon? We have a few mouse models we'd like to annotate to this.
https://www.cdc.gov/coronavirus/mers/about/index.html|https://pubmed.ncbi.nlm.nih.gov/23891402  
Thanks,
Sue

**Comment by lschriml** [comment]
Yes !!

**Comment by lschriml** [comment]
Added, @melodyswen - let's do another release before the website is updated next week.
To make this public. 

Cheers,
Lynn
