### ISSUE TITLE
New cancer-related terms

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#374]
I'm looking for terms for the following concepts. Any help would be appreciated. I can provide references for any of the terms if necessary. Thank you in advance.

- Erdheim-Chester histiocytosis: I think is http://purl.obolibrary.org/obo/DOID_4329? Add an alias if so.
- Myelodisplasic proliferative syndrome: I think: http://purl.obolibrary.org/obo/DOID_2226 ?
- Myelodisplasic syndrome: Never mind, it was spelled wrong! http://purl.obolibrary.org/obo/DOID_0050908
- Giant cell astrocytoma: http://purl.obolibrary.org/obo/DOID_5077 ?
- Hyper eosinophilic advanced snydrome: http://purl.obolibrary.org/obo/DOID_999?
- Eosinophilic chronic leukemia

**Comment by lschriml** [comment]
Hello Greg,
 Erhheim-Chester histiocytosis =   Erhheim-Chester disease

Myelodisplasic proliferative syndrome: =DOID:4972, myelodysplastic/myeloproliferative neoplasm

Giant cell astrocytoma -- where is this found ? 
          --> the only giant cell astrocytoma I know of is: DOID:5077, subependymal giant cell astrocytoma

I think this an advanced form of hypereosinophilic syndrome
      : Hyper eosinophilic advanced syndrome:, Did you find information that the community considers this a new disease ? I only found it described as a version of HES. 

--> We need to add: Eosinophilic chronic leukemia, to the DO, as a child of chronic leukemia
   Ref: 
https://ghr.nlm.nih.gov/condition/pdgfra-associated-chronic-eosinophilic-leukemia

Cheers,
Lynn

**Comment by stuppie** [comment]
Thanks Lynn!

Giant cell astrocytoma: Looks like the [FDA label](https://www.accessdata.fda.gov/drugsatfda_docs/label/2013/022334s022lbl.pdf) says "subependymal giant cell astrocytoma", so I will stick with that.

**Hyper eosinophilic advanced snydrome**: [This](https://www.ncbi.nlm.nih.gov/pubmed/12660384) is the reference, which only says "hypereosinophilic syndrome" and not "Hyper eosinophilic advanced syndrome", so I will stick with [hypereosinophilic syndrome](http://purl.obolibrary.org/obo/DOID_999)

**Comment by melodyswen** [comment]
DOID:0080367 has been added, child of chronic leukemia, added linked database cross reference. All issues resolved
