### ISSUE TITLE
"Pancreatic cancer" child terms

### ISSUE THREAD

**Issue by mikelivstone** [DiseaseOntology/HumanDiseaseOntology#376]
The following terms from ICD10 should be children of "pancreatic cancer" (DOID_1793):

ICD10 code | ICD10 diagnosis
-- | --
C25.0 | Malignant neoplasm of head of pancreas
C25.1 | Malignant neoplasm of body of pancreas
C25.2 | Malignant neoplasm of tail of pancreas
C25.3 | Malignant neoplasm of pancreatic duct

The first three terms are currently xrefs to DOID_1973.  Not sure about C25.3.

**Comment by lschriml** [comment]
Thank you Mike !!

**Comment by melodyswen** [comment]
Needs review: currently, C25.0, C25.1, C25.2 are synonyms of DOID:1793 pancreatic cancer

**Comment by lschriml** [comment]
The requested terms are part of the pancreas. They do not represent distinct diseases.
