### ISSUE TITLE
New Term Request: HYPERMANGANESEMIA WITH DYSTONIA 1

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#397]
Hi,

I would like to request this term: hypermanganesemia with dystonia-1 (HMNDYT1). OMIM: 613280. Thanks

Sridhar

**Comment by lschriml** [comment]
Thank you Sridhar,
I will take a look and review.

Cheers,
Lynn

**Comment by sbello** [comment]
Added to OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
Added to DO. 
Lynn
