### ISSUE TITLE
New term request: colorectal carcinoma

### ISSUE THREAD

**Issue by mikelivstone** [DiseaseOntology/HumanDiseaseOntology#399]
Please create "colorectal carcinoma" as a parent term of "colorectal adenocarcinoma," the distinction being that "adeno" specifies a glandular origin.

Ref: EFO_1001951

**Comment by lschriml** [comment]
Hello Mike,
Can do.
Cheers,
Lynn

**Comment by lschriml** [comment]
Added, done. 
Cheers,
Lynn
