### ISSUE TITLE
schwannoma of twelfth cranial nerve

### ISSUE THREAD

**Issue by alanruttenberg** [DiseaseOntology/HumanDiseaseOntology#406]
I submit reports like this when I'm browsing and happen to encounter something that looks wrong. 

In this case it looks like the following two axioms in the definition are inconsistent:

disease and ('located in' some 'hypoglossal nerve')
disease and ('located in' some 'glossopharyngeal nerve')

These are different nerves. glossopharyngeal nerve is the 9th cranial nerve, so I guess that's the one to remove.

**Comment by lschriml** [comment]
Thank you Alan !!

**Comment by lschriml** [comment]
The DO record has been updated, thank you Alan !! 
Cheers,
Lynn
