### ISSUE TITLE
New term request: Sweeney-Cox Syndrome; OMIM 617746

### ISSUE THREAD

**Issue by rankishore** [DiseaseOntology/HumanDiseaseOntology#408]
This paper describes this new clinical entity: Sweeney-Cox Syndrome, which has actually made it's way into OMIM, 617746.  Reference: PMID: 28369379, Hum Mol Genet. 2017 Jun 1;26(11):2118-2132. doi: 10.1093/hmg/ddx107.

Thanks!
Ranjana Kishore

**Comment by lschriml** [comment]
Thank you Ranjana !!

**Comment by sbello** [comment]
Added to OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
Added to DO.
