### ISSUE TITLE
New Term Request: McKusick-Kaufman syndrome

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#409]
Hi,

I would like to request this term: McKusick-Kaufman syndrome (MKKS). OMIM: 236700. Thanks

Sridhar

**Comment by lschriml** [comment]
Thank you Sridhar !!

**Comment by sbello** [comment]
On OMIM spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111255
