### ISSUE TITLE
Robinow syndrome xrefs

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#410]
I believe there are duplicate external IDs on the Robinow syndrome subclasses

http://purl.obolibrary.org/obo/DOID_0060254
has links to orphanet, but so do all of the children. The xref should only be on the parent.

And the same with ICD10 on the parent

Thanks

**Comment by lschriml** [comment]
Thank you Greg !!

**Comment by lschriml** [comment]
All fixed Greg.
And added OMIM:PS268310 to the parent term.

Cheers,
Lynn
