### ISSUE TITLE
"Grn-related frontotemporal lobar degeneration with Tdp43 inclusions" xref

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#415]
http://www.disease-ontology.org/?id=DOID:0060672 
ordo xref (http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=282 (frontotemporal dementia)) is already on 
http://www.disease-ontology.org/?id=DOID:9255 (frontotemporal dementia)

**Comment by melodyswen** [comment]
Hi!

Thanks for pointing this out - we'll review and get back to you!

Sorry for the late reply!
Cheers,
Melody

**Comment by lschriml** [comment]
the extra xref has been removed.
