### ISSUE TITLE
term requests, Julien Mariethoz

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#419]
Transferring sourceforge requests to GitHub

(1) Lewis lung carcinoma https://en.wikipedia.org/wiki/Lewis_lung_carcinoma
[feature-requests:#134] New rerm request

(2) [feature-requests:#135] New term request : Tn Polyagglutinability Syndrome
Tn Polyagglutinability Syndrome https://www.omim.org/entry/300622

(3) [feature-requests:#136] New term request : Erythroleukemia
Erythroleukemia redirects to https://en.wikipedia.org/wiki/Acute_erythroid_leukemia

**Comment by sbello** [comment]
300622 on OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
wotking on OMIM term

**Comment by sbello** [comment]
OMIM term has been added to DO

**Comment by lschriml** [comment]
Reviewed ticket: Outstanding new terms to add: 
Lewis lung carcinoma https://en.wikipedia.org/wiki/Lewis_lung_carcinoma
[feature-requests:#134] New rerm request

[feature-requests:#136] New term request : Erythroleukemia
Erythroleukemia redirects to https://en.wikipedia.org/wiki/Acute_erythroid_leukemia

**Comment by lschriml** [comment]
Lewis lung carcinoma is a cell line established from the lung of a C57BL mouse bearing a tumor resulting from an implantation of primary Lewis lung carcinoma. 

Added Erythroleukemia to DO.
