### ISSUE TITLE
New term request : Amyloidosis types (AA, AL, ATTR, Aβ2M, ...)

### ISSUE THREAD

**Issue by julienmariethoz** [DiseaseOntology/HumanDiseaseOntology#420]
Amyloidosis (DOID:9120) classification, including AA, AL and more (https://en.wikipedia.org/wiki/Amyloidosis -> classification + external links)

**Comment by lschriml** [comment]
Hello Julian,
  Thank you for your interest in the Disease Ontology !!
I will take a look and get these added to the DO.
Cheers,
Lynn

**Comment by lschriml** [comment]
Amyloidosis was reviewed and updated in 2019.

Nomenclature was updated in 2020:
https://www.tandfonline.com/doi/pdf/10.1080/13506129.2020.1835263?needAccess=true

Revising amyloidosis classification to align with updated nomenclature.

**Comment by lschriml** [comment]
The 2020 nomenclature update has been incorporated into DO.
