### ISSUE TITLE
New Term Request: Peters-Plus Syndrome

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#421]
Hi,

I would like to request this term: Peters-Plus Syndrome. OMIM: 261540. Thanks

Sridhar

**Comment by lschriml** [comment]
Thank you Sridhar !!

**Comment by lschriml** [comment]
Action: 
Add new DO term, as child of 'syndrome' 

References: 
https://www.ncbi.nlm.nih.gov/books/NBK1464/
Clinical characteristics.
Peters plus syndrome is characterized by anterior chamber eye anomalies, short limbs with broad distal extremities, characteristic facial features, cleft lip/palate, and variable developmental delay/intellectual disability. 

https://ghr.nlm.nih.gov/condition/peters-plus-syndrome
Peters plus syndrome is an inherited condition that is characterized by eye abnormalities, short stature, an opening in the lip (cleft lip) with or without an opening in the roof of the mouth (cleft palate), distinctive facial features, and intellectual disability.

Peters plus syndrome is a **rare disorder;** its incidence is unknown. Fewer than 80 people with this condition have been reported worldwide.

http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=709
https://en.wikipedia.org/wiki/Peters-plus_syndrome

**Comment by lschriml** [comment]
Added to DO
