### ISSUE TITLE
New diseases added by Wikidata users

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#422]
I'm looking to see if there are diseases in Wikidata that are not in DO. Many items in wikidata do not distinguish between diseases and phenotypes/medical signs/symptoms, so its a little hard to identify items that are specifically diseases. As a first pass, to use items with high confidence that they are "real", I wrote a query to find items in Wikidata that satisfy the following conditions:

- is a subclass of an item that has a DOID
- does not have a doid
- has an Orphanet ID AND an OMIM ID AND a GARD ID

We get 152 items. Below are the results.

Run query: http://tinyurl.com/yavbzw6r
Results Only: http://tinyurl.com/y8qnsa9v
There are more than 152 rows because some items have multiple OMIM IDs, so they show up in multiple rows (with the other columns the same)

Are these items you would want to consider? What about ones that don't have all three of Orphanet, OMIM and GARD IDs?

**Comment by lschriml** [comment]
Hello Greg,
 These are great !! 

Only 3 or 4 ‘with’ diseases, these are usually phenotype variants in OMIM.

We do want to add these to the DO. 
It is fine if they do not have all three IDs. 

Cheers,
Lynn

**Comment by stuppie** [comment]
Ok great.

Here is another query that only requires ONE of omim, gard, orphanet:

http://tinyurl.com/yauomxc5

**Comment by lschriml** [comment]
Thank you Greg !!
