### ISSUE TITLE
angular cheilitis xref

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#432]
[angular cheilitis](http://www.disease-ontology.org/?id=DOID:0060312)

Has: [UMLS_CUI:C0007971](https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0007971) (Cheilitis)
Should be: [UMLS_CUI:C0221237](https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0221237) (Angular cheilitis) 

Change from Wikidata
https://www.wikidata.org/wiki/Q1456558

**Comment by lschriml** [comment]
Great, fixed.
Thank you Greg !! 

Cheers,
Lynn
