### ISSUE TITLE
tongue squamous cell carcinoma umls xref

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#433]
[tongue squamous cell carcinoma](http://www.disease-ontology.org/?id=DOID:0050865)

Has: [UMLS_CUI:C0007137](https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0007137) (Squamous cell carcinoma)
Should be: [UMLS_CUI:C0349566](https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0349566) (Tongue Squamous Cell Carcinoma) 

Change from Wikidata
https://www.wikidata.org/wiki/Q28757362

**Comment by lschriml** [comment]
Thank you Greg !! 
Fixed. 

Cheers,
Lynn
