### ISSUE TITLE
DO site down

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#437]
Since Lynn is out of town I'm hoping someone else is checking these issues. 
The DO site (http://disease-ontology.org/) appears to be down as of 10:25 on 12/15/17. I’m getting a connection timed out error message. Was this a planned outage?
Thanks,
Sue

**Comment by elviram** [comment]
Worked for me just now.

**Comment by sbello** [comment]
Hmm, odd, I still can't get to the site

**Comment by srengel** [comment]
works for me too.  i can access the site.

**Comment by sbello** [comment]
Okay, must be a Jax issue. Not sure what is going on.

**Comment by lschriml** [comment]
Thank you Elvira !!

**Comment by lschriml** [comment]
Thank you Stacia and Sue !!
Glad to hear this has been resolved.
Cheers from Paris,
Lynn

**Comment by sbello** [comment]
Jax fixed whatever the issue was and we once again have access!
