### ISSUE TITLE
polycystic kidney disease - located in missing

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#450]
Please consider adding located_in kidney to the terms 
autosomal recessive polycystic kidney disease (DOID:0110861)
autosomal dominant polycystic kidney disease (DOID:898)
autosomal dominant polycystic kidney disease (DOID:898) has located_in kidney in the text definition but this is not the field needed for the inferred parent to be created.
Thanks,
Sue

**Comment by lschriml** [comment]
done
