### ISSUE TITLE
New Term Request: Familial chylomicronemia syndrome

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#451]
Hi,

I would like to request this term: Familial chylomicronemia syndrome. ORPHA:444490 (OMIM: 118830  207750  238600  615947) . Thanks

Sridhar

**Comment by lschriml** [comment]
Thank you Sridhar !! 
   This is a synonym for DOID:14118.

Based on OMIM, it looks like there are five types of this disease. 

This one (orphaned and OMIM: 238600 & 118830) are type 1. 

NORD link: https://rarediseases.org/rare-diseases/familial-lipoprotein-lipase-deficiency/ <https://rarediseases.org/rare-diseases/familial-lipoprotein-lipase-deficiency/>

Cheers,
Lynn

**Comment by sbello** [comment]
added to OMIM spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing
