### ISSUE TITLE
New term request: reversible infantile liver failure (RILF)

### ISSUE THREAD

**Issue by LaurensWilming** [DiseaseOntology/HumanDiseaseOntology#452]
Paper PMID:27689697 describes a mouse model for 'reversible infantile liver failure' (RILF). Another, older, paper (DOI 10.1007/s10545-014-9784-6) seems to call it 'reversible infantile mitochondrial disease'. It also seems to be called 'transient infantile liver failure' (LFIT) and 'reversible infantile respiratory chain deficiency'. Take your pick!

Thanks,
Laurens

**Comment by lschriml** [comment]
Thank you Laurens !! 
I will take a look. 
Cheers,
Lynn

**Comment by melodyswen** [comment]
https://www.omim.org/entry/613070

OMIM TERM

**Comment by lschriml** [comment]
Added to DO as a child of liver disease
https://rarediseases.info.nih.gov/diseases/10593/disease
GARD:10593
https://www.omim.org/entry/613070
OMIM:613070

PMID:27689697
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5045200/
