### ISSUE TITLE
suggested definition for DOID:679

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#462]
DOID:679 is missing a definition. I suggest:
A brain disease that affects either one or more of the basal ganglia, the groups of nuclei associated with the ability to carry out willed movements, including the caudate, putamen, nucleus accumbens, globus pallidus, substantia nigra, and subthalamic nucleus
The definition for basal ganglia is taken from MP:0006007

**Comment by lschriml** [comment]
Thank you Sue !!

**Comment by lschriml** [comment]
I have added the definition. 
Cheers,
Lynn
