### ISSUE TITLE
Glioblastoma and Astrocytoma

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#466]
If we are to take NCIT as canonical for neoplasms then we must change

```
        is_a HP:0009733 ! Glioma
         is_a HP:0009592 ! Astrocytoma
          is_a HP:0100843 ! Glioblastoma *** 
```

See
https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues/23#issuecomment-361999516

Note from the linked ticket that HP does is in the same way as everyone except NCIT, who are more careful to separate these concepts. What is our policy here?

**Comment by lschriml** [comment]
Hello Chris,
 I think you may have unintentionally submitted this to the DO rather than your MonDO tracker. 

Cheers,
Lynn

**Comment by cmungall** [comment]
Ah, I actually meant to send this to the HP tracker, sorry about that

**Comment by lschriml** [comment]
no problem :)
