### ISSUE TITLE
Move exact synonyms, create parent-child relationships

### ISSUE THREAD

**Issue by gthayman** [DiseaseOntology/HumanDiseaseOntology#468]
Hello,
Could three of the exact synonyms of Macular Degeneration (DOID:4448): Age Related Maculopathies,   Age Related Maculopathy,   Age-Related Macular Degenerations be moved under age related macular degeneration (DOID:10871)? Exact synonym Age Related Macular Degeneration could be eliminated, as it is a term itself. Also could age related macular degeneration (DOID:10871) be made a parent of the fifteen terms: age related macular degeneration 1, 8, 11, 12 and Macular Degeneration, Age-Related, 2-7, 9, 10, 13-15? Thanks,
Tom Hayman

**Comment by lschriml** [comment]
Hello Tom,
 Thank you for your term update requests !! 
Could you tell me where you are looking at the DO ? 

   Having a look at the DO file (GitHub - in Protege) and DO website, for DOID:4448 
    the exact synonyms you mentioned are not attached to this DOID record.

And DOID:10871 is the parent for the age related macular degeneration (1-15) terms. 

Cheers,
Lynn

**Comment by gthayman** [comment]
Hi Lynn,
I was looking at our disease ontology, which I thought reflected DO’s parent-child relationships for terms originally from DO, rather than looking at the DO website – my mistake. Our parent child relationships are being changed to more faithfully reflect those in DO. Do you think the three exact synonyms I mentioned (Age Related Maculopathies, Age Related Maculopathy, Age-Related Macular Degenerations) would be worth adding to ‘age related macular degeneration’? Thanks,
Tom

**Comment by lschriml** [comment]
Hello Tom,
Happy to add the synonyms !!
Cheers,
Lynn

**Comment by lschriml** [comment]
done
