### ISSUE TITLE
New term request: Nonalcoholic fatty acid liver disease (NAFLD)

### ISSUE THREAD

**Issue by danielcouch** [DiseaseOntology/HumanDiseaseOntology#471]
Hi,

I'd like to request the addition of NAFLD to DO.
OMIM entry:
https://www.omim.org/entry/613282

Thanks,
Daniel

**Comment by lschriml** [comment]
Thank you Daniel !!

**Comment by cerivs** [comment]
Thanks for requesting ZFIN needs the term too.

**Comment by lschriml** [comment]
Done !!
