### ISSUE TITLE
metabolic acidosis

### ISSUE THREAD

**Issue by okkn** [DiseaseOntology/HumanDiseaseOntology#472]
The relation of "metabolic acidosis" (DOID:0050758) and "lactic acidosis" (DOID:3650) are reversed. Not all "metabolic acidosis" is "lactic acidosis" (https://en.wikipedia.org/wiki/Metabolic_acidosis), and "lactic acidosis" is a form of "metabolic acidosis" (https://en.wikipedia.org/wiki/Lactic_acidosis), so "metabolic acidosis" should be a superclass of "lactic acidosis".

**Comment by lschriml** [comment]
Thank you for pointing this out. I have made the fixes you suggested. 
We really appreciate your helping us to improve the Disease Ontology.

Cheers,
Lynn
