### ISSUE TITLE
doid OBO files broken

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#476]
Hi Lynn,

Our parser is failing on the latest doid-merged.obo file and I get error messages when I try to open the OBO file with OBO-edit.

The error message our parser throws is:
Caused by: Error: Unterminated xref list
on line: 85261 of file:/usr/local/pgsql/jenkins_data/etl_build/etl/output/do/2018.03.06.04.37.02/DiseaseOntology.obo
charnum: 146
line: def: "A sphingolipidosis characterized by dysfunctional metabolism of sphingolipids." [url:https\://ghr.nlm.nih.gov/condition/niemann-pick-disease, url:https\://en.wikipedia.org/wiki/Niemann–Pick_disease"]
                at org.obo.dataadapter.OBOParseEngine.translateException(OBOParseEngine.java:1431)

When I check that line in the do-edit.owl file I see that the definition and database_cross_references for the DO term Niemann-Pick disease are lacking a 'type' selection. The type should be set to string. Would you please correct this as MGI can not fully load the March release until this is fixed.

Thanks,
Sue

**Comment by lschriml** [comment]
Hello Sue, 
Thank you for catching this. 
I see that there was an extra “ in the xref field.

I also added the type string in the doid-edit.owl file.

Much appreciated,
Please let me know if there is anything else I can do.

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Sue,
the file is updated and pushed back to GitHub.
You should be all set. 

Cheers,
Lynn

**Comment by sbello** [comment]
Thanks Lynn! The file loads now. We really appreciate the quick turn around time on this.
Sue

**Comment by lschriml** [comment]
Great !!
Cheers,
Lynn
