### ISSUE TITLE
OMIM glioma susceptibility terms

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#477]
The OMIM cross references for the DO term malignant glioma (DOID:3070) need to be cleaned up. The OMIM IDs : 137800, 613033, 613032, 613030, 613028, 607248, 613031 are in as cross references but these are susceptibility entries in OMIM. The OMIM terms for  137800, 613028 are also in with the contributes to condition relationship. The other OMIM terms in this phenotypic series should be moved to this relationship as well.

**Comment by lschriml** [comment]
Thank you Sue !!

**Comment by lschriml** [comment]
I have updated these in the DO. 
Removed as xrefs, created glioma susceptibility # in the omit_susceptibility import 

added OMIM xref: PS137800 to 'malignant glioma' 

editing the omit_susceptibility import: 

-- create SubClass of 
  'contributes to condition' some 'malignant glioma' 
   'omit_susceptibility' 

Annotation:
rds:label  
id
create child terms with: 
IRI: http://purl.obolibrary.org/obo/OMIM_#
  then add in rdfs:label & id

OMIM IDs : 
137800   GLIOMA SUSCEPTIBILITY 1  --> already omim_susceptibility
613028 GLIOMA SUSCEPTIBILITY 2   --> already omim_susceptibility
       [OMIM:613029] -- already omim_susceptibility --> 'glioma susceptibility 3'
607248  GLIOMA SUSCEPTIBILITY 4 
     glioma susceptibility 4 - done
613030  GLIOMA SUSCEPTIBILITY 5
      glioma susceptibility 5 -done
613031   GLIOMA SUSCEPTIBILITY 6
       glioma susceptibility 6 - done
613032  GLIOMA SUSCEPTIBILITY 7
       glioma susceptibility 7 -done
613033  GLIOMA SUSCEPTIBILITY 8  
       glioma susceptibility 8
    [OMIM:616568 -- already omim_susceptibility --> 'glioma susceptibility 9'

**Comment by lschriml** [comment]
I have updated these in the DO. 
Removed as xrefs, created glioma susceptibility # in the omit_susceptibility import 

added OMIM xref: PS137800 to 'malignant glioma' 

editing the omit_susceptibility import: 

-- create SubClass of 
  'contributes to condition' some 'malignant glioma' 
   'omit_susceptibility' 

Annotation:
rds:label  
id
create child terms with: 
IRI: http://purl.obolibrary.org/obo/OMIM_#
  then add in rdfs:label & id

OMIM IDs : 
137800   GLIOMA SUSCEPTIBILITY 1  --> already omim_susceptibility
613028 GLIOMA SUSCEPTIBILITY 2   --> already omim_susceptibility
       [OMIM:613029] -- already omim_susceptibility --> 'glioma susceptibility 3'
607248  GLIOMA SUSCEPTIBILITY 4 
     glioma susceptibility 4 - done
613030  GLIOMA SUSCEPTIBILITY 5
      glioma susceptibility 5 -done
613031   GLIOMA SUSCEPTIBILITY 6
       glioma susceptibility 6 - done
613032  GLIOMA SUSCEPTIBILITY 7
       glioma susceptibility 7 -done
613033  GLIOMA SUSCEPTIBILITY 8  
       glioma susceptibility 8
    [OMIM:616568 -- already omim_susceptibility --> 'glioma susceptibility 9'
