### ISSUE TITLE
NTR: "Nodal Marginal Zone Lymphoma"

### ISSUE THREAD

**Issue by mikelivstone** [DiseaseOntology/HumanDiseaseOntology#478]
Ref: http://purl.obolibrary.org/obo/NCIT_C8863
NCIt definition: "A primary nodal B-cell non-Hodgkin lymphoma which morphologically resembles lymph nodes involved by marginal zone lymphomas of extranodal or splenic types, but without evidence of extranodal or splenic disease."
NCIt synonyms: Nodal marginal zone B-cell lymph., Nodal Marginal Zone B-Cell Lymphoma, Nodal marginal zone B-cell lymphoma, Nodal Marginal Zone Lymphoma, Monocytoid B-Cell Lymphoma

This should be a child of "marginal zone B-cell lymphoma" (DOID_0050748)

**Comment by lschriml** [comment]
Thank you Mike !!

**Comment by lschriml** [comment]
Added to the DO. 
Cheers,
Lynn
