### ISSUE TITLE
NTR: "Primary mediastinal large B-cell lymphoma"

### ISSUE THREAD

**Issue by mikelivstone** [DiseaseOntology/HumanDiseaseOntology#479]
Ref: http://www.orpha.net/ORDO/Orphanet_98838

OrphaNet definition: "Primary mediastinal B-cell lymphoma (PMBL) is a rare subtype of diffuse large B-cell lymphoma (DLBCL; see this term), arising from B cells of thymic origin, that affects mainly women between the ages of 20-30, that usually presents with a bulky and rapidly expanding anterior mediastinal mass, often with pleural and pericardial effusions, and that can invade the lungs, superior vena cava, pleura, pericardium, and chest wall, leading to manifestations of cough, dyspnea, and superior vena cava syndrome."

OrphaNet Synonyms: Med-DLBCL, Primary mediastinal clear cell lymphoma of B-cell type, Mediastinal diffuse large-cell lymphoma with sclerosis, Large cell lymphoma of the mediastinum

This should be a child of DLBCL (DOID_0050745)

**Comment by lschriml** [comment]
Thank you Mike !!

**Comment by lschriml** [comment]
Added to the DO. 
Cheers,
Lynn
