### ISSUE TITLE
smallpox link to WHO broken

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#482]
The links to WHO pages in the DO file go to deleted pages. See DOID:8736 for example.  The link in DO is currently:
 http://www.who.int/mediacentre/factsheets/smallpox/en/ 
but should be 
 http://www.who.int/csr/disease/smallpox/en/

I spot checked a few other WHO links and these have all been good so far, so this doesn't seem to be a widespread issue.

**Comment by lschriml** [comment]
Thank you Sue !! 
Fixed. 

Also found the link broken for Variola major 

Cheers,
Lynn
