### ISSUE TITLE
intellectual disability (DOID:1059) has broken definition links

### ISSUE THREAD

**Issue by cmpich** [DiseaseOntology/HumanDiseaseOntology#483]
The three definition hyper links for intellectual disability (DOID:1059) are broken...

**Comment by lschriml** [comment]
Thank you for pointing out these broken links !!
I have updated the links. 
They will be public in our next release.

Cheers,
Lynn

**Comment by lschriml** [comment]
In two weeks

**Comment by cmpich** [comment]
Hello, I still cannot see the changes. has the new version been released yet?

**Comment by lschriml** [comment]
Apologies,
The release got delayed by a week, as we are finalizing testing to automate more components of our release. 
We will push out a release early next week.
Cheers,
Lynn
