### ISSUE TITLE
New term request: gamma-delta T-cell lymphoma

### ISSUE THREAD

**Issue by mbernste** [DiseaseOntology/HumanDiseaseOntology#485]
Hi, I would like to request a term for 'gamma-delta T-cell lymphoma'.  See this paper: https://www.nature.com/articles/nrclinonc.2009.169

"γδ TCLs originate from γδ T cells, a small subset of peripheral T cells with direct antigen recognition capability acting at the interface between innate and adaptive immunity."

Matt

**Comment by lschriml** [comment]
Thank you Matt,
  I will take a look and get this added to DO.
Cheers,
Lynn

**Comment by lschriml** [comment]
The requested term has been added to the DO.
primary cutaneous gamma-delta T-cell lymphoma


[rare T-cell lymphomas]

     hepatosplenic T-cell lymphoma (HSTL). (HSTCL)
                  NCI:C8459
                  --> [definition]:  An extranodal, mature T-cell non-Hodgkin lymphoma that originates from cytotoxic T-cells, usually of gamma/delta T-cell type. It is characterized by the presence of medium-size neoplastic lymphocytes infiltrating the hepatic sinusoids. A similar infiltrating pattern is also present in the spleen and bone marrow that are usually involved at the time of the diagnosis.

https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC7596851/

     --> add as a child of : DOID:0050743  mature T-cell and NK-cell lymphoma

=============================================
    [DOID:0060061] cutaneous T cell lymphoma
             --> update disease name:   **Primary Cutaneous T-Cell Non-Hodgkin Lymphoma**, PCTCL 
             --> add   NCI:C3467. 

 [new child term]
 
     **primary cutaneous gamma-delta T-cell lymphoma** (PCGD-TCL)    [NCI:C45340]
          [synonyms] 
                (cutaneous gamma/delta T-cell lymphoma).  (GD-TCL)
                            https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC3471805/
                (Primary Cutaneous Gamma-Delta T Cell Lymphomas). (PCGDTCLs)
                             https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC8628721/
  
          [definition]
    --> characterised by the clonal cutaneous proliferation of activated mature gamma-delta T cells with a cytotoxic phenotype.

HSTL is a well-characterized extranodal lymphoma that has a disguised onset, secondary to intrasinusoidal infiltration of the spleen, liver and bone marrow, has a rapidly progressive course that is poorly responsive to chemotherapy, and often ensues in the setting of immune system suppression.

PCGD-TCL can present with prominent epidermal involvement or with a panniculitis-like clinical picture that can be complicated by a concurrent hemophagocytic syndrome;


Cutaneous T-cell lymphomas (CTCLs) are a group of disorders characterized by an abnormal accumulation of cancerous [T-cells](http://www.nlm.nih.gov/medlineplus/ency/article/003516.htm) (a type of white blood cells) in the skin resulting in an itchy, red rash that can thicken or form a tumor
