### ISSUE TITLE
Psoriasis and pityriasis rosea are different skin conditions

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#486]
Currently 'pityriasis rosea' is-a 'psoriasis'. This is incorrect. Please see: https://www.healthline.com/health/psoriasis/psoriasis-vs-pityriasis-rosea#psoriasis-vs-pityriasis-rosea

How about creating 'pityriasis' term under 'skin disease' and assign to it 'pityriasis rosea' and 'pityriasis rubra piliaris'?

**Comment by lschriml** [comment]
Thank you !!
I will take a look at these terms !!

Cheers,
Lynn

**Comment by lschriml** [comment]
Apologies for the delay, the terms have been updated. 

Cheers,
Lynn
