### ISSUE TITLE
thoracic cancers 

### ISSUE THREAD

**Issue by ahwagner** [DiseaseOntology/HumanDiseaseOntology#487]
`DOID:5093 - thoracic cancer` is defined in the ontology as (emphasis mine):

> An organ system cancer located_in the thoracic cavity that **develops in the different types of cells within the lungs**, as well as less common cancers of the esophagus, the trachea, or the chest wall.

This is a very reasonable definition, and one I am accustomed to using with other investigators that focus on lung cancers. However, `DOID:1324 - lung cancer` is found under `DOID:0050615 - respiratory system cancer`, which is also correct.

The problem is that the definition of thoracic cancer here is misrepresentative. Importantly, breast cancer is listed as a thoracic cancer, though it is not in the thoracic cavity. Given that breast and lung cancer are both highly investigated (and highly occurring) cancer types, incorrect attribution of these diseases to the appropriate cancer organ systems is highly visible to cancer researchers using the Disease Ontology.

I propose that you:

1. remove the respiratory organ system concept (`DOID:0050615`) and replace it with:
  a. an upper respiratory tract ID containing DOIDs `2596`, `10811`, and `0050619` that `is_a` `DOID:0050686 - organ system cancer`
  b. a lower respiratory tract ID containing DOIDs `1325`, `1324`, and `11920` that `is_a` `DOID:5093 - thoracic cancer`
2. change `DOID:1612 - breast cancer` from `is_a` `DOID:5093 - thoracic cancer` to `is_a` `DOID:0050686 - organ system cancer`

**Comment by lschriml** [comment]
Hello Alex,
  Thank you for the feedback. 

I appreciated the suggestions to improve our representation. 
I see what you mean, as we have not included lung cancer as a type of thoracic cancer, rather we have 
Represented it as a child of respiratory system cancer. 

The conundrum we face is where to place breast cancer ? 

For breast cancer, determining the most appropriate anatomic region/system, we previously decided that the thorax was the best anatomical placement, as breasts  are composed primarily of adipose cells overlaying the pectoral muscles and are not part of any other body system (not part of the respiratory tract).

thorax defn: 
the part of the body of a mammal between the neck and the abdomen, including the cavity enclosed by the ribs, breastbone, and dorsal vertebrae, and containing the chief organs of circulation and respiration; the chest.

—> For our thoracic terms, we will update to state that they are located_in the thorax, rather than the thoracic cavity. 

Now that we are representing anatomical location via logical definitions we can add thorax as a logical definition for lung cancer. 


Looking at the anatomy ontologies, FMA: breast is a child of ‘region of pectoral part of chest’ , Uberon, as a child of ‘thoracic segment of trunk -> chest’ 

I will look at this further. 

Cheers,
Lynn

**Comment by kkrysiak** [comment]
I would like to revisit this. I agree that including `breast cancer` as a thoracic cancer remains confusing. As you mention, breast is not part of another anatomical site. Could Neoplasm of the breast not be under disease of anatomical entity? DCIS and breast cancers are handled very differently than thoracic cancers. Using the ontology, I would not want to include breast cancer with other thoracic cancers (lung, thymoma, mediastinal lymphoma, etc).

**Comment by lschriml** [comment]
Hello KK,
    I too have struggled to determine where to place breast diseases, anatomically. 
Where do you think 'breast' best fits anatomically ?? 
    Would creating a new term: superficial thoracic cancer -- work to distinguish the location of the breast, breast tissue, breast cancer ?? 

     anatomically: superficial : 'on the surface' 

Looking again at this, here are some notes (and their sources): 

Anatomically, the adult breast sits atop the pectoralis muscle (the "pec" chest muscle), which is atop the ribcage.
               https://pathology.jhu.edu/breast/overview

Anatomically, 
    the breast is made up of fat, glands (mammary), connective tissue and ducts & thoracic vascular system
         (multiple systems are involved):  lymphatic system, (accessory organs of): female reproductive system, circulatory system

https://www.ncbi.nlm.nih.gov/books/NBK519575/#:~:text=Deep%20inside%20the%20breast%20are,into%20the%20chest%20wall%20veins.&text=The%20breast%20also%20has%20extensive,receives%20lymphatics%20from%20glandular%20tissues.

This resource: **Anatomy, Thorax:** 
https://www.ncbi.nlm.nih.gov/books/NBK557710/#:~:text=%5B6%5D%20Breast%20tissue%20is%20composed,areolar%20complex%2C%20and%20the%20nipple.&text=The%20thoracic%20cavity%20is%20found,the%20neck%20(thoracic%20aperture).

**--> defines the 'thorax':**
 The thorax is the region between the abdomen inferiorly and the root of the neck superiorly. The thorax forms from the thoracic wall, **its superficial structures (breast, muscles, and skin**), and the thoracic cavity.


lymphatics and the breast:
https://medlineplus.gov/ency/anatomyvideos/000084.htm#:~:text=Lymphatic%20circulation%20in%20breast%20tissue,as%20cancer%20through%20the%20body.

thoracic circulatory system:
The internal thoracic vein is located deep within your chest. It collects blood from the chest wall and breasts and returns it to your heart

https://my.clevelandclinic.org/health/body/23066-internal-thoracic-vein

Cheers,
Lynn

**Comment by ahwagner** [comment]
Hi @lschriml. My [prior suggestions to fix this issue](https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/487#issue-317758974) are getting a little stale so I’ll give this another try.
IMO, it seems like the disconnect here is that you are stating the breast is on the chest which is part of the thorax, ergo breast cancer is a thoracic cancer. @kkrysiak and I are not contesting the relationship between breast and its anatomical placement on the chest/thorax. However, we _are_ stating that breast **cancer** is not a thoracic **cancer**.

## On the definition of thoracic cancers
Broadly, the wholistic term of “thoracic cancer” includes cancers that are derived from tissues of the thoracic **cavity**, which would exclude breast cancers.

Here are a few medical institutions that define thoracic cancer in this way:
- [UC Davis](https://health.ucdavis.edu/conditions/cancer/thoracic-cancer#:~:text=Thoracic%20cancer%20is%20any%20cancer,cavity%20cancer%20is%20lung%20cancer.)
- [Dana Farber Cancer Institute](https://www.dana-farber.org/cancer-care/treatment/thoracic-lung-cancer/programs#:~:text=The%20Lowe%20Center%20for%20Thoracic%20Oncology%20treats%20lung%20cancer%20%E2%80%94%20non%2Dsmall%20cell%20lung%20cancer%2C%20small%20cell%20lung%20cancer%2C%20and%20mesothelioma%20%E2%80%94%20and%20other%20cancers%20of%20organs%20within%20the%20chest.)
- [UCSF](https://radonc.ucsf.edu/conditions-treatments/conditions-we-treat/thoracic-cancers/)
- [Brigham and Women’s Hospital](https://www.brighamandwomens.org/surgery/thoracic-surgery/thoracic-cancer#:~:text=board%2Dcertified%20thoracic%20surgeons%20specialize%20in%20lung%20cancer%2C%20esophageal%20cancer%2C%20mesothelioma%2C%20thymoma%2C%20airway%20malignancies%20and%20other%20cancers%20within%20the%20chest)
- [Yale](https://www.yalecancercenter.org/patient/programs/thoracic/)

Therefore, if DO needs to align these concepts with relevant anatomical sites, I would suggest linking “thoracic cancer” to “thoracic cavity” as the anatomical site. I'm a little confused about why this is an issue, though, since the [current definition of "thoracic disease" in DO actually has this nuance](https://github.com/DiseaseOntology/HumanDiseaseOntology/blame/1c1cc0fccc7ae37233a364ad791114840adaca0a/src/ontology/subsets/DO_GXD_slim.obo#L102):

>A disease of anatomical entity that is located_in the thoracic cavity.
http://en.wikipedia.org/wiki/Thoracic_cavity

so it is not clear why breast cancer would belong under thoracic disease following this definition, even with the presented logical relation between breast and the thorax.

## On the grouping of the breast cancer concept

> Where do you think ‘breast’ best fits anatomically ??

I don’t have any strong opinions on what organ system the DO might associate breast tissue with (and therefore where DO might place the "breast cancer" concept), though from what I have seen “reproductive system” seems like a common placement and already exists in DO. I think you referenced this and some other candidates in [your above comment](https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/487#issuecomment-2307489306). However, the other ontologies that I have seen classifying cancer types focus on _tissue_ of origin instead of _organ system_ of origin, in which case breast would be a top-level concept.

## Don't forget about lung cancer
I know that @kkrysiak raised the issue about the misplacement of breast cancer, but I also want to point out that Lung Cancer, a type of thoracic cancer that is _so common the two terms are often used interchangeably_, is not related to the thoracic cancer concept in DO. IMO, this should also be addressed.

**Comment by lschriml** [comment]
Thank you Alex @ahwagner and KK @kkrysiak
        --  breast disease has been moved up the tree, out of thorax disease as an asserted parent. 
As suggested the other diseases that should be inferred under thorax have been updated as well.

Cheers,
Lynn

**Comment by kkrysiak** [comment]
Thanks @lschriml! Sorry for delayed engagement, I have been out of the office for most of the last month. But it sounds like everyone is happy with the outcome so thanks for looking at it.
