### ISSUE TITLE
rippling muscle disease 2

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#488]
DOID:0060255 term name is inadequate. It should be 'rippling muscle disease' since it lists OMIM:600332 [rippling muscle disease 1] and OMIM:606072 [rippling muscle disease2] as evidence. Perhaps child terms corresponding to each OMIM variants should be created, too?

**Comment by lschriml** [comment]
Thank you for your interest in the Disease Ontology !! 
We will check this out and update the file.

Cheers,
Lynn

**Comment by lschriml** [comment]
Agreed, we will create a new DOID for rippling muscle disease 1, and clean up the other disease term. 
Cheers,
Lynn

**Comment by Apujar** [comment]
Created new term and updated DOID:0060255.

cheers
anu
