### ISSUE TITLE
cartilage disease problem

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#490]
Consider different parent terms for DOID:1221 and DOID:6227

Currently DOID:1222 [cartilage disease] is-a [articular cartilage disease]. This is counterintuitive, because I would rather expect the opposite relationship: [articular cartilage disease] is a [cartilage disease]. [Articular cartilage disease] is narrowed to joints. Cartilage is present not only in joints but also in nose and ear, etc. Please see: https://www.mananatomy.com/basic-anatomy/cartilage-types

**Comment by lschriml** [comment]
Agreed, Thank you !! 
Fixed.
