### ISSUE TITLE
broken link in DOID:12849 definition

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#492]
http://wwww.neurodevnet.ca in the definition for DOID:12849 does not appear to be functional, possibly the url is wrong or the project has lost funding?

Do we have a way to automatically test urls in the DO file? Could be useful to try to keep these up-to-date more systematically.
Thanks,
Sue

**Comment by sbello** [comment]
Ignore this. There seems to be an issue with the link format at the Alliance site. From the DO site this link works fine.

**Comment by lschriml** [comment]
Thank you Sue !!
We will take a look and get it fixed. 
Becky, CC’d, has a script we run periodically to find these URL issues. We will re-run.

Much appreciated,
Lynn

**Comment by lschriml** [comment]
Thank you Sue !!
