### ISSUE TITLE
duplicates [multiple symmetrical lipomatosis]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#493]
Consider merge:

DOID:3137 multiple symmetrical lipomatosis
DOID:14116 multiple symmetric lipomatosis

**Comment by lschriml** [comment]
Thank you !!!
I will take care of these terms.
Much appreciated,
Lynn

**Comment by lschriml** [comment]
fixed

Thank you !!
