### ISSUE TITLE
uberon_import.owl classes are not correctly mapped. 

### ISSUE THREAD

**Issue by jimmccusker** [DiseaseOntology/HumanDiseaseOntology#496]
Please align your imports with the https://github.com/obophenotype/upheno project or use their imports. Importing DO and HP cause reasoning inconsistencies.

**Comment by rctauber** [comment]
We are working on cleaning up our imports (and resolving #497) - could you please specify which terms are causing issues? Thanks!

**Comment by jimmccusker** [comment]
go:0003674 should be subclassof bfo:0000015, not bfo:0000034.

**Comment by rctauber** [comment]
When I create a new ontology and import DO and HP together, without anything else, it shows as the correct GO subclass; DO isn't using `GO:0003674`.

Are you importing any other ontologies that may be importing OBI? They define `GO:0003674` as a subclass of `BFO:0000034` - https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0003674
