### ISSUE TITLE
Incorrect use of Uberon term in DO

### ISSUE THREAD

**Issue by balhoff** [DiseaseOntology/HumanDiseaseOntology#497]
The DO OWL file `http://purl.obolibrary.org/obo/doid.owl` imports an Uberon extract, `http://purl.obolibrary.org/obo/doid/imports/uberon_import.owl`. This file includes a term labeled as 'anatomy', with ID `UBERON:0000000`. However, in Uberon, `UBERON:0000000` is [processual entity](http://purl.obolibrary.org/obo/UBERON_0000000). DO incorrectly places many other Uberon terms under this concept, resulting in logical inconsistencies.

**Comment by rctauber** [comment]
Thanks for pointing this out. I'll make sure our Uberon import file gets resolved ASAP.
