### ISSUE TITLE
Koolen de Vries syndrome duplicate

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#498]
http://purl.obolibrary.org/obo/DOID_0070076
and
http://purl.obolibrary.org/obo/DOID_0050880

Koolen-De Vries syndrome
and
Koolen de Vries syndrome

**Comment by stuppie** [comment]
and a duplicate issue :-D
https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/491

**Comment by lschriml** [comment]
Thank you Greg !!
