### ISSUE TITLE
Review spinocerebellar ataxia type 5 dbxref/def of spinocerebellar ataxia

### ISSUE THREAD

**Issue by obophenotype-user** [DiseaseOntology/HumanDiseaseOntology#50]
We are curating a model of Spinocerebellar ataxia type 5 (SCA5) OMIM:600224 based on PMID:20368622.

Currently, OMIM:600224 is listed as a dbxref for the general sounding DO term spinocerebellar ataxia ; DOID:1441. However, SCA5 is caused by deletions/missense mutations in SPTBN2 rather than expanded CAG repeats so isn't consistent with the DO definition "A spinocerebellar degeneration that has_material_basis_in expanded CAG triplet repeats resulting in spinal cord and cerebellum degeneration."

Looks like the general term needs a less specific definition to be able group these conditions and SCA5 should possibly be a separate term? 

At present there are only 5 children of DOID:1441 but OMIM has a 'phenotypic series' consisting of 33 types of spinocerebellar ataxia. As the current DO children of DOID:1441 are all undefined it isn't clear why some have a entry in their own right rather than being linked to the general parent. It would be great if these could be reviewed at some point to add defs and ensure that all that merit a separate entry have one. I'm guessing this might not be straightforward in terms of classification. I also noticed that OMIM:615386 SCAR14 (also caused by mutation in SPTBN2) is not included as a dbxref in DO (I haven't checked all 33!). 

Reported by: stweedie

Original Ticket: [diseaseontology/feature-requests/50](https://sourceforge.net/p/diseaseontology/feature-requests/50)

**Comment by lschriml** [comment]
the additional terms were added to DO.
