### ISSUE TITLE
DOID:0060680, child of glaucoma?

### ISSUE THREAD

**Issue by cindyJax** [DiseaseOntology/HumanDiseaseOntology#504]
Should pigment dispersion syndrome (DOID:0060680) be considered a child of glaucoma? 

Also there is a typo at the end of the definition "gluacoma." vs glaucoma.

**Comment by lschriml** [comment]
Hello Cindy,
Thank you for finding the typo, we will get it fixed. And will take a look at pigment dispersion syndrome.
Really appreciate your contributing to improving the DO!! 

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Cindy,
  typo fixed -- Thank you !!
Looking at these two diseases, I would not place pigment dispersion syndrome (loss of pigment from the back of the eye) as a child of glaucoma (due to changes in interocular pressure).

Cheers,
Lynn
