### ISSUE TITLE
incomplete [myofibrillar myopathy 7] (DOID:0080098)

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#505]
According to OMIM:
OMIM:613869 [MYOPATHY, MYOFIBRILLAR, FATAL INFANTILE HYPERTONIC, ALPHA-B CRYSTALLIN-RELATED] is associated with CRYAB gene
OMIM:617114 [MYOPATHY, MYOFIBRILLAR, 7] is associated with KY gene

The OMIM summary indicates, these two OMIM terms are quite related. Same according to http://www.malacards.org. 

I propose to add OMIM:617114 with synonyms to the DO term.

**Comment by lschriml** [comment]
Thank you !!
I really appreciate your pointing this out!!

Cheers,
Lynn

**Comment by lschriml** [comment]
I have updated myofibrillar myopathy 7 -- the OMIM ID changed -- it is now OMIM:617114
Added myofibrillar myopathy 8 
for: 
fatal infantile hypertonic myofibrillar myopathy (part of the same OMIM Phenotypic series)
OMIM: 613869

A recent review: https://www.ncbi.nlm.nih.gov/pubmed/23995273

Cheers,
Lynn
