### ISSUE TITLE
Retinal disease and Blindness

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#506]
Currently blindness is a subclass of `retinal disease`.
A retinal disease can cause blindness, just like a "lens disease" or "corneal disease", and so it doesn't make sense to be a subclass of retinal disease.

See: https://www.wikidata.org/wiki/User_talk:Gstupp#retinal_disease_in_blindness

**Comment by lschriml** [comment]
Thank you Greg,
I will take a look.
Cheers,
Lynn

**Comment by lschriml** [comment]
Agreed, updated. 
Thank you Greg !!
