### ISSUE TITLE
add integumentary and skin located_in for respective diseases

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#507]
Please add located in information for:
integumentary system disease
skin disease
These are missing this information or it is formatted incorrectly and this is resulting in the related cancer terms not falling under and MGI slim parent.
Thanks,
Sue

**Comment by lschriml** [comment]
Hello Sue,
 they were added this past week and will go out in our release next week.

Cheers,
Lynn
