### ISSUE TITLE
broken definition link in DOID:0050557

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#508]
The link http://www.ninds.nih.gov/disorders/md/detail_md.htm in the definition of DOID:0050557 goes to an error page at the NINDS site. I'm guessing we should link to this page https://www.ninds.nih.gov/Disorders/All-Disorders/Muscular-Dystrophy-Information-Page instead.

**Comment by lschriml** [comment]
Thank you Sue !! 
Fixed !!
