### ISSUE TITLE
Ohtahara syndrome (DOID:0050709)

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#509]
DOID:0050709 has the primary label Ohtahara syndrome with the synonym 'early infantile epileptic syndrome' both OMIM and DO use 'early infantile epileptic syndrome' as the primary term name. I suggest we change the primary label to 'early infantile epileptic syndrome'.

Orphanet splits the OMIM series OMIM:PS308350 into at least 3 ORDO records ORDO:1934 (EIEE),  ORDO:442835 (Undetermined early-onset epileptic encephalopathy), and ORDO:33069 (Dravet syndrome). There may be more as there are over 60 entries in the OMIM series.  I'll update this as I work my way through the series. I'm guessing DO also has these spread around to various terms as xrefs.

**Comment by lschriml** [comment]
Thank you Sue !! 
I will take a look. 

Is the name change related to a publication ? 

Cheers,
Lynn

**Comment by sbello** [comment]
Digging around for some references to indicate why the name change happened. So far I have:
https://www.ncbi.nlm.nih.gov/pubmed/25266964 review uses both interchangeably
https://www.scopus.com/record/display.uri?eid=2-s2.0-0017116633&origin=inward&txGid=3ea5ae8738fb4cfe3f95cb039221451b - first article on the syndrome by Ohtahara et al refers in the title and abstract to "Early-Infantile Epileptic Encephalopathy with Suppression-Burst" (I can't actually read the article as it is in Japanese). 
Many of the articles I've looked at use the 2 names interchangeably but OMIM and Orphanet us EIEE as the primary label

**Comment by sbello** [comment]
GARD also uses EIEE https://rarediseases.info.nih.gov/diseases/9255/early-infantile-epileptic-encephalopathy

**Comment by sbello** [comment]
I've color coded the OMIM IDs to show the relation to the various ORDO groupings, ones that are not colored are either not in ORDO or hava a 1 to 1 relationship (in which case the ORDO ID is included).

**Comment by lschriml** [comment]
Thank you Sue !!
This is very helpful !!

**Comment by lschriml** [comment]
Reviewing this term and it's subtypes:
Currently in DO:
DOID:0050709  name: Ohtahara syndrome  
    (ORDO:1934, GARD: 9255)
          --> update name to early infantile epileptic encephalopathy
         --> synonym: EIEE
   OMIM: PS308350
 
I will update this DO term. 

Cheers,
Lynn
