### ISSUE TITLE
Missing data-version information in the doid-non-classified files

### ISSUE THREAD

**Issue by jlparmley** [DiseaseOntology/HumanDiseaseOntology#510]
We have noticed that there is no data-version value in any of the 3 file formats for doid-non-classified for the current version. I have not checked other files. 

Please can this be re-instated. Many thanks

**Comment by lschriml** [comment]
Thank you !!

**Comment by lschriml** [comment]
resolved by @rctauber

**Comment by jlparmley** [comment]
Hello, 

I've only now noticed that this file also does not contain any is_a definitions. 

Please can you have a look into this?

Many thanks

**Comment by lschriml** [comment]
Thank you, this is a glitch in the ROBOT build we ran. 
It is being fixed in the build we are running today.

Much appreciated,
Lynn
