### ISSUE TITLE
Incorrect date in the header of the doid-merged.obo file

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#511]
The doid-merged.obo file (https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid-merged.obo) has the date 05:03:2019 in the date field. Unless the file can time travel, this date is incorrect.

**Comment by lschriml** [comment]
Thank you Sue,
  We will get this fixed. 
Cheers,
Lynn

**Comment by sbello** [comment]
Hi Lynn,
I'm also seeing an error when I try to open the doid.obo file in OBO edit (see below). The doid-merged.obo file opens without an issue.

Load Error, line 1 Expected :. 
org.obo.dataadapter.OBOParseEngine.translateException(OBOParseEngine.java:1476)
org.obo.dataadapter.OBOParseEngine.translateAndThrow(OBOParseEngine.java:1468)
org.obo.dataadapter.OBOParseEngine.doParse(OBOParseEngine.java:408)
org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:43)
org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:68)
org.obo.dataadapter.OBOFileAdapter.doOperation(OBOFileAdapter.java:270)
org.bbop.dataadapter.DataAdapterOperationTask.execute(DataAdapterOperationTask.java:43)
org.bbop.util.AbstractTaskDelegate.run(AbstractTaskDelegate.java:60)
org.bbop.swing.BackgroundEventQueue$BackgroundEventThread.executeTask(BackgroundEventQueue.java:137)
org.bbop.swing.BackgroundEventQueue$BackgroundEventThread.run(BackgroundEventQueue.java:79)

**Comment by lschriml** [comment]
Thank you Sue !!
Apologies for the bugs, we are moving the ROBOT for our builds and this was our first build. We will get this fixed.
Cheers,
Lynn

**Comment by lschriml** [comment]
Good Morning Becky and Sue,
 Looking at the May 15th release, doid.obo has the owl axioms included. 
 They should be removed along with: 
import: http://purl.obolibrary.org/obo/doid/obo/ext.owl
and the non-DO Typedef’s at the end of the file.

Cheers,
Lynn

**Comment by rctauber** [comment]
Thanks Lynn! I'll get this fixed.

**Comment by lschriml** [comment]
Great, thank you !!

**Comment by sbello** [comment]
@rctauber You have to have an old version of Java installed on your machine to run OBO edit. I have 2 versions of Java on my machine for this reason.
Yes, that was the full error message.

**Comment by rctauber** [comment]
@sbello - I just pushed a fix for it, please let me know if the new `doid.obo` file opens for you. Thanks!

**Comment by lschriml** [comment]
Resolved by @rctauber

**Comment by lschriml** [comment]
Resolved by @rctauber

**Comment by lschriml** [comment]
Resolved by @rctauber
