### ISSUE TITLE
autosomal mental retardation 61

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#512]
DOID:0080229 autosomal dominant mental retardation 61, xref: OMIM:617773
DOID:0080239 autosomal recessive mental retardation 61

https://www.omim.org/entry/617773 refers only to [autosomal recessive mental retardation 61] -- I could not find anywhere the term [autosomal dominant mental retardation 61], not in OMIM, not by googling.

I propose to either merge these two terms, or provide some xrefs justifying the existence of DOID:0080229

**Comment by lschriml** [comment]
Reviewing these two DOIDs:
  --> DOID:0080229 autosomal dominant mental retardation 61
           -- was made in error, this should be the autosomal recessive form.
    I have merged the two DOIDs for tracking and removed the incorrect disease name. 
In OMIM: there are over 60 of the autosomal recessive forms, we will be adding these to DO shortly.

Cheers,
Lynn
