### ISSUE TITLE
MALT lymphoma

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#513]
Currently [MALT lymphoma] (DOID:0050909) is-a [non-Hodgkin lymphoma] (DOID:0060060). And that's correct.

However, according to http://www.cancerresearchuk.org/about-cancer/non-hodgkin-lymphoma/types/malt it also belongs to 'marginal zone lymphomas'.

Therefore please consider to set [marginal zone B-cell lymphoma] (DOID:0050748) as the parent of 
[MALT lymphoma] (DOID:0050909). ([marginal zone B-cell lymphoma] is also a [non-Hodgkin lymphoma])

**Comment by lschriml** [comment]
Thank you for pointing this out.
Great cancer resource !!
I have updated MALT lymphoma.

The change will be public in our next release (next week).

Cheers,
Lynn
