### ISSUE TITLE
duplicate OMIM:256810

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#514]
OMIM:256810 [MITOCHONDRIAL DNA DEPLETION SYNDROME 6 ] is assigned to both

DOID:0080125 [mitochondrial DNA depletion syndrome 6]
DOID:0080126 [mitochondrial DNA depletion syndrome 7]

Any plans to provide definitions and synonyms for terms [mitochondrial DNA depletion syndrome ....]?

Thank you!

**Comment by lschriml** [comment]
Thank you !! 
I will take a look on Monday and get this updated. 
Yes, we are adding these.

Cheers,
Lynn

**Comment by lschriml** [comment]
Fixed.
 We have added up to #13 in this series.
Cheers,
Lynn
