### ISSUE TITLE
NTR: CRANIOLENTICULOSUTURAL DYSPLASIA

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#517]
OMIM:607812 
Synonym: BOYADJIEV-JABS SYNDROME 
Synonym: cranio-lenticulo-sutural dysplasia
Synonym: CLSD
Craniolenticulosutural dysplasia is an autosomal recessive disorder characterized by facial dysmorphism, late-closing fontanels, cataract, and skeletal defects.  PubMed: 16980979

is_a autosomal recessive disease
is_a congenital disorder of glycosylation PMID: 29161034
is_a collagen disease

PMID: 29161034  says we show that individual O-GlcNAcylation sites of SEC23A, an essential COPII component, are required for its function in human cells and vertebrate development, because mutation of these sites impairs SEC23A-dependent in vivo collagen trafficking and skeletogenesis in a zebrafish model of CLSD.
It may also be a protein trafficking disease, a endoplasmic reticulum disease, 
The collagen disease is an indirect effect caused by aberrant protein trafficking caused by absent glycosylation.

**Comment by Apujar** [comment]
The term has been added.

Cheers
anu
