### ISSUE TITLE
NTR post-cardiac arrest syndrome 

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#518]
Collection of pathologies that are the result of surviving a cardiac arrest (myocardial infarction) caused at least partially by  reperfusion injury mechanisms.  Conditions include but are not limited to post-cardiac arrest brain injury,  post-cardiac arrest myocardial dysfunction, systemic ischaemia/reperfusion response, and persistent precipitating pathology.  PMID:15365608, PMID:29055751, PMID:18963350

**Comment by lschriml** [comment]
Thank you !! 
I will take a look.
Cheers,
Lynn

**Comment by cerivs** [comment]
This is is_a syndrome

**Comment by lschriml** [comment]
Thank you !!

**Comment by lschriml** [comment]
Post-cardiac arrest syndrome has four main components: post-cardiac arrest brain injury, post-cardiac arrest myocardial dysfunction, systemic ischemia reperfusion response, and per- sistent precipitating pathologies

**Comment by Apujar** [comment]
The term has been added.

Cheers
anu
