### ISSUE TITLE
broken definition link in DOID:0050557

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#519]
The link http://www.ninds.nih.gov/disorders/md/detail_md.htm in the definition of DOID:0050557 leads to a 404 error page not found page. I'm guessing the link should go here https://www.ninds.nih.gov/Disorders/All-Disorders/Muscular-Dystrophy-Information-Page This is where the link from the parent term in DO goes.

**Comment by lschriml** [comment]
Thank you Sue !! 
I will get this fixed. 

Cheers,
Lynn

**Comment by lschriml** [comment]
fixed !!
