### ISSUE TITLE
the size of the "doid-merged.obo" changes a lot.

### ISSUE THREAD

**Issue by zhutixiaojie0120** [DiseaseOntology/HumanDiseaseOntology#520]
the number of items in the previous "doid-merged.obo" (version 1.2, data-version: releases/2018-02-03) is: 21075

the number of items in the current "doid-merged.obo" (version 1.2, data-version: releases/2018-05-15) is: 11882

I found the "name" in the previous data become the "synonym" in the current data. It is fine, since it is still in the data. 
But I also found that a huge number of "name"s only appear in the previous "doid-merged.obo" file (neither in the current name list nor in the current synonym list). They disappear in the current data. 
The number of this kind of items is: 8864

Why there are 8864 items omitted?

**Comment by lschriml** [comment]
Thank you for pointing this out.
We will take a look and let you know. 
Cheers,
Lynn

**Comment by lschriml** [comment]
Thank you for your patience, as we were working to move our release work to a new software.
Updates are done, the files are aligned to their previous size.
