### ISSUE TITLE
NTR: drug induced hearing loss

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#523]
related synonym: ototoxicity
Def: The pharmacological adverse reaction affecting the inner ear or auditory nerve, characterized by cochlear or vestibular dysfunction resulting in loss of hearing.  PMID: 29471610 PMID: 25629145 PMID: 20301595 PMID:20096805

is_a nonsyndromic deafness

**Comment by Apujar** [comment]
The term has been added.

Cheers
anu
