### ISSUE TITLE
primary hyperaldosteronism vs cushing syndrome

### ISSUE THREAD

**Issue by slaulederkind** [DiseaseOntology/HumanDiseaseOntology#525]
I think there was an incorrect merging of terms between DOID:446 [primary hyperaldosteronism] and  DOID:12252 [Cushing syndrome].  None of the cross-references for DOID:446 [primary hyperaldosteronism] mention Cushing Syndrome.  DOID:446 [primary hyperaldosteronism] is a disease of mineralocorticoid excess, whereas Cushing Syndrome is a disease of glucocorticoid excess.  "corticosteroid" covers both mineralocorticoid and glucocorticoid, but is sometimes used as a synonym for the latter, so that may be the source of confusion in combining Cushing Syndrome and primary hyperaldosteronism.  I believe the two terms should be represented by separate DO entries.  Thanks.

**Comment by lschriml** [comment]
Thank you Stan !! 
I totally agree, 
   Looks like this happened for ticket #396. 
   
I reversed the merge and updated the DOIDs. 

I then did the merge from ticket #396. 
Conn's syndrome 

All fixed. 
Cheers,
Lynn
