### ISSUE TITLE
absence epilepsy

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#527]
DO has terms for age of onset specific forms of absence epilepsy (DOID:0060172, juvenile absence epilepsy; DOID:1825, childhood absence epilepsy; DOID:0050708, early onset absence epilepsy) but no term for 'absence epilepsy' without an age of onset. MGI has mouse models of absence epilepsy (see PMID:25010494, PMID:15800200 for example). Therefor, would you please add the term:

absence epilepsy
child-of: electroclinical syndrome (DOID:0050701)
definition: An electroclinical syndrome characterized by the occurrence of generalized onset seizures that cause lapses in awareness, begin and end abruptly, typically last only a few seconds and are associated with abnormal spike-wave discharges as seen by electroencephalogram.
references: https://www.epilepsy.com/learn/types-seizures/absence-seizures ; PMID:15800200 ; https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3697883/
This term should have the existing onset specific DO terms as children.

Thanks,
Sue

**Comment by lschriml** [comment]
Thank you Sue !!

**Comment by lschriml** [comment]
Hello Sue,
 these terms have the parent term: adolescence-adult electroclinical syndrome
DOID:0050705

We can add 'absence epilepsy' as a parent of the above DOID.

Cheers,
Lynn

**Comment by Apujar** [comment]
Created new term under DOID:0050701 with existing onset specific DO terms as children.
