### ISSUE TITLE
inconsistent naming for child terms of DOID:0070162

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#528]
for child terms of [hereditary sensory and autonomic neuropathy type 1] (DOID:0070162):

hereditary sensory neuropathy type ID (DOID:0070156) -- for consistency, please consider to change the name to [hereditary sensory neuropathy type 1D]

Also, for [hereditary sensory neuropathy type 1F] (DOID:0070154) and [hereditary sensory neuropathy type ID (DOID:0070156)], please consider to change the definition and drop 'autonomic' phrase from the definition. According to OMIM (https://www.omim.org/entry/162400), if the autonomic features are not present, [hereditary sensory neuropathy (HSN)] phrase is used instead of [hereditary sensory and autonomic neuropathy HSAN]

**Comment by lschriml** [comment]
Thank you for pointing out these needed updated.
I will take a look and get them fixed.

Much appreciated,
Lynn

**Comment by lschriml** [comment]
All fixed.
Thank you !!
