### ISSUE TITLE
duplicate [apparent mineralocorticoid excess]?

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#529]
There are two terms that have very similar names and overlapping xrefs. Consider a merge.

DOID:0090121 [apparent mineralocorticoid excess]
DOID:4367 [apparent mineralocorticoid excess syndrome]

**Comment by lschriml** [comment]
Thank you for identifying this case.
I will take a look and see if a merge is needed.

Cheers,
Lynn

**Comment by lschriml** [comment]
Agreed, they should be merged.
DOID:0090121 apparent mineralocorticoid excess] merged into DOID:4367
Done
