### ISSUE TITLE
Megacystis microcolon intestinal hypoperistalsis syndrome

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#530]
Request by Joseph Miano. 

Megacystis microcolon intestinal hypoperistalsis syndrome
 to be added to DO.
[LMOD1 KO - PNAS.pdf](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/2138078/LMOD1.KO.-.PNAS.pdf)

**Comment by lschriml** [comment]
Thank you for bringing this to our attention !! 

We will need to look into this further. 
And we will update you via this ticket. 

In DO we have: 
megacystis-microcolon-intestinal hypoperistalsis syndrome
DOID:0060610

This DO record includes a link to OMIM: 155310,
VISCERAL MYOPATHY; VSCM
(synonyms):
MEGACYSTIS-MICROCOLON-INTESTINAL HYPOPERISTALSIS SYNDROME; MMIH

This OMIM phenotype record, is associated with the ACTG2 gene,
on Chr 2. 

 as OMIM also has: 
https://www.omim.org/entry/602715?search=lmod1%20gene&highlight=gene%20lmod1
OMIM:602715 gene record on Chr 1

Cheers,
Lynn

**Comment by lschriml** [comment]
add both OMIM IDs to the DO record, add requested synonym

**Comment by Apujar** [comment]
added to DO record. 

cheers
anu
