### ISSUE TITLE
encephalitis (DOID:9588) issue

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#531]
Currently the term [encephalitis] (DOID:9588) has the following parents:

is_a: DOID:934 ! viral infectious disease
is_a: DOID:936 ! brain disease

[DOID:934 ! viral infectious disease] is incorrect. Viral encephalitis (DOID:646) is the most common form of encephalitis, but not the only one.

Proposal:
Drop DOID:934 parent from [encephalitis] (DOID:9588), and add DOID:934 parent to [viral encephalitis] (DOID:646)

**Comment by lschriml** [comment]
Thank you !! 
I will take a look and update DO.

Cheers,
Lynn

**Comment by lschriml** [comment]
Thank you for pointing this out. 
As we are adding in many logical definitions, this does cause some unexpected movement of terms and parentage.
Fixed.
Cheers,
Lynn
