### ISSUE TITLE
What happened with ICD9?

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#532]
Between the 2018-06-14 release and the current (2018-06-25) release, 1,613 ICD9 xrefs were removed. 
I haven't checked them all, but many correct xrefs were removed. Why were these all removed?

Example: 
In 2018-06-14/doid.owl, [gout](http://purl.obolibrary.org/obo/DOID_13189) had [ICD9CM:274](http://www.icd9data.com/2014/Volume1/240-279/270-279/274/default.htm)

**Comment by lschriml** [comment]
We cleaned out old xrefs.

**Comment by lschriml** [comment]
We can add them back in, if that is desired. 

Cheers,
Lynn

**Comment by stuppie** [comment]
What do you mean by "old" ? Did these come from a different source than the others? Do you get the sense that these are less accurate? I just randomly spot checked ~10 of them and they looked right. We can devise a way to check the suspect or old xrefs before removing them all..

**Comment by lschriml** [comment]
The ICD9 codes are less in use now that ICD10 is in place,
So it seems redundant to now keep both sets. 

We get both the ICD9 and ICD10 codes from the UMLS.

**Comment by stuppie** [comment]
Sorry I'm still not understanding. Before, there were ~4000 ICD9 xrefs, and now there are ~2500. What is different between the 1500 that were removed and the 2500 left? The 1500 that were removed are from UMLS? I think there is an argument to keep both. If the idea is to differentiate between directly curated ICD9s and those coming from UMLS, that can be done.

**Comment by lschriml** [comment]
Hello Greg,
 I am adding them back in, updating from the ICD9 2014 release. 
The files will be out next week.

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Greg,
 New DO file released with updated MESH and ICD9

Cheers,
Lynn
