### ISSUE TITLE
disease term typos

### ISSUE THREAD

**Issue by slaulederkind** [DiseaseOntology/HumanDiseaseOntology#533]
There seems to be a typo in each of the disease terms "methylmalonic acidemia cb1A type" (DOID:0060742) and "methylmalonic acidemia cb1B type" (DOID:0060743).  Considering the terms from different sources including OMIM, MeSH, and SnowMed and the fact that the symbols come from "cobalamin A" and "cobalamin B", I think the "1" in each term needs to be changed to "l" (That's a lower case L).

**Comment by slaulederkind** [comment]
Also consider the sibling terms in DO.

**Comment by lschriml** [comment]
Thank you Stan !!
 I will get this updated.

Cheers,
Lynn

**Comment by lschriml** [comment]
Agreed !! 
Fixed
