### ISSUE TITLE
MRD30 wrong parent

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#535]
[Term]
id: DOID:0070060
name: autosomal dominant non-syndromic intellectual disability 30
synonym: "MRD30" EXACT []
is_a: DOID:0070059 ! autosomal dominant non-syndromic intellectual disability 29

This parent term relationship does not make sense to me.

**Comment by lschriml** [comment]
Thank you !! 
Agreed, 
I will take a look and update the file.

Cheers,
Lynn

**Comment by lschriml** [comment]
fixed
