### ISSUE TITLE
cancer vs neoplasm

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#536]
In general, cancer is associated with malignancy (unless explicitly stated that it is benign).

Therefore I propose to review, the following parent term relationships or terms themselves:

1) [Term]
id: DOID:3675
name: childhood kidney neoplasm
synonym: "pediatric renal tumor" EXACT [NCI2004_11_17:C6563]
is_a: DOID:263 ! kidney cancer

unless further details will be added, it makes more sense to say that 'childhood kidney neoplasm' is-a 'kidney neoplasm', or rename the term to 'childhood kidney cancer'

2)[Term]
id: DOID:3842
name: skull base neoplasm
synonym: "tumors of Skull Base" EXACT [NCI2004_11_17:C4676]
is_a: DOID:1863 ! skull cancer

unless further details will be added, I'd rather say that 'skull base neoplasm' is-a 'skull neoplasm' or rename the term to 'skull base cancer'

3)[Term]
id: DOID:4618
name: maxillary neoplasm
def: "A jaw cancer and maxillary disease that effects the maxilla or upper jaw." 
synonym: "maxillary neoplasm" RELATED []
synonym: "upper jaw bone cancer" RELATED []
xref: MESH:D008441
xref: SNOMEDCT_US_2018_03_01:126550004
xref: UMLS_CUI:C0024954
xref: url:http\://www.vitals.com/disorders/ny-new_york-musculoskeletal_diseases-c05-upper_jaw_bone_cancer_maxillary_neoplasm-8094.html
is_a: DOID:1862 ! jaw cancer

illogical: if the term encompasses any maxillary neoplasms, (cancer or not) it CANNOT be a parent of 'jaw cancer'; also the xref url does not work for me

**Comment by lschriml** [comment]
Interestingly, in NCI, historically, neoplasm has been used interchangeable. 

For DO, to deal with this situation, we used: benign neoplasm to distinguish from neoplasm [aka malignancy], and to also avoid a large amount of term churning at that time.

In these examples, looking at the terms, and their usage, I see no reason not to update:

childhood kidney neoplasm --> childhood kidney cancer
skull base neoplasm --> skull base cancer
maxillary neoplasm. --> maxillary cancer
         
           maxillary cancer is a child of jaw cancer, not a parent 

Updated completed.

Cheers,
Lynn
