### ISSUE TITLE
leukemia parentage

### ISSUE THREAD

**Issue by slaulederkind** [DiseaseOntology/HumanDiseaseOntology#537]
In DO the parent of lymphoid leukemia (DOID:10747) is lymphoblastic leukemia (DOID:1037).  In MeSH, SNOMED, and ICD9 the reverse parent-child relationship is the case.  Maybe DO should consider making lymphoid leukemia (DOID:10747) the parent of lymphoblastic leukemia (DOID:1037).

**Comment by lschriml** [comment]
Hello Stan,
  Thank you!!
I will take a look.

Much appreciated,
Lynn

**Comment by lschriml** [comment]
Revisiting our classification of leukemia:
--> these are synonyms, I am going to merge 
lymphoid leukemia (DOID:10747) is lymphoblastic leukemia (DOID:1037)

Cheers,
Lynn
