### ISSUE TITLE
typo in [congenital nongoitrous hypothryoidism ...]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#538]
Terms with DOID:0070123..DOID:0070128 have a typo in their 3rd word of their names:

It is: [congenital nongoitrous hypothryoidism ...]

Should be: [congenital nongoitrous hypothyroidism ...]

Fortunately, the definitions are OK!

**Comment by lschriml** [comment]
Thank you,
I will make the updates.

Cheers,
Lynn

**Comment by lschriml** [comment]
updated
