### ISSUE TITLE
merge Jensen syndrome

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#539]
deafness dystonia syndrome (DOID:0050757)
and
Jensen syndrome (DOID:0050867)

should be merged.

OMIM merged these two: https://omim.org/entry/311150

ORPHA merged them too: https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=2868&Disease_Disease_Search_diseaseType=ORPHA&Disease_Disease_Search_diseaseGroup=3213&Disease%28s%29/group%20of%20diseases=Jensen-syndrome&title=Jensen-syndrome&search=Disease_Search_Simple

**Comment by lschriml** [comment]
Thank you ! !
I will take a look at these two.

Cheers,
Lynn

**Comment by lschriml** [comment]
merged, name updated.
