### ISSUE TITLE
spinocerebellar ataxia type 15/16

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#540]
according to OMIM and ORPHANET, the two terms below are the same -- merge suggested

spinocerebellar ataxia type 15 (DOID:0050965)
spinocerebellar ataxia type 16 (DOID:0050966)

**Comment by lschriml** [comment]
Thank you !!
Interesting, Hmm.
We would have made the two terms based on OMIM,
 I wonder if they are making changes. 
I will take a look and get it figured out. 

Cheers,
Lynn

**Comment by lschriml** [comment]
OMIM:606658

-- agreed, merge.

**Comment by lschriml** [comment]
merged.
