### ISSUE TITLE
NCI2004_11_17, MTHICD9_2006 xref prefixes

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#541]
There's almost 2k xrefs with the namespace "NCI2004_11_17". Is this equivalent to NCI? Does the date mean they are using the NCI version from 2004? Should these been treated differently than the NCI xrefs?

Similar question with "MTHICD9_2006" (count: 457) vs "ICD9CM_2006" (count: 455) vs "ICD9CM" (count: 2558)
What do the "MTH" and "2006" mean?

Thanks!

**Comment by lschriml** [comment]
Hello Greg,
 We did an update from UMLS.
Where we had previously brought in some of these xrefs (years ago),
 we wanted to refresh & enrich this information and bring in versions of the xrefs
that we hadn’t pulled from UMLS before. 
This occurs as we have pulled data over a time period. 


So for NCI, both NCI and NCI2004 can be treated as NCI.
We are still using the most up to date NCI file (our NCI: xref),
But we also wanted to represent their earlier release NCI 2004

The same for MTH (UMLS Metathesaurus)
And SNOMED

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Greg,
 Upon further investigation,
The new categories of xrefs were pulled from our synonym records.
They are correct, and are showing the provenance of the synonym. 
If it causes problems, it is fine with me if you want to not load them 
into Wikidata. 

Cheers,
Lynn
