### ISSUE TITLE
immune system cancer

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#544]
Couple of request:
1. Please add located_in immune system to immune system cancer so the inferred link to immune system disease will be created. This will capture these terms under an MGI slim category

2. Please review the relationship between hematologic cancer and immune system cancer. Currently hematologic cancer is a child of immune system cancer but I don't think this relationship is always correct. For example myelodysplastic syndrome (grandchild of hematologic cancer)  involves red cells and platelets as well as immune cells. The wiki reference for the DO term hematologic cancer explicitly states that this is tumors of both hematopoietic and lymphoid tissues.

Thanks,
Sue

**Comment by lschriml** [comment]
Thank you Sue ! !
Happy to add in the located in. 
I will take a look at these two cancers. 
Much appreciated,
Lynn

**Comment by lschriml** [comment]
logical definition added (Thank you James)

for hematologic cancer : agreed. 
Detangling some of the logical defs made for our earlier work, 
re-assigned is_a parent, to separate these two. 

Cheers,
Lynn
