### ISSUE TITLE
New term request: "idiopathic postprandial syndrome"

### ISSUE THREAD

**Issue by mikelivstone** [DiseaseOntology/HumanDiseaseOntology#545]
is_a hypoglycemia (DOID:9993)
xref: "Reactive hypoglycemia" ([HP_0012051](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0012051))

synonyms:
- carbohydrate intolerance
- adrenergic postprandial syndrome
- idiopathic reactive hypoglycemia

[Reference](https://www.healthline.com/health/idiopathic-postprandial-syndrome)

**Comment by lschriml** [comment]
Thank you Mike !!
I will take a look and get this reviewed. 

Cheers,
Lynn

**Comment by mikelivstone** [comment]
Thanks, Lynn. BTW, the link on the DO home page directed me to your old SourceForge ticketing system; I had to dig up the GitHub link through an old email.

-M

**Comment by lschriml** [comment]
Thank you Mike !! 

Can you tell me which link you clicked ? 

Much appreciated !! 

Lynn

**Comment by mikelivstone** [comment]
http://disease-ontology.org/faq/

…then I went to the line that said:

Where can I submit a question or term request?
New terms, definitions, suggestions and questions regard the Disease Ontology can be submitted to the DO Term Tracker<http://sourceforge.net/tracker/?group_id=79168&atid=555739>

Note where the link points.  (I just copied this right out of the web page.)

Thanks,
M

**Comment by lschriml** [comment]
Thank you Mike !! 

Missed that one when we moved to GitHub.
We will get it updated.

Much appreciated,
Lynn

**Comment by mikelivstone** [comment]
My pleasure.  It’s weird because it used to point to GitHub for all of my previous tickets.  Did you move the HTML to GitHub recently?

**Comment by lschriml** [comment]
That is weird.
We moved the system to GitHub a couple of years ago.
Didn’t make any changes in the html.

My engineers were working on the back end last week.
I will check with them, to see if that is what happened. 

Cheers,
Lynn

**Comment by mikelivstone** [comment]
Yeah, that’s possible.  It might have been an unintentional rollback.

**Comment by Apujar** [comment]
Hi Lynn, 

There seems to an active debate in scientific papers and by clinicians about the occurrence of Hypoglycemia following the intake of carbohydrates (referred to as reactive, functional and idiopathic postpandrial forms) to be a "nondisease". Research articles also indicate that the diagnosis criteria are being questioned. 

https://jamanetwork.com/journals/jama/fullarticle/391267 
http://diabetes.diabetesjournals.org/content/diabetes/30/12/996.full.pdf 
http://diabetes.diabetesjournals.org/content/30/12/996.long 
https://www.uptodate.com/contents/postprandial-reactive-hypoglycemia 

cheers
anu

**Comment by lschriml** [comment]
Thank you Anu,
  I will take a look when I am back at IGS. 
Cheers,
Lynn

**Comment by lschriml** [comment]
New term request: "idiopathic postprandial syndrome
is_a hypoglycemia (DOID:9993)
xref: "Reactive hypoglycemia" 
   synonyms:
     carbohydrate intolerance
     adrenergic postprandial syndrome
     idiopathic reactive hypoglycemia

--> looking at literature, via PubMed: 
   the term postprandial syndrome is not often used,
 and idiopathic postprandial syndrome, seems to be mainly discussed in a 1984 article
 https://www.ncbi.nlm.nih.gov/pubmed/6690833
however, 
  I was able to find a few 2014 papers for postprandial hypoglycemia

https://www.ncbi.nlm.nih.gov/pubmed/24246338
https://www.ncbi.nlm.nih.gov/pubmed/25381469

--> the information supports this term as a phenotype, aka insulin crash, but not a disease. 

I am going to hold off on creating a disease term. 

Cheers,
Lynn
