### ISSUE TITLE
New Term Request: Blepharocheilodontic syndrome

### ISSUE THREAD

**Issue by LeylaR** [DiseaseOntology/HumanDiseaseOntology#546]
Could you please create a new term: Blepharocheilodontic syndrome
http://omim.org/entry/119580
Here's a relevant publication:
https://www.ncbi.nlm.nih.gov/pubmed/?term=29348693%5Buid%5D
Thanks,
Leyla

**Comment by lschriml** [comment]
Hello Layla,
  Thank you for the term request.
Happy to add this term.

Additional references:
https://ghr.nlm.nih.gov/condition/blepharocheilodontic-syndrome
http://disorders.eyes.arizona.edu/category/alternate-names/bcd-syndrome

And we also add: 
> Blepharocheilodontic syndrome
> 
OMIM: 617681
https://omim.org/entry/617681

Cheers,
Lynn

**Comment by lschriml** [comment]
Added, the updates will be public with our next release.

Cheers,
Lynn
