### ISSUE TITLE
Defintion and synonyms DOID:3526  stroke

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#547]
DOID:3526
Synonym : ischemic stroke
Def:  Vascular occlusion leading to death of neural tissue of the brain and resulting in loss of motor, sensory and/or cognitive function.
OMIM: #601367

**Comment by lschriml** [comment]
Thank you for the adding to the DO !!
Do you have a reference for this definition ?

Cheers,
Lynn

**Comment by cerivs** [comment]
Hi Lynn, 
I used the OMIM entry to write a concise definition. 
Ceri

**Comment by lschriml** [comment]
Thank you !! 
I have updated the record, adding the definition and OMIM ID.
