### ISSUE TITLE
NTR Intracranial hemorrhage and child terms

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#548]
NTR intracranial hemorrhage
Def:  Bleeding within the skull
is_a: vascular disease DOID:178
https://en.wikipedia.org/wiki/Intracranial_hemorrhage

NTR: intracerebral hemorrhage
Def: intracranial bleed that occurs within the brain tissue or ventricles.
https://en.wikipedia.org/wiki/Intracerebral_hemorrhage
Is_a  NTR Intracranial hemorrhage

NTR: subdural hemorrhage
Def: intracranial bleeding that occurs between the dura and  arachnoid.  Can lead to subdural hemotoma
Is_a  NTR Intracranial hemorrhage
narrow xref  ICD 10 I62.00
narrow synonym: Nontraumatic subdural hemorrhage

**Comment by lschriml** [comment]
Thank you for the new terms !!

**Comment by tutajm** [comment]
You can also consider to create a 'container' term [hemorrhage]. And, if you feel to it, you can all different subtypes of hemorrhage known, not only [intracranial hemorrhage] :-)

**Comment by lschriml** [comment]
Hello Yvonne,
   I have been re-researching these terms, to see how best to handle them.
Trying to be careful to classify them properly, as bleeding and hemorrhage are both symptoms, rather than diseases.  

--> I think the best classification for these are as symptoms, rather than diseases. 

vascular symptom 
      intracranial hemorrhage -- agreed, is a type of bleeding that occurs inside the skull 
          intracerebral hemorrhage. -- occurs within the brain tissue or ventricles.
          subdural hemorrhage -- occurs between the dura and arachnoid

Cheers,
Lynn

**Comment by lschriml** [comment]
symptoms have been added to the symptom ontology
