### ISSUE TITLE
cerebrovascular disease term name

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#549]
DOID:6713  is restricted to use in arterial disease,  can the term name be changed to reflect this usage.  Perhaps cerebroarterial disease would be a better name for arterial brain diseases.

**Comment by lschriml** [comment]
Thank you for your question !!
It should include both.

Cheers,
Lynn

**Comment by cerivs** [comment]
Then it looks like the logical definition needs fixing.  Right now cerebrovascular disease is_a artery disease it probably should be is_a vascular disease.




 DOID:178

**Comment by lschriml** [comment]
Thank you for pointing this out. 
I have fixed this. 
cerebrovascular disease, is now a is_a of vascular disease,
 and the logical definition has been fixed.

Cheers,
Lynn
