### ISSUE TITLE
incorrect synonym to DOID:0090014

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#550]
[Term]
id: DOID:0090014
name: severe combined immunodeficiency, autosomal recessive, T cell-negative, B cell-positive, Nk cell-positive

currently, this term has:

synonym: "autosomal recessive T cell-negative, B-cell negative, NK cell-positive SCID" EXACT []

This is wrong, as the synonym should be:

synonym: "autosomal recessive T cell-negative, B-cell positive, NK cell-positive SCID" EXACT []

Btw, why not to assign a synonym to similar term:

[Term]
id: DOID:0090013
name: severe combined immunodeficiency, autosomal recessive, T cell-negative, B cell-negative, Nk cell-positive
synonym: "autosomal recessive T cell-negative, B-cell negative, NK cell-positive SCID" EXACT []

**Comment by lschriml** [comment]
Thank you for these updates !!
Great idea on the synonyms !!
We will get them updated.

Cheers,
Lynn

**Comment by Apujar** [comment]
The synonyms have been updated.

Cheers
anu
