### ISSUE TITLE
merge 2 terms for X-linked dilated cardiomyopathy

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#551]
I believe, these two terms are identical and should be merged:

id: DOID:0110461
name: dilated cardiomyopathy 3B

id: DOID:0060561
name: DMD-related dilated cardiomyopathy

Also, I propose to change the name to [X-linked dilated cardiomyopathy] as per https://ghr.nlm.nih.gov/condition/x-linked-dilated-cardiomyopathy

**Comment by lschriml** [comment]
Thank you for pointing out this update !!

Agreed, 
   I have merged the two diseases, as recommended and updated the disease name. 
Added xrefs and papers. 

Cheers,
Lynn
