### ISSUE TITLE
new term requests for phenotypic series PS250950

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#552]
Please kindly add 2 missing terms to complete the phenotypic series PS250950 (https://www.omim.org/phenotypicSeries/PS250950).

The missing terms are:
https://www.omim.org/entry/617248
https://www.omim.org/entry/617698

Also please add an xref OMIM:PS250950 to term DOID:0060336 [3-methylglutaconic aciduria ]

**Comment by lschriml** [comment]
Thank you for pointing these out. We get them added.
Cheers,
Lynn

**Comment by Apujar** [comment]
The two terms and the xref have been added. 

Cheers
anu

**Comment by sbello** [comment]
Hi Lynn,
When the first members of this series were entered we changed the Roman numerals to Arabic ones. Is the policy still to use Arabic numbers in the primary label? The two new entries are using Roman numerals. I just want to be sure I'm doing this correctly when I split other series.
Thanks,
Sue

**Comment by lschriml** [comment]
Hello Sue,
 I see in OMIM that they are using Roman numerals.
I am fine with continuing to use arabic ones. 
Do you have a preference ?

Cheers,
Lynn

**Comment by sbello** [comment]
No preference, as I recall Elvira said we should use Arabic ones so that was what I did. It just jumped out to me that new terms were using Roman when the older ones weren't.

**Comment by lschriml** [comment]
Overall, 
I think we have followed the nomenclature from OMIM.

To keep that consistent, I would suggest that we move back to Roman Numbers in the name and move the Current name to a synonym.

Cheers,
Lynn

**Comment by sbello** [comment]
Sounds good. I'll stop changing the number in OMIM labels from now on.
Sue
