### ISSUE TITLE
"artemis deficiency" and "SCID due to artemis deficiency"

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#553]
Can these be reviewed? I think "severe combined immunodeficiency with sensitivity to ionizing radiation" AKA "SCID due to artemis deficiency" should be a subclass of "artemis deficiency"?

http://www.disease-ontology.org/?id=DOID:0090012
http://www.disease-ontology.org/?id=DOID:0060006

**Comment by lschriml** [comment]
Thank you for pointing this out Greg. 
Upon review, I see that these should be merged. 
Cheers,
Lynn
