### ISSUE TITLE
"Autosomal dominant hypocalcemia" is not an "acquired metabolic disease"

### ISSUE THREAD

**Issue by okkn** [DiseaseOntology/HumanDiseaseOntology#554]
"Disease of metabolism" (DOID:0014667) is devided into "acquired metabolic disease" (DOID:0060158) and "inherited metabolic disorder" (DOID:655). And now "mineral metabolism disease" (DOID:0050032) is a child of "aquired metabolic disease" (DOID:0060158).

However, some descendant entities of "mineral metabolism disease" (DOID:0050032), including "autosomal dominant hypocalcemia" (DOID:0090109), are not acquired diseases, but obviously inherited diseases.

I think it would be unreasonable to devide all of the metabolic diseases into acquired ones and inherited ones just under the node of "disease of metabolism" (DOID:0014667).

**Comment by lschriml** [comment]
Thank you for bringing this to our attention. 
Agreed, the autosomal dominant hypocalcemia terms should be classified under the inherited metabolic disorder parent term. 

For metabolic diseases, it is important for us to distinguish between inborn errors of metabolism and acquired metabolic diseases, as their etiology is quite distinct. 

We will update the parentage, definitions for these terms.

Cheers,
Lynn

**Comment by lschriml** [comment]
I have made the updates.
Moved this term to be a child of metal metabolism disorder
Cheers,
Lynn
