### ISSUE TITLE
Oat cell carcinoma of lung

### ISSUE THREAD

**Issue by mikelivstone** [DiseaseOntology/HumanDiseaseOntology#555]
The term "[lung small cell carcinoma](https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_5409)" has both:

- a synonym "Oat cell carcinoma of lung" and
- a child "[lung oat cell carcinoma](https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_5411)"

That's not exactly a TPV but should probably be resolved, or else the term is logically its own child!

**Comment by lschriml** [comment]
Thank you Mike, 
  We will take a look !! 

Much appreciated,
Lynn

**Comment by Apujar** [comment]
Hello Mikelivstone,

The mismatched synonyms and SNOMED xrefs have been cleaned up in DO. 

Cheers
anu
