### ISSUE TITLE
orphanet Emery-Dreifuss muscular dystrophy

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#557]
Can you please check the xrefs for this, for orphanet they are not exact matches

http://www.disease-ontology.org/?id=DOID:11726

**Comment by Apujar** [comment]
Hello Stuppie,

Thank you for pointing out the mismatch, they are currently being reviewed and will be reassigned. 

Cheers
anu

**Comment by lschriml** [comment]
Hello Greg,
 thank you for pointing this out.

We have split this term into it's subtypes (as outlined in OMIM). 

I have reviewed and updated the xrefs. 

Cheers,
Lynn
