### ISSUE TITLE
[cold-induced sweating syndrome] issue

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#558]
1) Currently [cold-induced sweating syndrome] (DOID:0060294) is-a [autosomal dominant disease]. However, the popular sources like orphanet, malacards or https://ghr.nlm.nih.gov/condition/cold-induced-sweating-syndrome, assign 'autosomal recessive' inheritance.

2) How about adding more parent terms? 'sweat gland disease'?

**Comment by Apujar** [comment]
Hello Tutajm,

Thank you for pointing this out. The DO file has been updated with the correct inheritance. 

The suggestion for new parent term 'sweat gland disease' is being reviewed. 

Cheers
anu
anu

**Comment by lschriml** [comment]
Hello Tutajm,
   I have updated this record:
parent = syndrome
added three child terms for the 3 OMIM subtypes.
Added definitions, xrefs. 

Cheers,
Lynn
