### ISSUE TITLE
add parentage for anti-GBM disease

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#559]
Let's start with: https://www.healthline.com/health/anti-glomerular-basement-membrane
https://unckidneycenter.org/kidneyhealthlibrary/glomerular-disease/anti-gbm-disease/
https://en.wikipedia.org/wiki/Goodpasture_syndrome

Goodpasture syndrome (DOID:9808)
anti-basement membrane glomerulonephritis (DOID:4780) 

Facts: Anti-GBM disease that only affects the kidneys is called anti-GBM glomerulonephritis. Anti-GBM disease that causes both kidney disease and lung disease is called Goodpasture’s syndrome. 

Therefore, for anti-basement membrane glomerulonephritis (DOID:4780):
1) add parent is_a: DOID:417 ! autoimmune hypersensitivity disease

And for [Goodpasture’s syndrome]:
1) add parent is-a DOID:4780, 
2) add parent is-a [interstitial lung disease (DOID:3082)]
3) add parent [syndrome] DOID:225 
4) drop parent DOID:417 (redundant -- implied by DOID:4780 parentage)

It won't hurt to add some synonyms to these terms as well.

**Comment by lschriml** [comment]
In DO, Goodpasture syndrome is_a asserted child of autoimmune hypersensitivity disease
     synonyms of Goodpasture syndrome:  anti-Glomerular Basement Membrane Disease
                                                                       anti-GBM disease

Anti-GBM disease is the result of injury to small blood vessels (capillaries) in the kidney or lung. 
Anti-GBM disease that causes both kidney disease and lung disease is called Goodpasture’s syndrome

Goodpasture syndrome (GPS), also known as anti-glomerular basement membrane disease, is a rare autoimmune disease in which antibodies attack the basement membrane in lungs and kidneys, leading to bleeding from the lungs and kidney failure. 

       -- moving: (to be an asserted is_a child of Goodpasture syndrome)
                 anti-basement membrane glomerulonephritis (DOID:4780)
                        Anti-GBM disease that only affects the kidneys is called anti-GBM glomerulonephritis

Axioms have been added for the lung and kidney, thus inferred parents. 

Cheers,
Lynn
