### ISSUE TITLE
Metadata Cleanup

### ISSUE THREAD

**Issue by rctauber** [DiseaseOntology/HumanDiseaseOntology#560]
Hey Lynn -

I know this week is busy with the conference so I wanted to make an issue for this so it doesn't get lost in the emails.

I’d like to start using the ROBOT report feature to check for violations within the ontology. We can't use it as a check until we fix things that are being logged as ERRORs: duplicate definitions, duplicate labels, ontology metadata, and missing labels.

**Ontology metadata**:
The ontology header needs the following annotations:
* license
* title
* description (we have a comment, but not a `dc:description` annotation)

**Duplicate definitions**:

| Class 1 | Class 2 |
| --- | --- |
| DOID:0110825 (hereditary spastic paraplegia 9B) | DOID:0110824 (hereditary spastic paraplegia 9A) |
| DOID:0110914 (infantile hypophosphatasia) | DOID:0110915 (childhood hypophosphastasia) |
| DOID:0070069 (autosomal dominant non-syndromic intellectual disability 39) | DOID:0070070 (autosomal dominant non-syndromic intellectual disability 40) |
| DOID:0110735 (neurodegeneration with brain iro accumulation 2a) | DOID:0110736 (neurodegeneration with brain iro accumulation 2b) |
| DOID:3324 (mood disorder) | DOID:2030 (anxiety disorder) |
| DOID:5275 (gallbladder leiomyosarcoma) | DOID:4057 (gallbladder rhabdomyosarcoma) |

**Duplicate labels**:
For these, at least one of each pair is deprecated suggesting we can just change the deprecated ones to be altIDs of the non-deprecated ones.

| Class 1 | Class 2 |
| --- | --- |
| obo:DOID_0040094 | obo:DOID_0050146 |
| obo:DOID_9814 | obo:DOID_0050827 |
| obo:DOID_12804 | obo:DOID_0050808 |
| obo:DOID_1173 | obo:DOID_0050770 |
| obo:DOID_8485 | obo:DOID_0050595 |
| obo:DOID_0080025 | obo:DOID_14789 |
| obo:DOID_4716 | obo:DOID_6949 |

Finally, there are a handful of entities that are missing labels. All of these are properties, which we can easily fix by just adding labels!

**Comment by lschriml** [comment]
Great idea !! 
Agreed

**Comment by lschriml** [comment]
Updated some of these fixes: 
Fixed:
DOID:0110914 (infantile hypophosphatasia
hereditary spastic paraplegia 9A and 9B
autosomal dominant non-syndromic intellectual disability 39 and 40
mood disorder
gallbladder leiomyosarcoma
gallbladder rhabdomyosarcoma

For: two terms, same name, obsoleted term, needed to be renamed 'obsoleted' term name: 

obo:DOID_0040094 |   obo:DOID_0050146
        DOID_0050146. autoimmune glomerulonephritis - obsoleted -- renamed 
obo:DOID_9814 | obo:DOID_0050827
      DOID_9814 -- renamed
obo:DOID_12804 | obo:DOID_0050808
     DOID:0050808. renamed 

obo:DOID_1173 | obo:DOID_0050770
      DOID_1173. -- renamed
       DOID:0050770:  polycystic liver disease

obo:DOID_8485 | obo:DOID_0050595
    -- reinstated mucormycosis 

obo:DOID_0080025 | obo:DOID_14789
   DOID_0080025.  renamed 
obo:DOID_4716 | obo:DOID_6949
DOID:6949 -renamed

Cheers,
Lynn

**Comment by rctauber** [comment]
For the duplicated labels that you're marking as `obsolete`, do you want to merge them into the non-obsoleted terms instead?

**Comment by lschriml** [comment]
Good idea Becky !!

**Comment by rctauber** [comment]
Resolved by 83b47f3
