### ISSUE TITLE
Duplicate IRIs

### ISSUE THREAD

**Issue by rctauber** [DiseaseOntology/HumanDiseaseOntology#561]
There are a handful of terms that have had their IRIs duplicated. It looks like this isn't in the release yet, so I can give them new IRIs over the weekend as long as they aren't in use yet. @lschriml - do you know if these new terms have been implemented by anyone who might be using `doid-edit.owl`?

The *prefix* for these terms was incorrectly set as `http://purl.obolibrary.org/obo#DOID_` instead of `http://purl.obolibrary.org/obo/DOID_` so Protege didn't catch these as duplicates.

* 3-methylglutaconic aciduria type VIII (not duplicated but needs the `#` fixed)
* 3-methylglutaconic acuduria type IX (duplicates 'neoplastic disease')
* absense epilepsy (duplicates 'Seckel syndrome 1')
* craniolenticulosutural dysplasia (duplicates 'myeloid neoplasm')
* drug-induced hearing loss (duplicates 'Seckel syndrome 8')
* post-cardiac arrest syndrome (duplicates 'blastoma')
* rippling muscle disease 1 (duplicates 'Seckel syndrome 6')
* oligoasthenoteratozoospermia (duplicates 'Seckel syndrome 4')

**Comment by lschriml** [comment]
Hello Becky,
  Can you determine where these came from ? Which commit ?

No one other than the DO team uses the doid-edit.owl file. 

Thank you for finding this and addressing the issue !!

Great talks today at ICBO !!

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Becky,
 I had a look at these. 
They are the DOIDs created this week by Anu, based on the DOID ID range.

Becky: please go ahead and fix these IRIs. 
Can you assign new DOIDs for these terms ?

Anu: can you update your ID space so that your IRI is of the format: 
http://purl.obolibrary.org/obo/DOID_

Thank you,
Lynn

**Comment by Apujar** [comment]
Hello Becky, Lynn,


Those terms are from my commits, indeed.

Thank you, Becky! I am very glad that the error was spotted so early before I created more terms.


I will update to the correct IRI format.


Cheers

anu

________________________________

**Comment by rctauber** [comment]
Hi @Apujar - I'm updating these now and I also noticed that the definitions are annotations on the label annotations. I'll fix these as well, but please make sure the definitions are separate annotations!

Thanks!

**Comment by rctauber** [comment]
Resolved by 3893993
