### ISSUE TITLE
[polycythemia vera] parentage tune up

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#562]
Currently, [polycythemia vera], DOID:8997, is_a: DOID:8432 ! polycythemia

However, many sources, including https://www.omim.org/entry/263300, consider [polycythemia vera] to be a form [primary polycythemia] DOID:10780

Suggestion: make [primary polycythemia] DOID:10780 the parent term for [polycythemia vera], instead of [polycythemia]

**Comment by lschriml** [comment]
Agreed, polycythemia vera is a child of primary polycythemia.

Additionally, it is a rare cancer, a myeloproliferative neoplasm.

Cheers,
Lynn
