### ISSUE TITLE
merge DOID:0080126 and DOID:0050556

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#564]
PROPOSAL: merge [infantile onset spinocerebellar ataxia] (DOID:0050556) and [mitochondrial DNA depletion syndrome 7] (DOID:0080126).

JUSTIFICATION: Per latest research performed by OMIM (https://www.omim.org/entry/271245), these two terms represent the same disease.

**Comment by lschriml** [comment]
Thank you !!
I will review for the merge.
I am on vacation for the next week.
Cheers,
Lynn

**Comment by lschriml** [comment]
Looking at this potential merge: 

I am updating the OMIM assignments, 
reviewed OMIM IDs for all of the mitochondrial DNA depletion syndrome terms.
Added two new subtypes. 

And merging infantile onset spinocerebellar ataxia into mitochondrial DNA depletion syndrome 7

--> in OMIM:
I see that OMIM:271245 is now = mitochondrial DNA depletion syndrome 7

    OMIM: 256810
  is now: 
     mitochondrial DNA depletion syndrome 6

Cheers,
Lynn
