### ISSUE TITLE
equivalence axiom for hypothalic disease

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#565]
The axiom for hypothalamic disease is currently 
'thalamic disease'
 and ('located in' some hypural)
But hypural is a bone of the fin. I would suggest using instead hypothalamus (UBERON:0001898)

**Comment by lschriml** [comment]
Thank you Sue !!
 We will get this updated.
Cheers,
Lynn

**Comment by lschriml** [comment]
Fixed.
Thank you Sue !!
