### ISSUE TITLE
New Term Request Aortic Valve Disease 1 and 2 under DOID:62

### ISSUE THREAD

**Issue by erbolton** [DiseaseOntology/HumanDiseaseOntology#566]
OMIM Entries:

# 109730
AORTIC VALVE DISEASE 1; AOVD1

Alternative titles; symbols

AORTIC VALVE DISEASE
BICUSPID AORTIC VALVE; BAV
AORTIC VALVE, BICUSPID
AORTIC VALVE, CALCIFICATION OF
AORTIC STENOSIS, CALCIFIC

Related to mutation in NOTCH1 gene
____________________________________________________________________
# 614823
AORTIC VALVE DISEASE 2; AOVD2

Alternative titles; symbols

BICUSPID AORTIC VALVE
AORTIC VALVE STENOSIS

Related to mutation in SMAD6 gene

Thanks!

Liz Bolton

**Comment by lschriml** [comment]
Hello Liz,
   In DO currently: 
DOID: 62  aortic valve disease
DOID: 1712 aortic valve stenosis 
            child terms:
             subvalvular aortic stenosis
             supravalvular aortic stenosis


Researching these diseases: 
  the aortic valve stenosis -- are conditions where the valve opening has narrowed

whereas the two OMIM IDs represent two genetic diseases, familial forms of aortic valve disease: 

OMIM:109730  aortic valve disease 1
               links to:  GHR for NOTCH1 gene 

OMIM:614823. aortic valve disease 2 
              in OMIM   links to:
               Orphanet: Familial bicuspid aortic valve 
                    -- this term in Orphanet links to both OMIM IDs 
                     definition: defined as a presence of abnormal two-leaflet aortic valve in at least 2 first-
                                      degree relatives.


Updates:  
  -- creating a new child term of aortic valve disease: 
               bicuspid aortic value disease 
       --   adding PS109730 
       --  will link to Orphanet, Familial bicuspid aortic valve
             will add Orphanet: 402075
          -- I am not going to add the ICD-10: Q23.1 xref, listed in Orphanet, as it to a non-specific term
          -- will create two child terms for: 
                   aortic valve disease 1 and aortic valve disease 2 

-- will remove OMIM:109730 and OMIM:614823 from DOID:1712, aortic valve stenosis

DOID:1712, aortic valve stenosis
     MESH:D001024 & NCI are  correct
     removing: ICD9CM:395.0 -- not correct xref 
     removing ICD10 xrefs, not correct xrefs


More info on aortic valve stenosis -- I will update DO with this info.

DOID: 1712 aortic valve stenosis
          GARD:5830 -- Aortic valve stenosis (AVS) is a condition characterized by narrowing of the 
                                   heart's aortic valve opening. 
           OMIM:109730 and OMIM:614823 
           definition: An aortic valve disease that has_physical_basis_in incomplete 
                             opening of the aortic valve.
   
          child terms:
             subvalvular aortic stenosis    GARD:5052
                 aka: subaortic stenosis

         It is characterized by a narrowing of the section of the heart under the aortic valve resulting in left ventricular outflow obstruction.  

          https://www.ncbi.nlm.nih.gov/pubmed/26731888
          https://www.ncbi.nlm.nih.gov/pubmed/29377232

             supravalvular aortic stenosis. GARD:743, OMIM:185500
                    Supravalvular aortic stenosis (SVAS) is a type of heart defect that develops before birth. 
                     It is characterized by a narrowing of the section of the aorta just above the       
                      valve that connects the aorta to the heart.
           https://rarediseases.info.nih.gov/diseases/743/supravalvular-aortic-stenosis
          https://ghr.nlm.nih.gov/condition/supravalvular-aortic-stenosis


Updates have been added to DO.
Cheers,
Lynn
