### ISSUE TITLE
New Term Request: Culler-Jones Syndrome

### ISSUE THREAD

**Issue by erbolton** [DiseaseOntology/HumanDiseaseOntology#567]
# 615849
CULLER-JONES SYNDROME; CJS

Alternative titles; symbols

PALLISTER-HALL SYNDROME 2, FORMERLY; PHS2, FORMERLY
Caused by mutations in the GLI2 gene.

Mutation in the GLI2 gene also causes holoprosencephaly-9 (HPE9; 610829), or HPE-like features, which may be considered at the severe end of the spectrum of features associated with GLI2 mutations.

Thanks!

Liz Bolton

**Comment by lschriml** [comment]
added to DO.
