### ISSUE TITLE
Expansion of DO terms, to include multiple subtypes of a disease

### ISSUE THREAD

**Issue by obophenotype-user** [DiseaseOntology/HumanDiseaseOntology#57]
I am creating this ticket to help keep track of DO terms that need to be expanded. 
We will add to this list and use this ticket to keep track of our progress. 

Disease term:

(1) spastic paraplegia (DOID: 2476 name:hereditary spastic paraplegia

    There are at least 15 subtypes of spastic paraplegia.
Mine Genetic Home Reference, OMIM and Orphanet, to define each type and add child terms with definitions to DO. 
http://ghr.nlm.nih.gov/search?query=spastic+paraplegia&Search=

(2) spinocerebellar ataxia  -- at least 30 subtypes
   examine Harrison's list of types. 

Reported by: lschriml

Original Ticket: [diseaseontology/feature-requests/57](https://sourceforge.net/p/diseaseontology/feature-requests/57)

**Comment by lschriml** [comment]
OMIM IDs added to DO term for many spastic paraplegia subtypes.
