### ISSUE TITLE
Congenital anomalies of the kidney and urinary tract 1 (CAKUT1)

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#570]
Hi,

I would like to request this term: Congenital anomalies of the kidney and urinary tract 1 (CAKUT1). OMIM: 610805. ORPHANET: 93545 appears to be a term for Renal or urinary tract malformation (CAKUT). The article is PMID:23862974 in ZFIN. Also referenced in the OMIM record. Thanks

Sridhar

**Comment by lschriml** [comment]
Thank you Sridhar !!
