### ISSUE TITLE
multinucleated neurons, anhydramnios, renal dysplasia, cerebellar hypoplasia and hydranencephaly (MARCH)

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#571]
Hi,

I would like to request this term: multinucleated neurons, anhydramnios, renal dysplasia, cerebellar hypoplasia and hydranencephaly (MARCH). OMIM: 236500, ORPHANET: 500135 .The article is PMID:28264986. Thanks

Sridhar

**Comment by lschriml** [comment]
Thank you Sridhar,
  We will review and get it added.
Cheers,
Lynn

**Comment by lschriml** [comment]
Added, I am going to hold off on adding the Orphaned ID, as their record is not yet populated.
