### ISSUE TITLE
problem with the doid.obo file

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#573]
Hi Lynn, 
There is an error in the doid.obo file that is causing the parsing of the file to fail in the Alliance loader. Dustin has traced this back to an error at line 14790 for term DOID:0060281, the cross-reference has a mis-placed comma: [, url:http\://en.wikipedia.org/wiki/Photosensitive_epilepsy]
Removing that comma allowed the ontology to be correctly parsed and the "definition", "xref", "synonyms" fields to come through. 
Would you please remove the offending comma from the edit file and push out a new release.
Thank,s
Sue

**Comment by sbello** [comment]
Looking in the doid-edit.owl file there appears to be an empty database_cross_reference field for the defintion. My guess is this is what is causing things to break

**Comment by lschriml** [comment]
Thank you Sue and Dustin !! 

I see the same thing. Fixed.
and pushing a new release.

Much appreciated !!!!
Cheers,
Lynn
