### ISSUE TITLE
duplicate term: Peters plus syndrome

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#574]
Hello, I believe, these two terms below are identical, so I do propose to merge them:

id: DOID:0080201
name: Peters plus syndrome

id: DOID:0070312
name: Peters-Plus Syndrome

Also, since there is a synonym [Peters anomaly-short limb dwarfism syndrome] please consider adding the term [Peters anomaly DOID:0060673] as a parent term; it looks to me, [Peters plus syndrome] is an 'extended' version of 'Peters anomaly'.

Thank you, Marek

**Comment by lschriml** [comment]
Thank you Marek !! 
I will take a look and get these updated.

Cheers,
Lynn

**Comment by lschriml** [comment]
Thank you Marek for catching this recent duplicate entry.
I have merged the two records. 

Peters anomaly is an eye disease, Peters plus syndrome includes this anomaly plus, limb, facial, palate and ID features -- together they are a syndrome. 

So I will not make Peters anomaly the parent term. 

Cheers,
Lynn
