### ISSUE TITLE
typo: bad parentage for synonym 

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#576]
[Term]
id: DOID:0060550
name: ablepharon macrostomia syndrome
synonym: "poikiloderma with neutropenia, Clericuzio type" EXACT []

I could not find any justification for the synonym listed above to be assigned to DOID:0060550.

However, the synonym mentioned fits nicely to the other term, DOID:0060551:

[Term]
id: DOID:0060551
name: poikiloderma with neutropenia

**Comment by lschriml** [comment]
Agreed, I have made the fix.
Thank you for pointing this out !! 

Cheers,
Lynn
