### ISSUE TITLE
update MGI slim set

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#577]
Hi Lynn,
Given the changes to DO structure we have a number of redundant terms in the MGI slim. Therefore I would like to remove the following terms from the MGI slim:

DOID:0050013 | carbohydrate metabolism disease
DOID:0060388 | chromosomal deletion syndrome
DOID:1925 | Coffin-Siris syndrome
DOID:170 | endocrine gland cancer
DOID:3119 | gastrointestinal system cancer
DOID:0060056 | hypersensitivity reaction disease
DOID:14793 | hypohidrotic ectodermal dysplasia
DOID:3093 | nervous system cancer
DOID:374 | nutrition disease
DOID:574 | peripheral nervous system disease
DOID:193 | reproductive organ cancer
DOID:5093 | thoracic cancer

Thanks,
Sue

**Comment by lschriml** [comment]
Hello Sue,
 No problem. 
The MGI slim has been updated.

Please let me know if you want other terms added.

Cheers,
Lynn
