### ISSUE TITLE
brain ischemia equivalence axiom

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#578]
The equivalence axiom for brain ischemia is current:
SYMP_0000209
 and (RO_0001025 some UBERON_0000955)
I think instead it should be 
DOID_326
 and (RO_0001025 some UBERON_0000955)
While both the symptom and DO terms are called 'ischemia' the use of the symptom instead of the DO term is causing the symptom to be inferred to be a parent of brain ischemia in the doid-merged file and this is breaking the MGI load.
Thanks,
Sue

**Comment by lschriml** [comment]
Thank you Sue !! 
We will get this fixed right away.

Cheers,
Lynn

**Comment by lschriml** [comment]
Fixed Sue,
Pushing a new release now. 

Cheers,
Lynn
