### ISSUE TITLE
duplicate terms: sideroblastic anemia with spinocerebellar ataxia

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#579]
id: DOID:0060064
name: sideroblastic anemia with spinocerebellar ataxia

id: DOID:0050554
name: X-linked sideroblastic anemia with ataxia

Consider to merge these terms, as they seem to be the same. For example look at this: https://www.dovemed.com/diseases-conditions/sideroblastic-anemia-and-spinocerebellar-ataxia/

**Comment by lschriml** [comment]
Thank you for pointing this out. 
here is my review and updates I will make today.

Cheers,
Lynn 




Looking at OMIM for 
      sideroblastic anemia.  https://www.omim.org/phenotypicSeries/PS300751
          sideroblastic anemia 1. X-linked recessive, OMIM:300751
                 [DOID:0060063: X-linked sideroblastic anemia]
                 --> will update DO's disease term name

          sideroblastic anemia 2, pyridoxine-refractory, autosomal recessive, OMIM:205950
           [DOID:0060065] 
                  pyridoxine-refractory autosomal recessive sideroblastic anemia
                 --> will update the disease name to align with OMIM 

          sideroblastic anemia 3, pyridoxine-refractory, autosomal recessive, OMIM:616860
                --> will update: DOID:0060066


          sideroblastic anemia 4, autosomal dominant, OMIM:182170
             [DOID:0060335]
                   autosomal dominant sideroblastic anemia
               --> will update the disease name to align with OMIM 

        sideroblastic anemia with spinocerebellar ataxia, X-linked recessive, OMIM:301310
             [DOID:0050554]
         --> will merge id: DOID:0060064 into this term. 
https://rarediseases.info.nih.gov/diseases/668/anemia-sideroblastic-and-spinocerebellar-ataxia


--> will add the OMIM:PS to sideroblastic anemia

**Comment by lschriml** [comment]
one adjustment: 

sideroblastic anemia 3, pyridoxine-refractory, autosomal recessive, OMIM:616860
            --> will create a new DOID
