### ISSUE TITLE
X linked disease

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#582]
Hi Lynn,
Please consider changing the label of the term 'X-linked disease' (DOID:0060827) to 'X-linked monogenic disease' as this better fits the definition. I suggest the change because with the new inferred relationships I was wondering why many X-linked diseases were listed under genetic disease and not under X-linked genetic disease.
Same thing for Y-linked disease (DOID:0050738)

Also, please review the subclass statements for monogenic X-linked diseases. I'm finding many of these out under genetic disease rather than under 'X-linked disease'. Possibly the GO term for X chromosome (http://purl.obolibrary.org/obo/GO_0000805) could be added to the subclass designation to push this down to X-linked disease?

Examples:
X-linked lymphoproliferative syndrome 2 (DOID:0060706)
X-linked lymphoproliferative syndrome 1 (DOID:0060705)
X-linked intellectual disability-psychosis-macroorchidism syndrome (DOID:0060827)
X-linked intellectual disability-cardiomegaly-congestive heart failure syndrome (DOID:0060828)
X-linked immunodeficiency with magnesium defect, Epstein-Barr virus infection, and neoplasia (DOID:0080319)
X-linked mental retardation with cerebellar hypoplasia and distinctive facial appearance (DOID:0080311)
X-linked spermatogenic failure 2 (DOID:0070185)
X-linked Emery-Dreifuss muscular dystrophy 6 (DOID:0070251)
X-linked Emery-Dreifuss muscular dystrophy 1 (DOID:0070246)
X-linked dyskeratosis congenita (DOID:0070025)
X-linked dilated cardiomyopathy (DOID:0110461)
X-linked cone-rod dystrophy 3 (DOID:0111007)
X-linked cone-rod dystrophy 1 (DOID:0111008)
X-linked chronic granulomatous disease (DOID:0070195)

**Comment by lschriml** [comment]
Hello Sue,
  Thank you !! 

The re-assignment to be under X-linked is in progress,
The remaining disease will be there shortly. 

Cheers,
Lynn

**Comment by sbello** [comment]
Thanks Lynn!

**Comment by lschriml** [comment]
Done, terms queried, reviewed, updated.
