### ISSUE TITLE
sea-blue histiocyte syndrome definition xref

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#583]
There are weird characters in the xref for the DO term sea-blue histiocyte syndrome (DOID:4423)
![sea-blue](https://user-images.githubusercontent.com/10979793/46040442-4e13e700-c0de-11e8-89ac-9ca0d5f52207.PNG)
These are causing display issues in MGI, please correct the URL.
Thanks,
Sue

**Comment by lschriml** [comment]
Thank you for pointing this out Sue !! 

Weird, it was a dash. 
All fixed.

Cheers,
Lynn
