### ISSUE TITLE
phaeochromocytoma

### ISSUE THREAD

**Issue by slaulederkind** [DiseaseOntology/HumanDiseaseOntology#584]
DO preferably uses U.S. spellings, correct?  phaeochromocytoma (DOID:0050771) should be 'pheochromocytoma' with phaeochromocytoma as synonym.

**Comment by lschriml** [comment]
Hello Stan,
 Thank you for this term update !!

Yes, the DO's spellings are in U.S. English.

Reviewing and revising for this term: 

Term: **pheochromocytoma**
Definition: 
DOID:0050771    OMIM:171300
parentage: 
(1) I will move pheochromocytoma, to be a child of :  endocrine organ benign neoplasm
        
Definition: 
An endocrine organ benign neoplasm that arises within the adrenal medulla, releasing epinephrines and norepinephrines hormones that cause either episodic or persistent high blood pressure.

Synonym: benign pheochromocytoma
                  phaeochromocytoma

(2) I will create a new term: **malignant pheochromocytoma**, to be a child of adrenal medulla cancer' 
       --> Since ~ 10 % of these pheochromocytoma tumors are malignant

(3) **paraganglioma**
    pheochromocytoma's that arise outside of the adrenal medulla are paraganglioma
     -->  these arise in extraadrenal sympathetic ganglia

-- this is a benign tumor, 
parent: pheochromocytoma

 pheochrom
sources:
https://www.omim.org/entry/171300?search=171300&highlight=171300
https://www.mayoclinic.org/diseases-conditions/pheochromocytoma/symptoms-causes/syc-20355367
https://rarediseases.info.nih.gov/diseases/7385/pheochromocytoma

--> The changes are all made in the DO file. 
Will be public in next week's release.

Cheers,
Lynn
