### ISSUE TITLE
incomplete PS for 'exudative vitreoretinopathy'

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#586]
At the moment we have terms:

id: DOID:0050535
name: exudative vitreoretinopathy

id: DOID:0080264
name: exudative vitreoretinopathy 7

Any chance to complete the Phenotypic Series PS133780 for 'exudative vitreoretinopathy' and to add the missing terms?

**Comment by lschriml** [comment]
Yes, no problem. 
We are adding OMIM subtypes this week.

Cheers,
Lynn

**Comment by sbello** [comment]
added to split priority list, see also ticket #677
