### ISSUE TITLE
Request of doid for a newly described IRF2BPL-associated disease

### ISSUE THREAD

**Issue by vmt25** [DiseaseOntology/HumanDiseaseOntology#588]
Request of doid for a new disease associated with putative IRF2BPL loss-of-function alleles, described in PMID: 30057031.

It is a neurodevelopmental disorder with regression, abnormal movements, loss of speech, and seizures.

Possible names: 'IRF2BPL-deficiency syndrome' or 'neurodevelopmental disorder with regression, abnormal movements, loss of speech, and seizures'

**Comment by lschriml** [comment]
Thank you for sending us this new term for DO !!

I will take a look and get it reviewed.

Cheers,
Lynn

**Comment by lschriml** [comment]
Reviewing the current literature, this is still a phenotype, not yet associated with a human disease.
Ref: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6081494/pdf/main.pdf
https://pubmed.ncbi.nlm.nih.gov/31227826/
https://pubmed.ncbi.nlm.nih.gov/30057031/
https://www.omim.org/entry/618088
Lynn
