### ISSUE TITLE
bad parentage for [X-linked hypophosphatemic rickets]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#589]
id: DOID:0050445
name: X-linked hypophosphatemic rickets
is_a: DOID:0050736 ! autosomal dominant disease

https://ghr.nlm.nih.gov/primer/inheritance/inheritancepatterns

Technically, if a disease is X-linked, it could be 'X-linked dominant' or 'X-linked recessive' -- 'autosomal' should *not* be used for sex chromosomes.

**Comment by lschriml** [comment]
I have split the two X-linked forms, one for recessive the other dominant. 
SubClass Of axioms updated.

Cheers,
Lynn
