### ISSUE TITLE
X-linked severe combined immunodeficiency

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#592]
With renaming of the term DOID:0060013 to [X-linked severe combined immunodeficiency], I notice substantial overlap in synonyms to the term DOID:628 [combined T cell and B cell immunodeficiency]

These terms must be merged, or at the least their synonyms must be reviewed.

*and* [X-linked severe combined immunodeficiency] is *not* an [autosomal dominant disease].

**Comment by lschriml** [comment]
Thank you, I have removed the X-linked synonym from DOID:628, and updated the SubClass of statement to be X-linked recessive disease for DOID:0060013.

Cheers,
Lynn
