### ISSUE TITLE
autosomal in X-linked diseases

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#593]
October 5, 2018 release added many 'autosomal' parentage to X-linked diseases.

Example:

id: DOID:0060022
name: CD40 ligand deficiency
xref: OMIM:308230
is_a: DOID:0050737 ! autosomal recessive disease

These should be corrected to their respective X-linked parentage.

**Comment by lschriml** [comment]
Thank you !!! 
This has been fixed !! 

Cheers,
Lynn
