### ISSUE TITLE
parentage for DOID:0060292 incomplete

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#594]
[Term]
id: DOID:0060292
name: X-linked chondrodysplasia punctata
xref: OMIM:302950
xref: OMIM:302960
is_a: DOID:0080009 ! X-linked dominant disease

OMIM:302950 reports inheritance as X-linked recessive

Consider to add parent 'X-linked recessive disease'

**Comment by lschriml** [comment]
Thank you for reviewing these terms and sending the updates.

For X-linked chondrodysplasia punctat, OMIM has split the two X-linked types,
type 1 : recessive, type 2: dominant.
I created a type 2, updated OMIM IDs, and SubClass Of axioms for inheritance.

Cheers,
Lynn
