### ISSUE TITLE
consistant local identifier zero padding

### ISSUE THREAD

**Issue by TomConlin** [DiseaseOntology/HumanDiseaseOntology#598]
Not seeing any issues related to this but 
sometimes DOID's are represented as  zero padded 
and sometimes they are not.
Is there information encoded in this discrepancy? 
If so, knowing what it is would be good. 
Is there any plan to converge on one or the other formats?

thanks Tom

**Comment by lschriml** [comment]
Hello Tom,
 When DO started back in 2003, we began with a 4 digit ID, as the project grew, around 2006 or so, with multiple editors, we adopted our longer ID number, gave ourselves space to grow. 
We are not planning on converging the formats.

Cheers,
Lynn

**Comment by TomConlin** [comment]
Okay just checking, would have been handy if there was a simple cutoff
i.e. 9999  or less and it is the unpadded format 
but I find 'DOID:14798' unpadded and  'DOID:0001816' as padded
