### ISSUE TITLE
DOID:0080327: definition in xref ?

### ISSUE THREAD

**Issue by gm119** [DiseaseOntology/HumanDiseaseOntology#599]
Hi DO folks,

Spotted this problem when updating the doid.obo in FlyBase.

It looks like the definition for DOID:0080327 has ended up in the xref slot by mistake.

This issue is in the latest version of http://purl.obolibrary.org/obo/doid.obo

Here is the snippet of the obo file:

[Term]
id: DOID:0080327
name: multinucleated neurons, anhydramnios, renal dysplasia, cerebellar hypoplasia and hydranencephaly
synonym: "MARCH" EXACT []
xref: A syndrome that is characterized by severe hydranencephaly with almost complete absence of the cerebral hemispheres\, which are replaced by fluid\, relative preservation of the posterior fossa structures\, and renal dysplasia or agenesis and has_material_basis_in autosomal recessive homozygous mutation in the CEP55 gene on chromosome 10q23. {xref="https://www.ncbi.nlm.nih.gov/pubmed/28264986"}
xref: OMIM:236500
is_a: DOID:0050737 ! autosomal recessive disease
is_a: DOID:225 ! syndrome

**Comment by lschriml** [comment]
Thank you !!
My error when editing.
I really appreciate your pointing this out.
This is now fixed, and will be public in our next release.

Cheers,
Lynn
