### ISSUE TITLE
DOID:0080351: badly formatted xref ?

### ISSUE THREAD

**Issue by gm119** [DiseaseOntology/HumanDiseaseOntology#600]
Hi DO folks,

one of our developers spotted this while updating the doid.obo in FlyBase

One of the xbrefs for DOID:0080351 doesn't have the standard "db:accession" format.

Here is term from the latest  http://purl.obolibrary.org/obo/doid.obo

[Term]
id: DOID:0080351
name: CLOVES syndrome
def: "A syndrome that is characterized by congenital lipomatous overgrowth, progressive, complex and mixed truncal vascular malformation, and epidermal nevi that has_material_basis_in somatic mosaicism for postzygotic activiating mutations in the PIK3CA gene on chromosome 3q26." [url:https\://www.ncbi.nlm.nih.gov/pubmed/25209813]
synonym: "congenital lipomatous overgrowth, vascular malformations, and epidermal nevi" EXACT []
xref: GARD:10939
xref: ICD10CQ87.3
xref: OMIM:612918
xref: ORDO:140944
is_a: DOID:225 ! syndrome

the problem xref is ICD10CQ87.3

**Comment by lschriml** [comment]
Thank you !! 

Great catch, I will get it updated today.

Cheers,
Lynn

**Comment by lschriml** [comment]
Fixed, the update will be in our next release.

Cheers,
Lynn
