### ISSUE TITLE
new terms for CIVic

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#601]
"Mullerian Tumor",
 "pericytoma",
 "Endometrial Hyperplasia",
 "Peritoneal Pseudomyxoma",
 "Glioma",
 "Hepatocellular Mixed Fibrolamellar Carcinoma",
 "Chronic Myelomonocytic Leukemia",
 "Chronic Neutrophilic Leukemia",
 "epithelioid hemangioendothelioma",
 "PTEN Harmatoma Tumor Syndrome",
 "Desmoid Fibromatosis",
 "Breast, Ovarian, SCLC, Pancreatic",
 "Breast, Ovarian, Pancreatic, SCLC",
 "Chronic Eosinophilic Leukemia",
 "Kabuki-Syndrome",
 "Ovarian Sex Cord-stromal Tumours",
 "Epithelioid Inflammatory Myofibroblastic Sarcoma",
 "Anaplastic Thyroid Cancer",
 "Aggressive Fibrosis",
 "Diffuse Intrinsic Pontine Glioma",
 "Aggressive Fibromatosis",
 "Anaplastic Thyroid Carcinoma",
 "Pediatric B-lymphoblastic Leukemia",
 "Pediatric B-cell Lymphoblastic Leukemia",
 "Pediatric B-cell Acute Lymphoblastic Leukemia",
 "Essential Thrombocythemia",
 "Lipofibromatosis-like Neural Tumor (LPF-NT)",
 "Juvenile Polyposis Syndrome"

**Comment by lschriml** [comment]
new terms, synonyms, xrefs will be added to DO.
Cheers,
Lynn

**Comment by lschriml** [comment]
terms all reviewed, notes in google doc:
https://docs.google.com/spreadsheets/d/14VbyPDpeU7b7gzSJY1BrA-_GJMVm9KUfOZQDuDriDSo/edit#gid=0

**Comment by lschriml** [comment]
All terms have been added to the doid-edit.owl file, terms added to DO cancer slim.
In the google doc, I have marked terms with a green highlighter, where additional discussion is needed. 

Cheers,
Lynn

**Comment by arpaddanos** [comment]
Another term to add for use in CIViC could be
gastroesophageal adenocarcinoma 
Currently there are DOID for gastroesophageal junction adenocarcinoma (DOID 4944).

but note in this ASCO abstract:
https://meetinglibrary.asco.org/record/168588/abstract
a distinction is made between 
gastroesophageal adenocarcinoma (GEA)
and 
gastroesophageal junction adenocarcinoma (GEJ)
So GEJ does not seem to cover all cases in current use, and we need GEA to cover this type of evidence.

**Comment by arpaddanos** [comment]
See Also
http://www.discoverymedicine.com/Amikar-Sehdev/2013/08/26/gastroesophageal-cancer-focus-on-epidemiology-classification-and-staging/

**Comment by lschriml** [comment]
(email from CIViC):
Another term to add for use in CIViC could be **gastroesophageal adenocarcinoma**
Currently there are DOID for gastroesophageal junction adenocarcinoma (DOID 4944).

--> moving the review notes to a google doc:
https://docs.google.com/document/d/1fjf5Zs2AEABtPJe9n0QJbwgRQ6F1I_kVfZG5d0Grm0c/edit?usp=sharing

--> finalizing terms and definitions tomorrow, then will integrate into DO.
Cheers,
Lynn

**Comment by lschriml** [comment]
Terms added and defined. 
Will be available in the next DO release.
Cheers,
Lynn
