### ISSUE TITLE
update MGI slim

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#606]
Please remove the following terms from the MGI slim set:
primary immunodeficiency disease DOID:612
ciliopathy DOID:0060340
multiple pterygium syndrome DOID:0080110
Cornelia de Lange syndrome DOID:11725
chondrodysplasia punctata DOID:2581
orofaciodigital syndrome DOID:4501
malignant hyperthermia DOID:8545
maturity-onset diabetes of the young DOID:0050524

**Comment by lschriml** [comment]
The MGI slim has been updated in the doid-edit.owl file. 
The changes will be public in our next release.

Any additions ?? 
Cheers,
Lynn
