### ISSUE TITLE
Opitz-GBBB syndrome

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#607]
Opitz-GBBB syndrome is currently a child of both autosomal dominant disease and X-linked recessive disease. Since an is_a child should always be a child of all its parents this is incorrect. Please review the parentage of this term. I would suggest moving this up to monogenic disease.
Thanks,
Sue

**Comment by lschriml** [comment]
Hello Sue,
 thank you for this update.

For: Opitz-GBBB syndrome
  it's is_a parent is monogenic disease,
the other connections are via subClassOf axioms. 

Cheers,
Lynn

**Comment by sbello** [comment]
Yes, but the subclass of axioms are resulting in incorrect inferred parents in the OBO files. In the OBO file this term is showing up only as a child of both autosomal dominant disease and X-linked recessive disease. See http://www.informatics.jax.org/disease/DOID:0050780 The tree diagram at the bottom shows the issue nicely. 
![opitz](https://user-images.githubusercontent.com/10979793/48282842-d220f480-e428-11e8-90e3-69e3a7dd7a35.PNG)

**Comment by tutajm** [comment]
Another proposal: consider adding child terms:

 Opitz GBBB Syndrome, Type 1 (OMIM:300000), X-linked

 Opitz GBBB Syndrome, Type 2 (OMIM:145410), autosomal

Then,  Opitz GBBB Syndrome could be simply a child of 'syndrome' term

**Comment by lschriml** [comment]
Thank you Marek !!

**Comment by lschriml** [comment]
Parentage was updated, 
   two new subtypes need to be added.

**Comment by lschriml** [comment]
subtypes added to DO.
