### ISSUE TITLE
New Term Request: PEHO Syndrome

### ISSUE THREAD

**Issue by LeylaR** [DiseaseOntology/HumanDiseaseOntology#608]
Hi,
I would like to request this term: 
PEHO syndrome ((progressive encephalopathy with edema, hypsarrhythmia, and optic atrophy)
OMIM:260565
https://omim.org/entry/260565
Here is a publication discussing this syndrome:
https://www.ncbi.nlm.nih.gov/pubmed/28335020
Thanks,
Leyla

**Comment by lschriml** [comment]
Thank you Layla !!
We will get this term reviewed for DO.
Cheers,
Lynn

**Comment by LeylaR** [comment]
Accidentally closed issue (and reopened)

**Comment by sbello** [comment]
added to OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
Added to DO.
