### ISSUE TITLE
Fraser Syndrome - incomplete

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#609]
Currently DOID:0090001 [Fraser syndrome] lists only OMIM:21900, [Fraser Syndrome 1]. That's incomplete: there are other versions of Fraser syndrome:

Fraser Syndrome 2 [OMIM:617666]
Fraser Syndrome 3 [OMIM:617667]

Please consider to add whole phenotypic series PS219000 to the current term [Fraser syndrome]

**Comment by lschriml** [comment]
Thank you Marek !!
We are in the process of making these updates — adding in OMIM subtypes. When we do, we keep the parent class term, and add the numbered subtype terms.

Cheers,
Lynn

**Comment by sbello** [comment]
added to OMIM spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing
