### ISSUE TITLE
NTR Combined malonic and methylmalonic aciduria

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#611]
Hi Lynn,

could I please request 
Combined malonic and methylmalonic aciduria
synonym CMAMMA
OMIM # 614265

Cheers

**Comment by sbello** [comment]
On OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111263
