### ISSUE TITLE
NTR congenital dyserythropoietic anemia type II

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#612]
Hello, 
can I please request
congenital dyserythropoietic anemia type II
is_a DOID:1338
OMIM # 224100

**Comment by sbello** [comment]
Added to OMIM spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by Antonialock** [comment]
Hello, I can't see the relevant entry in that spreadsheet,

It looks like all type of congenital dyserythropoietic anemia  are lumped into  DOID:1338

will there be a more specific new term for type II disease or should I annotate to the parent disorder?

**Comment by sbello** [comment]
Sorry for the delay. I thought it was on the spreadsheet but I don't see it either. I've added it again and get to it ASAP.

**Comment by Antonialock** [comment]
thanks!

**Comment by sbello** [comment]
added in my latest commit

**Comment by Antonialock** [comment]
fab thanks!
