### ISSUE TITLE
Multiple Sclerosis susceptibility terms

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#613]
I can't find a DO term that has a relationship to OMIM:614810, OMIM:612595, OMIM:612596, OMIM:612594 or OMIM:126200.  It would be helpful if there was some relationship between the all the MS susceptibility loci and the DO MS term DOID:2377.

**Comment by lschriml** [comment]
We can add in the susceptibility loci and link them to the MS DO term. 

We will add SubClass of: 
    'contributes to condition' some 'multiple sclerosis'
    omit_susceptibility
