### ISSUE TITLE
DOID:0050462

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#614]
DOID:0050462 has two OMIM xrefs

however according to OMIM
"Antley-Bixler syndrome with disordered steroidogenesis (ABS1) is caused by homozygous or compound heterozygous mutation in the gene encoding cytochrome P450 oxidoreductase (POR; 124015) on chromosome 7q11.

A form of Antley-Bixler syndrome with normal steroidogenesis (ABS2; 207410) is a distinct disorder caused by mutation in the FGFR2 gene (176943)."

**Comment by lschriml** [comment]
Add the two new terms, include 'with' and 'without' part of name

**Comment by sbello** [comment]
on OMIM split spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing
