### ISSUE TITLE
NTR Fumaric aciduria

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#615]
Fumaric aciduria

synonym fumarase deficiency

is_a organic aciduria
PMID:6616883

ORPHA:24
omim 606812

thanks!

**Comment by sbello** [comment]
on OMIM spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111261
