### ISSUE TITLE
NTR Galactosialidosis

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#616]
Galactosialidosis

PMID:28603679
is_a DOID:3211

OMIM # 256540
ORPHA:351

**Comment by lschriml** [comment]
Thank you Antonia !!
  Agreed, will add as a child of lysosomal storage disease.

https://rarediseases.info.nih.gov/diseases/3953/galactosialidosis
http://www.omim.org/entry/256540?search=256540&highlight=256540

Cheers,
Lynn

**Comment by sbello** [comment]
added to OMIM spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
added to DO. 
Lynn
