### ISSUE TITLE
NTR Hyperprolinemia ( types 1 and 2 )

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#618]
NTR Hyperprolinemia
is_a DOID:9252

NTR Hyperprolinemia type 1
This subtype is caused by mutations in proline dehydrogenase
ORPHA419
omim 239500

NTR Hyperprolinemia type 2 
This subtype is caused by mutations in proline dehydrogenase
ORPHA79101
OMIM 239510

**Comment by sbello** [comment]
added to OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
add to DO.
Lynn
