### ISSUE TITLE
NTR Glutathionuria

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#619]
NTR Glutathionuria

I'm guessing it is_a DOID:9252 - although it is metabolism of amino acid rather than synthesis/degradation?

OMIM 231950
ORPHA33573

**Comment by lschriml** [comment]
agreed, a child of amino acid metabolic disorder.

Thank you for suggesting parentage for the terms. 
It is greatly helpful for our review !!

I will add this term. 

Cheers,
Lynn

**Comment by sbello** [comment]
on OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111257
