### ISSUE TITLE
NTR Postnatal progressive microcephaly with seizures and brain atrophy

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#620]
Postnatal progressive microcephaly with seizures and brain atrophy

This is a type of secondary microcephaly (evident postnatally), so is_a DOID:10907

OMIM 613668
ORPHA:402364

**Comment by lschriml** [comment]
Thank you Antonia,
  -- reviewed, I will add in a 'secondary microcephaly' term to DO 
and this new term as a is_a child term. 

references:
https://www.ncbi.nlm.nih.gov/pubmed/23622158
http://www.medlink.com/article/microcephaly
https://en.wikipedia.org/wiki/Microcephaly

another secondary microcephaly OMIM: 
617481
http://www.omim.org/entry/617481?search=prune1&highlight=prune1
neurodevelopmental disorder with microcephaly, hypotonia, and variable brain anomalies (NMIHBA)

Cheers,
Lynn

**Comment by sbello** [comment]
on OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111262, used the Orphanet term name as that put the primary cause of microcephaly first
