### ISSUE TITLE
NTR Jalili syndrome

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#621]
Jalili syndrome

Results from mutations in  CNNM4 and is characterized by the combination of cone-rod dystrophy of the retina and amelogenesis imperfecta

OMIM 217080

**Comment by sbello** [comment]
added to OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by Antonialock** [comment]
This is still not available

**Comment by Antonialock** [comment]
ta!

**Comment by lschriml** [comment]
Hello,
I am on vacation. I will update our public files next week.
Cheers,
Lynn

**Comment by sbello** [comment]
@Antonialock I closed this as the new edit file now has this term. Once Lynn pushes out a new version of the ontology the term will be in all the public files. This is true for the other tickets I closed recently.
Sue

**Comment by Antonialock** [comment]
Awesome! I just sais 'ta' as in 'thanks' for dealing with it so quickly :-) how do I find out when you do releases - I always look at your main page http://www.disease-ontology.org/

it says your last update was March 07 - but you have clearly updated since then?

the 'DO new website launch" news item doesn't say you have a new URL so is  http://www.disease-ontology.org/ still the correct website to use?

<img width="633" alt="Screenshot 2019-10-02 at 21 05 10" src="https://user-images.githubusercontent.com/12727506/66077816-a767ef00-e558-11e9-9ab2-67cca4dcf2c8.png">

**Comment by sbello** [comment]
Yes, the URL is the same but there are a bunch of new features and functions on the website. The March 7 date was for the last website update (prior to the big one that just happened). 

The ontology file is updated much more frequently. These are announced by Lynn and posted on the DO GitHub page on the releases tab (https://github.com/DiseaseOntology/HumanDiseaseOntology/releases). The new versions are then picked up by all the downstream DO users at various time. The last update to the ontology file was September 16.
