### ISSUE TITLE
NTR mitochondrial pyruvate carrier deficiency

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#622]
Mitochondrial Pyruvate Carrier Deficiency

ORPHA:447784
OMIM 614741

**Comment by lschriml** [comment]
Hello Antonia,
Thank you for the new term suggestion !!

   Reviewed, will add as a child of mitochondrial metabolism disease.

Cheers,
Lynn

**Comment by Antonialock** [comment]
Thank you, sorry for the many requests. It's a "one off" submission of many terms. We are doing mappings...

**Comment by lschriml** [comment]
Added to DO
