### ISSUE TITLE
NTR spondyloepiphyseal dysplasia tarda, SEDT

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#623]
spondyloepiphyseal dysplasia tarda, SEDT

ORPHA:93284
OMIM 313400

**Comment by lschriml** [comment]
Hello Antonia,
   I will add this as a new child term of spondyloepimetaphyseal dysplasia, DOID:0080027.

Cheers,
Lynn

**Comment by lschriml** [comment]
Added to DO.
