### ISSUE TITLE
Tricho-hepato-enteric syndrome

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#625]
Tricho-hepato-enteric syndrome

caused by mutation in SKIV2L or in TTC37

ref https://ojrd.biomedcentral.com/articles/10.1186/1750-1172-8-5

synonyms
Trichohepatoenteric syndrome
syndromic diarrhea
phenotypic diarrhea
SD/THE

ORPHA:84064
narrow xref OMIM 222470

**Comment by sbello** [comment]
added to add priority spreadsheet  https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by Antonialock** [comment]
this is still not available. I don't mind having more specific or general term(s), whatever fits the ontology best
