### ISSUE TITLE
NTR Ruijs-Aalfs syndrome

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#626]
synonym
Progeroid features-hepatocellular carcinoma predisposition syndrome

OMIM 616200
ORPHA:435953

**Comment by sbello** [comment]
on OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111264
