### ISSUE TITLE
NTR pentosuria

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#628]
Pentosuria is characterized by abnormally high levels of pentose L-xylulose in urine. It results from L-xylulose reductase deficiency, an enzyme encoded by the DCXR gene.

is_a DOID:2978

OMIM 260800
ORPHA:2843

**Comment by sbello** [comment]
on OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111258
