### ISSUE TITLE
NTR Phosphoribosylpyrophosphate synthetase I superactivity

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#629]
Phosphoribosylpyrophosphate synthetase I superactivity is an X-linked inborn error of metabolism resulting from increased PRPS1 enzyme activity. Symptoms include hyperuricemia and gout.

is_a DOID:653

OMIM 300661

**Comment by sbello** [comment]
on OMIM priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111260
