### ISSUE TITLE
NTR microcephalic osteodysplastic primordial dwarfism 

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#631]
This is a novel form of 
microcephalic primordial dwarfism 

the type I want to annotate is caused by mutations in WDR4
PMID: 26416026

I'm not sure if it is best to create a sibling term to DOID:0060608 and DOID:0060609 - I can't find a type number, or make it a parent term (without specifying WDR4 - that would be enough for my purposes).

WDR4 is on this gene panel
https://services.nhslothian.scot/clinicalgeneticsservice/GeneticLaboratoryServices/molecular_genetics/DNA_Tests/Documents/Microcephaly_tech_info_0117.pdf

**Comment by Antonialock** [comment]
This is OMIM 618346

**Comment by lschriml** [comment]
Added to the DO, DOID:0081051
