### ISSUE TITLE
NTR postaxial acrofacial dysostosis

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#633]
postaxial acrofacial dysostosis 

results from mutations in DHODH

is_a DOID:0060379

synonyms
POADS
Miller syndrome
Genee-Wiedemann syndrome

xref 
OMIM 263750

**Comment by sbello** [comment]
on spreadsheet for OMI priority adds https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111259
