### ISSUE TITLE
update AGR slim

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#635]
Hi Lynn,
We would like to update the DO_AGR_slim to include the following terms (full list below, many of these are in the slim set currently):
bacterial infection (new)
fungal infection (new)
parasitic infection (new)
viral infection (new)
cardiovascular system disease
central nervous system disease (new)
endocrine system disease
gastrointestinal system disease
hematopoietic system disease
immune system disease
integumentary system disease
musculoskeletal system disease
peripheral nervous system disease (new)
reproductive system disease
respiratory system disease
sensory system disease (new)
thoracic disease
urinary system disease
benign neoplasm
pre-malignant neoplasm
cancer
chromosomal disease (new)
monogenic disease (new)
disease of mental health
disease of metabolism
physical disorder (new)
syndrome (new)

drop from the slim:
disease of infectious agent
nervous system disease (splitting this into child terms)

Thanks,
Sue

**Comment by lschriml** [comment]
Hello Sue !!
Happy to make the updates.
I’ll be pushing out a release late next week. These updates will be included.
Cheers,
Lynn

**Comment by sbello** [comment]
Thank you!

**Comment by lschriml** [comment]
Added and updated !!

Cheers,
Lynn
