### ISSUE TITLE
Jena warnings and errors parsing doid.owl

### ISSUE THREAD

**Issue by ppavlidis** [DiseaseOntology/HumanDiseaseOntology#636]
Hi DO team, when parsing http://ontologies.berkeleybop.org/doid.owl, we recently started getting a slew (about 100) of warnings from Jena like this:

>  com.hp.hpl.jena.rdf.model.impl.RDFDefaultErrorHandler.warning(49) | http://ontologies.berkeleybop.org/doid.owl(line 101 column 105): {W107} Bad URI: <Optional.of(http://purl.obolibrary.org/obo/doid.obo)#complicated_by> Code: 0/ILLEGAL_CHARACTER in SCHEME: The character violates the grammar rules for URIs/IRIs.

Using the version at https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid.owl, we get those warnings and a fatal error to boot:

>https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid.owl(line 44 column 91): Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.

In addition to these errors:

> https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid.owl(line 41 column 3): {E201} The attributes on this property element, are not permitted with any content; expecting end element tag.
>  https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid.owl(line 42 column 3): {E201} The attributes on this property element, are not permitted with any content; expecting end element tag.
> https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid.owl(line 42 column 44): {E201} XML element <meta> inside an empty property element, whose attributes prohibit any content.
>  https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid.owl(line 43 column 3): {E201} The attributes on this property element, are not permitted with any content; expecting end element tag.
> https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid.owl(line 44 column 3): {E201} The attributes on this property element, are not permitted with any content; expecting end element tag.

Any advice appreciated, thanks!

**Comment by rctauber** [comment]
What are you using to parse DO? Jena in a Java tool? I'd like to recreate
the issue.

**Comment by cmungall** [comment]
This is unrelated to your issue but I note you are using an incorrect URL, the OBO page is always the authoritative source for download URLs for any OBO ontology: http://obofoundry.org/ontology/doid.html

**Comment by ppavlidis** [comment]
@rctauber Yes, this is with Jena 2.7.4 in Java. Old, I know.

But thanks @cmungall  -  the OWL file linked there works fine for me, all good. Sorry about my confusion about where to get the right file!

**Comment by rctauber** [comment]
Was this issue resolved by using the OBO Foundry link? As Chris said, the
OBO Foundry PURL is the correct one to use. One other thought is the GitHub
link you provided is not the raw version of the doid.owl file. So, if you
do something like `curl` that link, it won't be the actual ontology file;
it will be the GitHub page. I'm not sure if this is the problem, but the
OBO Foundry PURL should point to the same content as doid.owl on GitHub.

**Comment by rctauber** [comment]
If you don't follow the redirect on the PURL, you'll get this content:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid.owl">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at purl.obolibrary.org Port 80</address>
</body></html>
```
As long as everything is working well with http://purl.obolibrary.org/obo/doid.owl (using redirects), I'm going to close this issue. Please feel free to reopen if you have any other questions!

**Comment by lschriml** [comment]
Hello Paul,
Thank you for working with DO to figure this out !!!!

Happy Holidays,
Lynn
