### ISSUE TITLE
Linking to DO

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#637]
hi Lynn,

is it possible to link to specific DO IDs? (is there a pattern URL e.g. www.diseasontology/DOID:0040085 that will load the disease in the browser?

We have  external links on other term pages e.g. https://www.pombase.org/term/GO:0061709
just wondered if we can do the same for DO

cheers
Antonia.

**Comment by Antonialock** [comment]
Nevermind, found these links
e.g. http://disease-ontology.org/term/DOID%3A0070131/

It would be extra nice to see the term in context of the browser though :-)

**Comment by lschriml** [comment]
Hello Antonia,
   link directly to DO.

http://www.disease-ontology.org/?id=DOID:9256


http://www.disease-ontology.org/term/DOID%3A11725/

Cheers,
Lynn

**Comment by Antonialock** [comment]
thanks!
