### ISSUE TITLE
missing def xrefs

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#638]
In The Dec 14 2018 release, xrefs for term definitions are missing. Is this intentional?

Definition xrefs was a useful and unique feature of DO ontology. We will miss it if it will be gone forever :-(

**Comment by rctauber** [comment]
Hi Marek,

The definition cross references have been moved to the 'definition source'
field in the OWL release of DO. OBO format doesn't have the 'definition
source' property, so they cannot be viewed there. If this is something you
need in the OBO release, I'm happy to re-add the xrefs to the OBO file
automatically during the release process.

**Comment by tutajm** [comment]
Well, doid.obo file is in obo format 1.2. According to spec (http://owlcollab.github.io/oboformat/doc/GO.format.obo-1_2.html), 'def' line can contain dbxrefs describing the origin of the definition.

So it is really a mystery to me why you did remove those def xrefs? They are part of OBO 1.2 spec! I would hate to download the human-non-readable owl version, use robot to convert the file to obo and parse out those def xrefs that are missing in the official doid.obo file.

I'd really appreciate if you will keep those def xrefs in the obo file, just as they were available in November release.

Thank you, very much, Marek

FYI: def line spec from 1.2 obo format document:

def

The definition of the current term. There must be zero or one instances of this tag per term description. More than one definition for a term generates a parse error. **The value of this tag should be the quote enclosed definition text, followed by a dbxref list containing dbxrefs that describe the origin of this definition (see dbxref formatting for information on how dbxref lists are encoded)**. An example of this tag would look like this:
def: "The breakdown into simpler components of (+)-camphor, a bicyclic monoterpene ketone." [UM-BBD:pathway "", http://umbbd.ahc.umn.edu/cam/cam_map.html ""]

**Comment by cmungall** [comment]
Using axiom annotations (def xrefs in obo) is very standard for most ontologies that the MODs use, I recommend switching back. I would recommend having the OWL follow the OBO rather than implementing a specific transform as this will confuse things.

(In fact I think all ontologies should use axiom annotation, as there are numerous advantages and in future some tooling will assume this; but this is a matter for OBO)

**Comment by rctauber** [comment]
I forwarded a message to @lschriml but she's out of office for the holidays. I'd like to see how she wants to proceed, as we moved to the IAO `definition source` property to annotate the definition sources with ECO evidence classes (as opposed to doing another axiom annotation on an axiom annotation).

We could add an automated process to move `definition source` to a definition xref for the OBO format release (using a SPARQL update), and then we wouldn't need to maintain two separate fields with the same annotation. The ECO evidence references wouldn't be translated into the OBO format release. The other option is to manually maintain the two separate fields, but I'm worried that would get out-of-sync.

**Comment by cmungall** [comment]
On 17 Dec 2018, at 9:09, Rebecca Tauber wrote:

> I forwarded a message 
> to [@lschriml](<https://github.com/lschriml>) but she's out of 
> office for the holidays. I'd like to see how she wants to proceed, as 
> we moved to the IAO `definition source`property to annotate the 
> definition sources with ECO evidence classes (as opposed to doing 
> another axiom annotation on an axiom annotation).

can you not put this annotation directly on the annotation assertion?

Note in the obo this would result in additional trailing qualifiers. 
This may trip MOD parsers that don't follow the obo format spec, but I 
can with that.

See also the iao ticket I just linked

> We could add an automated process to move `definition source` to a 
> definition xref for the OBO format release (using a SPARQL update), 
> and then we wouldn't need to maintain two separate fields with the 
> same annotation. The ECO evidence references wouldn't be translated 
> into the OBO format release. The other option is to manually maintain 
> the two separate fields, but I'm worried that would get out-of-sync.

yeh, also have sync concerns.

**Comment by rctauber** [comment]
> can you not put this annotation directly on the annotation assertion?

Our concern with this is it would be seen as just another definition xref for the definition, e.g.
```
AnnotationAssertion(
    Annotation(oboInOwl:hasDbXref "PMID:xxx") 
    Annotation(oboInOwl:hasDbXref "ECO:xxx")
    obo:IAO_0000115 ex:my_term "My definition")
```
When really, the `ECO:xxx` should be an annotation on `PMID:xxx`.

With the `definition source` (`IAO:0000119`), it ends up as:
```
AnnotationAssertion(
    obo:IAO_0000115 ex:my_term "My definition")
AnnotationAssertion(
    Annotation(oboInOwl:hasDbXref "ECO:xxx")
    obo:IAO_0000119 ex:my_term "PMID:xxx")
```

> See also the iao ticket I just linked

Yeah, I think this is a good discussion to have.

**Comment by lschriml** [comment]
Hello Marek,
  They are not gone just moved to a new field. Definition source.
   If this is causing a problem, please let me know.

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Becky,
   If you have the band width for this update this week, please move the definition source back to the definition xref field. And push another release. 
    For the release please check the date and sunset fields for the obo files in,
    Ontology/subsets and in the release folder. 
     We can discuss how to handle the ECO codes when I am back.

Thank you for coordinating this update. 

Cheers,
Lynn

**Comment by lschriml** [comment]
Apologies for any problems this may have caused.
Becky will update the DO this week.

Cheers,
Lynn

**Comment by cmungall** [comment]
> Our concern with this is it would be seen as just another definition xref for the definition

I was thinking you'd use a different property than hasDbXref for the ECO annotation. Not sure which prop as I don't have a strong sense of the use case.

What are some typical ECO classes that would be used here? I'm more familiar with ECO supporting statements about biology rather than text.

**Comment by rctauber** [comment]
I've just published another release returning the definition xrefs. Please let me know if you have any other questions - we will discuss how best to proceed with the ECO xrefs after the holidays.

@cmungall we have added new "curator inference" terms to talk about definition sources from things like encyclopedias and databases.

**Comment by lschriml** [comment]
This issue has been resolved.
