### ISSUE TITLE
update OMIM xrefs on DOID:0050580

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#639]
Please update the OMIM xrefs for DOID:0050580
remove xrefs for child terms:
 OMIM:153100, OMIM:153200, OMIM:247440 (obsolete), OMIM:611944, OMIM:613480, OMIM:615907

add xref for OMIM series
OMIM:PS153100

The members of the OMIM series have been split off into child terms so the IDs should no longer be directly associated with the parent term.

Thanks,
Sue

**Comment by lschriml** [comment]
Thank you Sue !!
We will get this fixed. 
We will be focusing on OMIM splits in January.
Cheers,
Lynn

**Comment by lschriml** [comment]
Done
