### ISSUE TITLE
typo in OMIM xref for DOID:0080360

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#640]
There is a typo in the xref for DOID:0080360. The OMIM ID is currently OMIM:606501 but this is a gene record. The ID should be OMIM:616501, note the first 0 should be a 1.

**Comment by lschriml** [comment]
Thank you !!!
 I will get this fixed ASAP.
Cheers,
Lynn

**Comment by lschriml** [comment]
Fixed.
