### ISSUE TITLE
Add OMIM: xref to DOID:3145

### ISSUE THREAD

**Issue by vforget** [DiseaseOntology/HumanDiseaseOntology#641]
Hi,

DOID:3145 -- hyperlipoproteinemia type III does not currently include OMIM:617347

https://omim.org/entry/617347

Thanks,

Vince

**Comment by lschriml** [comment]
Thank you Vince,
 I will review and get this added.

Cheers,
Lynn

**Comment by lschriml** [comment]
Added,
Thank you !!!
