### ISSUE TITLE
problematic synonym & gene desc for DOID:0111138

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#643]
id: DOID:0111138
name: congenital generalized lipodystrophy type 4

Definition mentions gene PTRF -- however, this gene is now named CAVIN1 (please see https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:9688)

Also there is a synonym "Brunzell syndrome AGPAT2-related". This could be a mistake: AGPAT2 gene is associated with related term [congenital generalized lipodystrophy type 1]

**Comment by lschriml** [comment]
Thank you for sharing this update with us !! 
We get this integrated into the DO.

Cheers,
Lynn

**Comment by lschriml** [comment]
The updates have been included in the DO.

Thank you for identifying this needed update.

Cheers,
Lynn
