### ISSUE TITLE
refine parentage of DOID:0080089

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#644]
id: DOID:0080089
name: tubular aggregate myopathy
is_a: DOID:423 ! myopathy

multiple sources classify this disease as a form of 'congenital myopathy', f.e.:

https://www.malacards.org/card/myopathy_tubular_aggregate_1  (look at ICD10 classification)
https://monarchinitiative.org/disease/OMIM:160565

Please consider assigning a more specific parent to this term. Candidate:
id: DOID:0080100
name: congenital myopathy

**Comment by lschriml** [comment]
based on age of onset - see OMIM records
  these are not congenital conditions
