### ISSUE TITLE
OMIM:607208 xref

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#645]
OMIM:607208 (EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 6; EIEE6) is an xref to two different DOIDs:
id: DOID:2481
name: infantile epileptic encephalopathy

id: DOID:0060171
name: Dravet syndrome

The two diseases are in different DO branches under 'epilepsy'.  Not sure if one xref should be removed, or DO terms should be merged, or....

**Comment by lschriml** [comment]
Thank you Steven,
 I have merged these two records, based on OMIM's data. 
I retained DOID:0080422 as Dravet syndrome. 

Cheers,
Lynn

**Comment by sjm41** [comment]
Thanks Lynn!
