### ISSUE TITLE
Add OMIM:252650 as xref to DOID:2368?

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#646]
[Term]
id: DOID:2368
name: gangliosidosis
synonym: "mucolipidosis type IV" EXACT []
xref: GARD:12510
xref: ICD10CM:E75.10
xref: MESH:D005733
xref: SNOMEDCT_US_2018_03_01:50967008
xref: UMLS_CUI:C0017083
is_a: DOID:1927 ! sphingolipidosis

https://www.omim.org/entry/252650
MUCOLIPIDOSIS IV; ML4

**Comment by lschriml** [comment]
I've finished researching these two sets of diseases, notes below,
I am in the process of making the updates. 

Cheers,
Lynn


For gangliosidosis -- I'm removing the mucolipidosis IV synonym. 
        This is an incorrect synonym. 
     mucolipidosis IV has the synonym, ganglioside sialidase deficiency,
  --> the synonym has been removed [DONE]

To Do: 
       I am adding in a new DO term, for gangliosidosis GM3,
          OMIM:230650
           https://www.omim.org/entry/230650
           https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=79257


looking at **mucolipidosis** : 

to do: 
  creating a parent term: mucolipidosis  [DONE]
  --> moved the three subtypes under this parent [DONE]
     type I:
           **mucolipidosis type I.** --> glycoproteinosis DOID:3343 
             this is OMIM:256550

         type II: inclusion-cell disease, DOID:0080070
             this is OMIM:252500

       type III: pseudo-Hurler polydystrophy
              OMIM:252600

To Do: 

        type IV: I will create a new DO term
                 https://www.omim.org/entry/252650
           MUCOLIPIDOSIS IV; ML4
  

Notes: 
The four types of ML are sialidosis (sometimes referred to as ML I), and types II, III, and IV.
**Mucolipidosis type I** (ML I) or sialidosis results from a deficiency in one of the digestive enzymes known as sialidase. 


References:
mucolipidosis:
https://www.ninds.nih.gov/Disorders/Patient-Caregiver-Education/Fact-Sheets/Mucolipidoses-Fact-Sheet

Mucolipidosis type 4
     https://ghr.nlm.nih.gov/condition/mucolipidosis-type-iv
Other Names: ML 4; Berman syndrome; Ganglioside neuraminidase deficiency


https://rarediseases.info.nih.gov/diseases/94/index
https://www.ncbi.nlm.nih.gov/pubmed/30740407

**Comment by lschriml** [comment]
new DOIDs added, with OMIM IDs. 

Cheers,
Lynn

**Comment by sjm41** [comment]
Sounds good, thanks.
