### ISSUE TITLE
Add OMIM:603285 to id: DOID:0060671

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#647]
[Term]
id: DOID:0060671
name: cerebral cavernous malformation 3
def: "A cerebral cavernous malformation that_has_material_basis in mutation in the PDCD10 gene on chromosome 3q26.1." [url:https\://www.ncbi.nlm.nih.gov/pubmed/15543491]
subset: DO_rare_slim
synonym: "CCM3" EXACT []
xref: ICD10CM:Q28.3
xref: ORDO:221061
is_a: DOID:0060669 ! cerebral cavernous malformation

https://www.omim.org/entry/603285
CEREBRAL CAVERNOUS MALFORMATIONS 3; CCM3

**Comment by lschriml** [comment]
Thank you Steven !!
 I have added the OMIM ID, 
I also added cerebral cavernous malformation 1 and 
updated the classification.

Cheers,
Lynn
