### ISSUE TITLE
Add more OMIM xrefs to DOID:0050709?

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#650]
early infantile epileptic encephalopathy (DOID:0050709) has ~16 OMIM xrefs to OMIM terms like "EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 9; EIEE9".
But not all such OMIM terms are included as xrefs.
E.g.
https://www.omim.org/entry/616645
EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 34; EIEE34 

Is there a reason for this, or can these additional EIEE OMIMs be added as xrefs?

**Comment by lschriml** [comment]
Hello Steven,
   this update is part of our work to split DO terms based on their molecularly defined subtypes, outlined in OMIM. 
  Previously, before the OMIM phenotypic series were created and the new DO terms are created, we would include the breadth of OMIM IDs under the parent term. 
  for this disease, the phenotypic series PS OMIM ID has been added to the parent term, and the child OMIM IDs have been assigned. 

Cheers,
Lynn

**Comment by sjm41** [comment]
Thanks, sounds good.  But just to be clear - are you saying you'll be making separate DO terms for all EIEE subtypes?
