### ISSUE TITLE
 Add more OMIM xrefs to DOID:14450?

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#651]
46 XX gonadal dysgenesis (DOID:14450) already has 6 xrefs to OMIM, including 2 "OVARIAN DYSGENESIS *; ODG*" terms.
Wondering whether ODG6 (https://www.omim.org/entry/618078) and maybe other ODG OMIMs should be added?

**Comment by lschriml** [comment]
Hello Steven,
   this is a term we are splitting based on the OMIM subtypes. 
I have added the phenotypic series OMIM ID to the parent term: PS233300

I have added in the 8 ovarian dysgenesis subtypes to the DO. 

Cheers,
Lynn

**Comment by sjm41** [comment]
Thanks!
