### ISSUE TITLE
More OMIM xrefs for DOID:1827?

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#652]
idiopathic generalized epilepsy (DOID:1827) already has these OMIM refs:
EPILEPSY, IDIOPATHIC GENERALIZED, SUSCEPTIBILITY TO, 2; EIG2 (606972)
EPILEPSY, IDIOPATHIC GENERALIZED, SUSCEPTIBILITY TO, 3; EIG3 (608762)
EPILEPSY, IDIOPATHIC GENERALIZED, SUSCEPTIBILITY TO, 4; EIG4 (609750)
EPILEPSY, IDIOPATHIC GENERALIZED, SUSCEPTIBILITY TO, 5; EIG5 (611934)
EPILEPSY, IDIOPATHIC GENERALIZED, SUSCEPTIBILITY TO, 7; EIG7 (604827)

Just wondering if other similar OMIMs should be added as xrefs?
E.g.  EPILEPSY, IDIOPATHIC GENERALIZED, SUSCEPTIBILITY TO, 14; EIG14 (616685)
(there are several others)

**Comment by lschriml** [comment]
Thank you Steven,
 yes, this one has been added. 

Cheers,
Lynn
