### ISSUE TITLE
 Zellweger syndrome (DOID:905) OMIM xrefs

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#653]
Zellweger syndrome (DOID:905) currently has a single OMIM xref:
OMIM:214100 PEROXISOME BIOGENESIS DISORDER 1A (ZELLWEGER); PBD1A

But OMIM has at least 11 other subtypes:
 # 214110. PEROXISOME BIOGENESIS DISORDER 2A (ZELLWEGER); PBD2A
 # 614859. PEROXISOME BIOGENESIS DISORDER 3A (ZELLWEGER); PBD3A
 # 614862. PEROXISOME BIOGENESIS DISORDER 4A (ZELLWEGER); PBD4A
 # 614866. PEROXISOME BIOGENESIS DISORDER 5A (ZELLWEGER); PBD5A
 # 614870. PEROXISOME BIOGENESIS DISORDER 6A (ZELLWEGER); PBD6A
 # 614872. PEROXISOME BIOGENESIS DISORDER 7A (ZELLWEGER); PBD7A
 # 614876. PEROXISOME BIOGENESIS DISORDER 8A (ZELLWEGER); PBD8A
 # 614882. PEROXISOME BIOGENESIS DISORDER 10A (ZELLWEGER); PBD10A
 # 614883. PEROXISOME BIOGENESIS DISORDER 11A (ZELLWEGER); PBD11A
 # 614886. PEROXISOME BIOGENESIS DISORDER 12A (ZELLWEGER); PBD12A
 # 614887. PEROXISOME BIOGENESIS DISORDER 13A (ZELLWEGER); PBD13A

Should these all be added as additional xrefs to DOID:905, or would the DO create all these subtypes?

**Comment by lschriml** [comment]
Thank you !!
New subtypes.

Much appreciated,
Lynn

**Comment by lschriml** [comment]
I have added the subtypes and will push this out in the next DO release.
Planned for tomorrow.
Cheers,
Lynn
