### ISSUE TITLE
Fabry disease parentage

### ISSUE THREAD

**Issue by ValWood** [DiseaseOntology/HumanDiseaseOntology#654]
Should this have the "monogenic" parent?

V

**Comment by lschriml** [comment]
Hello, 
Thank you for suggesting an update for Fabry disease. 
I have updated the Fabry definition:

A sphingolipidosis that is characterized by the buildup of globotriaosylceramide in the body's cells and has_material_basis_in X-linked inherited mutations in the GLA gene, encoding alpha-galactosidase A, on chromosome Xq22.

I will be adding a logical definition for the X-linked inheritance shortly. 
The GENO ontology has recently added a X-linked inheritance term.

Cheers,
Lynn
