### ISSUE TITLE
Pachyonychia congenita should have keratosis as a parent 

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#656]
Pachyonychia congenita  DOID:0050449 should  be a child of   keratosis DOID:161

**Comment by melodyswen** [comment]
Hi!

Thanks for reaching out - we'll look into this! 

Cheers,
Melody

**Comment by melodyswen** [comment]
Hi, 

After reviewing this issue, we have decided to keep DOID:0050449 as a child of 'autosomal dominant disease', as that is its primary inheritance. When referencing the Gennetics Home page for both keratosis and pachyonychia congenita, keratin is a commonality between the two diseases, keratosis primarily affects the skin and mucuous membranes, whereas pachyonychia congenita primarily affects the skin and nails. 

https://ghr.nlm.nih.gov/condition/pachyonychia-congenita

Thank you again for pointing this issue out, and we appreciate you addressing this issue. We apologize for the late reply! 

Cheers,
Melody
