### ISSUE TITLE
improved parentage for DOID:7558

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#659]
Consider adding 'glossopharyngeal nerve disease (DOID:3418)' as parent term for 'glossopharyngeal motor neuropathy' (DOID:7558)

**Comment by melodyswen** [comment]
Hi! 

Thanks for your comment, we'll review this!

**Comment by melodyswen** [comment]
Hi! 

We have linked these two terms, available in our OWL file for the next release. 

Thanks!
Melody
