### ISSUE TITLE
merge DOID:0110466

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#660]
Please see https://www.omim.org/entry/616958

Consider merging 'autosomal recessive nonsyndromic deafness 105' (DOID:0110466) into 'autosomal recessive nonsyndromic deafness 32 (DOID:0110491)'

**Comment by lschriml** [comment]
Thank you Marek !! 
I will take a look at these suggestions.
Much appreciated,
Lynn

**Comment by lschriml** [comment]
Agreed, 
OMIM has merged #105 into #32  


autosomal recessive nonsyndromic deafness 32
DOID:0110491
An autosomal recessive nonsyndromic deafness that is characterized by prelingual onset with severe to profound, stable hearing loss and has_material_basis_in variation in the chromosome region 1p22.1-p13.3. 
https://www.ncbi.nlm.nih.gov/pubmed/12634867
OMIM:608653

autosomal recessive nonsyndromic deafness 105
DOID:0110466
An autosomal recessive nonsyndromic deafness that has_material_basis_in mutation in the CDC14A gene on chromosome 1p21. 
https://www.ncbi.nlm.nih.gov/pubmed/27259055


Cheers,
Lynn
