### ISSUE TITLE
HumanDo.obo contains multi-parent disease classification?

### ISSUE THREAD

**Issue by need47** [DiseaseOntology/HumanDiseaseOntology#661]
As I understand it from the readme: https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/README_DO_Files

> DO Single Parentage ontology. 
The DO's disease classification is represented as both a single is_a hierarchy (doid-non-classified.obo). 
This file is equivalent to DO's HumanDO.obo file. We will continue to produce both files as the HumanDO naming 
schema was utilized and published for the first decade of the project. 

When I check the obo for example DOID:1441, I see two is_a relationships:
[Term]
id: DOID:1441
name: autosomal dominant cerebellar ataxia
alt_id: DOID:2478
def: "A hereditary ataxia that has_material_basis_in autosomal dominant inheritance." [url:http\://www.ncbi.nlm.nih.gov/books/NBK1138/,
subset: DO_FlyBase_slim
subset: NCIthesaurus
synonym: "spinocerebellar ataxia" EXACT []
xref: MESH:D020754
xref: NCI:C82341
xref: UMLS_CUI:C0087012
**is_a: DOID:0050736 ! autosomal dominant disease**
**is_a: DOID:0050951 ! hereditary ataxia**

**Comment by lschriml** [comment]
Thank you for your interest in the Disease Ontology.

You are correct the HumanDO.obo should only have one is_a parent. 
I am tagging in one of our engineers @rctauber, so that we can troubleshoot
of build process. 

Cheers,
Lynn

**Comment by lschriml** [comment]
Fixed in last weeks release
