### ISSUE TITLE
Move OMIM:137750 xref from 'open-angle glaucoma' to 'juvenile glaucoma'

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#663]
I _think_ the OMIM:137750 xref should be moved down one level, from 'open-angle glaucoma' (DOID:1067) to 'juvenile glaucoma' (DOID:1068):

http://omim.org/entry/137750

**Comment by lschriml** [comment]
Reviewing the glaucoma branch:
   I moved the requested OMIM change.
Added definitions. 
I have included the various OMIM IDs for the glaucoma phenotypes.
I would not create separate disease terms for the OMIM phenotypes at this time. 

Cheers,
Lynn

glaucoma
   two main types:
    angle-closure glaucoma
    open-angle glaucoma
          Open-angle glaucoma is also called primary or chronic glaucoma


**open-angle glaucoma**
         A glaucoma characterized by optic nerve damage resulting in progressive loss of visual field and increased pressure in the eye due to trabecular blockage.

--> the angle in your eye where the iris meets the cornea is as wide and open as it should be, but the eye’s drainage canals become clogged over time, causing an increase in internal eye pressure and subsequent damage to the optic nerve.
https://www.glaucoma.org/glaucoma/symptoms-of-primary-open-angle-glaucoma.php


     **juvenile glaucoma**
         orphanet: Juvenile glaucoma (JG) is a rare autosomal dominant open angle glaucoma, characterized by early onset, severe elevation of intra ocular pressure of rapid progression, leading to optic nerve excavation and, when untreated, substantial visual impairment.

**https://eyewiki.aao.org/Juvenile_open_angle_glaucoma**
Juvenile open-angle glaucoma (JOAG) is a rare subset of glaucoma diagnosed in individuals greater than 3 years old and less than 40 years of age. It is characterized by autosomal dominant inheritance and early age of onset. Compared to adult onset primary open-angle glaucoma (POAG), the juvenile form tends to be rapidly progressive with more severely elevated and fluctuating intraocular pressures (IOPs).

--> Juvenile open-angle glaucoma (JOAG) is **an uncommon subset of primary open-angle glaucoma (POAG)** characterized by autosomal dominant inheritance and early age of onset. Like other forms of glaucoma, JOAG is a condition of optic nerve degeneration manifested by optic nerve head changes and corresponding visual field defects.
    
      **primary open angle glaucoma**
https://www.ncbi.nlm.nih.gov/pubmed/28223208
          https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C35394
        --> A form of glaucoma in which there is no visible abnormality in the trabecular meshwork.
definition:
      is characterized by the absence of any apparent obstruction of aqueous outflow through the trabecular meshwork with gonioscopy, but often with elevated intraocular pressure.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5464971/ 


**OMIM:**

open angle glaucoma 1 A      **OMIM:137750**               (GLC1A). --> juvenile form in OMIM
open angle glaucoma 1B.      OMIM:606689              (GLC1B)
open angle glaucoma 1D        OMIM:602429            (GLC1D)
open angle glaucoma 1 F        OMIM:603383           (GLC1F)
open angle glaucoma 1G.      OMIM:609887            (GLC1G)
open angle glaucoma 1 H        OMIM:611276          (GLC1H)
open angle glaucoma 1 I       OMIM:609745          (GLC1I)

open angle glaucoma 1 J        OMIM:608695           (GLC1J)
open angle glaucoma 1 K        OMIM:608696          (GLC1K)
open angle glaucoma 1 M        OMIM:610535          (GLC1M)
open angle glaucoma 1 N        OMIM:611274          (GLC1N)
open angle glaucoma 1 O        OMIM:613100          (GLC1O)
open angle glaucoma 1 P        OMIM:177700           (GLC1P)

primary open angle glaucoma,          OMIM:137760.   (POAG)
   primary open angle glaucoma 1C.  OMIM:601682.  (GLC1C)
primary congenital glaucoma 3,         OMIM: 231300 (GLC3A)

**Comment by sjm41** [comment]
Thanks Lynn!
