### ISSUE TITLE
Remove OMIM xrefs from microcephaly (DOID:10907)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#664]
All these OMIM xrefs are now included in specific child DO terms, so should be removed from the parent.

[Term]
id: DOID:10907
name: microcephaly
xref: OMIM:251200
xref: OMIM:604321
xref: OMIM:604804
xref: OMIM:608393
xref: OMIM:608716
xref: OMIM:612703

**Comment by lschriml** [comment]
done
