### ISSUE TITLE
Remove OMIM:160500 xref from distal muscular dystrophy (DOID:11720)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#665]
OMIM:160500 is included as an xref to the more specific distal myopathy 1 (DOID:0070197) so should be removed from the parent term, distal muscular dystrophy (DOID:11720)

**Comment by sjm41** [comment]
Looks like these should be removed too, for same reason:
OMIM:160300, OMIM:254130, OMIM:613318, OMIM:613319

**Comment by lschriml** [comment]
Thank you for pointing these out, we are cleaning these up now.
Cheers,
Lynn

**Comment by lschriml** [comment]
Done, thank you for this update to the DO.

Cheers,
Lynn
