### ISSUE TITLE
Jan 2019 release questions

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#666]
Hello, On Feb 21, 2019 you made 'Jan 2019' release available. Does that mean that 'Feb 2019 release' is coming soon (to cover the one month gap)?

Thank you,
Marek

**Comment by lschriml** [comment]
Hello Marek,
I combined the Jan and Feb releases. We added a lot of new terms, definitions, axioms and xrefs for this release. Likely, I will do a second Feb release in the next two weeks. 

Cheers,
Lynn

**Comment by lschriml** [comment]
We will be updating the DO files early next week with a new release, so that the HumanDO.obo file has only the asserted parents. 

Cheers,
Lynn
