### ISSUE TITLE
duplicate terms [multiple congenital anomalies-hypotonia-seizures syndrome 2]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#668]
These terms has the same name and OMIM ID. Consider merge.

id: DOID:0080466
name: multiple congenital anomalies-hypotonia-seizures syndrome 2

id: DOID:0080139
name: multiple congenital anomalies-hypotonia-seizures syndrome 2

**Comment by lschriml** [comment]
Thank you for pointing this out. 
Looking at the multiple congenital anomalies-hypotonia-seizures syndrome terms (3 diseases),
   reviewing them, I see they should be re-classified as lipid metabolism disorders.
  The three diseases are currently classified as is_a 'syndrome' 

**see:**
https://www.ncbi.nlm.nih.gov/pubmed/29974678
Glycosylphosphatidylinositol (GPI) anchoring is a special type of protein posttranslational modification, by which proteins with diverse function are attached to cell membrane through a covalent linkage between the protein and the **glycolipid**. 
**Phosphatidylinositol glycan anchor biosynthesis class A** (PIGA) is a key enzyme in GPI anchor biosynthesis, somatic mutations or genetic variants of which have been associated with paroxysmal nocturnal hemoglobinuria (PNH), or **PIGA deficiency,** respectively. More than 10 PIGA pathogenic or likely pathogenic variants have been reported in a wide spectrum of clinical syndromes of PIGA deficiency, including **multiple congenital anomalies hypotonia-seizures syndrome 2** (MCAHS2).

--> merging: 
id: DOID:0080466 into id: DOID:0080139

--> updated the classification, added definitions. 

Cheers,
Lynn
