### ISSUE TITLE
duplicate terms [congenital disorder of glycosylation type IIm]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#669]
Consider merge:

id: DOID:0080469
name: congenital disorder of glycosylation type 2m

id: DOID:0070265
name: congenital disorder of glycosylation type IIm

**Comment by lschriml** [comment]
Thank you for pointing out this merge:
Agreed,
    they are the same disease, should be a child of 
congenital disorder of glycosylation type II

--> merging 
           id: DOID:0080469
            name: congenital disorder of glycosylation type 2m

  into: 

      id: DOID:0070265
      name: congenital disorder of glycosylation type IIm
 

Cheers,
Lynn
