### ISSUE TITLE
problems with DOID:0080489

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#670]
id: DOID:0080489
name: gangliosidosis GM3
is_a: DOID:2368 ! gangliosidosis

According to GARD and OMIM, there is no disease [gangliosidosis GM3]. However, there is 
[GM1 gangliosidosis type 3].

Therefore please consider changing name to [gangliosidosis GM1 type 3] and use [gangliosidosis GM1] (DOID:3322) as the parent. And if you agree with these changes, please consider to add the remaining types of [GM1 gangliosidosis], as found here: https://rarediseases.info.nih.gov/diseases/10891/gm1-gangliosidosis

**Comment by lschriml** [comment]
Thank you for pointing this out. 
Agreed, I have updated the the disease name.

I reviewed GM1 and GM2 gangliosidosis 

parent term: 
     **GM1 gangliosidosis**.   (DOID:3322, gangliosidosis GM1 )
     GARD:
        https://rarediseases.info.nih.gov/diseases/10891/gm1-gangliosidosis
  --> disease name updated 
--> new definition added

      --> 3 GM1 child terms added/updated, defined 

 GM2 gangliosidosis
     --> disease name revised 
    --> added definitions to 3 child terms, 
    updated disease name for GM2 gangliosidosis, AB variant

Cheers,
Lynn

Notes: 
GM1 gangliosidosis
      is an inherited lysosomal storage disorder that progressively destroys nerve cells (neurons) in the brain and spinal cord.   GM1 gangliosidosis is caused by mutations in the GLB1 gene and is inherited in an autosomal recessive manner.   The condition may be classified into three major types based on the general age that signs and symptoms first appear.

https://ghr.nlm.nih.gov/condition/gm1-gangliosidosis


**GM1 gangliosidosis type 1**
classic infantile (type 1) 
https://rarediseases.info.nih.gov/diseases/6479/disease
Synonym(s) : Infantile GM1 gangliosidosis
OMIM: 230500

**GM1 gangliosidosis type 2**
juvenile (type 2) 
https://rarediseases.info.nih.gov/diseases/10126/disease
Synonym(s) : Juvenile GM1 gangliosidosis ; Late-infantile GM1 gangliosidosis
OMIM: 230600
UMLS: C0268272
ICD-10: E75.1


**GM1 gangliosidosis type 3**
adult onset or chronic (type 3). 
Synonym(s) : Adult-onset GM1 gangliosidosis
OMIM: 230650
UMLS: C0268273
ICD-10: E75.1

**GM2 gangliosidosis**   DOID:3321    (Parent term)
ORPHA:309152
ICD-10: E75.0
UMLS: C0039373  C0268274

GM2 gangliosidosis, AB variant.   (DOID:4795 - Tay-Sachs disease AB variant)
ORPHA:309246
OMIM: 272750
UMLS: C0268275
ICD-10: E75.0
      --> will update the disease name 

https://ghr.nlm.nih.gov/condition/gm2-gangliosidosis-ab-variant

Tay-Sachs disease. (DOID:3320)
 synonym: GM2 gangliosidosis, type 1
https://ghr.nlm.nih.gov/condition/tay-sachs-disease#genes
OMIM:272800

Sandoff disease. (DOID:3323) 
  synonym: GM2-GANGLIOSIDOSIS, TYPE II
   OMIM:268800
