### ISSUE TITLE
duplicate terms [leukocyte adhesion deficiency 2]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#671]
According to OMIM and GARD these two terms are the same:

id: DOID:0080492
name: leukocyte adhesion deficiency 2

id: DOID:0070255
name: congenital disorder of glycosylation type IIc

**Comment by sjm41** [comment]
Also see: https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/648

**Comment by lschriml** [comment]
Thank you for checking on these terms. 
As outlined in my review in #648, I found that the evidence supports two distinct diseases. 
We are not going to merge these two disease terms at this time.

Cheers,
Lynn

**Comment by tutajm** [comment]
Thank you for showing me your review in #648 -- very helpful.

Marek

**Comment by lschriml** [comment]
Thank you Marek,
   I find it helps me to figure out these complicated ones, by putting the notes in the ticket. 
   And it also is good to have the documentation.

I really appreciate your sharing your review of the disease terms. And figuring them out together.

Cheers,
Lynn
