### ISSUE TITLE
Missing UBERON relationships in the latest release?

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#672]
In the latest doid-merged.OBO file the term musculoskeletal system cancer (DOID:0060100) is no longer a child of musculoskeletal system disease. In prior versions (see the 12/17/18 release) this relationship existed. Was this an intentional change? It seems odd to me to not classify musculoskeletal system cancer as a musculoskeletal system disease. Musculoskeletal system cancer does have a located in axiom for musculoskeletal system.

The same issue is in the doid.obo file. 

Looking into it, I think the problem is that musculoskeletal system disease no longer has a relationship to the UBERON term musculoskeletal system.

Note cardiovascular system disease, nervous system disease, reproductive system disease, and muscular disease have also lost their relationships to the corresponding UBERON terms

**Comment by lschriml** [comment]
Hello Sue,
  Thank you for letting us know. 
As you noticed, this is not correct. We have experienced this before where axioms just disappear in Protege. I’ll add them back in tomorrow and make a new release. 

I really appreciate your keeping an eye on the DO !!

Cheers,
Lynn

**Comment by tutajm** [comment]
Also numerous terms lost 'is_a: DOID:0080012 ! X-linked recessive disease' relationships.

**Comment by lschriml** [comment]
-- replaced EQ to cardiovascular system, musculoskeletal system, nervous system, immune system cancer, reproductive organ benign neoplasm', 

making a new release now

**Comment by lschriml** [comment]
identifying lost X-linked recessive SubClass Of statements and replacing them. 
Re-doing the release

**Comment by lschriml** [comment]
For the X-linked recessive, this happened when I updated the RO for the logical def this past week.
For inheritance, we are using 'has material basis in' for the EQ/SubClass Of statement. 

Apologies !! 

Cheers,
Lynn

**Comment by lschriml** [comment]
resolved in last weeks release
