### ISSUE TITLE
Why was Nipah virus encephalitis deprecated?

### ISSUE THREAD

**Issue by nathanathan** [DiseaseOntology/HumanDiseaseOntology#675]
I noticed Nipah virus encephalitis (DOID_0050192) was removed from the ontology. I am curious why that decision was made. There do not appear to be any other Nipah virus related entities and I am unaware of alternative names for it.

**Comment by lschriml** [comment]
Thank you Nathan for pointing this out.
Agreed, this term shouldn't be obsoleted.
I've reinstated the term.
Much appreciated !!
Lynn

**Comment by lschriml** [comment]
Thank you for pointing this out.
I researched this term, and have reinstated it. 
Updated the sources for the definition. 

Cheers,
Lynn
