### ISSUE TITLE
incomplete PS series [exudative vitreoretinopathy]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#677]
id: DOID:0050535
name: exudative vitreoretinopathy

This term currently has only one child: DOID:0080264 [exudative vitreoretinopathy 7]

Please add the remaining child terms as found in https://www.omim.org/phenotypicSeries/PS133780

**Comment by lschriml** [comment]
Thank you for the request.
Starting next week, we will be focusing dedicated effort, to completing the PS series in the DO.
I am adding your request to our PS requested list. 

Cheers,
Lynn

**Comment by tutajm** [comment]
That's great news! This effort will be very important for us in RGD. Looking forward to new DO releases :-) 

Thank you
Marek

**Comment by sbello** [comment]
added to spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
add PS133780
  update is complete
