### ISSUE TITLE
incomplete PS series [Meier-Gorlin syndrome]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#678]
id: DOID:0060306
name: Meier-Gorlin syndrome

This term has currently only one child term: DOID:0080255 [Meier-Gorlin syndrome 8]

Please consider adding the remaining child terms as found in
https://www.omim.org/phenotypicSeries/PS224690

**Comment by lschriml** [comment]
I have added the subtypes, OMIM IDs and inheritance for each. 

Cheers,
Lynn
