### ISSUE TITLE
McCune Albright syndrome classification as AD is dubious

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#680]
https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_1858

![image](https://user-images.githubusercontent.com/50745/54776031-7df30180-4bcc-11e9-91db-c15d3154ecc4.png)

Both text def and classification is under AD but this seems dubious

https://rarediseases.info.nih.gov/diseases/6995/mccune-albright-syndrome

> McCune-Albright syndrome (MAS) is not inherited. It is caused by a random, somatic mutation in the GNAS gene. Mutations that cause MAS occur very early in development, after an egg is fertilized (conception). These mutations are not present in the egg or sperm of the parents of affected children. Because these mutations are acquired after conception, some of the body's cells have a normal GNAS gene, while other cells have the mutated gene. This phenomenon is called mosaicism.[5][6]

> Because mutations that cause MAS are acquired, a person with MAS does not pass the disorder on to children.

The OMIM entry sheds some light on historic AD classification
https://www.omim.org/entry/174800
> Happle (1986) made the intriguing suggestion that this disorder is caused by an autosomal dominant lethal gene that is compatible with viability of the conceptus only when it occurs in the mosaic state, having arisen by somatic mutation. Endo et al. (1991) described monozygotic twin girls of whom one showed major signs of MAS: precocious puberty, cafe-au-lait nevi, and polyostotic fibrous dysplasia. The lack of fully convincing familial cases, except for the occurrence in monozygotic twins (Lemli, 1977), is consistent with the Happle hypothesis. (In the twins reported by Lemli (1977), one had classic signs of McCune-Albright syndrome and the other had only radiologic signs of bone disease and elevated serum alkaline phosphatase.

**Comment by cmungall** [comment]
Also note the doid xref to ncit is for the related concept Polyostotic Fibrous Dysplasia http://purl.obolibrary.org/obo/NCIT_C34610

should be this:
http://purl.obolibrary.org/obo/NCIT_C48627 ! McCune-Albright Syndrome

**Comment by lschriml** [comment]
Thank you Chris for this update.

**For McCune Albright syndrome**, 
  reference: https://journals.lww.com/clindysmorphol/Fulltext/2019/04000/Meier_Gorlin_syndrome__an_additional_case_report.8.aspx

-- updated classification, definition and xref for this term. 

For the NCIT xref: 
these are the same disease, see the NCIT definition: 
Definition:  Fibrous dysplasia affecting more than one bone. When it is associated with café-au-lait skin pigmentation and endocrine disorders, it is known as McCune-Albright syndrome.

--> Thank you for pointing out the NCI ID for McCune-Albright syndrome
Added to DO.

https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf

Cheers,
Lynn
