### ISSUE TITLE
synonym updates

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#681]
Synonym update request from katnastou@biol.uoa.gr,
Katerina Nastou, University of Athens.

I would like to report some discrepancies regarding the following Disease Ontology terms: DOID:9246, DOID:0070027, DOID:0070028.
More specifically, the EXACT synonyms used for DOID:9246:
-dutch hereditary cerebral amyloid angiopathy [EXACT]
-Hereditary cerebral haemorrhage with amyloidosis - Dutch type [EXACT]
are actually synonyms of the child term DOID:0070028.
Moreover, the terms associated with DOID:0070027:
-Hereditary Cerebral Hemorrhage with Amyloidosis [EXACT]
-Cerebral Hemorrhage, Hereditary, with Amyloidosis [EXACT]
should be added as synonyms of the parent term DOID:9246, since all variants are described by that term and should be removed from the child term or replaced with: 
-Hereditary Cerebral Hemorrhage with Amyloidosis, Icelandic Variant
-Cerebral Hemorrhage, Hereditary, with Amyloidosis, Icelandic Variant
 
Thank you in advance for your kind efforts!

**Comment by msinclair2** [comment]
Agreed: 

Removed dutch hereditary synonyms from parent term DOID:9246 ([dutch type is APP associated](https://en.wikipedia.org/wiki/Cerebral_amyloid_angiopathy).

Indicated synonyms were moved from DOID:0070027 to parent term DOID:9246 as they are nonspecific for subtype.

Suggested synonyms were added to DOID:0070027.

Thank you very much Katerina for pointing this out!
