### ISSUE TITLE
Acute erythroid leukemia

### ISSUE THREAD

**Issue by julienmariethoz** [DiseaseOntology/HumanDiseaseOntology#682]
https://en.wikipedia.org/wiki/Acute_erythroid_leukemia

http://omim.org/entry/133180

https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=8562&Disease_Disease_Search_diseaseGroup=318&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Acute-erythroid-leukemia&title=Acute%20erythroid%20leukemia&search=Disease_Search_Simple

**Comment by lschriml** [comment]
https://en.wikipedia.org/wiki/Acute_erythroid_leukemia
a rare form of acute myeloid leukemia
characterized by a predominant erythroid population
http://codes.iarc.fr/code/4214

**Comment by lschriml** [comment]
this is a susceptibility,  
ERYTHROLEUKEMIA, FAMILIAL, SUSCEPTIBILITY TO; FERLK

**Comment by sbello** [comment]
added to add priority spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
Added as a DO term, 
   Still to complete:  addition of the OMIM IDs as a susceptibility term 
Cheers,
Lynn

**Comment by lschriml** [comment]
Adding to OMIM susceptibility import:
       Name: http://purl.obolibrary.org/obo/OMIM_133180
            IRI: http://purl.obolibrary.org/obo/OMIM_133180
rdfs:label:      susceptibility to acute erythroid leukemia
ID:OMIM:133180
SubClassOf: 
    RO_0003304 some DOID_0080780
