### ISSUE TITLE
TN POLYAGGLUTINATION SYNDROME

### ISSUE THREAD

**Issue by julienmariethoz** [DiseaseOntology/HumanDiseaseOntology#683]
synonym : TNPS

https://www.omim.org/entry/300622

**Comment by lschriml** [comment]
Hello Julien,
Thank you for submitting this request. Generally, we have not been adding acronyms unless they are more commonly used than the full disease name.
We’ll take a look at this one.

Cheers,
Lynn

**Comment by julienmariethoz** [comment]
Hello Lynn,
my intent was not to add the acronym, but rather provide you some common name, alias and reference. Whatever the name I have for this disease, I will use the name and doid you have for this entry.
Cheers,
Julien

**Comment by lschriml** [comment]
Great !!
Thank you Julien !!

**Comment by lschriml** [comment]
Thank you Julien, the new disease term has been added.
DOID:0080520

Cheers,
Lynn
