### ISSUE TITLE
NTR Pyridoxine dependent epilepsy OMIM:266100&OMIM:617290

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#684]
OMIM # 266100 

Def:  Epilepsy inherited autosomal recessive manner. Neurotoxic compounds such as: alpha-amino adipic semi-aldehyde (alpha-AASA), piperideine 6-carboxylate and pipecolic acid accumulate in body fluids. Neonatal or infantile onset seizures that are refractory to anti-epileptic medications are clinical features.  Likely caused by variants of ALDH7A1.  
PMID:29053735

**Comment by lschriml** [comment]
task: adding a new term

**Comment by cerivs** [comment]
Label 
Pyridoxine-dependent epilepsy

Definition: 
 Epilepsy inherited autosomal recessive manner. Neurotoxic compounds such as: alpha-amino adipic semi-aldehyde (alpha-AASA), piperideine 6-carboxylate and pipecolic acid accumulate in body fluids. Neonatal or infantile onset seizures that are refractory to anti-epileptic medications are clinical features. Treatment is by large daily doses of pyridoxine.  Likely caused by variants of ALDH7A1 or PLPBP.    
Definiton ref
PMID:30154848|PMID:29053735|PMID:30043187

ParentIRI

Exact synonym
Antiquitin deficiency|Vitamin B6-dependent seizures|Pyridoxine dependency with seizures|Aasa Dehydrogenase Deficiency 



DbXref(same disease other ontology; Pipe delimited list)
OMIM:266100|OMIM:617290|UMLS_CUI:C1849508|UMLS_CUI:C1291560|MeSH:C536254|ORDO:3006

From orphanet
ICD-10: G40.8

 	
Sources
https://ghr.nlm.nih.gov/condition/pyridoxine-dependent-epilepsy
https://rarediseases.info.nih.gov/diseases/9298/pyridoxine-dependent-epilepsy
https://rarediseases.org/rare-diseases/pyridoxine-dependent-epilepsy/
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=3006

https://meshb.nlm.nih.gov/record/ui?ui=C536254

**Comment by sbello** [comment]
Working on this, 266100 is also on UniProt list

**Comment by sbello** [comment]
Proposal is to create 3 terms
pyridoxine-dependent epilepsy with Orphanet cross reference as parent to:
pyridoxine-dependent epilepsy 1 (adding 1 to distinguish from parent) xref is OMIM:266100, gene is ALDH7A1
early-onset vitamin B6-dependent epilepsy - xref OMIM:617290, gene is PLPBP

**Comment by sbello** [comment]
Additional references https://www.ncbi.nlm.nih.gov/pubmed/18062169 -
"four inborn errors of metabolism are known to affect vitamin B6 concentrations in the brain. Three of them are hyperprolinemia type 2, antiquitin deficiency, and pyridoxine phosphate oxidase deficiency. The fourth disorder occurs in neonates with hypophosphatasia and congenital rickets. All patients with these conditions present with early-onset epilepsy that is resistant to conventional antiepileptic medications"

**Comment by sbello** [comment]
Possibly it would be better to create a "vitamin B6 metabolic disorder" parent and group the new and exiting DO terms under this? Then link to epilepsy using the symptom relationship? @lschriml

**Comment by cerivs** [comment]
Anything I can do to help get these terms added?

**Comment by lschriml** [comment]
pyridoxine-dependent epilepsy   
and two OMIMs added to DO.

Apologies for the delay.
Please send us a reminder as needed.

Cheers,
Lynn
