### ISSUE TITLE
NTR: Bronchiolectasis

### ISSUE THREAD

**Issue by callahantiff** [DiseaseOntology/HumanDiseaseOntology#685]
**NTR**
Bronchiolectasis

**Synonyms**
Bronchiolectasia

**Definition**
A chronic lung disease characterized by abnormal dilatation or widening of the bronchi and mild to moderate airway obstruction, which frequently co-occurs with long-term inflammation, airway infection, and bronchial lesions ([PMID:20037680](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2793069/), [PMID:14256715](https://www.ncbi.nlm.nih.gov/pubmed/14256715)). Clinical manifestations include chronic cough, ineffective clearance of mucus, chronic or recurrent infection, weight loss, fatigue, and in very rare cases, hemotysis ([PMID:26024063](https://www.ncbi.nlm.nih.gov/pubmed/26024063)).

**Parent Class**
DOID_1176 bronchial disease

**Associated Diseases**
Cystic Fibrosis ([PMID:28546748](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5436792/))
- Cystic fibrosis [DOID:1485](http://disease-ontology.org/term/DOID%3A1485/) 
- Cystic fibrosis [OMIM:606963](https://www.omim.org/entry/606963?search=COPD&highlight=copd)

**Comment by lschriml** [comment]
Thank you Tiffany !!

**Comment by lschriml** [comment]
the proper name is : 
bronchiectasis   - this is DO: DOID:9563
   -- no new term

    -- but we do need to make the splits, to align with OMIM

**Comment by sbello** [comment]
added to split spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by lschriml** [comment]
Done, add the three subtypes.

**Comment by callahantiff** [comment]
Thank you @lschriml!
