### ISSUE TITLE
'healthful obesity'

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#690]
We have a reference PMID:30566857 which reports a model of 'healthful obesity' or metabolically healthy/normal obesity. There is not currently an appropriate DO term for this. These mice are modeling obesity with out metabolic issues and in the absence of overnutrition so the DO term 'obesity' (DOID:9970) is not a good fit.

The paper includes this text
"Our identification of BCL6 as a repressor of adipose tissue
expansion shares features with other mouse models of healthful
obesity, including transgenic adipocyte overexpression of Glut4
(Shepherd et al., 1993; Yore et al., 2014), mitoNEET (Kusminski
et al., 2012), adiponectin (Kim et al., 2007), and Cidea (Abreu-
Vieira et al., 2015), or genetic deletion models targeting collagen
VI (Khan et al., 2009) or Pten (Morley et al., 2015). Although these
molecules are quite varied in their cellular roles, they commonly
impact growth pathway signaling, de novo adipocyte lipogenesis,
and insulin-sensitizing adipokines or lipokines. Of note,
however, in most of these other models, healthy adipose tissue
expansion is only observed in states of overnutrition. In contrast,
Bcl6AKO mice exhibit spontaneously increased adipose tissue
mass and enhanced insulin sensitivity even in the absence of
a HFD."
on page 3294 in the discussion that indicates there are multiple other models of the same condition. 

@lschriml I'm not sure what the appropriate term is or where best to put it but this could use some research to see if adding a new DO term would be appropriate.

**Comment by lschriml** [comment]
Interesting !!
Reading through the paper, they are describing: 
 B cell lymphoma 6 ,  Bcl6 deletion --> results in:
     developmental expansion of subcutaneous adipose tissue

that ablation of adipocyte Bcl6 
enhances subcutaneous adipocyte lipogenesis, increases levels of adiponectin and fatty acid esters of hydroxy fatty acids (FAHFAs), and prevents steatosis.

--> It looks like these studies are only in animal models, without a human disease identified to date. 

From the paperL 
Thus, our studies identify BCL6 as a negative regulator of subcutaneous adipose tissue expansion and metabolic health.

--> I would say that subcutaneous adipose tissue expansion --> is a phenotype in this case 

Up to 50% of obese adults are considered ‘‘metabolically healthy’’ based on varying criteria, and these individuals are typified by expanded subcutaneous, but reduced visceral and intrahepatic, fat distributions
 citation: 
Fabbrini E, Yoshino J, Yoshino M, Magkos F, Tiemann Luecking C, Samovski D, Fraterrigo G, Okunade AL, Patterson BW, and Klein S (2015). Metabolically normal obese people are protected from adverse effects following weight gain. J. Clin. Invest 125, 787–795. [PMC free article] [PubMed]


--> I don't see how we can include this as a disease, not until there are instances in human that are considered a disease. 

Looking at the human gene in NCBI:
https://www.ncbi.nlm.nih.gov/gene/604

This gene is found to be frequently translocated and hypermutated in diffuse large-cell lymphoma (DLCL), and may be involved in the pathogenesis of DLCL. 

Also looking at UniProt:
https://www.uniprot.org/uniprot/P41182

Involvement in diseasei
Chromosomal aberrations involving BCL6 are a cause of B-cell non-Hodgkin lymphomas (B-cell NHL), including diffuse large B-cell lymphoma and follicular lymphoma. Approximately 40% of diffuse large B-cell lymphomas and 5 to 10% of follicular lymphomas are associated with chromosomal translocations that deregulate expression of BCL6 by juxtaposing heterologous promoters to the BCL6 coding domain (PubMed:10469447, PubMed:10753856, PubMed:12414651, PubMed:11821949). Translocation t(3;14)(q27;q32). Translocation t(3;22)(q27;q11) with immunoglobulin gene regions (PubMed:11821949). Translocation t(3;7)(q27;p12) with IKZF1 gene 5'non-coding region (PubMed:10753856). Translocation t(3;6)(q27;p21) with Histone H4 (PubMed:12414651). Translocation t(3;16)(q27;p11) with IL21R. Translocation t(3;13)(q27;q14) with LCP1 (PubMed:10469447).


Cheers,
Lynn

**Comment by sbello** [comment]
That was my impression as well but I definitely wanted a second opinion. MGI will need to think about what to do with things that model human conditions/phenotypes rather than diseases.
