### ISSUE TITLE
OMIM gene ids assigned to some terms

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#691]
Several newly added terms (DOID:0080507, DOID:0080508, DOID:0080509) have assigned OMIM gene ids. It should use OMIM phenotype ids instead.

Reason: in general the assumption that a single gene is associated only with one disease phenotype is not true.

Btw, it will be great if entire DO ontology will be scanned for the presence of OMIM gene ids before release.

**Comment by sbello** [comment]
DOID:0080507 changed the OMIM xref to 610759

**Comment by sbello** [comment]
DOID:0080508 changed the OMIM xref to 614701

**Comment by sbello** [comment]
DOID:0080509 changed the OMIM xref to 300882

**Comment by sbello** [comment]
Thanks for catching these. I've changed all the xrefs to the correct OMIM disease IDs.
