### ISSUE TITLE
merge DOID:0050643 and DOID:0080082

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#693]
Both DOID:0050643 and DOID:0080082 have OMIM:206800 as an xref.  Based on the definition of DOID:0050643 and the OMIM entry for 206800 it appears to me that these are representing the same concept.
The definition for DOID:0050643 is "A nail disease that is characterized by absence of fingernails and toenails, has_material_basis_in homozygous or compound heterozygous mutation in the R-spondin-4 gene on chromosome 20p13."
The OMIM description for NDNC4 is "A number sign (#) is used with this entry because of evidence that autosomal recessive nonsyndromic congenital nail disorder-4 (NDNC4) can be caused by homozygous or compound heterozygous mutation in the R-spondin-4 gene (RSPO4; 610573) on chromosome 20p13."
I think we should merge these DO terms.

**Comment by lschriml** [comment]
Agreed, 
   I have merged the records.

Cheers,
Lynn
