### ISSUE TITLE
Latest doid.obo file missing default-namespace attribute in header

### ISSUE THREAD

**Issue by ybradford** [DiseaseOntology/HumanDiseaseOntology#694]
the following header attribute is missing in the disease file:

default-namespace: disease_ontology

Could you please put that back in? Our loader depends on a default namespace.

Thanks,
Yvonne

**Comment by lschriml** [comment]
Thank you Yvonne,
   Apologies for the error.
I have fixed the doid.obo file.

I am ccing @rctauber -- so that she can help us fix this in our make file. 

Cheers,
Lynn

**Comment by rctauber** [comment]
Resolved, thank you!
