### ISSUE TITLE
New MGI terms on ROBOT spreadsheet 4/25/19

### ISSUE THREAD

**Issue by MonikaTomczuk** [DiseaseOntology/HumanDiseaseOntology#695]
Added the following terms to the ROBOT template:
glutaric acidemia I
2-aminoadipic 2-oxoadipic aciduria
SHORT syndrome
GRACILE syndrome

https://docs.google.com/spreadsheets/d/1m_Skq97c4HwuRlClYe30ZuZqF6rboCl7RbigOFLS70U/edit?usp=sharing

**Comment by MonikaTomczuk** [comment]
Added the following terms to the ROBOT template:
glutaric acidemia 1
2-aminoadipic 2-oxoadipic aciduria
SHORT syndrome
GRACILE syndrome

https://docs.google.com/spreadsheets/d/1m_Skq97c4HwuRlClYe30ZuZqF6rboCl7RbigOFLS70U/edit?usp=sharing

**Comment by lschriml** [comment]
Thank you Monika !!

**Comment by sbello** [comment]
Closing this as the terms have been added
