### ISSUE TITLE
non-small cell lung carcinoma - add child term of lung non-squamous cell carcinoma

### ISSUE THREAD

**Issue by smockus** [DiseaseOntology/HumanDiseaseOntology#700]
Requested term corresponds to Lung Non-Squamous Non-Small Cell Carcinoma in NCI-T, Code C135017): https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=19.03d&ns=ncit&code=C135017&key=1069526203&b=1&n=null

**Comment by lschriml** [comment]
Hello Susan,
 I have added the term. 
DOID:0080521, lung non-squamous non-small cell carcinoma

Notes: 

Lung Non-Squamous Non-Small Cell Carcinoma (Code C135017)
Preferred Name:  Lung Non-Squamous Non-Small Cell Carcinoma

Definition:  A non-small cell lung carcinoma without evidence of squamous differentiation.

parent: 
  Lung Non-Small Cell Carcinoma 
  this is DOID:3908, non-small cell lung carcinoma
   --> updating the name for this term, to align with NCI

 lung non-small cell carcinoma 
     lung large cell carcinoma
     lung squamous cell carcinoma
     [new term]
     lung non-squamous non-small cell carcinoma
