### ISSUE TITLE
thyroid carcinoma - add child term of anaplastic thyroid carcinoma 

### ISSUE THREAD

**Issue by smockus** [DiseaseOntology/HumanDiseaseOntology#701]
This corresponds to NCI-T: Thyroid Gland Anaplastic Carcinoma (Code C3878)
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=19.03d&ns=ncit&code=C3878&key=1094999514&b=1&n=null

**Comment by lschriml** [comment]
Hello Susan,
 thank you for the new terms !! 

In the DO,
   thyroid carcinoma DOID:3963 (parent term)

--> created new term: DOID:0080522
     thyroid gland anaplastic carcinoma 
     (Code C3878)

Cheers,
Lynn

**Comment by kkrysiak** [comment]
Can this DOID be added to the Cancer_slim file?
