### ISSUE TITLE
Rework Tree for Thyroid Carcinoma

### ISSUE THREAD

**Issue by smockus** [DiseaseOntology/HumanDiseaseOntology#704]
Parent child terms for thyroid carcinoma need to be reworked and new terms added. This is important to cover specific subtypes of thyroid carcinoma as covered in NCCN Guidelines.
[Thyroid Terms.pptx](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/3176935/Thyroid.Terms.pptx)

**Comment by lschriml** [comment]
Hello Sue,
  Thank you for pointing out this update.
I have updated the DO file, with the new classification.
I updated disease names, added definitions, added xrefs.

These changes will be in our public release, first week of June.

Cheers,
Lynn

**Comment by smockus** [comment]
Thanks, Lynn!

Susan Mockus, Ph.D., MBA
Associate Director, Clinical Genomic Market Development
The Jackson Laboratory for Genomic Medicine
P: 860-837-2463                C: 860-839-4270

ckbhome.jax.org<https://ckbhome.jax.org/>
