### ISSUE TITLE
Cancer slim missing childhood cancer terms

### ISSUE THREAD

**Issue by obigriffith** [DiseaseOntology/HumanDiseaseOntology#705]
It looks like some (recently added) childhood cancer terms are missing from DO_cancer_slim.obo. See for example: http://www.disease-ontology.org/?id=DOID:0060592

Could we get an updated/current cancer slim for use with CIViC? Please. :-)

**Comment by msinclair2** [comment]
Hi Obi,

I've gone ahead and added all ClinGen pediatric cancer terms to the DO cancer slim subset.  They will be public the first week of June with our next release.  If you notice at that time any cancer terms not in the slim that you want, please let us know and we'd be happy to add them!  

-Michael

**Comment by obigriffith** [comment]
Thanks guys!
