### ISSUE TITLE
OMIM:114900 - carcinoid tumors, intestinal

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#707]
How should OMIM:114900 carcinoid tumors, intestinal be mapped to DO

Note we learned today that information after the comma may be considered non-essential to some disease names. If that were the case here then this would just be carcinoid tumors.

The Orphanet link at OMIM goes to Carcinoid syndrome (OROD:100093). This mapping makes more sense if we drop intestinal from the OMIM term name

**Comment by lschriml** [comment]
Next steps: 
  review annotations in MGI, HPO and UniProt.

**Comment by lschriml** [comment]
Reviewed: 
**add new term as child of : neuroendocrine tumor** (DOID:169)
    child term: carcinoid tumor 
A carcinoid (also carcinoid tumor) is a slow-growing type of neuroendocrine tumor originating in the cells of the neuroendocrine system.
https://en.wikipedia.org/wiki/Carcinoid

-- carcinoid tumor is a slow-growing type of cancer that can start in any part of the body that has neuroendocrine cells. These cells receive signals from the nervous system and then release hormones into the blood.
https://www.mdanderson.org/cancer-types/carcinoid-tumors.html

https://onf.ons.org/onf/37/6/carcinoid-tumor

https://onf.ons.org/onf/37/6/carcinoid-tumor

 has_material_basis_in neuroendocrine cells AND 'is indolent' 
   --> We don't currently have an import that would allow us to make the above axiom. 
These are 'slow growing' or indolent tumors. 
    
Cheers,
Lynn

**Comment by lschriml** [comment]
moved parentage to neuroendocrine tumor, done.
