### ISSUE TITLE
OMIM:115080 Cardiac conduction defect

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#708]
seems like this should just be an xref to DOID:10273, 

ORDO xref is ORDO:871 Familial progressive cardiac conduction defect which is an xref to DOID:0111073 but OMIM record mentions genetic and non-genetic causes, 

the only gene is susceptibility link

note, there are two included entities in the OMIM record so this is going to take some careful parsing

**Comment by lschriml** [comment]
OMIM:115080
    -- to be further reviewed

**Comment by lschriml** [comment]
DOID:10273.  heart conduction disease

DOID:0111073. progressive familial heart block
  --> add OMIM:115080 Cardiac conduction defect
     to this DO term.

**Comment by lschriml** [comment]
done
