### ISSUE TITLE
OMIM:102900 - Adenosine triphosphate, elevated, of erythrocytes

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#709]
good example of the line between disease and trait/phenotype

referred to as asymptomatic in papers, but reports for multiple families and multiple groups have requested, phenotypes are elevated red blood cell ATP, slight shortening of red cell life span, mild erythrocytosis, elevated red cell pyruvate kinase activity - 

Is this a disease in the DO sense of disease?

Joanna indicated she would consider this more of a trait, like blood groups

**Comment by lschriml** [comment]
-- call it a trait, move to excluded list
