### ISSUE TITLE
motor neuritis parentage

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#712]
Currently 'motor neuritis' DOID:683 is-a 'motor neuron disease'. And that looks good, but is also too general for my taste.

1) thes 2 synonyms 'peripheral motor neuropathy' suggest that the term has a common ground with 'motor peripheral neuropathy' DOID:2477. So that term looks a natural parent for DOID:683

2) having 'neuritis' in term name suggests parentage from 'neuritis' DOID:1803

3) MONARCH already has the parentage as proposed above: https://monarchinitiative.org/disease/MONDO:0004004

Please kindly review the parentage.

PS. Any news regarding DO release this month?

Thank you,

**Comment by lschriml** [comment]
Thank you for the review question. 
I'll take a look. 

This month's release is planned for next week.

Cheers,
Lynn

**Comment by lschriml** [comment]
Looking at these terms, with their low DOIDs:
   They were added in early years of the DO.

   Good that you suggested a re-review. 

To Do: review all neuritis terms: 
             move to be child terms of neuritis, add logical definitions for anatomy 
            

             **Add definition:** 
                    neuritis: inflammation of the nerve or the general inflammation of the peripheral nervous system. Symptoms depend on the nerves involved but may include pain, paresthesia (pins-and-needles), paresis (weakness), hypoesthesia (numbness), anesthesia, paralysis, wasting, and disappearance of the reflexes.

                          -- add 'motor neuritis' as a child term.   DOID:683
                                         defn: inflammation of the motor nerve
                   
          To Do: remove synonym (peripheral motor neuropathy), NCI:C3500


[peripheral nervous system disease]
    neuropathy
        motor peripheral neuropathy. -- assign NCI:C3500

--> review neuropathies
To Do: 
remove NCI:C75467 from DOID:2477,  belongs to Charcot-Marie-Tooth DOID:10595

**Comment by melodyswen** [comment]
Confirmed that NCI:C75467 is an xref in Charcot-Marie-Tooth, and removed same xref from DOID:2477
