### ISSUE TITLE
granular corneal dystrophy

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#713]
The DO record for granular corneal dystrophy (DOID:12318) does not have an xref for OMIM:121900 but the definition does have an xref to this OMIM record. I think this was an oversight and that this record was meant to represent gcd type 1 which used to be called just gcd. 

The other option is that this was meant to be a generic class for gcd and the entried for gcd1 and gcd2 (DOID:0060444) should be children of this term. 

It looks like the definition for gcd was only recently added to DO as it doesn't appear on any of the browsers. So I'm uncertain what the intent was for this term initially.

**Comment by lschriml** [comment]
Hello Sue,
   Thank you for pointing this out.
Agreed, this split was incomplete.
I've finished the split, added OMIM IDs, updated definitions. 
Cheers,
Lynn
