### ISSUE TITLE
cardiocutaneous syndrome class

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#715]
From Monika at MGI
I have a paper (J:264272, https://www.ncbi.nlm.nih.gov/pubmed/28069640) that describes the phenotype of patients with a mutation in the PPP1R13L gene and they conclude that these patients have a novel form of an autosomal recessive cardiocutaneous syndrome which they do not name. Examples of other cardiocutaneous syndromes they mention in the intro are Naxos disease and Carvajal syndrome. I found a nice review on cardiocutaneous syndromes (https://openheart.bmj.com/content/3/2/e000442) that lists a bunch of others

List of syndromes from the review with location in DO if they are in DO:
Naxos disease is in Orphanet and OMIM (ORPHA:34217 and OMIM:601214)
Carvajal syndrome is in DO (DOID:0090128) under autosomal recessive disease
Carney complex is in DO (DOID:0050471) under autosomal dominant disease
Costello syndrome is in DO (DOID:0050469) under autosomal dominant disease
cardiofaciocutaneous syndrome is in DO (DOID:0060233) under monogenic disease and syndrome
Ellis van Creveld syndrome is in DO (DOID:12714) under autosomal recessive disease
H syndrome in Orphanet and OMIM (ORPHA:168569 and OMIM:602782)
Leopard syndrome is in DO (DOID:14291) under autosomal dominant disease
Noonan syndrome is in DO (DOID:3490) under syndrome
Ehlers-Danlos syndrome in DO (DOID:13359) under collagen disease, current definition makes no mention of cardiac signs
Marfan syndrome in DO (DOID:14323) under eye disease and connective tissue disease
Cutis laxa in DO (DOID:3144) under skin disease

I suggest we consider adding a class term for cardiocutaneous syndrome (CCS) to collect these related disorders under a single parent. This would also give MODs a place to curate new CCS that do not currently have an entry in DO.

**Comment by lschriml** [comment]
To Do: 
  (1) update LEOPARD syndrome - updated name in GHR, subtypes in OMIM, remove  
                                                   cardiocutaneous syndrome from synonyms. 

            DO needs to update the disease name, for DOID:14291 

             OMIM: there are three subtypes of LEOPARD syndrome (PS151100)
      LEOPARD syndrome 1     OMIM:611554
      LEOPARD syndrome 2.   OMIM:613707
      LEOPARD syndrome 3.    OMIM:151100



  (2) cardiocutaneous syndrome -- I am not finding support for making this a new disease 

       PPP1R13L gene, OMIM:607463. [gene record]
             -- no associated human disease, also checked NCBI gene, no associated human disease


(3) Create a new DO term for  **Naxos disease**.  
                             is a cutaneous condition characterized by a palmoplantar keratoderma
                            https://en.wikipedia.org/wiki/Naxos_syndrome
                                  synonym: Diffuse non-epidermolytic palmoplantar keratoderma with 
                                                   woolly hair and cardiomyopathy

as a child of: 
           **nonepidermolytic palmoplantar keratoderma**. [DOID:0050428]
                              
move:          DOID:0090128    **Carvajal disease**   
                                 (synonym of "dilated cardiomyopathy with woolly hair and keratoderma"       )
            to be a child of  **nonepidermolytic palmoplantar keratoderma**. [DOID:0050428]
                               
             add:    GHR:https://ghr.nlm.nih.gov/condition/keratoderma-with-woolly-hair

Cheers,
Lynn





Notes: 
  
**cardiofaciocutaneous syndrome**
https://ghr.nlm.nih.gov/condition/cardiofaciocutaneous-syndrome#genes
     -- Cardiofaciocutaneous syndrome is a disorder that affects many parts of the body, particularly the heart (cardio-), facial features (facio-), and the skin and hair (cutaneous). People with this condition also have delayed development and intellectual disability, usually ranging from moderate to severe.
    -- malformations of one of the heart valves that impairs blood flow from the heart to the lungs (pulmonic stenosis), a hole between the two upper chambers of the heart (atrial septal defect), and a form of heart disease that enlarges and weakens the heart muscle (hypertrophic cardiomyopathy).

**Comment by lschriml** [comment]
I have updated LEOPARD syndrome, added the 3 OMIM subtypes.

DOID:0090128 name updated to --> Carvajal disease
(synonym of "dilated cardiomyopathy with woolly hair and keratoderma" )

added Naxos disease and updated Carvajal syndrome.

Cheers,
Lynn
