### ISSUE TITLE
new MGI slim set

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#716]
We would like a new slim tag for a new set of MGI slim terms to use with filters. This does NOT replace the existing DO_MGI_slim set. This would be a second set. Possibly use the tag DO_MGI2_slim or we could use DO_GXD_slim as the first use will be with filters on the gene expression pages.
Thanks,
Sue

**Comment by sbello** [comment]
The GXD team has not yet settled on the list of terms for this tag but I will add the tag to the terms once they do.

**Comment by lschriml** [comment]
DO_GXD_slim subset tag created.
Lynn

**Comment by lschriml** [comment]
New slim is included in latest DO release. 
Lynn
