### ISSUE TITLE
Brooks-Wisniewski-Brown syndrome

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#717]
Thank you for June'19 release! However, I noticed a conflict. According to OMIM, these two terms are the same:

[Brooks-Wisniewski-Brown syndrome] id: DOID:0060829
[syndromic X-linked intellectual disability Turner type] id: DOID:0060811

OMIM:300612, which is currently assigned to DOID:0060829, in May 2019 has been merged into OMIM:309590 which is currently assigned to DOID:0060811

**Comment by sbello** [comment]
@lschriml I took a look at this when OMIM:300612 showed up on the obsolete QC report. The question I had was whether there was consensus that the 2 DO terms should be merged from the disease community. Looking at the OMIM records it is fairly clear that OMIM has merged these and considers them to be the same disease. But it was not clear to me that others had reached the same conclusion.

**Comment by lschriml** [comment]
Hello @sbello 
    -- reviewing literature and OMIM, etc. information.
I have merged 
[Brooks-Wisniewski-Brown syndrome] id: DOID:0060829
into
[syndromic X-linked intellectual disability Turner type] id: DOID:0060811

and removed: OMIM:300612 

Cheers,
Lynn
