### ISSUE TITLE
suspicious parentage of [leukocyte adhesion deficiency 2]

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#718]
Currently

id: DOID:0080492
name: leukocyte adhesion deficiency 2
is_a: DOID:0110912 ! leukocyte adhesion deficiency 3

This looks like a bug. Should not the parent be [leukocyte adhesion deficiency] (DOID:6612) instead?

**Comment by lschriml** [comment]
Thank you for pointing this out. 
Agreed, this is not how these terms should be represented

The parent term, leukocyte adhesion deficiency
    --> moving to combined T cell and B cell immunodeficiency DOID:628
          --> will move parentage, so that the three subtypes are is_a to 
                the paren term: leukocyte adhesion deficiency

--> will add SubClassOf - anatomy for the parent term, 'located in some leukocyte

The DO file is updated, the updates will be in our public files with our next release. 

(Notes below)

Cheers,
Lynn



notes:
resource: 
**NCBI Books: Leukocyte Adhesion Deficiency**
https://www.ncbi.nlm.nih.gov/books/NBK539770/
**[Updated 2019]** 

leukocyte adhesion deficiency. (ORDO:2968)
       autosomal recessive disorder
   -- causes the immune system to malfunction
  -- is a defect of cellular adhesion molecules 
       a combined (B cell) and cellular (T cell) immunodeficiency disorder.

  

**There are three different types of LAD**
**Type I** - in which steady adhesion of leukocyte to endothelial surfaces is defective by mutations in CD18 gene resulting in defective or deficient beta-2 integrin

**Type II** - in which there is an absence of Sialyl Lewis X of E-selectin

**Type III** - in which there is a defect in beta integrins 1, 2, and 3; this impairs the integrin activation cascade - specifically, a mutation in the kindlin-3 gene causes this type of LAD


OMIM:116920 leukocyte adhesion deficiency 1
     GHR: https://ghr.nlm.nih.gov/condition/leukocyte-adhesion-deficiency-type-1



ORDO:99843  leukocyte adhesion deficiency 2
               NO OMIM

OMIM:612840   leukocyte adhesion deficiency 3
