### ISSUE TITLE
histiocytosis-lymphadenopathy plus syndrome

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#719]
The OMIM record histiocytosis-lymphadenopathy plus syndrome (OMIM:602782) combines 4 related syndromes  (Faisalabad histiocytosis, sinus histiocytosis with massive lymphadenopathy, H syndrome, and pigmented hypertrichosis with insulin-dependent diabetes mellitus syndrome) that were previously considered distinct. 
Orphanet takes the same 4 disorders and splits them into 2 groups; one for Faisalabad histiocytosis, H syndrome, and pigmented hypertrichosis with insulin-dependent diabetes mellitus syndrome and a second for sinus histiocytosis with massive lymphadenopathy. The placement of these two terms in the Orphanet hierarchy is very different.

@lschriml  Should these be combined in DO into a single entry (as in OMIM) or should we have 2 entries (as in Orphanet).

Some helpful references 
https://www.ncbi.nlm.nih.gov/pubmed/20140240
https://www.ncbi.nlm.nih.gov/pubmed/22238637
https://www.ncbi.nlm.nih.gov/pubmed/22356918
https://www.ncbi.nlm.nih.gov/pubmed/21178579

**Comment by sbello** [comment]
GARD also has 2 entries 
https://rarediseases.info.nih.gov/diseases/7588/index
https://rarediseases.info.nih.gov/diseases/10239/index
10239 was updated in 2016, 7588 was updated in 2013 
the OMIM record was updated in 9/25/2017

**Comment by lschriml** [comment]
Hello Sue,
  Looking at [GHR](https://ghr.nlm.nih.gov/condition/histiocytosis-lymphadenopathy-plus-syndrome#resources) and OMIM and references, 

   I would say represent this as one disease. 

One additional reference to include: 
https://www.ncbi.nlm.nih.gov/pubmed/23729543

Cheers,
Lynn

**Comment by sbello** [comment]
Thanks Lynn.
That was my inclination as well.
