### ISSUE TITLE
parentage of [Fukuyama congenital muscular dystrophy] (DOID:0050559)

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#720]
This term lists OMIM:253800 xref, which in turn describes this disease as [MUSCULAR DYSTROPHY-DYSTROGLYCANOPATHY (CONGENITAL WITH BRAIN AND EYE ANOMALIES), TYPE A, 4]

Recently term [congenital muscular dystrophy-dystroglycanopathy type A] (DOID:0111229) was added to DO.

It looks to me, DOID:0050559 should have DOID:0111229 as a parent.

Please kindly review.

**Comment by lschriml** [comment]
Thank you for pointing this one out.
Looking at this set of terms, I see that @sbello is curating this set of DO terms and their OMIM IDs.
I agree that DOID:0050559 (Fukuyama congenital muscular dystrophy - OMIM synonym: MUSCULAR DYSTROPHY-DYSTROGLYCANOPATHY (CONGENITAL WITH BRAIN AND EYE ANOMALIES), TYPE A, 4)
     --> will be moved to be a child of congenital muscular dystrophy-dystwroglycanopthy type A. 

I found these resources informative for looking into the changing nomenclature of these disease: 
 https://www.genome.jp/dbget-bin/www_bget?ds:H00120
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5006267/
https://ghr.nlm.nih.gov/condition/fukuyama-congenital-muscular-dystrophy

Cheers,
Lynn

**Comment by melodyswen** [comment]
Resolved - moved parentage of Fukuyama congenital muscular dystrophy to congenital muscular dystrophy-dystroglycanopathy type A.
