### ISSUE TITLE
new term request from Xenbase: non-alcoholic steatohepatitis (NASH)

### ISSUE THREAD

**Issue by Xenbase2** [DiseaseOntology/HumanDiseaseOntology#722]
request new DO term: non-alcoholic steatohepatitis (NASH)

references: 
C.P. Day, O.F.W. James
Steatohepatitis: a tale of two “hits”?
Gastroenterology, 114 (1998), pp. 842-845.

C.P. Day
From fat to inflammation
Gastroenterology, 130 (2006), pp. 207-210.

seen in Xenopus in this study:
M. Usal et al. 
Concomitant exposure to benzo[a]pyrene and triclosan at environmentally relevant concentrations induces metabolic syndrome with multigenerational consequences in Silurana (Xenopus) tropicalis.
Sci Total Environ June 25, 2019; 689 149-159.

**Comment by lschriml** [comment]
I have added two terms:
non-alcoholic steatohepatitis (NASH) and non-alcoholic fatty liver (NAFL).
