### ISSUE TITLE
Review 'mixed cell type cancer' logical definition

### ISSUE THREAD

**Issue by rctauber** [DiseaseOntology/HumanDiseaseOntology#724]
'mixed cell type cancer' (DOID:154) is equivalent to the following:
```
cancer
 and ((derives_from some 'ectodermal cell') or 
      (derives_from some 'mesodermal cell') or 
      (derives_from some 'endodermal cell'))
```

The definition states that it is:
> A cell type cancer that has_material_basis_in abnormally proliferating cells derives_from two germinal layers of tissue.

According to the equivalent class statement, 'mixed cell type cancer' can derive from *one* of those three options (e.g., it could derive from just 'mesodermal cell'). I'm not familiar with the cancer classifications, but that doesn't seem like "mixed" and it's not deriving from *two* layers.

I think it would be more appropriate to say, if it `derives_from` *two or more* layers:
```
cancer and 
    (((derives_from some 'ectodermal cell') 
        and (derives_from some 'mesodermal cell')
        and (derives_from some 'endodermal cell'))
    or
    (((derives_from some 'ectodermal cell') 
        and (derives_from some 'mesodermal cell'))
    or 
    ((derives_from some 'ectodermal cell') 
        and (derives_from some 'endodermal cell'))
    or 
    ((derives_from some 'mesodermal cell') 
        and (derives_from some 'endodermal cell')))
```

This change of equivalent class definition removes two inferred children, though:
* 'central nervous system endodermal sinus tumor'
* 'endodermal sinus tumor'

Both of those inferred children have the following axioms:
* `derived_from some 'endodermal cell'`
* `derived_from some 'germ cell'`

Are they truly mixed cell cancers? 

With the current equivalent axiom, anything that has the axiom `derives_from some 'x'` where `x` is one of 'endodermal cell', 'mesodermal cell', or 'ectodermal cell' will be inferred to be a 'mixed cell type cancer', even if it only derives from one of them (e.g., it only derives from 'ectodermal cell').

With the updated equivalent axiom, to be inferred a 'mixed cell type cancer', a class would need at least two of the axioms, such as:
* `derives_from some 'endodermal cell'`
* `derives_from some 'mesodermal cell'`

**Comment by lschriml** [comment]
Thank you for figuring this out.
Mixed cell type -> is for exactly two layers:

cancer and 
    (((derives_from some 'ectodermal cell') 
        and (derives_from some 'mesodermal cell'))
    or
    ((derives_from some 'ectodermal cell') 
        and (derives_from some 'endodermal cell'))
    or 
    ((derives_from some 'mesodermal cell') 
        and (derives_from some 'endodermal cell')))

**Comment by lschriml** [comment]
I've reviewed child terms (inferred), made revisions. 
Lynn
