### ISSUE TITLE
Missing logical axiom from 'Angelman syndrome'

### ISSUE THREAD

**Issue by rctauber** [DiseaseOntology/HumanDiseaseOntology#725]
'Angelman syndrome' (DOID:1932) previously had the subclass axiom:
```
(maternally_imprinted and loss_of_function_variant) 
  or (paternal_uniparental_disomy and loss_of_function_variant) 
  or (loss_of_function_variant and ('located in' exactly 1 gene)) 
  or ('has material basis in' min 1 
      (maternal_variant and loss_of_function_variant and chromosomal_deletion))
```

I think this axiom was logically incorrect, as it resulted in an Error in https://github.com/DiseaseOntology/HumanDiseaseOntology/commit/d65171eb1948829dc541abe54304541818742e3c and the axiom was removed. This axioms also states that 'Angelman syndrome' can be a subclass of the intersections of certain sequence attribute classes, making this disease a type of sequence attribute.

Could we review this axiom and determine the correct logical axiom? Perhaps it was meant to start with `has material basis in`?

**Comment by lschriml** [comment]
Yes, it was supposed to start with
 has material basis in 'min 1' 
documente in: 
https://docs.google.com/spreadsheets/d/1pqsxhfCzZN4KzMiF2mUCI4gzRVZY4rUEFS5cJEJ2NdE/edit#gid=0

I've added it back in as: 
'has material basis in' min 1  
(maternally_imprinted and loss_of_function_variant) 
  or (paternal_uniparental_disomy and loss_of_function_variant) 
  or (loss_of_function_variant and ('located in' exactly 1 gene)) 
  or ('has material basis in' min 1 
      (maternal_variant and loss_of_function_variant and chromosomal_deletion))

**Comment by rctauber** [comment]
I think there is an extra `has material basis in` at the end there. You would be saying: 
```
'has material basis in' 
  ('has material basis in' min 1 
    (maternal_variant 
     and loss_of_function_variant 
     and chromosomal_deletion))
```

And the axiom has appeared again in the ontology as the incorrect one above.

I think it would make sense to say:
```
'has material basis in' min 1
((maternally_imprinted and loss_of_function_variant)
or (paternal_uniparental_disomy and loss_of_function_variant)
or (loss_of_function_variant and ('located in' exactly 1 gene))
or (maternal_variant and loss_of_function_variant and chromosomal_deletion))
```

**Comment by lschriml** [comment]
Thank you for the help Becky !!
   As I am trying to edit this expression, 
I type it in, save the file, open the file and the expression has changed. 

Weird:

Trying to simplify the expression: 
Does this make sense? : 


'has material basis in' some loss_of_function_variant and 
'has material basis in' min 1 
    ( maternally_imprinted 
          or  paternal_uniparental_disomy 
        or (maternal_variant and chromosomal_deletion)
        or ('located in' exactly 1 gene) )

**Comment by lschriml** [comment]
Re-opening doid-edit.owl file: 
   The expression is now: 


('has material basis in' some loss_of_function_variant)
 and ('has material basis in' min 1 (maternally_imprinted or paternal_uniparental_disomy or (maternal_variant
 and chromosomal_deletion) or ('located in' exactly 1 gene)))

Any concerns with this expression ?

**Comment by rctauber** [comment]
Here's how that reads:

This disease has material basis in a loss of function variant AND it has material basis in maternally imprinted OR paternal uniparental disomy OR maternal variant and chromosomal deletion OR it is located in one gene.

Did you mean to say the maternal variant and chromosomal deletion are located in one gene?

**Comment by lschriml** [comment]
Did you mean to say the maternal variant and chromosomal deletion are located in one gene?

Yes

**Comment by rctauber** [comment]
OK, I think the correct way to state it would be two separate subclass axioms. One:
```
'has material basis in' some loss_of_function_variant
```

Two:
```
'has material basis in' min 1 
  (maternally_imprinted or 
   paternal_uniparental_disomy or 
   ((maternal_variant and chromosomal_deletion) 
     and ('located in' exactly 1 gene)))
```

This just changes that last OR to an AND statement to say that the material variant and the chromosomal deletion are located in exactly one gene, and *nothing else*.

Separate subclass axioms are the same as saying AND, but it's a little easier to read. So if you wanted to keep it as one axiom that would be the same as this.
