### ISSUE TITLE
Use of 'disease has basis in' vs. 'has material basis in' for genetic diseases

### ISSUE THREAD

**Issue by rctauber** [DiseaseOntology/HumanDiseaseOntology#726]
This may or may not be an issue, but if it could be clarified, that would be great!

Some genetic disease classes have logical axioms that state `'has material basis in' some sequence_variant` where `sequence_variant` is a specific one, such as `structural_variant`. For example, 'Prader-Willi syndrome' uses this pattern.

Most of the others, such as 'Oguchi disease-2', use 'disease has basis in', e.g.:
```
'disease has basis in' some structural_variant
```

And 'genetic disease' is equivalent to:
```
disease
 and ('disease has basis in' some structural_variant)
```
But, the definition of 'genetic disease' has the phrase 'has_material_basis_in':
> A disease that has_material_basis_in genetic variations in the human genome.

It seems like `has material basis in` is used more for 'inheritance pattern' terms, such as 'autosomal recessive disease':
```
disease
 and ('has material basis in' some 'autosomal recessive inheritance')
```

And it's also used for bacteria and viruses, e.g. for 'anthrax disease':
```
'has material basis in' some 'Bacillus anthracis'
```

Which is the pattern that should be followed? Perhaps adding definitions to these two properties would help clarify?

**Comment by lschriml** [comment]
The DO's design patterns for 'structural variants' --> genetic disease
   & inheritance are outlined in: https://docs.google.com/document/d/1tKLzosBS_WdaJi9PgV3whm_ldmA_FrJd8M2QH6-kQDU/edit

Years ago, we defined the relations we use -- back when we were adding these to textual definitions in"
https://docs.google.com/spreadsheets/d/1KoAjHPhqFcLJauMv9vAa8WGcqpqn13RMpud8LoOKjXk/edit#gid=0


**Defining 'genetic diseases'**
     (**'disease has basis in'** some structural_variant)

          --> has been used to identify any disease that has a known genetic component, 
             and thus to have the inferred parent (genetic disease)'
         
        This area of DO is under development, we will be replacing the higher level SO term 'structural 
         variant' with more specific child terms. 

Inheritance: 
   --> Defining Inheritance:
                'has material basis' in some 'autosomal dominant inheritance' 

'has material basis in' --> has long been used in the DO, to specify
