### ISSUE TITLE
metastatic cancer/metastasis

### ISSUE THREAD

**Issue by SianGramates** [DiseaseOntology/HumanDiseaseOntology#732]
I'm trying to curate a paper that is  very specifically modeling the genetic mechanisms of metastasis, but it looks like all DO terms involving metastatic cancer or metastasis have been systematically obsoleted. That seems like a rather major area of inquiry to be uncuratable.

**Comment by lschriml** [comment]
Hello Sian,
  Thank you for submitting this ticket.
When developing the DO, we did make a design decision not to include
metastasis - secondary malignant growth, but to instead define the 
primary cancers. 
Perhaps you could annotate the initial and metastasic cancers, 
with the annotation: neoplastic, metastatic  PATO:0002098
http://purl.obolibrary.org/obo/PATO_0002098

Cheers,
Lynn
