### ISSUE TITLE
Cancer term feedback from MMHCdb curator

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#735]
Hi Lynn,
Debbie Krupke who is a curator for the Mouse Models of Human Cancer database at MGI (formerly MTB) put together a spreadsheet of comments and questions related to DO cancer terms. I've attached this here.
[Feedback for DO from Debbie K July 2019.xlsx](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/3473654/Feedback.for.DO.from.Debbie.K.July.2019.xlsx)
I started poking through some. I suspect the comments on the slims have more to do with the purpose not being apparent from the slim name.
I think the 'some 2 branches some 1 branch' tab may be useful in finding cancer terms that are missing anatomy axioms.
The 'adjectives objects or of the' tab is tracking inconsistencies in primary term names for cancers.
Errors and inconsistencies catching mostly benign tumors that are in the cancer branch. 
We may want to schedule a call that includes Debbie to go through this.

**Comment by lschriml** [comment]
Thank you Sue and Debbie !! 
A call is a good idea. 
Let me take a look at the file, then 
we can plan a call. 

Cheers,
Lynn
