### ISSUE TITLE
Alzheimer disease subtypes

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#736]
Starting to work on updating the OMIM susceptibility relations (ticket #711 ) and immediately ran into a question related to Alzheimer's subtypes. It seems to me that the inclusion of susceptibility in the OMIM term title for these is somewhat arbitrary (compare for example https://www.omim.org/entry/615590, https://www.omim.org/entry/607116 and https://www.omim.org/entry/608907). I am inclined to create a DO term for Alzheimer disease 9 and then review all of the AD subtypes to decide if the OMIM record should be an xref or use the contributes to condition relation. I think in these cases it may be more useful to rely on the OMIM gene map file relationships. 
We may also want to review the Alzheimer disease subtype definitions. Should we be using 'has material basis' for these if the OMIM relationship is using susceptibility?

**Comment by lschriml** [comment]
Hello Sue,
  for Alzheimer's -- I suggest treating the 'susceptibility' phenotypes, just like the other subtypes.
--If OMIM defines the phenotype, then lets add a new DO term.

yes, continue to use the has_material_basis_in relation: 
e.g. Alzheimer's disease 4
An Alzheimer's disease that has_material_basis_in a mutation in the presenilin-2 gene (PSEN2) on chromosome 1q42.

Cheers,
Lynn

**Comment by lschriml** [comment]
Plan, make Alzheimer's 9 a new disease term.

**Comment by lschriml** [comment]
@sbello - Can we close this ticket ?
