### ISSUE TITLE
'peanut allergy' equivalent axiom review

### ISSUE THREAD

**Issue by beckyjackson** [DiseaseOntology/HumanDiseaseOntology#737]
'peanut allergy' (DOID:4378) has the equivalent axiom:
```
'nut allergy' and (located_in some 'pigmented ciliary epithelial cell')
```

We have been doing a review of the food allergies for IEDB and we didn't expect this axiom, so we just want to make sure it's accurate. Thank you!

**Comment by lschriml** [comment]
Hello Becky, 
 thank you for pointing this out. 
I don't see why this would have been added. 
I am removing it.

Cheers,
Lynn
