### ISSUE TITLE
NTR: mega corpus callosum syndrome

### ISSUE THREAD

**Issue by cindyJax** [DiseaseOntology/HumanDiseaseOntology#738]
Please add new term for 
MEGA-CORPUS-CALLOSUM SYNDROME WITH CEREBELLAR HYPOPLASIA AND CORTICAL MALFORMATIONS

https://www.omim.org/entry/618273

related to PMID:30449657
https://www.ncbi.nlm.nih.gov/pubmed/30449657?dopt=Abstract

**Comment by melodyswen** [comment]
Hi!

Thanks, we'll review this!

Cheers,
Melody
