### ISSUE TITLE
Questions from OMIM priority additions 8/23/19

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#740]
Some questionable terms I've come across working on OMIM additions today:

OMIM:122700 (requested by most groups) - this is Coumarin resistance I would not consider this a 'disease' I have noted that this should be skipped. This is not currently on the exclude spreadsheet. Possibly this could be cross-referenced in the symptom ontology?

**Comment by sbello** [comment]
OMIM:123150 - Jackson-Weiss syndrome I am putting this in but the OMIM record mentions a single case of what appeared to be the same syndrome associated with a second gene. As this was a single record, the associations was referred to as either appeared or considered to be the same disease and GARD does not mention the second gene I left the second gene out of the definition.

**Comment by sbello** [comment]
OMIM:123320 - Creatine phosphokinase, elevated serum - I'm a little unsure of this one, the OMIM record refers to this in the context of other diseases for much of the record but GHR represents this as a stand alone disorder in some cases. So, I'm inclined to enter this one. Do you agree?

**Comment by sbello** [comment]
Parentage for congenital leptin deficiency (OMIM:614962). I've put this under autosomal recessive disease. Since leptin is a hormone not an enzyme I don't think this fits under inherited or acquired metabolic disease disease. Any suggestions for a better parent?

**Comment by lschriml** [comment]
Some questionable terms I've come across working on OMIM additions today:
          OMIM:122700 (requested by most groups) - this is Coumarin resistance 
    -->> Agreed, this is a phenotype, not a disease, lets add this to the exclusion list
                 see:  https://ghr.nlm.nih.gov/condition/warfarin-resistance

OMIM:123150 - Jackson-Weiss syndrome 
     --->> agreed

OMIM:123320 - Creatine phosphokinase, elevated serum 
    --->>. agree, add the disease term, as a child of amino acid metabolic disorder

 congenital leptin deficiency (OMIM:614962)
      --> I would classify this term as a child of 'connective tissue disorder'
       Leptin is produced primarily in the adipocytes of white adipose tissue

--> I am still looking at : Laurin-Sandrow syndrome 
More tomorrow.
Cheers,
Lynn

**Comment by lschriml** [comment]
For Laurin-Sandrow syndrome
    AD inheritance is OK
  I would move this term to Syndrome, then add the logical defs: for anatomy and inheritance. 

Cheers,
Lynn
