### ISSUE TITLE
NTR: erythermalgia

### ISSUE THREAD

**Issue by sabrinatoro** [DiseaseOntology/HumanDiseaseOntology#742]
Please, add the following disease in the ontology: 

term name: erythermalgia
synonyms: small-fiber neuropathy,
references: # 133020

Note: I think this term should be a child of "neuropathy" (DOID:870), however, it is possible that it is a phenotype rather than a disease (??)

**Comment by lschriml** [comment]
Thank you for submitting this ticket for a new disease term !!

--> Looking in DO, OMIM, Genetics Home Reference,
 I found we have this term in DO, DOID:9240, erythromelalgia.

I updated the parentage, added a definition and added the synonym: erythermalgia. 

Cheers,
Lynn
