### ISSUE TITLE
DOID:0060027 problems

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#743]
In the newest release id: DOID:0060027 [B cell linker protein deficiency] has been renamed to [agammaglobulinemia 5] with xref: OMIM:613506.

However, this change is in conflict with the remaining synonyms and definition that most likely originated from OMIM:613502.

Anyway, the current term is a mess.

Consider splitting this term into 2 terms 'agammaglobulinemia 4' and 'agammaglobulinemia 5'.

**Comment by lschriml** [comment]
Thank you Marek for pointing out these needed updates !! 

Reviewing the agammaglobulinemia OMIM terms: 

agammaglobulinemia
agammaglobulinemia
agammaglobulinemia
agammaglobulinemia
agammaglobulinemia

**Comment by lschriml** [comment]
I will review and update.
Lynn

**Comment by lschriml** [comment]
I have made the split and cleaned up the records.
Cheers,
Lynn
