### ISSUE TITLE
[anterior segment dysgenesis] questions

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#744]
DOID:0060648 [corneal opacification and other ocular anomalies] has been renamed into [anterior segment dysgenesis] and it has the same [xref: OMIM:PS107250] as other term {DOID:0060605,
anterior segment mesenchymal dysgenesis}

Do you have any plans to work on terms from the series OMIM:PS107250 ???

Thank you, Marek

**Comment by lschriml** [comment]
Thank you for pointing this out.
I have merged the two terms, and updated the record.

Cheers,
Lynn
