### ISSUE TITLE
autosomal dominant/recessive parentage

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#745]
We noticed that In August releases numerous terms acquired both dominant and recessive parentage, f.e.

[Term]
id: DOID:0060752
name: familial temporal lobe epilepsy 5
is_a: DOID:0050736 ! autosomal dominant disease
is_a: DOID:0050737 ! autosomal recessive disease

Is this the way how the terms for diseases with both dominant and recessive inheritance will be represented in DO ontology as of now? I vaguely remember that in the past it was proposed to use [autosomal genetic disease (DOID:0050739)] parentage for this kind of diseases instead ...

Thank you

**Comment by lschriml** [comment]
Hello,
  yes, in August I went through all of the 'genetic' diseases, and if their inheritance is known, in OMIM or Genetics Home Reference, then I added logical axioms. 
When they are both dominant and recessive, they were defined as both axioms. 
We have the granularity now to be able to be this specific, so I went forward and added in the axioms. 

Cheers,
Lynn
