### ISSUE TITLE
Definition dbXref Review

### ISSUE THREAD

**Issue by beckyjackson** [DiseaseOntology/HumanDiseaseOntology#747]
There are a couple of DO terms that have questionable database cross references for their sources:

* prostate embryonal rhabdomyosarcoma (DOID:3251) - https://www.google.com/search?hl=en&client=firefox-a&hs=SMK&rls=org.mozilla%3Aen-US%3Aofficial&q=rhabdomyosarcoma+of+prostate&aq=f&aqi=&aql=&oq=&gs_rfai=
* esophagus sarcoma (DOID:1114) - http://www.google.com/search?hl=en&client=firefox-a&hs=X3f&rls=org.mozilla:en-US:official&ei=wxHfS4jAC4a8NualnMwH&sa=X&oi=spell&resnum=0&ct=result&cd=1&ved=0CA0QBSgA&q=esophageal+sarcoma&spell=1
* ovarian mesodermal adenosarcoma (DOID:4115) -http://www.google.com/search?q=ovarian+mesodermal+adenosarcoma&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a
* methylmalonic aciduria and homocystinuria type cblF (DOID:0050717) - http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CFMQFjAB&url=http%3A%2F%2Fpreventiongenetics.com%2FClinicalTesting%2FTestDescriptions%2FLMBRD1.pdf&ei=hzv3T__xH4qk6wGIlqn2Bg&usg=AFQjCNEq6PEmU_PvWZSYQVIf2Uhf7Qxp7w&sig2=Ed-CTWsLgGVSkht-OW43gA
* Hodgkin's lymphoma (DOID:8567) - url:v

Should these point to actual resources, rather than the Google searches? The last one seems to have been cut off and doesn't have an actual reference.

**Comment by lschriml** [comment]
Agreed, these should not be xrefs.
We shouldn’t have any google searches as xrefs.
Great catch. Remove them if you want to.
I can add in xrefs when I am back next week. 
Cheers,
Lynn

**Comment by beckyjackson** [comment]
Thanks for following up! I will remove them.

**Comment by lschriml** [comment]
Thank you Becky,
I am flying home in the morning.
Back in the office on Tuesday.
Cheers,
Lynn

**Comment by beckyjackson** [comment]
Resolved by e8bf031

**Comment by lschriml** [comment]
dbxrefs reviewed, updated.
