### ISSUE TITLE
xrefs converted to comments in doid.obo

### ISSUE THREAD

**Issue by Clare72** [DiseaseOntology/HumanDiseaseOntology#750]
At some point between the May and June releases, some of the definition dbxrefs were converted to comments - see example below for 'shrimp allergy'.

In the May release:

>[Term]
id: DOID:0040001
name: shrimp allergy
def: "A crustacean allergy that has_allergic_trigger shrimp." [IEDB:RV, url:https\://www.ncbi.nlm.nih.gov/pubmed/20471069]
is_a: DOID:0060524 ! crustacean allergy

In the June release:

>[Term]
id: DOID:0040001
name: shrimp allergy
def: "A crustacean allergy that has_allergic_trigger shrimp." [url:https\://www.ncbi.nlm.nih.gov/pubmed/20471069] {comment="IEDB:RV"}
is_a: DOID:0060524 ! crustacean allergy

We noticed this when updating to the Aug 22 release (from the May release) in FlyBase because escapes ('\\') have been lost in "DO:wk\\,ls" now that they are in comment form, rather than dbxref form. I find four examples of this string in v2019-05-13 as dbxrefs; there is one case in v2019-06-28 where this is retained as a dbxref (keeping the escape) and three cases where this is converted to a comment (losing the escape). The loss of escapes causes problems for our file conversion tool.

These xrefs should have their own prefixes, i.e. "DO:wk, DO:ls", to avoid the need for escapes. Comment references should also be converted back to normal dbxrefs.

[edit: escaped example escapes so that they show in post!]

**Comment by lschriml** [comment]
Apologies for this causing issues for you.
We were reviewing what should be contained in the dbxref field.
The IEDB:RV type of dbxref were utilized previously to denote the source of the group/individual submitting the data/annotation. 
More recently it was pointed out that this was no longer a proper dbxref in OWL. 
So, we systematically moved all such annotations to comments. 

Can you explain what you mean by 'escapes' ? 

Thank you,
Lynn

**Comment by Clare72** [comment]
Sorry, escapes were not showing in my post - I had to escape them! You can see what I mean now.

If it is an intentional change, that is fine, it just looks a bit strange in the obo file. Please can you change the four cases of 'DO:wk,ls' to 'DO:wk, DO:ls'? This should solve our file conversion problems.

**Comment by lschriml** [comment]
Yes, I can fix these.
Thank you for helping me understand the problem.
Cheers,
Lynn

**Comment by lschriml** [comment]
All fixed !!
