### ISSUE TITLE
Please add a new DO term for FLOATING-HARBOR SYNDROME; FLHS

### ISSUE THREAD

**Issue by Xenbase2** [DiseaseOntology/HumanDiseaseOntology#752]
Please add a new DO term for FLOATING-HARBOR SYNDROME; FLHS
https://www.omim.org/entry/136140

Suggested Definition: Floating-Harbor syndrome (FHS) is a developmental disorder associated with distinct craniofacial defects and other skeletal anomalies, and can also include hearing loss, seizures, gastroesophageal reflux, renal and genital anomalies.

It seems you don't ever add a 'cause' to the definition, but if you did   "which is caused by mutations in SRCAP, a gene encoding a chromatin remodeler mediating incorporation of histone variant H2A.Z)" from ref 1.

references:
1) PMID: 31491386 DOI: 10.1016/j.cell.2019.08.002
https://www.sciencedirect.com/science/article/pii/S0092867419308906?via%3Dihub

2) PMID: 23193612
https://www.ncbi.nlm.nih.gov/pubmed/23193612

3) PMID: 23621943
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3659005/

**Comment by sbello** [comment]
This is on the OMIM priority add list and I have a draft term done just waiting for my next ROBOT run.

**Comment by lschriml** [comment]
@sbello - please include the GHR reference for this new term.
https://ghr.nlm.nih.gov/condition/floating-harbor-syndrome
Cheers,
Lynn

**Comment by sbello** [comment]
added in latest commit
