### ISSUE TITLE
Is there any gmt file for gene set enrichment analysis?

### ISSUE THREAD

**Issue by chilampoon** [DiseaseOntology/HumanDiseaseOntology#754]
Hi there, I would like to do the gene set enrichment analysis using disease ontology terms, so is there any gmt file in the database? Thanks!

**Comment by sbello** [comment]
Hi @chilampoon 
This type of file is not available from the DO site but you could pull this type of information from the Alliance of Genome Resources site (https://build.alliancegenome.org/) either from the downloads page for all disease associations from all species in the Alliance (these are all made to DO terms). Or you could use the API to pull out data for a specific species.

**Comment by chilampoon** [comment]
Got it, thanks a lot!
