### ISSUE TITLE
Question about language in README_DO_Files about DO Single Parentage ontology

### ISSUE THREAD

**Issue by ddurkin** [DiseaseOntology/HumanDiseaseOntology#756]
The README_DO_Files mentions

DO Single Parentage ontology.
 The DO's disease classification is   represented as both a single is_a hierarchy (doid-non-classified.obo).  This file is equivalent to DO's   HumanDO.obo file. We will continue to produce both files as the HumanDO   naming schema was utilized and published for the   first decade of the project.

However, there are a number of terms with multiple is_a: relationships listed like

[Term]
id: DOID:7936
name: precursor T-lymphoblastic lymphoma/leukemia refractory
subset: NCIthesaurus
xref: NCI:C8696
xref: UMLS_CUI:C0854859
is_a: DOID:5599 ! precursor T-lymphoblastic lymphoma/leukemia
is_a: DOID:712 ! refractory hematologic cancer

Is this intended or should this file only have a single is_a: for each of the terms?

**Comment by melodyswen** [comment]
Hi!

We'll review this and get back to you! Thanks for your comment!

Cheers,
Melody

**Comment by melodyswen** [comment]
Comment: DOID:712 refractory hematologic cancer seems to be an older DO term, and is a parent of DOID:7936 precursor T-lymphoblastic lymphoma/ leukemia refractor. Could be an old parent

**Comment by ddurkin** [comment]
Thanks Melody!

I had a script that identified more than just this one instance, if that list would be helpful let me know and I can run it on the latest file and pass it along.

Dan

**Comment by melodyswen** [comment]
Hi @ddurkin ,

That would definitely be helpful if you have a chance to run the script! Thanks so much!

Sorry for the late reply - cheers!
Melody

**Comment by lschriml** [comment]
Thank you Dan !! 
    A list of the dual parentages would be great !!

For this case, 
   I did some additional research and found that this area of DO needed further review and updating, to align with current nomenclature. 
I have updated the terms, parentage and added definitions.

Cheers,
Lynn
