### ISSUE TITLE
Does DO have Breast Implant Associated Anaplastic Large Cell Lymphoma (BIA-ALCL)

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#759]
Hi, if DO doesn't have this term, can you please add this term?
Related information please check here: [FDA link for BIA-ALCL](https://www.fda.gov/medical-devices/breast-implants/questions-and-answers-about-breast-implant-associated-anaplastic-large-cell-lymphoma-bia-alcl)

**Comment by melodyswen** [comment]
Hi! 

Thanks for your comment - we will review this and get back to you!

Cheers,
Melody

**Comment by lschriml** [comment]
Thank you for sending the new disease term. We will review.
Cheers,
Lynn

**Comment by linikujp** [comment]
Thanks!

**Comment by melodyswen** [comment]
Hi @linikujp, breast implant-associated anaplastic large cell lymphoma DOID:0070333 has been added. We also included the FDA link as one of the cross-references. This will be available in the next DO release. 

Cheers,
Melody

**Comment by linikujp** [comment]
Thank you, Melody!
