### ISSUE TITLE
add missing relationship

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#760]
DOID:9280 is missing is_a urea cycle disorder

**Comment by melodyswen** [comment]
Hi! 

Urea cycle disorder has been added as a parent for DOID:9280. Are you using DO in OBO format? The parent will be shown when we make a release sometime next week. 

Cheers!
Melody

**Comment by lschriml** [comment]
Thank you for this review: 
Reviewing these DO terms,
 agreed, we will update the parentage of 
       carbamoyl phosphate synthetase I deficiency disease
              to:  urea cycle disorder : 
An amino acid metabolic disorder that involves a deficiency of one of the enzymes in the urea cycle which is responsible for removing ammonia from the blood stream. 
  --> and add 'autosomal recessive inheritance' 
       https://en.wikipedia.org/wiki/Ornithine_translocase_deficiency

Cheers,
Lynn

**Comment by melodyswen** [comment]
Hi @Antonialock , the parentage has been updated to urea cycle disorder, and we have added autosomal recessive inheritance as an inferred parent. This will be available in the next release. 

Cheers,
Melody
