### ISSUE TITLE
MESH ID as synonym (DOID:0050562)

### ISSUE THREAD

**Issue by need47** [DiseaseOntology/HumanDiseaseOntology#762]
The MESH:D013036 goes to synonyms, which I think should be in xrefs.
http://www.disease-ontology.org/?id=DOID:0050562

**Comment by melodyswen** [comment]
Hi! 

Thanks very much for pointing this out - we appreciate it! MESH:D013036 has now been changed to annotation database_cross_reference. 

Cheers,
Melody
