### ISSUE TITLE
mitochondriopathy 

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#763]
I'm working on splitting optic atrophy (DOID:5723) and I've run into an issue with one of the members of the OMIM phenotypic series. OMIM:617302 is titled "optic atrophy 11" but the symptoms include more than just optic atrophy (I have "delayed psychomotor development, intellectual disability, ataxia, optic atrophy, and leukoencephalopathy consistent with mitochondrial dysfunction" in the characterized part of the definition). The reference for this description refers to this as a 'novel mitochondriopathy'. I'm wondering if this disease should be a child of 'mitochondrial metabolism disease' (DOID:700) rather than optic atrophy. It seems odd to put a disease called optic atrophy # under a parent other than optic atrophy but it also seems wrong to put it under optic atrophy given that it impacts more than the optic disc.

Orphanet lumps this in with all the other autosomal recessive optic atrophies (ORPHA:98676).

Also should mitochondriopathy be a synonym for mitochondrial metabolism disease? Currently searching DO for mitochondriopathy gives no results.

Other optic atrophies are also associated with mitochondrial dysfunction (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5566899/) so possibly the direct is a parent should be the mitochondrial one and the relation to the optic nerve rely on the located in relationship?

**Comment by sbello** [comment]
from https://www.ncbi.nlm.nih.gov/pubmed/14508503 
"It is worth remembering that all known genes involved in hereditary optic neuropathies are either mitochondrial (LHON) or encode proteins with high mitochondrial targeting (OPA1, OPA3, TIMM8A (MIM 300356) and SDHA15). This is why we first decided to screen genes known to encode mitochondrial protein such as DECR1 and PDP. The absence of any mutation in these genes prompts us to search in the genetic interval defined by D8S1702 and D8S1794 all proteins potentially targeted to the mitochondria, using the prediction programs MITOPROT and PSORT II from the Mitochondria Project and PSORT server, respectively. This work is currently in progress."

**Comment by lschriml** [comment]
-- agreed, mitochondriopathy is an exact synonym to mitochondrial disease
However, as you noted we do not have a mitochondrial disease term. 
I think it would be difficult to create this term, as mitochondrial diseases are characterized throughout the DO diseases. (metabolic, genetic, anatomical). 

--  optic atrophy 11 is a  mitochondriopathy, but not a metabolic disease

-- since the evidence is only one family, and there is no evidence for metabolic dysfunction, 
I think this term is appropriately placed as a child of optic atrophy, at least for now.

Cheers,
Lynn

**Comment by sbello** [comment]
We might consider created located in relationships for subcellular components using GO terms as a way to eventually pull these together.

**Comment by lschriml** [comment]
yes, we could do that. For now, I think we can close this ticket.
