### ISSUE TITLE
add synonym to DOID:2742

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#764]
Hello, 

could you please add "deafness" as a related synonym to "auditory system disease"(DOID:2742) so that it is easier to search on?

Cheers

**Comment by lschriml** [comment]
Thank you for this suggestion to improve the DO.
I have added a definition for auditory system disease:
A sensory system disease that is characterized by auditory dysfunction located_in the auditory system.

Source: https://books.google.com/books?id=r3I0BwAAQBAJ&newbks=1&newbks_redir=0&lpg=PP1&dq=disorders%20of%20auditory%20system&pg=PP1#v=onepage&q=disorders%20of%20auditory%20system&f=false

Not all of the child terms of auditory system disease are types of deafness, as this term involves disease of the ear and the internal sensory organs. 

Cheers,
Lynn
