### ISSUE TITLE
Unexpected space in url in DOID:3604

### ISSUE THREAD

**Issue by haoyuanli** [DiseaseOntology/HumanDiseaseOntology#769]
[Term]
id: DOID:3604
name: ovarian mucinous cystadenocarcinoma
def: "An ovarian cystadenocarcinoma that is characterized by the presence of mucin." [url:https\://en.wikiped ia.org/wiki/Ovarian_mucinous_tumor]

This space in 'wikipedia' seems not necessary..

**Comment by lschriml** [comment]
Thank you for pointing this out. 
Agreed.
Fixed.

Cheers,
Lynn
