### ISSUE TITLE
add MeSH xref to DOID:0060731

### ISSUE THREAD

**Issue by need47** [DiseaseOntology/HumanDiseaseOntology#770]
Currently, it has the following name:
http://www.disease-ontology.org/?id=DOID:0060731

congenital central hypoventilation syndrome

Sounds a perfect match to this MeSH:
https://meshb.nlm.nih.gov/record/ui?ui=C536209

Congenital central hypoventilation syndrome

**Comment by lschriml** [comment]
Agreed, we will add C536209 to congenital central hypoventilation syndrome.
Cheers,
Lynn

**Comment by melodyswen** [comment]
This MESH ID has been added as a database cross reference. 

Cheers,
Melody
