### ISSUE TITLE
hyper IgE syndrome - parentage issues

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#771]
id: DOID:0080545
name: hyper IgE syndrome
xref: GARD:10956
xref: OMIM:PS147060
is_a: DOID:0050736 ! autosomal dominant disease

Please see https://rarediseases.info.nih.gov/diseases/10956/index and https://www.omim.org/phenotypicSeries/PS147060. Both sources list autosomal dominat and autosomal recessive subtypes of this syndrome. Therefore "is_a: DOID:0050736 ! autosomal dominant disease" looks incomplete (partially correct).

Please review inheritance parentage. And it will be very appreciated to provide child terms for both dominant and recessive subtypes of this syndrome.

**Comment by melodyswen** [comment]
Hi!

Thanks for bringing this up - we'll review and get back to you!

Cheers,
Melody

**Comment by lschriml** [comment]
Thank you for pointing this out.
This DOID is the parent term for four subtypes.

I have removed the inheritance for the parent term. 

I have added the three subtypes we were missing.

Cheers,
Lynn
