### ISSUE TITLE
dissease and symptoms 

### ISSUE THREAD

**Issue by alexgarciac** [DiseaseOntology/HumanDiseaseOntology#772]
Hi, is there a mapping between the DO and the symptoms ontology? I need a relation between a dissease and the corresponding symtoms.

**Comment by lschriml** [comment]
Hello Alexander,
 yes, we use the relation, has_symptom. 
These mappings can be seen in our doid.owl file.

Cheers,
Lynn














``

**Comment by melodyswen** [comment]
Hi Alexander, 

We are currently in the process of adding more logical definitions with the relation has_symptom to our doid.owl file! Yes, definitely check out the mappings. 

Best,
Melody
