### ISSUE TITLE
Invalid Definition Source Links

### ISSUE THREAD

**Issue by beckyjackson** [DiseaseOntology/HumanDiseaseOntology#773]
The follow DOIDs have the source `url:http://drzafariqbal.com/wp-content/uploads/2017/07/WHO-Female.pdf`. This page does not work. These terms all seem to be related to cervical, vaginal, and ovarian cancer.

- DOID:133
- DOID:1910
- DOID:2097
- DOID:2640
- DOID:3743
- DOID:4867
- DOID:5253
- DOID:5264
- DOID:5268
- DOID:5566
- DOID:6229
- DOID:6314
- DOID:6315
- DOID:6407
- DOID:6428
- DOID:6659
- DOID:6774
- DOID:7046
- DOID:7048
- DOID:7363
- DOID:7409
- DOID:7483
- DOID:7598
- DOID:7651
- DOID:7961
- DOID:8339
- DOID:9597

**Comment by beckyjackson** [comment]
The following DOIDs have the source `url:http://www.ilae-epilepsy.org`, which may be too broad. The page does not direct to any content about the specific disease, and I can't assign a resource type:

- DOID:0050708
- DOID:0060172
- DOID:7725

This DOID's resource does not load:

- DOID:0060042

**Comment by lschriml** [comment]
all of the DOIDs with the xref, :http://drzafariqbal.com/wp-content/uploads/2017/07/WHO-Female.pdf
are fixed.

**Comment by lschriml** [comment]
DOID:0050708
DOID:0060172
DOID:7725

-- fixed

**Comment by lschriml** [comment]
This doesn't seem like the correct resource, as it's pointing to a DO relations Wiki:
     DOID:4769 http://do-wiki.nubic.northwestern.edu/index.php/Relations_in_DO

--> checked that this only occurred once. 

Fixed.

**Comment by lschriml** [comment]
This is a PDF of a book, but it's only the preface and there's no content on the disease:
DOID:134
    -- Fixed

These are from answers.com which is an unofficial Q&A page, and I don't think it's a good resource:

DOID:4653 http://www.answers.com/topic/intraocular-retinoblastoma
DOID:6938 http://www.answers.com/topic/intraocular-retinoblastoma

-- Agreed, Fixed 
also fixed : pineoblastoma, DOID:1664

**Comment by lschriml** [comment]
NeuroDevNet
is now:
https://kidsbrainhealth.ca

**Comment by melodyswen** [comment]
Hi Lynn - just checking - did you edit Becky's table to remove the DOID's and links that you fixed?

**Comment by lschriml** [comment]
No, I didn’t :)

**Comment by lschriml** [comment]
Hello @melodyswen -- can you add a comment here on your progress towards resolving this ticket ? 
Thank you,
Lynn

**Comment by melodyswen** [comment]
Hi @lschriml , 

I have pushed changes for all fixed source links to GitHub. 

The following DOIDs are ones that I had trouble finding new links for, I will come back to these:
DOID:2338
DOID:1862
DOID:5772
DOID:5390
DOID:2769

Thanks!
Melody

**Comment by melodyswen** [comment]
mandibular cancer - NCI thesaurus 
jaw cancer - https://www.merckmanuals.com/professional/ear,-nose,-and-throat-disorders/tumors-of-the-head-and-neck/jaw-tumors
DOID:5772 - https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C5503
DOID:5390 https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C4151
DOID:2769 https://www.cdc.gov/ncbddd/tourette/diagnosis.html

**Comment by melodyswen** [comment]
All flagged DOIDs with invalid definition source links have been corrected.
