### ISSUE TITLE
Unknown Definition Resource Types

### ISSUE THREAD

**Issue by beckyjackson** [DiseaseOntology/HumanDiseaseOntology#774]
There are also some pages that I'm not sure about the resource type. I would appreciate help with these.

| DOID | Link | Potential Type
| --- | --- | --- |
DOID:0070333 | https://www.fda.gov/medical-devices/breast-implants/questions-and-answers-about-breast-implant-associated-anaplastic-large-cell-lymphoma-bia-alcl | FAQ Page
DOID:7347 | https://www.uptodate.com/contents/ovarian-hyperthecosis | Not sure if reviewed or unreviewed article? Not a real journal...
DOID:14037 | https://secure.ssa.gov/poms.nsf/lnx/0423022540 | A policy page?
DOID:0060287 | https://www.aao.org/bcscsnippetdetail.aspx?id=cc04d24c-8321-45bc-aab0-fe6a5667bbe4 | A "snippet" from something

**Comment by lschriml** [comment]
Thank you Becky !!
   I will take a look and review.
For the odd xrefs, I will review and most likely replace ten with a PubMed ID, so that you don’t have to create new types.
   It will be good to improve the sources. 
I’ll work on them this week. 

Cheers,
Lynn

**Comment by beckyjackson** [comment]
That would be great! Thanks @lschriml

**Comment by lschriml** [comment]
Hello Becky,
 these have been updated: 

For: DOID:0070333
   the xref is a .gov site, this would be a: 

'curator inference from authoritative source' <http://purl.obolibrary.org/obo/ECO_0007647>

For DOID:7347 and DOID:14037
   -- I replaced the refs with PubMed References

For DOID:0060287
I replaced the ref, with a refs: 
https://disorders.eyes.arizona.edu/handouts/cornea-plana
This is a database of eye disorders

'curator inference from database' <http://purl.obolibrary.org/obo/ECO_0007636>
