### ISSUE TITLE
Can someone please tell me where can I find annotation data?

### ISSUE THREAD

**Issue by AshuiRUA** [DiseaseOntology/HumanDiseaseOntology#778]
I'm trying to find diseases's causative genes for a large number of diseases. Acooding to Khader Shameer said on biostars :"Disease Ontology (DO) and Disease Ontology - Lite (DO-Lite) based annotations very efficient in mapping a given gene to different diseases". So, I come here for help.
But after looking into DO's Github repository, I can't find annotation data. Can someone please tell me where can I find annotation data? It will be a great help. Thank you.

**Comment by lschriml** [comment]
Hello Ashui, 
    the DO itself contains the disease terms that many groups use in these annotations. 
There are many citations in PubMed,
check out papers from this link: 
https://pubmed.ncbi.nlm.nih.gov/?term=Disease+Ontology+AND+annoations+AND+gene

Cheers,
Lynn
