### ISSUE TITLE
bad parentage for DOID:0111502

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#779]
Please see:

[Term]
id: DOID:0111502
name: combined oxidative phosphorylation deficiency 6
def: "A combined oxidative phosphorylation deficiency that has_material_basis_in hemizygous mutation in AIFM1 on chromosome Xq26.1." 
synonym: "severe X-linked mitochondrial encephalomyopathy" EXACT []
xref: OMIM:300816
is_a: DOID:0050737 ! autosomal recessive disease

PROBLEM:
"is_a: DOID:0050737 ! autosomal recessive disease" parentage looks wrong for a disease associated with chromosome X gene.

**Comment by melodyswen** [comment]
Hi Marek, 

Thank you for pointing this out! We've fixed the parentage for combined oxidative phosphorylation deficiency 6 for X-linked recessive. This will be available in the next release! 

Happy holidays,
Melody
