### ISSUE TITLE
issues for DOID:0110155

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#780]
Currently:

[Term]
id: DOID:0110155
name: Charcot-Marie-Tooth disease type 2A2
def: "A Charcot-Marie-Tooth disease type 2  that has_material_basis_in heterozygous mutation in the MFN2 gene on chromosome 1p36.2."
xref: OMIM:609260
is_a: DOID:0050539 ! Charcot-Marie-Tooth disease type 2
is_a: DOID:0050736 ! autosomal dominant disease

According to OMIM, there is OMIM:609260
CHARCOT-MARIE-TOOTH DISEASE, AXONAL, AUTOSOMAL DOMINANT, TYPE 2A2A. So far so good.

But there is also OMIM:617087
CHARCOT-MARIE-TOOTH DISEASE, AXONAL, AUTOSOMAL RECESSIVE, TYPE 2A2B, which is autosomal recessive on the same gene.

Therefore please consider incorporating this additional information into DOID:0110155 term, or perhaps adding two additional child terms to follow OMIM approach?

Thank you,

**Comment by lschriml** [comment]
Thank you, we will update the DO to incorporate these changes.
@sbello -- can you add these new OMIM records ? 

Thank you,
Lynn

**Comment by sbello** [comment]
I'll review the full series for any other new additions since the series was split.

**Comment by sbello** [comment]
We have 5 new entries. I'll work on adding these to the MGI ROBOT spreadsheet. I'll plant to do a ROBOT run to add new terms next week unless that will cause an issue for you @lschriml 

The existing DO term has been renamed to 2A2A by OMIM so I'll need to change that as well.

**Comment by lschriml** [comment]
Hello @sbello -- sounds good.
We want to push out a release next week - can you do the update by Wednesday and coordinate with @melodyswen -- as she will do the release.

Cheers,
Lynn

**Comment by sbello** [comment]
Added this and a few other CMT types in the latest ROBOT run
