### ISSUE TITLE
typo in doid.owl (DOID_0070256 and DOID_0070254)

### ISSUE THREAD

**Issue by goekce** [DiseaseOntology/HumanDiseaseOntology#782]
The newlines in the following synonyms in doid.owl should be removed. These newlines introduce difficulties in parsing. (DOID_0070256 and DOID_0070254)

```
<oboInOwl:hasExactSynonym>CDGIId
</oboInOwl:hasExactSynonym>

<oboInOwl:hasExactSynonym>glucosidase I deficiency
</oboInOwl:hasExactSynonym>
```
I also encountered unneeded newlines in <rdfs:comment> blocks of the following classes:
- DOID_14448
- DOID_14743
- DOID_6457

**Comment by beckyjackson** [comment]
Thanks for catching this @goekce. This is actually something that ROBOT report should catch, but it looks like it doesn't. I've fixed this in doid-edit.owl so the fix will be available in the next release. I'm also updating the ROBOT report query to catch things like this in the future.

**Comment by goekce** [comment]
Thank you for fixing @beckyjackson! Everything that I mentioned seem to be fixed, but the comment block of DOID_14448 seem to be untouched by the commit 542ed00cfb8c4a7a8df75e00c12cab363ef7fde9.

**Comment by lschriml** [comment]
Thank you for pointing out this fix. 
I have updated the diid-edit.owl file.

Cheers,
Lynn
