### ISSUE TITLE
New Term Request: Alkuraya-Kucinskas syndrome 

### ISSUE THREAD

**Issue by sramachand** [DiseaseOntology/HumanDiseaseOntology#784]
Hi,

I would like to request this term: Alkuraya-Kucinskas syndrome (ALKKUCS) and in OMIM: 617822. The article is PMID:29290337
Thanks

Sridhar

**Comment by melodyswen** [comment]
Hi Sridhar, 

Thanks for your request, we will review this and get back to you! 

Cheers,
Melody

**Comment by sbello** [comment]
added to MGI ROBOT template

**Comment by sbello** [comment]
Added in my last ROBOT run
