### ISSUE TITLE
organization of skeletal dysplasias

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#785]
DO currently has a term for spondyloepimetaphyseal dysplasia (DOID:0080027) and for metaphyseal dysplasia (DOID:0080019) but lacks terms for spondyloepiphyseal dysplasia and spondylometaphyseal dysplasia. I think we should consider adding the latter 2 classes and then reviewing the organization of these classes.

OMIM has at least 6 entries using spondylometaphyseal dysplasia in the term name and at least 8 using spondyloepiphyseal dysplasia.

References:
https://ghr.nlm.nih.gov/condition/spondyloepiphyseal-dysplasia-congenita
https://www.ncbi.nlm.nih.gov/pubmed/31824186
https://www.ncbi.nlm.nih.gov/pubmed/20301324
https://www.ncbi.nlm.nih.gov/pubmed/24830047
https://www.ncbi.nlm.nih.gov/pubmed/22529034
https://ghr.nlm.nih.gov/condition/spondyloepimetaphyseal-dysplasia-strudwick-type

**Comment by lschriml** [comment]
Hello @sbello -- agreed, we need to re-organize this section.

--> agreed, add the new terms. 
Looking at the terms, I don't think we can organize them as parent, child terms. 
Let's have them be child terms of : 
osteochondrodysplasia

spine (spondylo-) and two regions (epiphyses and metaphyses)

**spondyloepiphyseal dysplasia**    
      spine (spondylo-) and the ends (epiphyses)

**spondyloepimetaphyseal dysplasia** (DOID:0080027)
        located_in epiphysis, located_in metaphysis.

**metaphyseal dysplasia** (DOID:0080019) 
spine (spondylo-) and   metaphyses


**spondylometaphyseal dysplasia** 

Cheers,
Lynn

**Comment by sbello** [comment]
The thing we're going to have to check is for any inferred relationships based on located_in can we be clear that spondyloepimetaphyseal dysplasia means located in both while the other two mean located in epiphysis or metaphyses but NOT in both.

**Comment by sbello** [comment]
I'll work on adding the new terms in the MGI ROBOT spreadsheet

**Comment by lschriml** [comment]
Hello @sbello - checking on older tickets. 
Is this one able to be closed ?

Cheers,
Lynn

**Comment by sbello** [comment]
circling back to this ticket, adding terms to the MGI spreadsheet

**Comment by lschriml** [comment]
Great !!
Thank you Sue !!

**Comment by sbello** [comment]
Reviewed and added terms from OMIM and Orphanet
Skipped spondylometaphyseal dysplasia X-linked (OMIM:313420|ORDO:168544|GARD:8343|UMLS_CUI:C0796172|MESH:C563124|SNOMEDCT_US_2018_03_01:773304004) despite existing in multiple databases I could not find any reference in pubmed for this subtype. Only published reference in OMIM record is from 1977 and is not in pubmed.
