### ISSUE TITLE
parentage of retinal degeneration

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#786]
Currently retinal degeneration (DOID:8466) is a child of retinal disease (DOID:5679) but NOT a child of eye degenerative disease (DOID:9799). I suggest making the asserted parent of this disease be eye degenerative disease and add a located_in retina relationship to allow the inference to retinal disease. It seems odd to me to not find retinal degeneration under eye degeneration disease.

Same suggestion for corneal degeneration (DOID:1237)

Also choroidal sclerosis (DOID:980) is currently under eye degenerative disease and not under choroid disease, so this could use a located_in relationship as well.

**Comment by lschriml** [comment]
Agreed, go ahead and make the changes.

Cheers,
Lynn

**Comment by sbello** [comment]
Added EQs of the format
'eye degenerative disease' and ('located in' some 'anatomical entity') for the terms
conjunctival degeneration
corneal degeneration
retinal degeneration
choroidal sclerosis
