### ISSUE TITLE
Support British English aliases

### ISSUE THREAD

**Issue by kkrysiak** [DiseaseOntology/HumanDiseaseOntology#787]
A few examples that would be useful for searching:
Pediatric == Paediatric
Hematopoietic == Haematopoietic
Estrogen == Oestrogen
Fiber == Fibre
Behavoir == Behaviour

I've made a similar request of HPO. There are likely relevant terms that I am missing.

https://github.com/obophenotype/human-phenotype-ontology/issues/5103

**Comment by kkrysiak** [comment]
tumor == tumour
edema == oedema
etiology == aetiology
anemia == anaemia
hemoglobin == haemoglobin

A few more

**Comment by lschriml** [comment]
Agreed !! 
Will look into getting these added !! 
Cheers,
Lynn

**Comment by lschriml** [comment]
We will put together a plan on how to do this programmatically. 
Looking in the DO, we have both US and British english versions of terms and 
synonyms. 
My overall plan thus far, would be to set up a sprawl query, to identify all of the cases: 
query first: 
DO terms : US spellings, British Spellings, then treat them as two groups of updates 
    -- if US spelling, do we have a British spelling synonym, if yes, then add flag in DO that the synonym is British spelling
    -- if we don't have the British spelling synonym, we will add it. 

DO term -- if UK spelling, same as above

Look at DO synonyms, same steps as above. 
Cheers,
Lynn

**Comment by lschriml** [comment]
To be systematic, 
we will compile a list of terms to review from: 
http://translation-clinic.com/spelling-medical-terms-british-american-english/
or a similar source.

**Comment by matentzn** [comment]
I wrote a little ROBOT pipeline to do automatically create british language synonyms for HPO, maybe @beckyjackson can "steal" it an adopt it for your case. Seems to work well. It takes all labels and existing synonyms (using ROBOT query) then creates british english translations using some dictionary (that you can maintain yourself), and then creates a ROBOT template with only those BE synonyms that are not yet in the ontology.

**Comment by matentzn** [comment]
Oops forget the link: https://github.com/obophenotype/human-phenotype-ontology/pull/5109

**Comment by beckyjackson** [comment]
Thanks @matentzn ! I will take a look next week when I'm back from vacation 🙂

**Comment by lschriml** [comment]
This would be great !!
Very useful.

May I suggest you submit an abstract for Biocuration for this work ?
Deadline January 24th.

I think there would be a lot of interest in the community. 

Thank you Nico !! 

Cheers,
Lynn

**Comment by matentzn** [comment]
Thanks Lynn! This is just a little script I wrote in two hours :) not worth to be mentioned I think! Let me know if you need help adopting it to your case.

**Comment by lschriml** [comment]
Thank you Nico !!

**Comment by lschriml** [comment]
Hello @beckyjackson --- did we need to discuss further ? 
Cheers,
Lynn

**Comment by beckyjackson** [comment]
I was just curious if you wanted this to be a one-time process, or run every time you build a release in the `Makefile`?

**Comment by lschriml** [comment]
Good point. 
I think we want to incorporate this into our release process. 
So that we keep the synonyms up to date. 

Cheers,
Lynn

**Comment by lschriml** [comment]
Thank you Becky !!
    I've reviewed the British synonym spreadsheet, 
in [google docs](https://docs.google.com/spreadsheets/d/1TQGAlURq0a1QK4pw2_OcaSxJIZqf_SFEQlNt0q_bw-s/edit#gid=0),
**--> No problems.** 
It is very helpful to look through the changes, I appreciate the extra step for QC.

**Becky - please go ahead and implement for all of the British spellings** 

- 10 terms from CIViC
- There are an additional 20 other UK to US medical terms.
I have compiled these in the same google doc, US-UK list tab.

Cheers,
Lynn

**Comment by beckyjackson** [comment]
Alright, I'll do that now.

It looks like almost all of those are in the HPO British-American dictionary already, but a few are missing. @matentzn - could we add these to the dict? I can make a PR if that's easiest.


American | British
--- | ---
celiac | coeliac
cesarian | caesarian
dyslipidemia | dyslipidaemia
dyspnea | dyspnoea
glycemic | glycaemic
ischemic | ischaemic

**Comment by matentzn** [comment]
Gladly!

**Comment by matentzn** [comment]
(If you can make a PR perfect)

**Comment by lschriml** [comment]
Done

**Comment by lschriml** [comment]
Hello @beckyjackson -- what do we need to update in Protege, so that when entering a synonym manually, we have the "British" language option. 
   Noticed this today, while added a new synonym. 

Cheers,
Lynn

**Comment by lschriml** [comment]
Decided to not add British option.
