### ISSUE TITLE
Split Kleefstra syndrome (DOID:0060352)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#789]
Can this:
id: DOID:0060352
name: Kleefstra syndrome
alt_id: DOID:0070075
xref: OMIM:610253

be split into these two:
name: Kleefstra syndrome 1
xref: OMIM:610253

name: Kleefstra syndrome 2
xref: OMIM:617768

**Comment by sbello** [comment]
This appears to be a case where OMIM renamed/redefined a term without changing the ID. The DO term DOID:0060352 definition matches the definition of OMIM 610253 (what is now type 1). I would suggest renaming the existing DO term to "Kleefstra syndrome 1" to match the OMIM term then adding a new term for type two and the generic parent. 

Type 2 involves a different gene on a different chromosome so it would not fall under the exiting DO term.

Note Orphanet has 3 entries:
ORPHA:261494 - general parent term, mapped to OMIM 610253
ORPHA:261652 - resulting from point mutation mapped to OMIMs 610253  617768
ORPHA:96147 - resulting from 9q34 microdeletion, mapped to OMIM 610253
The second 2 are children of the first and point to that one for the definition.

It seems odd to me to lump based on point mutation vs microdeletion. OMIMs type 1 covers the point mutation and microdeletion on chromosome 9q34 (the point mutation is within the microdeletion region) while type 2 involves a point mutation in a gene on a different chromosome.

My suggestion is to:
1) create a new parent mapped to OMIM PS and general Orphanet term (ORPHA:261494)
2) rename the existing DO term to type 1 and retain mapping to OMIM 610253, add mapping to ORPHA:96147 but remove mapping to ORPHA:261494 (this moves to the new parent)
3)create a new term for Type 2 that maps to OMIM 617768 but not to an Orphanet ID 

The other option would be to leave the existing DO term label alone, not create a common parent and add a new entry for type 2 (still fixing the cross-references) . However, this would mean we would have no good mappings for the OMIM PS or the Orphanet general term. 

@lschriml thoughts?

**Comment by lschriml** [comment]
@sbello -- I agree on your plan. 

I did the updates, added the new terms and OMIM IDs. 
DONE 
Cheers,
Lynn

**Comment by sjm41** [comment]
Thanks both!
