### ISSUE TITLE
Split primary hyperoxaluria (DOID:2977)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#791]
Can this:
id: DOID:2977
name: primary hyperoxaluria
xref: OMIM:260000
xref: OMIM:613616

be split into these three:
name: primary hyperoxaluria type I
xref: OMIM:259900

name: primary hyperoxaluria type II
xref: OMIM:260000

name: primary hyperoxaluria  type III
xref: OMIM:613616

**Comment by sbello** [comment]
added to ROBOT spreadsheet

**Comment by sjm41** [comment]
Hi Sue.
Just checking on this - you closed this last week, but I don't see the split in the latest DO file (2020-02-04) - did the split just miss the cut-off date?

**Comment by sbello** [comment]
My mistake, they were at the top of the list just above a set I had issues with and I forgot to copy them over. I'll get them in on the next run. Sorry Steven and thanks for checking!

**Comment by sbello** [comment]
really entered now

**Comment by sjm41** [comment]
Great!  I really appreciate your speedy turnaround with these recent tickets!!
