### ISSUE TITLE
New term request: COMBINED D-2- AND L-2-HYDROXYGLUTARIC ACIDURIA

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#792]
Could you add "COMBINED D-2- AND L-2-HYDROXYGLUTARIC ACIDURIA" (OMIM: 615182)?

I guess it should be a direct child of:
id: DOID:0050573
name: 2-hydroxyglutaric aciduria

**Comment by sbello** [comment]
on MGI ROBOT spreadsheet
