### ISSUE TITLE
New term request: SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 4

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#793]
Could you add:
SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 4; SCAR4 (OMIM:607317)

I guess as a direct child of:
id: DOID:0050950
name: autosomal recessive cerebellar ataxia

**Comment by sbello** [comment]
reviewed OMIM:PS213200 to identify additional members not yet in DO and am working on adding the full set
