### ISSUE TITLE
Split distal arthrogryposis (DOID:0050646)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#795]
This is probably already on another list somewhere (!), but would be good to split this (FlyBase at least, needs one of the more specific subtypes for annotation)

id: DOID:0050646
name: distal arthrogryposis
xref: OMIM:108120
xref: OMIM:108145
xref: OMIM:108200
xref: OMIM:114300
xref: OMIM:121050
xref: OMIM:121070
xref: OMIM:158300
xref: OMIM:187370
xref: OMIM:193700
xref: OMIM:601680
xref: OMIM:609128
xref: OMIM:614335
xref: OMIM:615065

**Comment by sbello** [comment]
These are split on the MGI ROBOT template, I'll add them the next time I do a ROBOT run

**Comment by sjm41** [comment]
Great, thanks a lot!
