### ISSUE TITLE
New term request for OMIM:608105

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#798]
EPILEPSY, ROLANDIC, WITH PAROXYSMAL EXERCISE-INDUCED DYSTONIA AND WRITER'S CRAMP; EPRPDC
https://www.omim.org/entry/608105

Needed to curate PMID: 31257402 

Thanks.

**Comment by sbello** [comment]
added to MGI ROBOT spreadsheet
