### ISSUE TITLE
New term request for DOOR syndrome (OMIM # 220500)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#799]
DEAFNESS, ONYCHODYSTROPHY, OSTEODYSTROPHY, MENTAL RETARDATION, AND SEIZURES SYNDROME; DOORS
https://www.omim.org/entry/220500

Needed to curate PMID: 27669036.

Thanks.

**Comment by sbello** [comment]
Actually just reached this one on the priority add list this week, this will be going in with the next ROBOT run
