### ISSUE TITLE
Update load of NCBITAXON organismal classification

### ISSUE THREAD

**Issue by melodyswen** [DiseaseOntology/HumanDiseaseOntology#800]
Looking at the obofoundry page for NCBITAXON, it looks like the most recent load was in 2018, at least based on Ontology Lookup Service. Could we get that updated? We'd like to be able to reflect the most updated content in our ncbitaxon import. 

@jamesaoverton

**Comment by melodyswen** [comment]
http://build.berkeleybop.org/job/build-ncbitaxon/lastSuccessfulBuild/

According to this, ncbitaxon was last built October 1st 2019. Thanks!

**Comment by beckyjackson** [comment]
Hi @melodyswen ! There is some code in the `Makefile` to reload this. All you need to do is run:
```
make ncbitaxon
```

And it will remake the import file. This file will also be remade whenever you add something to import text file in the imports directory, but we haven't needed to add any new organisms recently.

I'm running the process right now and I'll push the commit when it's done, but please let me know if you have any questions on how you can do this in the future 😃

**Comment by beckyjackson** [comment]
NCBITaxonomy import is now updated. Here are the changes from the most recent version:

| Old ID | Old Label | New ID | New Label |
| --- | --- | --- | --- | 
| NCBITaxon:227859 | SARS coronavirus | NCBITaxon:694009 | Severe acute respiratory syndrome-related coronavirus |
| NCBITaxon:11619 | Junin virus | NCBITaxon:2169991 | Argentinian mammarenavirus |
| NCBITaxon:45709 | Sabia virus | NCBITaxon:2169992 | Brazilian mammarenavirus |

I updated `doid-edit.owl` to use the new IDs as well.

**Comment by melodyswen** [comment]
Hi Becky, 

To be clear, did you add these to the import file in Protege directly? Since the ncbitaxon import is too large to do it through ROBOT?

**Comment by beckyjackson** [comment]
I updated the `ncbitaxon_terms.txt` file in the imports directory to replace the old IDs with these new IDs, as the old ones no longer exist in NCBITaxonomy.

It's not that the NCBITaxonomy is *too* large, it just needed a little extra memory, which I updated to include in the `Makefile`. So you can still add a new term to the `ncbitaxon_terms.txt` file, and run `make ncbitaxon`.

**Comment by melodyswen** [comment]
Thank you so much for explaining! Makes sense to me!
