### ISSUE TITLE
New term request for OMIM: 618652

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#803]
NEUROOCULOCARDIOGENITOURINARY SYNDROME; NOCGUS
https://www.omim.org/entry/618652

Needed to curate PMID: 31327508

**Comment by sbello** [comment]
added to ROBOT spreadsheet

**Comment by sjm41** [comment]
Thanks Sue.
I see this in the latest DO as DOID:0111675 - closing ticket.
