### ISSUE TITLE
New term request for OMIM:618687

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#804]
INTELLECTUAL DEVELOPMENTAL DISORDER WITH SHORT STATURE AND BEHAVIORAL ABNORMALITIES; IDDSSBA
https://www.omim.org/entry/618687

Needed to curate PMID: 31607425

**Comment by sbello** [comment]
on the ROBOT spreadsheet

**Comment by sjm41** [comment]
Thanks Sue - I see this in the latest DO as DOID:0111674 - closing ticket.
