### ISSUE TITLE
ocular tuberculosis 

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#805]
Looks like is_a  DOID:0050598
Located in some eye UBERON_0000019
https://www.ncbi.nlm.nih.gov/pubmed/27379384

**Comment by lschriml** [comment]
- add as child of tuberculosis (DOID:399)
 add SubClass of Axiom, located_in some 'eye

   additional sources:
    https://www.ncbi.nlm.nih.gov/pubmed/29891262

**Comment by melodyswen** [comment]
New term ocular tuberculosis has been added
