### ISSUE TITLE
Desmoplastic small round cell tumor term request

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#806]
Would you please consider adding "Desmoplastic small round cell tumor" as a child term for sarcoma?

Taofei Yin, PhD
Clinical Scientific Curator
The Jackson Laboratory

**Comment by lschriml** [comment]
@melodyswen  - please add as a child of sarcoma

  xref: NCI:C8300
-- primarily occurs as masses in the abdomen.

Sources: 
https://www.cancer.gov/pediatric-adult-rare-tumor/rare-tumors/rare-soft-tissue-tumors/desmoplastic-small-round-cell-tumors

GARD:6265

https://rarediseases.info.nih.gov/diseases/6265/desmoplastic-small-round-cell-tumor

https://en.wikipedia.org/wiki/Desmoplastic_small-round-cell_tumor

**Comment by melodyswen** [comment]
@lschriml this term has DOID:6785 that was obsoleted - should I un-obsolete and update?

**Comment by melodyswen** [comment]
Update on this ticket: unclear why this term was obsoleted in the past - no past tickets/issues concerning this term. 
Next step: review literature/ search DO documentation

**Comment by lschriml** [comment]
Updated in DO.
