### ISSUE TITLE
New term request: CATARACT 48 (OMIM:618415)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#808]
https://www.omim.org/entry/618415

Needed to curate PMID:30290152.

Thanks.

**Comment by lschriml** [comment]
Add 2 OMIM IDs as new child terms of cataract, OMIM: PS116200
  please also add  612018.  (cataract 47)
  https://www.omim.org/entry/612018

**Comment by melodyswen** [comment]
two new child terms of cataract have been added
