### ISSUE TITLE
New term request: OMIM 618170

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#809]
# 618170
NEURODEGENERATION, CHILDHOOD-ONSET, STRESS-INDUCED, WITH VARIABLE ATAXIA AND SEIZURES; CONDSIAS
https://www.omim.org/entry/618170

Needed to curate PMID:30100084

thanks.

**Comment by melodyswen** [comment]
This term has been added: DOID:0070352 stress-induced childhood-onset neurodegeneration with variable ataxia and seizures
