### ISSUE TITLE
New term request: SMALED2A (OMIM: 615290)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#810]
SPINAL MUSCULAR ATROPHY, LOWER EXTREMITY-PREDOMINANT, 2A, CHILDHOOD ONSET, AUTOSOMAL DOMINANT; SMALED2A
https://omim.org/entry/615290

Needed to curate PMID:29528393.

(it would make sense to add this related term at the same time:
SPINAL MUSCULAR ATROPHY, LOWER EXTREMITY-PREDOMINANT, 2B, PRENATAL ONSET, AUTOSOMAL DOMINANT; SMALED2B
https://omim.org/entry/618291)

**Comment by lschriml** [comment]
GHR:
https://ghr.nlm.nih.gov/condition/spinal-muscular-atrophy-with-lower-extremity-predominance

 https://omim.org/phenotypicSeries/PS158600

https://omim.org/phenotypicSeries/PS158600
        --> add New DO term: 
          spinal muscular atrophy with lower extremity predominance
         OMIM:PS158600
   --> add three subtypes:  https://omim.org/phenotypicSeries/PS158600

   --> autosomal dominant inheritance

      def: characterized by muscle weakness and wasting in the lower limbs, most severely 
      affecting the thigh muscles.

**Comment by melodyswen** [comment]
new term + subtypes added
