### ISSUE TITLE
New term request: EMPF1 (OMIM: 614388)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#811]
ENCEPHALOPATHY DUE TO DEFECTIVE MITOCHONDRIAL AND PEROXISOMAL FISSION 1; EMPF1
https://omim.org/entry/614388

Needed to curate PMID:30850373.

Thanks.

**Comment by lschriml** [comment]
add as new syndrome

**Comment by melodyswen** [comment]
new term added
