### ISSUE TITLE
New term request: VETD (OMIM: 618223)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#812]
VERTEBRAL ANOMALIES AND VARIABLE ENDOCRINE AND T-CELL DYSFUNCTION; VETD
https://omim.org/entry/618223

Needed to curate PMID:29726930

Thanks.

**Comment by lschriml** [comment]
--Add as a syndrome:

name: vertebral anomalies and variable endocrine and T-cell dysfunction

From PubMed reference:
https://www.ncbi.nlm.nih.gov/pubmed/29726930

has_material_basis_in heterozygous mutation in the TBX2 gene on chromosome 17q23.

characterized by: 
craniofacial dysmorphisms, cardiac anomalies, skeletal malformations, immune deficiency, endocrine abnormalities and developmental impairments

heterozygotes for TBX2 variants

autosomal dominant

**Comment by melodyswen** [comment]
New term added in doid-edit.owl
