### ISSUE TITLE
Faulty term ID 

### ISSUE THREAD

**Issue by cmpich** [DiseaseOntology/HumanDiseaseOntology#815]
This stanza looks wrong in the latest OBO file: The term ID should only be a DOID.

`[Term]
id: http://purl.obolibrary.org/obo/DOID:0080614
name: oculocutaneous albinism type VI
def: "An oculocutaneous albinism that has_material_basis_in an autosomal recessive null mutation of SLC24A5 on chromosome 15q21.1." [url:https\://www.omim.org/entry/203100?search=albinism%20type%20ia&highlight=albinism%20ia%20type]
synonym: "OCA1A" EXACT []
xref: OMIM:113750
is_a: DOID:0050632 ! oculocutaneous albinism`

**Comment by melodyswen** [comment]
Hi Christian, 

Thank you so much for pointing this out - I've fixed the error and reran the build - now available!
