### ISSUE TITLE
NTR OMIM: 618571 NEURODEVELOPMENTAL DISORDER WITH CATARACTS, POOR GROWTH, AND DYSMORPHIC FACIES

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#817]
https://www.omim.org/entry/618571?search=NDCAGF&highlight=ndcagf
NEURODEVELOPMENTAL DISORDER WITH CATARACTS, POOR GROWTH, AND DYSMORPHIC FACIES
PMID: 30622326
Patients had global developmental impairment with mildly delayed walking (around 3 years of age), abnormal gait, hypotonia, and impaired intellectual development with poor or absent speech. Several had features consistent with autism spectrum disorder, and some had feeding difficulties. All patients developed cataracts between 1 and 3 years of age. More variable ocular findings included myopia, microphthalmia, microcornea, and coloboma. Common dysmorphic features included frontal bossing, small palpebral fissures, widely spaced eyes, full cheeks, broad nasal bridge with a broad nasal tip, low-set and simple ears, downturned corners of the mouth, and small chin. Other features included diastema, short neck, pectus deformities, and broad halluces with overlapping toes.

**Comment by lschriml** [comment]
add as a syndrome, when more is known, can re-classify.
Lynn

**Comment by melodyswen** [comment]
New term has been added
