### ISSUE TITLE
Split DOID:0060308 (autosomal recessive non-syndromic intellectual disability)?

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#818]
Hi,

I would like to use a DO term equivalent to OMIM:607417 (https://omim.org/entry/607417) to curate PMID:29530986.
I see that OMIM is currently one of many xrefs to DOID:0060308.
Any chance of that DOID being split anytime soon? If not, I can use DOID:0060308 in my curation for now.

**Comment by sbello** [comment]
Hi Steven,
I've been trying to get in touch with OMIM about this series and the related syndromic and non-syndromic series. The issue I'm trying to figure out is how the division between syndromic and non-syndromic is being made. In reviewing the entries there were many that I would have classified as syndromic that are in the non-syndromic branch. See ticket #746 for more details.
I suspect this split is still going to take some time to sort out properly.
Sue

**Comment by sjm41** [comment]
Thanks for that explanation Sue - I should have noticed that there was already a ticket on this OMIM term.....  I'm now watching that ticket - I understand this won't be a quick fix!

**Comment by sbello** [comment]
Thanks Steven. I'm going to close this ticket. I'll put any further updates in #746
