### ISSUE TITLE
isolated cryptophthalmos

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#819]
The changes made recently to obsolete eye and adnexa disease resulted in and MGI annotation for a model of 'isolated cryptophthalmos' no longer has a DO term to use for the annotation. 
The annotation comes from PMID:30802441 
"Cryptophthalmos is a rare congenital disorder characterized by ocular dysplasia with eyelid malformation. Complete cryptophthalmos is characterized by the presence of continuous skin from the forehead over the eyes and onto the cheek, along with complete fusion of the eyelids."
I'd like to add a term for 'isolated cryptophthalmos' but I think the only parent for this would be syndrome. Does anyone have a better suggestion for a parent?

**Comment by melodyswen** [comment]
Hi Sue - what about DOID:37 'skin disease'? or DOID:530 'eyelid disease'?

**Comment by lschriml** [comment]
Hello Sue,
  as this is congenital, I suggest making it a child of disorder, 
with a logical definition to link it to eyelid disease

https://disorders.eyes.arizona.edu/disorders/cryptophthalmos
https://www.karger.com/Article/Pdf/422027

https://www.omim.org/entry/123570?search=CRYPTOPHTHALMOS&highlight=cryptophthalmo

synonym: hidden eye

--> there are 3 types: 

ORPHA:98562    Cryptophthalmia [parent term]
   ORPHA:98949  Complete cryptophthalmia
   ORPHA:91396    Isolated cryptophthalmia
   ORPHA:98950     Partial cryptophthalmia

Cheers,
Lynn

**Comment by sbello** [comment]
working on these

**Comment by sbello** [comment]
terms added using ROBOT
