### ISSUE TITLE
New term request: Pediatric High Grade Glioma

### ISSUE THREAD

**Issue by obophenotype-user** [DiseaseOntology/HumanDiseaseOntology#82]
Hello, 
I am requesting a new term, which would probably be a child of DOID:3620 - central nervous system cancer

New term: Pediatric High Grade Glioma
publications: PMID: 22937526 

Thank you 
Sabrina

Reported by: sabrinatoro

Original Ticket: [diseaseontology/feature-requests/82](https://sourceforge.net/p/diseaseontology/feature-requests/82)

**Comment by lschriml** [comment]
Hello Sabrina,
 apologies for the delay in resolving this issue.
In DO, we classify cancers by cell type and location, but not by grade. 
As we have aligned our classification with the NCI.

I would suggest mapping Pediatric High Grade Glioma to DOID:0060108  brain glioma.
Please let us know what you think. 
Cheers,
Lynn
