### ISSUE TITLE
Special characters in Griscelli syndrome type 2 DOID:0060833 synonym name

### ISSUE THREAD

**Issue by ybradford** [DiseaseOntology/HumanDiseaseOntology#821]
one of the synonym for Griscelli syndrome type 2 DOID:0060833 produces special characters in the synonym name:
Griscelli-Pruni��ras syndrome type 2 [EXACT]

It would be helpful if these were changed or removed.

Thanks!
Yvonne

**Comment by lschriml** [comment]
Thank you Yvonne !!
Found a few other instances of �� and have fixed those as well.
We really appreciate your pointing this issue out so that we can improve the data.

Cheers,
Lynn
