### ISSUE TITLE
NTR: CHEGDD OMIM:213000

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#823]
https://www.omim.org/entry/213000
CEREBELLAR HYPOPLASIA/ATROPHY, EPILEPSY, AND GLOBAL DEVELOPMENTAL DELAY; CHEGDD (213000)

Needed to curate PMID:31785787

**Comment by lschriml** [comment]
Reviewing this request: 
(1) We need to add cerebellar hypoplasia to DO, as a child of cerebellar disease (DOID:2786)
         **cerebellar hypoplasia**  [not currently in DO]
                 xref:  GARD:1194
                 definition info:  - Cerebellar hypoplasia is a neurological condition in which the 
                   cerebellum is smaller than usual or not completely developed.
     Source: 
     https://www.ninds.nih.gov/Disorders/All-Disorders/Cerebellar-Hypoplasia-Information-Page
      https://en.wikipedia.org/wiki/Cerebellar_hypoplasia

    **Related terms in DO:**  --> Needs to be moved to syndrome
     DOID:0050997, cerebellar ataxia, mental retardation and dysequlibrium syndrome
    --> is_a autosomal recessive cerebellar ataxia
                Need to add exact synonyms: 
              **VLDLR Cerebellar Hypoplasia**
              Cerebellar Ataxia, Mental Retardation, and Dysequilibrium Syndrome 1 (CAMRQ1)
 
          OMIM:**cerebellar ataxia, mental retardation, and dysequilibrium syndrome** (CAMRQ1) is caused by homozygous mutation in the VLDLR gene (192977), which encodes the very low density lipoprotein receptor, on chromosome 9p24.

          Sources: 
                    https://www.ncbi.nlm.nih.gov/books/NBK1874/
                    https://ghr.nlm.nih.gov/condition/vldlr-associated-cerebellar-hypoplasia
          Xref:
               GARD:1998, Dysequilibrium syndrome

**Term request:**     --> add as a child of syndrome
https://www.omim.org/entry/213000
CEREBELLAR HYPOPLASIA/ATROPHY, EPILEPSY, AND GLOBAL DEVELOPMENTAL DELAY; CHEGDD (213000)

       OMIM: **cerebellar hypoplasia/atrophy, epilepsy, and global developmental delay** (CHEGDD) is caused by homozygous or compound heterozygous mutation in the OXR1 gene (605609) on chromosome 8q23.

     --> links to : 
          Orphanet: ORPHA:2246, **Cerebellar hypoplasia-tapetoretinal degeneration syndrome**
               GARD definition:
                 with a cerebellar malformation as a major feature characterized by cerebellar hypoplasia, bilateral retinal pigmentary changes, intellectual disability that can range from mild to moderate and pronounced language development delay. It presents with early developmental delay, central and peripheral non-progressive visual impairment or asymptomatic retinal changes, hypotonia, non-progressive ataxia and nystagmus. 

Cheers,
Lynn

**Comment by melodyswen** [comment]
Data updated - new terms added, parentage changed
