### ISSUE TITLE
Cancer/Benign Neoplasm Overlap Classes

### ISSUE THREAD

**Issue by beckyjackson** [DiseaseOntology/HumanDiseaseOntology#824]
The following DOID classes are subclasses of both "cancer" and "benign neoplasm", which are disjoint with one another. This means that a child of cancer cannot also be a child of benign neoplasm:
* **pancreatic intraductal papillary-mucinous adenoma** (DOID:7851) -> subclass of 'pancreatic intraductal papillary-mucinous neoplasm' (cancer) and 'gastrointestinal system benign neoplasm' (benign neoplasm)
* **benign struma ovarii** (DOID:5209) -> subclass of 'struma ovarii' (cancer) and 'ovarian benign neoplasm' (benign neoplasm)
* **nervous system hibernoma** (DOID:6607) -> subclass of 'nervous system cancer' (cancer) and 'central nervous system lipoma' (benign neoplasm)
* **urinary bladder villous adenoma** (DOID:5427) -> subclass of 'urinary bladder cancer' (cancer) and 'urinary system benign neoplasm' (benign neoplasm)
* **epidural spinal canal angiolipoma** (DOID:3617) -> subclass of 'epidural spinal canal neoplasm' (cancer) and 'angiolipoma' (benign neoplasm)
* **rete testis adenoma** (DOID:6483) -> subclass of 'rete testis neoplasm' (cancer) and 'male reproductive organ benign neoplasm' (benign neoplasm)

These should only have *one* asserted parent.

**Comment by lschriml** [comment]
Data updated.
