### ISSUE TITLE
OMIM:600145 SACRAL DEFECT WITH ANTERIOR MENINGOCELE

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#825]
The OMIM ID 600145 is on the UniProt request list but this is a bit of a messy one.

The primary entity for this ID is "sacral defect with anterior meningocele" (SDAM) but there are multiple included entities in this record, these are:

- caudal dysgenesis syndrome - UMLS C1838569

- caudal regression syndrome - gene association in OMIM is for this entity
    Orphanet 3027 https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=3027
    Orphanet name is Caudal regression sequence
        has synonyms: Caudal dysplasia, Sacral agenesis syndrome, Sacral regression syndrome
    has multiple UMLS xrefs in Orphanet 
       C0300948 - Caudal regression syndrome
       C1867774 - invalid ID 
       C2609260 - invalid ID
    has multiple MEDDRA xrefs
        10054842 - sacral agenesis (MEDDRA record has this "classified as Caudal regression syndrome"
        10059387 - Caudal regression syndrome
        10068896 - Caudal dysplasia syndrome (MEDDRA record has this "classified as Caudal regression syndrome"

- sacral agenesis
     C0344490 - Sacral agenesis (xref to ORDO:3027)

- sirenomelia (see ticket #315 ) - Orphanet 3169 (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=3169)
     UMLS C0037205

Text in the OMIM record indicates:

- SDAM is a form of caudal dysgenesis

- "Caudal dysgenesis syndrome and caudal regression syndrome are broad terms that refer to a heterogeneous constellation of congenital caudal anomalies affecting the caudal spine and spinal cord, the hindgut, the urogenital system, and the lower limbs"

**Comment by lschriml** [comment]
Hello @sbello - looking at GHR, notes below, and publications.

This term can be added as a child of physical disorder. 
Basically, what was once considered a number of different diseases, is
now considered one disease: caudal regression syndrome

**GHR: caudal regression syndrome**
a disorder that impairs the development of the lower (caudal) half of the body. Affected areas can include the lower back and limbs, the genitourinary tract, and the gastrointestinal tract.
**Other Names (GHR):** 
caudal dysgenesis syndrome
caudal dysplasia sequence
caudal regression sequence
sacral agenesis
sacral defect with anterior meningocele
2020 publication:  https://www.ncbi.nlm.nih.gov/pubmed/32200015
Caudal Regression Syndrome - A Review Focusing on Genetic Associations.
Caudal regression syndrome (CRS) represents a spectrum of clinical phenotypes with varying degrees of malformation of the lower body with involvement of structures deriving from all three layers of the trilaminar embryo.
Caudal regression syndrome is a rare malformative syndrome associated, to varying degrees, with agenesis of sacral and coccygeal vertebrae, lower limb shortening and gastrointestinal, genitourinary and cardiovascular abnormalities.
https://www.ncbi.nlm.nih.gov/pubmed/30574238

Cheers,
Lynn

**Comment by lschriml** [comment]
Updated in the DO.
Lynn
