### ISSUE TITLE
NTR: NEPHROTIC SYNDROME, TYPE 20; NPHS20

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#827]
Hi,

Can you make a new term for this entry:
NTR: NEPHROTIC SYNDROME, TYPE 20; NPHS20 # 301028
https://www.omim.org/entry/301028

Needed to curate PMID:31732614

Thanks.

**Comment by melodyswen** [comment]
Hi, I'll make this a child term under our syndrome branch. 

Thanks for bringing this up! 
Melody

**Comment by lschriml** [comment]
Thank you Melody,
   this term can be added as an additional child term of: 
DOID:2590
familial nephrotic syndrome
 
Cheers,
Lynn

**Comment by melodyswen** [comment]
Thanks Lynn, new term has been added!
