### ISSUE TITLE
pancreatic adenocarcinoma located in some pancreas?

### ISSUE THREAD

**Issue by jonathanbona** [DiseaseOntology/HumanDiseaseOntology#829]
Pancreatic adenocarcinoma (http://purl.obolibrary.org/obo/DOID_4074) is a subclass of _(cancer and ('located in' some pancreas)_.

My concern about using this is that when someone's pancreatic adenocarcinoma metastasizes to his lungs then there's an instance of pancreatic adenocarcinoma that is not located in the pancreas, and that may persist even if the patient has no pancreas (for instance if the pancreas has to be removed), leading to false inferences like: _this person has a pancreas_.

This also seems to be an instance of the located_in domain violation discussed in issue https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/649.

**Comment by melodyswen** [comment]
Thanks Jonathan - we'll discuss this and get back to you!

**Comment by lschriml** [comment]
Hello Jonathan,
   Thank you for connecting with us. 

   As DO was developed we grappled with this exact problem.
   In representing diseases as distinct classes, we represent each disease
   distinctly, that is, the primary cancer in this example, pancreatic adenocarcinoma.
   And the latter disease as lung adenocarcinoma. 
      In our data model, we do not represent metastasis, or disease    
     progression/disease course. 

   NCI thesaurus represents metastatis:
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C19151


<img width="299" alt="Screen Shot 2020-03-26 at 2 16 43 PM" src="https://user-images.githubusercontent.com/4333069/77681921-777c3000-6f6c-11ea-8a5d-a276202a9271.png">

Cheers,
Lynn

**Comment by andredekker** [comment]
I would request to reopen this issue. It is a given reality that a e.g. a prostate cancer can be located in the spine. It could even be that the prostate is no longer there (e.g. because it has been removed). By including the "located_in" axiom you assume that a prostate must be there which is not true. In my opinion you should change it to a property such as the NCI thesaurus which uses has_primary_site.

**Comment by jonathanbona** [comment]
Could this be resolved by replacing located_in with disease_has_location, as in https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/649#issuecomment-461236504 ?
