### ISSUE TITLE
"nephrolithiasis"-related terms in DO

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#830]
Hi,

I'm absolutely no expert in this area, but I was just curating PMID:31364377 and got confused by how DO currently handles "nephrolithiasis"-related terms. Thought I'd report in case there's really an issue here that could be solved.
The paper creates a fly model of "uric acid (urate) nephrolithiasis".
Searching for "nephrolithiasis" in DO gives me 4 hits:

**1. nephrolithiasis (DOID:585)**
- is_a kidney disease
- no Def.
- OMIM:167030 -> caused by mutation of SLC26A1

**2. acute urate nephropathy (DOID:580)**
- is_a kidney disease
- no Def.
 - no OMIM (_might be 191700??_)
- synonyms inc. "Uric acid nephrolithiasis"

**3. hypophosphatemic nephrolithiasis/osteoporosis 1 (DOID:0080077)**
- is_a impaired renal function disease
- no Def.
- OMIM:612286 -> caused by mutation of SLC34A1

**4. hypophosphatemic nephrolithiasis/osteoporosis 2 (DOID:0080078)**
- is_a impaired renal function disease
- no Def.
- OMIM:612287 -> caused by mutation of SLC9A3R1

From a simple name match, I initially thought PMID:31364377 was talking about DOID:585 or DOID:580, but then comparing the stated implicated gene (SLC9A3R1, aka NHERF1), it seems they are specifically modeling DOID:0080078.

I was thinking the best thing to do might be to use a parental 'nephrolithiasis' grouping term, but there's currently not one in the DO - note the 4 terms above map to 2 different parents.  Is such a grouping term possible/appropriate do you think?
Also, the current nephrolithiasis (DOID:585) term might be better named ''calcium oxalate nephrolithiasis" to (i) make it clear it's NOT a grouping term; and (ii) better match the OMIM name.

Anyway, this is primarily a report of my findings - hoping someone there is better placed to judge whether these terms/relationships can be improved.

**Comment by sjm41** [comment]
Great, thanks for looking into this so quickly and deeply Lynn!
Your reorganisation/additions look much better!

**Comment by lschriml** [comment]
Great, 
  Appreciate your insights !! 
  I've updated the DO with this new and revised content. 

Cheers,
Lyn
