### ISSUE TITLE
NTR: VISUAL IMPAIRMENT AND PROGRESSIVE PHTHISIS BULBI

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#831]
Can you add a new DO entry for this please:
VISUAL IMPAIRMENT AND PROGRESSIVE PHTHISIS BULBI; VIPB (# 618283)
https://www.omim.org/entry/618283

Needed to curate PMID:29771303

**Comment by lschriml** [comment]
Review:
  This is an eye disease 

An eye disease that is characterized by poor vision at birth, with development of bilateral phthisis by adulthood and that has_material_basis_in homozygous mutation in the MARK3 gene on chromosome 14q3.

References:
https://www.ncbi.nlm.nih.gov/pubmed/29771303
UniProt: https://www.uniprot.org/diseases/DI-05463
https://en.wikipedia.org/wiki/Phthisis_bulbi

   xref.   MESH:D005128

  SubClassOf:  'has material basis in' some 'autosomal recessive inheritance'

**Comment by melodyswen** [comment]
This has been added as a new term! Thanks!

**Comment by sjm41** [comment]
Thanks Melody.
