### ISSUE TITLE
NTR: MUSCULAR DYSTROPHY, LIMB-GIRDLE, AUTOSOMAL RECESSIVE 21

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#832]
Hi,

Can you add a DO term for this please:

MUSCULAR DYSTROPHY, LIMB-GIRDLE, AUTOSOMAL RECESSIVE 21; LGMDR21
# 617232
https://www.omim.org/entry/617232

Needed to curate PMID:31897643

Thanks.

**Comment by lschriml** [comment]
added to DO
