### ISSUE TITLE
Update DOID:11776  

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#834]
It looks like this term might map to absolute glaucoma  http://www.icd9data.com/2012/Volume1/320-389/360-379/360/360.42.htm
Convert to ICD-10-CM: 360.42 converts approximately to:

    2015/16 ICD-10-CM H44.519 Absolute glaucoma, unspecified eye

Perhaps a definition of 
Progressive blindness caused by increased intraocular pressure (glaucoma).

**Comment by lschriml** [comment]
Thank you for identifying this update. 
Much appreciated !!
I've moved the term to be a child of glaucoma, updated the term name, 
added a definition and ICD10CM code.

Cheers,
Lynn
