### ISSUE TITLE
synonym typo for DOID:0080474

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#835]
[Term]
id: DOID:0080474
name: pustular psoriasis 14
synonym: "deficiency of IL-36R antagonistacrodermatitis continua of hallopeau" EXACT []

It looks like two synonyms have been inadvertently merged into one. And 'hallopeau' should be 'Hallopeau'.

**Comment by lschriml** [comment]
Agreed.
 Fixed.

Thank you for pointing out this error. 
Much appreciated !!
Lynn
