### ISSUE TITLE
FTDALS term names

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#836]
Just wondering...is there a good reason why these 4 DO term names use the abbreviation rather than a 'full name'?  I don't remember seeing abbreviations used as the full-name for other DO terms.
DOID:0110068 | FTDALS3
DOID:0110069 | FTDALS4
DOID:0060214 | FTDALS2
DOID:0060213 | FTDALS1

**Comment by melodyswen** [comment]
Hi! 

Good catch - we will change the abbreviation to use the full-name. Thank you for your comment!

Cheers,
Melody

**Comment by lschriml** [comment]
fixed, updated. 
Cheers,
Lynn
