### ISSUE TITLE
NTR: FANCONI RENOTUBULAR SYNDROME 4 WITH MATURITY-ONSET DIABETES OF THE YOUNG

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#837]
FANCONI RENOTUBULAR SYNDROME 4 WITH MATURITY-ONSET DIABETES OF THE YOUNG; FRTS4 (OMIM: # 616026)
https://www.omim.org/entry/616026

Needed to curate PMID: 31875549 

Thanks.

**Comment by lschriml** [comment]
updated: 
Fanconi renotubular syndrome - PS134600   [DOID:1062]

Added: 
    OMIM:134600. Fanconi renotubular syndrome 1
    OMIM:613388. Fanconi renotubular syndrome 2
    OMIM:615605. Fanconi renotubular syndrome 3
    OMIM:616026. Fanconi renotubular syndrome 4
    OMIM:618913. Fanconi renotubular syndrome 5
