### ISSUE TITLE
review request for DOID:0050802

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#840]
The current term name is not adequate to content. Please review it and possibly add child terms.

Ehlers-Danlos syndrome progeroid type (DOID:0050802) currently is based on OMIM:615349.

But OMIM lists additionally OMIM:130070 and OMIM:612350.

Additionally, OMIM:130070 justifies the term name change 'Ehlers-Danlos syndrome, spondylodysplastic type'. Also ORDO:75496 uses 'spondylodysplastic' in term name. So I propose to change the term name like above.

**Comment by lschriml** [comment]
Thank you !!
These will be reviewed and updated.

Cheers,
Lynn

**Comment by lschriml** [comment]
Ehlers-Danlos syndrome
 The 2017 classification describes 13 types of Ehlers-Danlos syndrome.
 include rare forms of Ehlers-Danlos syndrome
- the Villefranche nomenclature: that reduced the number of types to six and gave them descriptive names based on their major features

I've reviewed all of the subtypes, determined which DOIDs map to these subtypes, and where new DOIDs need to be created. 
documented in: https://docs.google.com/document/d/1Y_4OZEp19TkR8uZmD-ICf20HjUh4Xb-keNDyEPyYZFI/edit?usp=sharing

@sbello - Can you let me know if these are in your OMIM spreadsheet for updating and if I should proceed with the fixes.

Cheers,
Lynn

**Comment by lschriml** [comment]
The terms have been added to the DO.
They will be public in next week's release.

Cheers,
Lynn
