### ISSUE TITLE
Add B-ALL prefix Aliases 

### ISSUE THREAD

**Issue by arpaddanos** [DiseaseOntology/HumanDiseaseOntology#841]
<img width="1162" alt="BALL" src="https://user-images.githubusercontent.com/13948978/78948349-9363f380-7a8d-11ea-808b-a478a8e46563.png">

The recent set of B-lymphoplastic leukemia/lymphoma terms for WHO subtypes were added and incorporated into CIViC. Request that the aliases be added in the form "B-ALL _subtype_":

B-ALL with IAMP21
B-ALL with IL3-IGH
...

For the eight different variants added. (IAMP21, IL3-IGH, BCR-ABL1, TCF3-PBX1, ETV6-RUNX1, KMT2A Rearranged, Hypodiplidy, Hyperdiploidy)

**Comment by lschriml** [comment]
Added earlier today. 
Will be in next weeks release.

Cheers,
Lynn
