### ISSUE TITLE
synonym typos

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#842]
It is 'syndrom', should be 'syndrome'

[Term]
id: DOID:0050167
name: autoimmune polyendocrine syndrome type 1
synonym: "Whitaker syndrom" EXACT []

[Term]
id: DOID:0110090
name: short-rib thoracic dysplasia 7 with or without polydactyly
synonym: "short rib-polydactyly syndrom type V" EXACT []

**Comment by lschriml** [comment]
Thank you for pointing this out !! 
Fixed.

Cheers,
Lynn
