### ISSUE TITLE
duplicate terms alert

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#844]
There is a significant overlap of these two terms (below). Also many external sources list 'autosomal dominant endosteal hyperostosis' as synonym to 'Worth's syndrome'. Please review -- the terms look as duplicates. 

id: DOID:0111372
name: autosomal dominant endosteal hyperostosis
synonym: "Autosomal dominant osteosclerosis, Worth type" EXACT []
synonym: "endosteal hyperostosis, Worth type" EXACT []
synonym: "hyperostosis corticalis generalisata, benign form of worth, with torus palatinus" EXACT []

id: DOID:0080037
name: Worth's syndrome
synonym: "autosomal dominant endosteal hyperostosis" EXACT []
synonym: "autosomal dominant osteosclerosis" EXACT []
synonym: "benign form of Worth hyperostosis corticalis generalisata with torus platinus" EXACT []
synonym: "Worth syndrome" EXACT []

**Comment by lschriml** [comment]
Agreed:
  Merge   DOID:0111372
               name: autosomal dominant endosteal hyperostosis
into
      Worth's syndrome. [rename Worth syndrome]

https://pubmed.ncbi.nlm.nih.gov/29709743/?from_term=%22endosteal+hyperostosis%22&from_sort=date&from_pos=3

DO has been updated !!
Thank you !!
Cheers,
Lynn
