### ISSUE TITLE
Placement of 'autoimmune disease of skin and tissue' after reasoning

### ISSUE THREAD

**Issue by beckyjackson** [DiseaseOntology/HumanDiseaseOntology#846]
'autoimmune disease of skin and tissue' appears under 'rheumatic disease', which is a child of 'autoimmune disease of musculoskeletal system', after reasoning. When you remove redundancies, 'autoimmune disease of skin and tissue' is placed only under 'rheumatic disease'. This is causing some weird things for the IEDB disease tree. 

Here's the robot commands:
```
robot reason --input src/ontology/doid.owl
    relax reduce 
    remove --select "equivalents" \
    --output doid-clean.owl
```

This first reasons, then relaxes all equivalent axioms to "subClass of" axioms, and then reduces by removing redundancies. Finally, it removes equivalent axioms. We need these steps to make a clean structure for the IEBD tree, but we end up with this:

![image](https://user-images.githubusercontent.com/16750150/80236525-0b92f300-8610-11ea-8848-c0e9bd15a456.png)

Could we review the axioms for 'rheumatic disease' and and 'autoimmune disease of skin and tissue'?

**Comment by lschriml** [comment]
yes, I will review. 

Cheers,
Lynn

**Comment by lschriml** [comment]
Looking these over,
 I revised classification for rheumatic disease, move it to 
musculoskeletal system disease

Moved EQ to a SubClass statement for location of 
'autoimmune disease of skin and connective tissue
   
Should be fixed for you.
Cheers,
Lynn

**Comment by beckyjackson** [comment]
Thank you!

**Comment by beckyjackson** [comment]
Just a small fix - the axiom for 'autoimmune disease of skin and connective tissue' should be:
```
'located in' some ('zone of skin' and 'connective tissue')
```

The current axiom is still causing it to reason under musculoskeletal system.

Can we add the equivalence axiom to 'autoimmune hypersensitivity disease':
```
'has phenotype' some Autoimmunity
```
Currently 'rheumatoid arthritis' has this subclass axiom, but it doesn't place it under autoimmune disease because there is no equivalence axiom there.

This could actually solve the two parents for #847 because we could just add that same subclass axiom to that term as well.

Please let me know if this sounds OK to you and I can make the changes! Thank you 😄

**Comment by beckyjackson** [comment]
As a side note, I think that we can make this an equivalence axiom on 'autoimmune disease of skin and connective tissue' without causing any overlap with musculoskeletal system.
