### ISSUE TITLE
Placement of DOID:5213

### ISSUE THREAD

**Issue by beckyjackson** [DiseaseOntology/HumanDiseaseOntology#847]
'chronic inflammatory demyelinating polyradiculoneuropathy' (DOID:5213)
> a slowly developing autoimmune disorder in which the body's immune system attacks the myelin that insulates and protects your body's nerves

... should also be a subclass of 'autoimmune disease of peripheral nervous system'

~I don't know a good way to make this happen with reasoning unless we can add an equivalence axiom to its current parent, 'polyradiculoneuropathy', so it's possible this would need two parents.~

If we add the equivalence axiom to 'autoimmune hypersensitivity disease' and add:
```
'has phenotype' some Autoimmunity
```
... to this term, it *should* reason under the correct place without needing a second parent.

**Comment by lschriml** [comment]
Hello Becky,
   I have reviewed and revised the peripheral nervous system diseases: polyradiculoneuropathy, polyradiculopathy and polyneuropathy.
  The inflammatory conditions (below) cause the above peripheral nervous system diseases. [See Refs, below]. 
Along with acute and chronic inflammatory demyelinating polyradiculoneuropathy.

I have re-classified chronic inflammatory demyelinating polyradiculoneuropathy to be a child of autoimmune disease of peripheral nervous system

Ref:
https://www.ncbi.nlm.nih.gov/pubmed/22810934
Acute and chronic polyradiculopathies.
https://rarediseases.org/rare-diseases/chronic-inflammatory-demyelinating-polyneuropathy/

Cheers,
Lynn
