### ISSUE TITLE
organization of keratosis follicularis spinulosa decalvans related terms

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#849]
Orphanet has 3 OMIM IDs (308800  604093  612843) associated with the entry for Keratosis follicularis spinulosa decalvans (ORDO:2340) 
One of the OMIM terms OMIM:604093 has the same name as the term ORDO uses as the parent for ORDO:2340, keratosis pilaris atrophicans. 
These are clearly not identical as the OMIM entry for keratosis pilaris atrophicans specifies a gene association which does not match the gene associated with OMIM:308800
Possibly we could organize this as:
 Keratosis pilaris atrophicans ORPHA:498
          -X-linked keratosis follicularis spinulosa decalvans (OMIM)
          -autosomal dominant keratosis follicularis spinulosa decalvans (OMIM)
          -keratosis pilaris atrophicans 1 (OMIM but add the number to indicate this is a gene specific entry)
Downside, we would not be able to incorporate keratosis follicularis spinulosa decalvans (ORDO:2340)
OMIM:308800 is from the UniProt list

**Comment by lschriml** [comment]
--> reviewed, notes below.
New DO terms to be added. 
Cheers,
Lynn

parent (of KPA): ichthyosis (DOID:1697)
   
**keratosis pilaris atrophicans**  (ORPHA:498)
             [Keratosis pilaris atrophicans (KPA) represents a group of rare genodermatoses 
             characterized by perifollicular keratosis and inflammation that progresses to atrophy
               and scarring of the facial skin.] 
              (OMIM:604093).    https://www.omim.org/entry/604093
                   -autosomal recessive -
    
     --> don't need to add a 1 to this disease name, that I can see. 

                      perifollicular: tissues surrounding a follicle.
                      keratosis: a horny growth, especially on the skin.
           
    KPA is the parent term of: 
                      3 subtypes
                      (1)   keratosis pilaris atrophicans faciei (KPAF)
                      (2)  [parent]keratosis follicularis spinulosa decalvans (KFSD)
                         (ORPHA:2340) --> is for the parent term (includes multiple inheritance types)
                             [child 1 of KFSD]:  X-linked keratosis follicularis spinulosa decalvans                            
                                            (GARD:6829) X-linked
                                            (OMIM:308800)  X-linked keratosis follicularis spinulosa decalvans
                            [child 2 of KFSD]: autosomal dominant keratosis follicularis spinulosa decalvan
                                          (OMIM: 612843)


                     (3) atrophoderma vermiculata (AVA; see OMIM:209700) 
                                (ORPHA:79100) (GARD:9744)
                                 [Orphanet links to this OMIM number and to the OMIM for the parent term, 
                                               keratosis pilaris atrophicans]
                                     - typically presents in childhood with erythema and follicular keratotic 
                                     papules that slowly progress to characteristic atrophy, which has been 
                                     described as worm-eaten, reticular, or honeycomb, and occurs on the 
                                     cheeks, preauricular area, and forehead.
       



**keratosis follicularis spinulosa decalvans** (ORDO:2340)
[  https://rarediseases.info.nih.gov/diseases/6829/keratosis-follicularis-spinulosa-decalvans ]
Keratosis follicularis spinulosa decalvans (KFSD) is a rare, inherited , skin condition. KFSD is a form of ichthyoses, a group of inherited conditions of the skin in which the skin tends to be thick and rough, and to have a scaly appearance. The face, neck, and forearms are frequently involved.

Keratosis follicularis spinulosa decalvans 
          is a disorder affecting the hair follicles characterized by scarring alopecia of the scalp, eyebrows, and axillae, sometimes associated with photophobia and keratoderma. Being X-linked, it is more commonly seen in males but can be rarely seen in females also. 
[ https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4639957/]

**Comment by lschriml** [comment]
terms added to the DO. 
Lynn
