### ISSUE TITLE
term request: Limbic encephalitis

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#850]
The IEDB would like to request this term:
Name:
Limbic encephalitis
Definition:
Encephalitis characterized by autoimmune   inflammation of the limbic system and other parts of the brain.
Parent   Relationships:
encephalitis (but note that this not an infectious disease)
Parent   Relationships:
autoimmune disease of central   nervous system
Xrefs:
https://rarediseases.info.nih.gov/diseases/8742/limbic-encephalitis,   G04.81, Schott JMLimbic encephalitis: a clinician’s guidePractical Neurology   2006;6:143-153

Thanks

**Comment by lschriml** [comment]
added to DO
