### ISSUE TITLE
New term request: Libman–Sacks endocarditis

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#851]
The IEDB would like to request this term:
Name:
Libman–Sacks   endocarditis
Definition:
A nonbacterial   endocarditis that occurs in association with systemic lupus erythematosus.
Synonyms:
Libmann–Sachs,   Endocarditis in systemic lupus erythematosus
Parent   Relationships:
endocarditis
Parent   Relationships:
autoimmune   disease of cardiovascular system
Xrefs:
PMID: 30422459,   M32.11
Thanks

**Comment by lschriml** [comment]
Added to DO.
