### ISSUE TITLE
add parent for atopic dermatitis

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#852]
Is it possible to make atopic dermatitis | DOID:3310
a child of 
allergic contact   dermatitis | DOID:3042?
we expected it to reason there.
Thanks

**Comment by lschriml** [comment]
yes, done.

also updated 'allergic contact dermatitis'
  to be a direct child of 'contact dermatitis' and inferred child of 'allergic disease'
