### ISSUE TITLE
children for autoimmune hypersensitivity disease

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#853]
We have several terms that we expected to find as children of 
autoimmune  hypersensitivity disease DOID:417
We double checked that this is the general consensus that these are autoimmune diseases:
Behcet's   disease
Felty's syndrome
Lambert-Eaton myasthenic   syndrome
cicatricial pemphigoid
epidermolysis bullosa   acquisita
mixed connective tissue   disease
pemphigoid gestationis
pemphigus
polymyalgia rheumatica
psoriasis
relapsing polychondritis
temporal arteritis
type 1 diabetes mellitus
ulcerative colitis
ankylosing spondylitis
Thanks

**Comment by lschriml** [comment]
Following IEDB recommendation, updated DO term to 'autoimmune disease' from 'autoimmune hypersensitivity disease' 
DOID:417

added: 'has phenotype' some 'Abnormal immunoglobulin level'

Behcet's disease
Felty's syndrome
Lambert-Eaton myasthenic syndrome
cicatricial pemphigoid
epidermolysis bullosa acquisita
mixed connective tissue disease
pemphigoid gestationis
pemphigus
polymyalgia rheumatica
psoriasis
relapsing polychondritis
temporal arteritis
type 1 diabetes mellitus
ulcerative colitis
ankylosing spondylitis
