### ISSUE TITLE
update Aarskog syndrome

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#856]
Currently Aarskog syndrome (DOID:6683) is in as a child of 'syndromic X-linked intellectual disability' and has an X-linked inheritance relationship. This is incorrect as:
1. Most patients with Aarskog syndrome don't have intellectual disability (the OMIM ID has an included entity for a second syndrome that includes ID and that is why it is on the OMIM list)
2. There are at 2 OMIM entries for Aarskog-Scott syndrome, 305400 - X-linked and 100050 - autosomal dominant (there is a third entry for an Aarskog-like syndrome with recessive inheritance 227330)
3. The current DO release has the autosomal dominant OMIM ID as an xref to the X-linked disease (I've changed this to the x-linked one in the edit file already)

I propose we:
1. Change the label of existing DO term to X-linked Aarskog syndrome
2. Add a new parent of Aarskog syndrome - this would have the Orphanet term (ORDO:915) as an xref as the Orphanet term covers both OMIM forms
3. Add a new term 'autosomal dominant Aarskog syndrome' as a child of Aarskog syndromw
4. Place Aarskog syndrome under syndrome 
5. Remove the relationship to 'syndromic X-linked intellectual disability' for DOID:6683 and update the definition to include the new parent and the gene relationship

@lschriml does this sound okay to you

**Comment by sbello** [comment]
GARD:4775 - refers to X-linked syndrome

**Comment by lschriml** [comment]
Thank you @sbello - Agreed, sounds OK to me !!

Cheers,
Lynn

**Comment by sbello** [comment]
Thanks Lynn. I have the new terms prepped and I'll clean up the xrefs and synonyms after my next ROBOT run.

**Comment by lschriml** [comment]
Great !!
