### ISSUE TITLE
congenital diaphragmatic hernia ICD code change

### ISSUE THREAD

**Issue by plasmak11** [DiseaseOntology/HumanDiseaseOntology#857]
Hi my name is Jung Hoon Son, pathologist/informaticist. First of all, thanks for the great project repo!

[congenital diaphragmatic hernia
](https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_3827) DOID:3827 

Has mapping to ICD10 [K44](https://www.icd10data.com/ICD10CM/Codes/K00-K95/K40-K46/K44-) (which is diaphragmatic hernia, not necessarily congenital)

Correct ICD should be [Q79.0](https://www.icd10data.com/ICD10CM/Codes/Q00-Q99/Q65-Q79/Q79-/Q79.0)

**Comment by lschriml** [comment]
Thank you Jung Hoon Son for letting us know about this update !!

I've reviewed and updated the DO. 
The change will be available in next week's release.

Cheers,
Lynn

**Comment by plasmak11** [comment]
Thank you @lschriml  Hope to contribute more.
