### ISSUE TITLE
autoimmune arthritis terms

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#860]
reactive arthritis and rheumatoid arthritis should be children of  autoimmune disease of musculoskeletal system, as both are known to be autoimmune diseases. I believe that they used to reason this way in the past. Thanks

**Comment by beckyjackson** [comment]
I believe 'rheumatoid arthritis' is already fixed in the current edit file (just not released), as the edit file reasoned to have it under 'autoimmune disease of musculoskeletal system'

For 'reactive arthritis', we would just need to add this axiom:
```
'has phenotype' some 'Abnormal immunoglobulin level'
```

cc @lschriml

**Comment by lschriml** [comment]
done
