### ISSUE TITLE
trichothiodystrophy

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#873]
Currently DO has the terms:
photosensitive trichothiodystrophy (DOID:2960) - no definition, most xrefs go to generic 'trichothiodystrophy' except for the OMIM xref which is for photosensitive trichothiodystrophy 1
nonphotosensitive trichothiodystrophy (DOID:0050528) - definition and OMIM xref are specific for nonphotosensitive trichothiodystrophy 4

There are 5 other OMIM subtypes of trichothiodystrophy (OMIM:PS601675).
Orphanet lumps all of these under a single term ORDO:33364

Proposed plan

- add a new parent "trichothiodystrophy"

- change title of DOID:0050528 to nonphotosensitive trichothiodystrophy 4 to match the existing definition

- add new term nonphotosensitive trichothiodystrophy - add new terms under this for additional nonphotosensitive subtypes

- leave photosensitive trichothiodystrophy (DOID:2960) as is but add definition and fix xrefs

- add additional photosensitive subtypes under DOID:2960

This came up as part of the UniProt list

Does this sound okay to you @lschriml

**Comment by sbello** [comment]
commit on 6/8/20 implements these changes

**Comment by lschriml** [comment]
@sbello - OK with me.

Lynn
