### ISSUE TITLE
Linear skin defects with multiple congenital anomalies 

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#875]
OMIM has a 3 member series 'Linear skin defects with multiple congenital anomalies' one member is in DO (DOID:0111808) as a child of syndromic microphthalmia (DOID:0080636). The other 2 members are on the UniProt list.

The question I have is do I enter the OMIM series? If I do, do I change the asserted parent of the existing DO term to the new series parent? The other 2 members do not have microphthalmia so I can't place the new series term under this parent. In OMIM this entry (309801) is a member of both series.

Note Orphanet has a single entry ORPHA:2556 that has all 3 OMIM terms as xrefs but the description and synonyms go only with OMIM:309801

OMIM:309801 = DOID:0111808 has microphthalmia
OMIM:300952 - not in DO, no microphthalmia
OMIM:300887 - not in DO, no microphthalmia

**Comment by sbello** [comment]
Commit on 6/8 adds new terms and moves type 1 under new parent

**Comment by lschriml** [comment]
I would create a new syndrome term: 
Microphthalmia with Linear Skin Defects Syndrome
   synonym: MIDAS syndrome
 
[child terms]
  [1]    (DOID:0111808).  --  linear skin defects with multiple congenital anomalies 1
  [2]   OMIM:300952 - not in DO, no microphthalmia
  [3] OMIM:300887 - not in DO, no microphthalmia

Cheers,
Lynn




Notes:
Parent term in DO: 
syndromic microphthalmia  (DOID:0080636)
         GHR: Microphthalmia is an eye abnormality that arises before birth. In this condition, one 
                   or both eyeballs are abnormally small.
                   https://ghr.nlm.nih.gov/condition/microphthalmia
         [OMIM:309801] 

     (DOID:0111808).  --  linear skin defects with multiple congenital anomalies 1
            synonym: syndromic microphthalmia 7
             GHR: https://ghr.nlm.nih.gov/condition/microphthalmia-with-linear-skin-defects-
                     syndrome#genes

           Gene reviews: 
                 Microphthalmia with Linear Skin Defects Syndrome
                 - a disorder that mainly affects females. In people with this condition, one or both eyes may be very small or poorly developed (microphthalmia). Affected individuals also typically have unusual linear skin markings on the head and neck. These markings follow the paths along which cells migrate as the skin develops before birth

**Comment by sbello** [comment]
Given that 2 of the 3 subtypes do not have microphthalmia as a symptom I had put these in under the term name "linear skin defects with multiple congenital anomalies". I was hoping that adding a relation to microphthalmia as a symptom would allow for the type 1 entry to also be inferred to be a type of that disease. 

I think this is a case where the series was named for the most frequent type and the various resources have not yet all gotten in sync. 

The cases used to identify the COX7B associated mutation both have normal eye morphology (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3487127/)

In https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4385192/ they state  "Linear skin defects, which are present at birth, are the major clinical criteria of MLS syndrome."
Again the patients in this case have linear skin defects but lack microphthalmia 

MLS or Microphthalmia With Linear Skin Defects Syndrome in the papers seems to be used interchangeably to refer to either all 3 types or to mean just type 1.

I've not seen MIDAS used except for type 1.

I'm reluctant to use 'Microphthalmia With Linear Skin Defects Syndrome' as the primary term name as I think it will just add to the confusion. Similarly I'm uncomfortable with creating children of microphthalmia syndrome where the patients do not display microphthalmia.

I'll make the changes if that is what you want but wanted to make sure the situation was clear as the papers are confusing and muddled.
