### ISSUE TITLE
NTR: Burn-McKeown Syndrome

### ISSUE THREAD

**Issue by srengel** [DiseaseOntology/HumanDiseaseOntology#879]
Hi,
i'm looking for a DO term for Burn-McKeown Syndrome, but i'm not finding it.  

this is the paper i need this term for:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4259969/pdf/main.pdf

other helpful links?
https://www.omim.org/entry/608572
https://monarchinitiative.org/disease/MONDO:0012064
ORPHA:1200

**Comment by lschriml** [comment]
Hello Stacie,
  Thank you for the addition.
I have added the term to DO.

Cheers,
Lynn
