### ISSUE TITLE
New Term Request:Lymphedema, microcephaly and chorioretinopathy syndrome

### ISSUE THREAD

**Issue by obophenotype-user** [DiseaseOntology/HumanDiseaseOntology#88]
Hi,
I wanted to find out if this new term could be added to the ontology: Lymphedema, microcephaly and chorioretinopathy syndrome
(MeSH:C1835265). There are also what appear to be child terms such as: Microcephaly and chorioretinopathy, autosomal recessive, 1 (MIM:251270), Microcephaly and chorioretinopathy, autosomal recessive, 2 (MIM:616171) and Microcephaly and chorioretinopathy, autosomal recessive, 3 (MIM:616335).

Would this be mapped to microcephaly and retinal disease separately?
publications: PMID: 5936364, 25817018

Thanks

Sridhar

Reported by: sramacha

Original Ticket: [diseaseontology/feature-requests/88](https://sourceforge.net/p/diseaseontology/feature-requests/88)

**Comment by lschriml** [comment]
The three new terms have been added to DO. 
Lynn
