### ISSUE TITLE
NTR: Winchester Syndrome

### ISSUE THREAD

**Issue by LeylaR** [DiseaseOntology/HumanDiseaseOntology#880]
I'd like to request a DO term for Winchester Syndrome.

Publication:
https://pubmed.ncbi.nlm.nih.gov/29741626/
OMIM entry:
https://omim.org/entry/277950
Monarch entry:
https://monarchinitiative.org/disease/MONDO:0010201

Thank you

**Comment by lschriml** [comment]
Thank you for submitting this term.
I have reviewed and added to the DO.

Much appreciated,
Lynn
