### ISSUE TITLE
review parentage for DOID:9562

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#881]
It is:

id: DOID:9562
name: primary ciliary dyskinesia
is_a: DOID:0060340 ! ciliopathy
is_a: DOID:0080012 ! X-linked recessive disease

However, according to https://www.omim.org/phenotypicSeries/PS244400, most variants of primary ciliary dyskinesia have autosomal recessive inheritance, not X-linked. Please review.

**Comment by sbello** [comment]
This was coming from an incorrect subclass axiom. I've removed it. Thanks for pointing this out.
