### ISSUE TITLE
extraosseous Ewing sarcoma DOID:4232 is a child of bone tummor

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#882]
Looks like only Ewing sarcoma of bone  DOID:3368  should be a child of bone sarcoma.
While extraosseous Ewing sarcoma DOID:4232  maybe should be a child of  nervous system cancer DOID:3093 or just a sarcoma.

**Comment by lschriml** [comment]
Looking at Ewing sarcoma: 
     'Ewing sarcoma of bone' is_a 'Ewing sarcoma', which is_a 'bone sarcoma'
-- since Ewing sarcoma occurs in both bone and soft tissue 
and
   extraosseous Ewing sarcoma -- occurs outside of the bone 
         originating in soft tissue 


--> since Ewing sarcoma is either bone or soft tissue
   I will move it's parentage to 'connective tissue cancer' 
       and use axioms to have 'Ewing sarcoma of bone' also have a 'bone sarcoma' parent

Cheers,
Lynn
