### ISSUE TITLE
thrombophilia

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#883]
OMIM has a series 'thrombophilia' with 12 members. Two of these are in DO as children of 'inherited blood coagulation disease' and 2 as xrefs to 'thrombophilia' (DOID:2452) which is a sibling of 'inherited blood coagulation disease'. Two of the other 8 members are on the Uniprot list. I'm going to add the series and split the two off of thrombophilia.

My question is what is the best parent? I'm inclined to add a new parent 'inherited thrombophilia' so that I can capture the OMIM PS ID but then I still need a parent for this. If I make the asserted parent 'thrombophilia' is it possible for us to infer the parent 'inherited blood coagulation disease'?

Also note thrombophilia and its existing child terms lack definitions.

**Comment by lschriml** [comment]
thrombophilia  OMIM:PS188050  [DOID:2452] 
     --> updated 
 -- I reorganized the branch, merged some redundant old terms.
Should be all set for adding additional child OMIM terms.

Cheers,
Lynn

**Comment by sbello** [comment]
Thanks Lynn!
I've got the new terms on the MGI spreadsheet I'll update the parents and these will go in the next time I do a ROBOT run.
Sue

**Comment by sbello** [comment]
Latest commit (MGI Adds 7/9/20) has the new children for thrombophilia
