### ISSUE TITLE
New Term Request: infantile liver failure syndrome type 1 (ILFS1)

### ISSUE THREAD

**Issue by LeylaR** [DiseaseOntology/HumanDiseaseOntology#884]
I would like to request a new DO term for "infantile liver failure syndrome type 1 (ILFS1)", a type of infantile hepatopathy.

This publication describes a possible ILFS1 model in zebrafish:
https://pubmed.ncbi.nlm.nih.gov/30262142/
Additional publication that describes the syndrome:
https://pubmed.ncbi.nlm.nih.gov/22607940/

OMIM:  https://omim.org/entry/615438

Thank you

**Comment by lschriml** [comment]
Added to DO. 

Cheers,
Lynn
