### ISSUE TITLE
NTR: Epileptic encephalopathy, early infantile-82 OMIM#618721

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#885]
EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 82 

Synonym: GLUTAMATE OXALOACETATE TRANSAMINASE, MITOCHONDRIAL, DEFICIENCY OF GOT2, EIEE82,Malate-Aspartate Shuttle-Related Encephalopathy
is_a:early infantile epileptic encephalopathy(DOID:0050709)
https://omim.org/entry/618721
PMID:31422819

**Comment by cerivs** [comment]
Is there any info I can provide to help get this term request added to the DO?

**Comment by lschriml** [comment]
Apologies for the delay.
The term has been added to the DO.
Cheers,
Lynn
