### ISSUE TITLE
obsolete DOID:0111810

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#887]
OMIM has obsoleted syndromic microphthalmia 4 and merged this into syndromic microphthalmia 1. Looking at the OMIM record this appears to be based on https://pubmed.ncbi.nlm.nih.gov/30842225/

The entry for 4 had only a genomic region (no associated gene) and this region overlapped that of type 1.

The reference above resequenced the family used to establish type 4 and found a mutation in NAA10 which is the same gene as for type 1.

I suggest we obsolete syndromic microphthalmia 4.

**Comment by lschriml** [comment]
merged DO terms, obsoleted OMIM ID

**Comment by sbello** [comment]
Thanks Lynn!
