### ISSUE TITLE
Hereditary Alpha Tryptasemia: new syndrome for inclusion in DO

### ISSUE THREAD

**Issue by Xenbase2** [DiseaseOntology/HumanDiseaseOntology#888]
A new Disease, and potentially a new branch of diseases for your consideration.

Hereditary Alpha Tryptasemia, a disease caused by duplications of the TPSAB1 gene in humans.

I think it would be “is_a syndrome’’ due to symptoms across multiple systems, but could also be a branch of disease caused by gene duplications, perhaps.

Reference: Lyons, JJ Hereditary Alpha Tryptasemia: Genotyping and Associated Clinical Features.
Immunology and Allergy Clinics of North America, 08 Jun 2018, 38(3):483-495
DOI: 10.1016/j.iac.2018.04.003 PMID: 30007465 PMCID: PMC6411063

**Comment by lschriml** [comment]
Thank you for sending the term request. 
The reference is very helpful. 
We will review and update the DO.

Cheers,
Lynn

**Comment by lschriml** [comment]
I have created the new term.

Cheers,
Lynn

**Comment by Xenbase2** [comment]
Thank you!
