### ISSUE TITLE
obsolete DOID:0070190

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#889]
The only reference support for autosomal dominant chronic granulomatous disease (DOID:0070190) was OMIM:138990. OMIM has obsoleted this entry and merged it with OMIM:306400 - X-linked chronic granulomatous disease (DOID:0070195)

I suggest we obsolete DOID:0070190.

Thanks,
Sue

**Comment by lschriml** [comment]
agreed, done
