### ISSUE TITLE
typo in definition for dyskeratosis congenita, autosomal recessive 1

### ISSUE THREAD

**Issue by nicolevasilevsky** [DiseaseOntology/HumanDiseaseOntology#891]
For the term: DOID:0070015 dyskeratosis congenita, autosomal recessive 1

The text def is:
A dyskeratosis congenita that has_material_basis_in an autosomal dominant mutation of NOLA3 on chromosome 15q14.

I believe it should be:
A dyskeratosis congenita that has_material_basis_in an autosomal _recessive_ mutation of NOLA3 on chromosome 15q14.

**Comment by lschriml** [comment]
Thank you Nicole, I fixed the definition. Yes, this was a typo.

Much appreciated !!
Lynn
