### ISSUE TITLE
epidermolysis bullosa acquisita parent

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#895]
epidermolysis bullosa acquisita is reasoning as a child of autoimmune disease instead of as a child of autoimmune disease of skin and connective tissue. can you look into it? 
Thanks

**Comment by lschriml** [comment]
fixed with updated axiom:

(('has phenotype' some 'Abnormal immunoglobulin level') and ('located in' some ('zone of skin'
     and 'connective tissue')))
