### ISSUE TITLE
type 1 diabetes mellitus parent

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#897]
type 1 diabetes mellitus is reasoning as a child of  autoimmune disease instead of as a child of autoimmune disease of endocrine system. is it something strange in our owl file?
Thanks,
Randi

**Comment by lschriml** [comment]
updated, added the anatomy term to the axiom:

(('has phenotype' some 'Abnormal immunoglobulin level') and ('located in' some 'endocrine system'))

**Comment by rvita** [comment]
thank you so much!
