### ISSUE TITLE
allergic rhinitis

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#899]
allergic rhinitis is reasoning as a allergic hypersensitivity disease instead of as a respiratory allergy
Thanks

**Comment by lschriml** [comment]
with the SubClassOf axiom, has_symptom some 'allergic reaction' 
    allergic rhinitis reasons to be an 'allergic disease'  DOID:1205
         --> the name of this term was updated from 'allergic hypersensitivity disease'

**Comment by rvita** [comment]
Yes, sorry by allergic hypersensitivity disease, I do mean 'allergic disease' DOID:1205, but allergic rhinitis should still be reasoning as a child of respiratory allergy DOID:0060496 instead
--

**Comment by lschriml** [comment]
Updated. 
Has to make an EQ for respiratory allergy. 

Cheers,
Lynn
