### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by cmpich** [DiseaseOntology/HumanDiseaseOntology#903]
When you switched over from using master as a branch name to main the master branch is still available and caused issues at ZFIN as that branch is not any longer maintained. It would be better to remove that branch so that it becomes obvious that if I am still using the old branch that I have to look for a new URL locator.

**Comment by lschriml** [comment]
Apologies Christian.
Thank you for the suggestion.

Cheers,
Lynn

**Comment by beckyjackson** [comment]
This is taken care of. The `master` branch has been deleted as per the instructions here: https://jarv.is/notes/github-rename-master/
