### ISSUE TITLE
Update exact SKOS matches

### ISSUE THREAD

**Issue by beckyjackson** [DiseaseOntology/HumanDiseaseOntology#906]
All SKOS exact matches should be represented as `skos:exactMatch [CURIE]` annotation properties.

Just making a ticket so I don't lose track of it 🙂

**Comment by lschriml** [comment]
Hello @beckyjackson - checking in on the status of this update.
  To see if we can make these changes for a release next week.

Cheers,
Lynn

**Comment by beckyjackson** [comment]
Hi Lynn! Sorry I haven't had a chance to write the script yet. I'll be able to get this done on Friday 🙂

**Comment by lschriml** [comment]
Super !!  Thank you !!

**Comment by beckyjackson** [comment]
This is completed.

**Comment by lschriml** [comment]
Super !! 
Thank you !!
