### ISSUE TITLE
review craniometaphyseal dysplasia DOID:0080033

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#907]
DOID:0080033 contains xrefs OMIM:122860, OMIM:123000, OMIM:218400, OMIM:614099, OMIM:614378, but its definition and inheritance (autosomal dominant) match only OMIM:123000. Also term name does not match the definition and inheritance (OMIM:218400, OMIM:614099, OMIM:614378 are autosomal recessive).

Thank you

**Comment by lschriml** [comment]
Thank you Marek  
Notes below, all updates completed, will be in public in next week's release.

   This is a term that has been split at OMIM.
I have updated the Disease Ontology with the subtypes and their OMIM IDs.

[DOID:0080033] craniometaphyseal dysplasia
   xref: ORPHA:1522
https://medlineplus.gov/genetics/condition/cranioectodermal-dysplasia/
https://www.ncbi.nlm.nih.gov/books/NBK154653/
 

Craniometaphyseal dysplasia - PS123000
         Craniometaphyseal dysplasia.  (autosomal dominant) OMIM:123000
          Craniometaphyseal dysplasia, autosomal recessive. OMIM:218400


--> keep Sensenbrenner syndrome (and rename to cranioectodermal dysplasia) as a syndrome

Sensenbrenner syndrome  [DOID:0050577] [is_a syndrome]
     has synonym: cranioectodermal dysplasia
      with xrefs: OMIM:218330 and  OMIM:613610

  --> add in subtypes

In OMIM: 
Cranioectodermal dysplasia - PS218330
      OMIM:614099        cranioectodermal dysplasia-3 
     OMIM:614378        cranioectodermal dysplasia-4. (autosomal recessive inheritance)

    OMIM:218330.       cranioectodermal dysplasia-1   (autosomal recessive inheritance)
    OMIM:613610        cranioectodermal dysplasia-2.  (autosomal recessive inheritance)


Craniodiaphyseal dysplasia 
 is a severe bone dysplasia characterized by massive generalized hyperostosis and sclerosis, especially involving the skull and facial bones.

DOID:0080032   craniodiaphyseal dysplasia  
       OMIM:218300
--> adding subtype: 
     OMIM:122860     autosomal dominant **craniodiaphyseal** dysplasia

Cheers,
Lynn
