### ISSUE TITLE
new term request: human cytomegalovirus

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#908]
We are requesting the term human cytomegalovirus
as a child of viral infectious disease 
with the definition of: A viral infectious disease that   has_material_basis_in Human betaherpesvirus 5 
synonyms: Human betaherpesvirus 5, CMV, HCMV
Xref: PMID: 25205255
This terms refers specifically to NCBI:txid10359 Human betaherpesvirus 5

**Comment by lschriml** [comment]
added to DO
