### ISSUE TITLE
new term request: congenital disease of the urogenital tract

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#912]
congenital disease of the urogenital tract needed as parent term for renal agenesis DOID:14766 and child of congenital disease. Request is for clinical RedCap intake forms, which use this term to cover a variety of conditions, such as cystic kidneys, renal agenesis, and congenital renal dysplasia.
--

**Comment by lschriml** [comment]
Thank you Randi, I will take a look.

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Randi,
 Is it possible for the RedCap forms to have them be more specific for the disease terms ? 
Creating disease bins (e.g. congenital disease of the urogenital tract) that are not diseases 
 is not an ideal way to classify disease, will lead to odd reasoning. 
  As the DO has refined disease classification, we have intentionally removed these types of bins, in favor of 
more precise classifications. 
 Could this type of compound binning term be annotated with a combination of terms, e.g. physical disorder (for congenital disease). Urogenital combines the reproductive system (reproductive system disease) and urinary system disease?

Cheers,
Lynn

**Comment by rvita** [comment]
Yes, we can do a combination of terms & did that for several others, so it will also work for us here. We do not have control over what terms are in the RedCap forms, they are proprietary. We are just trying to find the best ontology fit for wat we have. But are you saying that all physical disorders are congenital? Thanks

**Comment by lschriml** [comment]
yes:  But are you saying that all physical disorders are congenital
