### ISSUE TITLE
neuroacanthocytosis

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#913]
Currently the DO term neuroacanthocytosis (DOID:0050765) specifies in the definition 'homozygous or compound heterozygous mutation in the VPS13A gene' but I have a new term that I would like to add that involves mutation in XK. The definition references the OMIM entry for the current child term choreaacanthocytosis and the NORD site. The NORD entry lists multiple subtypes including the one I want to add.

I think the gene association was added by mistake. I would like to remove this from the definition but wanted to check with you first (@lschriml ) as this is close to the line of changing the meaning of the term and possibly it would be more appropriate to obsolete the existing term and replace it with a new version. The new version would have the same label but be defined without specifying any gene.

**Comment by lschriml** [comment]
I have updated the definition of neuroacanthocytosis. Added the Orphanet ID xref. 
The reference to OMIM was also removed. 

Cheers,
Lynn
