### ISSUE TITLE
term request: disease of the urogenital system

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#921]
There are existing DO terms that are located in 'urogenital system' like  'urogenital tuberculosis' and 'autoimmune disease of urogenital tract', but there is no term for 'disease of the urogenital system', which is needed to create the redcap term 'congenital   urogenital anomaly' via a combination of 'physical disorder' and 'disease of the urogenital system'
thanks
--

**Comment by lschriml** [comment]
Hello Randi,
    DO does not have a 'disease of the urogenital system', as it does not represent a single system, but does represent the combination of two distinct system,  in DO we represent the two systems seperately-  'urinary system disease' and 'reproductive system disease'.

Can you represent: 'congenital urogenital anomaly' 
  via a combination of 'physical disorder' and  ('urinary system disease' and 'reproductive system disease') ??

Cheers,
Lynn
