### ISSUE TITLE
Question regarding parentage of 'lung adenocarcinoma'

### ISSUE THREAD

**Issue by sepatterson** [DiseaseOntology/HumanDiseaseOntology#922]
I'm wondering if 'lung adenocarcinoma' (DOID:3910) should be a child of 'lung non-small cell carcinoma' (DOID:3908) rather than a direct child of 'lung cancer' (DOID:1324)?

**Comment by lschriml** [comment]
Hello Sara,
 agreed, I've made the update.
Much appreciated !!
Cheers,
Lynn

**Comment by sepatterson** [comment]
That's great. Thanks Lynn!
