### ISSUE TITLE
Syntax Error in the New Release

### ISSUE THREAD

**Issue by shana-p** [DiseaseOntology/HumanDiseaseOntology#924]
There seems to be a syntax error in the new release. When parsing the HumanDO.obo file (as well as doid.obo) with pronto:
`disease_ontology = Ontology('https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/main/src/ontology/releases/2020-12-21/doid.obo')`
I get the following error:
File "https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/main/src/ontology/releases/2020-12-21/doid.obo", line 145284
    namespace: A hypereosinophilic syndrome that is characterized by subacute onset of myalgias and peripheral eosinophilia, followed by chronic neuropathy and skin induration. {xref="url:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3848710/", xref="url:https://rarediseases.org/rare-diseases/eosinophilia-myalgia-syndrome/"}␊
                 ^
SyntaxError: expected EOL

Likely caused by the curly brackets around the xref rather than square brackets.

**Comment by lschriml** [comment]
Shana, 
 Thank you for pointing out this error.
This DOID had two has_obo_namespace annotations.

Fixed now.
Much appreciated.
Happy Holidays.

Cheers,
Lynn
