### ISSUE TITLE
DOID:5426: xref to Orphanet class that doesn't exist

### ISSUE THREAD

**Issue by nicolevasilevsky** [DiseaseOntology/HumanDiseaseOntology#926]
https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_5426

DOID:5426 premature ovarian failure has an xref to ORDO:619 but this class does not appear to exist in Orphanet.

Related to: 
https://github.com/monarch-initiative/mondo/issues/2552

**Comment by lschriml** [comment]
Hello Nicole,
   Thanks for letting us know about this issue !!
We greatly appreciated working together to improve our ontologies.

I had a look at Orphanet.
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=619
I see that for this DO term, the term name has been updated in Orphanet to 
Primary ovarian failure. 
The Orphanet xref is associated with this DOID. 

Looking at this term, I see that it needs to be split into the OMIM subtypes.
OMIM is calling this disease: Premature ovarian failure 

OMIM: Phenotypic series: OMIM:PS311360

Looking at GHR, the name of this disease is now: primary ovarian insufficiency
https://medlineplus.gov/genetics/condition/fragile-x-associated-primary-ovarian-insufficiency/#synonyms


References:
https://pubmed.ncbi.nlm.nih.gov/27861765/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7477642/
 Note: In this 2020 paper (Recent advances in understanding primary ovarian insufficiency)
           Table 1 lists the various causes of primary ovarian insufficiency (genetic, autoimmune, infectious and environmental)

For the classification of this disease, I will update the DO to be: 

parent term:     primary ovarian insufficiency 
                          synonyms: primary ovarian failure, premature ovarian failure
                              OMIM:PS311360
                              Orphanet:619

       [subtypes]
                                 OMIM name                                                GHR name
                  
OMIM:311360   premature ovarian failure-1  --> Fragile X-associated primary ovarian insufficiency
                                                      GARD:4480    FMR1-related primary ovarian insufficiency

 & --> subtypes in OMIM:PS311360

Cheers,
Lynn
