### ISSUE TITLE
Likely error in DOID:0080315

### ISSUE THREAD

**Issue by asoket** [DiseaseOntology/HumanDiseaseOntology#927]
In DOID:0080315 (data-version: releases/2020-12-22/doid.obo) the 'synonym' text includes:
'synonym: "megalencephalic leukodystrophy\\megalencephaly-cystic leukodystorphy syndrome" EXACT []' 
The '\\' is causing a syntax error in Neo4j cypher command. I suppose it was intended to be forward slash instead of backslash.

When I made the following changes, it worked successfully. 
'synonym: "megalencephalic leukodystrophy/megalencephaly-cystic leukodystorphy syndrome" EXACT[]'
 
DOID details are:
date: 22:12:2020 16:14 downloaded from https://github.com/DiseaseOntology/HumanDiseaseOntology on 26th January 2021.

**Comment by lschriml** [comment]
Thank you for sharing this error !!
I have removed the \ from the synonym.

Much appreciated,
Lynn
