### ISSUE TITLE
Request to add doid to cancer slim file

### ISSUE THREAD

**Issue by jsaliba10** [DiseaseOntology/HumanDiseaseOntology#928]
DOID 2997 - Sertoli-Leydig cell tumor 

Please add the above DOID to the cancer slim file for curation in CIViC. Thank you.

**Comment by lschriml** [comment]
Hello Jason,
   I've added Sertoli-Leydig cell tumor to the DO cancer slim.
It will be in our release next week.

Cheers,
Lynn
