### ISSUE TITLE
add tubulinopathy

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#931]
Consider adding a term for 
tubulinopathy
def: 
A congenital nervous system abnormality characterized by complex cortical malformations including in most cases dysmorphic basal ganglia that has_material_basis_in mutation in one or more of the tubulin genes

Add loacted in relationship to cerebral cortex (UBERON:0000956)

references: 
https://pubmed.ncbi.nlm.nih.gov/24860126/
"Complex cortical malformations associated with mutations in tubulin genes: TUBA1A, TUBA8, TUBB2B, TUBB3, TUBB5 and TUBG1 commonly referred to as tubulinopathies" 
and 
"Systematic review of patients' neuroimaging and neuropathological data allowed us to distinguish at least five cortical malformation syndromes: (i) microlissencephaly (n = 12); (ii) lissencephaly (n = 19); (iii) central pachygyria and polymicrogyria-like cortical dysplasia (n = 24); (iv) generalized polymicrogyria-like cortical dysplasia (n = 6); and (v) a 'simplified' gyral pattern with area of focal polymicrogyria (n = 19)."

https://pubmed-ncbi-nlm-nih-gov/31386652/ - mouse models

https://www.ncbi.nlm.nih.gov/books/NBK350554/
"Clinical characteristics.
The tubulinopathies are a wide and overlapping range of brain malformations caused by mutation of one of seven genes encoding different isotypes of tubulin. Brain malformations include:
- A range of lissencephalies (classic lissencephaly, lissencephaly with cerebellar hypoplasia, lissencephaly with agenesis of the corpus callosum, and centrally predominant pachygyria),
-     Polymicrogyria-like cortical dysplasia,
-     Simplified gyral pattern, and
-     Microlissencephaly often in combination with dysplastic basal ganglia, corpus callosum abnormalities, and hypoplasia or dysplasia of the brain stem and cerebellum."

@lschriml as this isn't an OMIM related one I wanted to check before I add it to the ROBOT spreadsheet.

**Comment by lschriml** [comment]
Hello Sue,
   It looks like tubulinopathy is a parent of DOID:0050453 lissencephaly. 
and a child of 'congenital nervous system abnormality' DOID:249
And that lissencephaly needs to be split into OMIM subtypes for PS607432

Agreed, add this term to the ROBOT spreadsheet. 
Along with the lissencephaly subtypes.

Cheers,
Lynn

**Comment by sbello** [comment]
Adding this to my ROBOT template

**Comment by lschriml** [comment]
Sounds good. 
Thank you Sue !!
