### ISSUE TITLE
NTR: cerebellofaciodental syndrome (CFDS)

### ISSUE THREAD

**Issue by srengel** [DiseaseOntology/HumanDiseaseOntology#932]
New Term Request: cerebellofaciodental syndrome (CFDS)

Alternative titles; symbols: CEREBELLAR-FACIAL-DENTAL SYNDROME

references:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC5389939/
https://omim.org/entry/616202

**Comment by lschriml** [comment]
Hello Stacia,
  Thank you for the new term. 
Added to DO. DOID:0080898

**Comment by srengel** [comment]
awesome, thanks Lynn :)
