### ISSUE TITLE
Typo in NARP syndrome cross-references

### ISSUE THREAD

**Issue by jsstevenson** [DiseaseOntology/HumanDiseaseOntology#934]
Hello,

It looks like the database cross-references to Orphanet and GARD for the "NARP syndrome" entry have been concatenated as "ORDO:644:GARD:262".

See http://purl.obolibrary.org/obo/DOID_0111273

Thanks!

**Comment by lschriml** [comment]
Hello James,
 thank you for pointing out this error.
I've updated the DO to fix this. 

Much appreciated,
Lynn
