### ISSUE TITLE
synonym request: Uner Tan syndrome

### ISSUE THREAD

**Issue by srengel** [DiseaseOntology/HumanDiseaseOntology#937]
can we please add synonym 'Uner Tan syndrome' to DOID:0050997 cerebellar ataxia, mental retardation and dysequlibrium syndrome?

ref: https://pubmed.ncbi.nlm.nih.gov/28013290/

from the intro: "Uner Tan syndrome (also known as Cerebellar Ataxia, Mental Retardation, And Dysequilibrium Syndrome, CAMRQ) is a collection of recessive single gene disorders, in which affected individuals show quadrupedalism, mental retardation and cerebellar developmental defects (26–29). To date, mutations in VLDLR, WDR81, CA8 and ATP8A2 have been described as causative in this disease (26–29).
Here we report the discovery of a homozygous TUBB2B variant that segregates with a familial case of Uner Tan syndrome (UTS) with cerebellar hypoplasia."

**Comment by lschriml** [comment]
Hello Stacie,
  added.
Cheers,
Lynn
