### ISSUE TITLE
difference between cranial nerve palsy and cranial nerve disease?

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#938]
The definition of cranial nerve palsy is not given, therefore, there is no differentiation with cranial nerve disease.
Both of which are mapped to the MESH D003389 (Cranial Nerve Diseases)
Please provide the updated definition of the cranial nerve palsy.

**Comment by lschriml** [comment]
Thank you for the update request.
the MESH IDs was removed from cranial nerve palsy.
These are two distinct terms, definition added to cranial nerve palsy.

Cheers,
Lynn
