### ISSUE TITLE
DOID:0060040 should map to MESH:D002659

### ISSUE THREAD

**Issue by linikujp** [DiseaseOntology/HumanDiseaseOntology#939]
Both are pervasive developmental disorder.

**Comment by lschriml** [comment]
Thank you for the term updates !! 
I have added the MESH term. 

For DOID:0060040, pervasive developmental disorder, 

https://www.ninds.nih.gov/Disorders/All-Disorders/Pervasive-Developmental-Disorders-Information-Page

The diagnostic category of **pervasive developmental disorder**s (PDD) refers to a group of disorders characterized by delays in the development of socialization and communication skills. Parents may note symptoms as early as infancy, although the typical age of onset is before 3 years of age. Symptoms may include problems with using and understanding language; difficulty relating to people, objects, and events; unusual play with toys and other objects; difficulty with changes in routine or familiar surroundings, and repetitive body movements or behavior patterns. 
**Autism** (a developmental brain disorder characterized by impaired social interaction and communication skills, and a limited range of activities and interests) is the most characteristic and best studied PDD. 
**Other types of PDD include** Asperger's Syndrome, Childhood Disintegrative Disorder, and Rett's Syndrome. 
**Children with PDD** vary widely in abilities, intelligence, and behaviors. Some children do not speak at all, others speak in limited phrases or conversations, and some have relatively normal language development. Repetitive play skills and limited social skills are generally evident. Unusual responses to sensory information, such as loud noises and lights, are also common.


MESH:D002659
Child Development Disorders, Pervasive
Severe distortions in the development of many basic psychological functions that are not normal for any stage in development. These distortions are manifested in sustained social impairment, speech abnormalities, and peculiar motor movements.

Cheers,
Lynn
