### ISSUE TITLE
NTR: non-obstructive coronary artery disease

### ISSUE THREAD

**Issue by bonitalam** [DiseaseOntology/HumanDiseaseOntology#944]
Hello, the ENCODE project has a request for a term to be made for "nonobstructive coronary artery disease" (subclass of "coronary artery disease" DOID:3393).

**Definition:** Nonobstructive coronary artery disease (CAD) is atherosclerotic plaque that would not be expected to obstruct blood flow or result in anginal symptoms. (PMID:25369489)

Thank you for your help!

**Comment by lschriml** [comment]
Hello Bonita,
   Thank you for the term request.
I have added the new term to the DO, DOID:0080938

The new term will be available in our next release.

Cheers,
Lynn

**Comment by bonitalam** [comment]
Great, thank you so much Lynn!
