### ISSUE TITLE
has material basis in

### ISSUE THREAD

**Issue by alanruttenberg** [DiseaseOntology/HumanDiseaseOntology#945]
The use of 'has material basis in' in actinomycosis is problematic. There are 7 uses of the term relating to different bacteria. The problem is that they are a conjunction. It isn't the case that every instance of the disease has material basis in _all_ of these at the same time. Rather it is the case that the disease has a basis in (at least) _one_ of them. So, the superclass expression should be of the form 
>'has material basis in' some ( 'Actinomyces gerencseriae' or 'Actinomyces israelii' or ... )

There are many disease terms that follow the same pattern and so have the same issue.

**Comment by lschriml** [comment]
Thank you @alanruttenberg for pointing out this issue. 
Agreed, this needs to be updated. 

I have gone through the virus, bacteria and fungal branches and updated the axioms with 'or' as needed. 
Much appreciated !!

Cheers,
Lynn
