### ISSUE TITLE
MedDRA to DOID cross-references

### ISSUE THREAD

**Issue by ireneisdoomed** [DiseaseOntology/HumanDiseaseOntology#947]
Hi,

from an analysis of FAERS data, we have obtained a list of 11 MedDRA to DOID mappings that we believe have a very high level of confidence:
```
+----------+---------------------+-----+--------------------------+-------------------------------+
|efoId     |efoName              |score|traitId                   |traitName                      |
+----------+---------------------+-----+--------------------------+-------------------------------+
|DOID_10718|giardiasis           |0.999|10018261                  |Giardia lamblia infection      |
|DOID_7551 |gonorrhea            |1.0  |10018610-10018611-10018604|Gonorrhea                      |
|DOID_10718|giardiasis           |1.0  |10018262                  |Giardiasis                     |
|DOID_1947 |trichomoniasis       |1.0  |10044620-10044623         |Trichomoniasis                 |
|DOID_1947 |trichomoniasis       |0.999|10044618                  |Trichomonas infections         |
|DOID_10718|giardiasis           |0.999|10018260                  |Giardia infections             |
|DOID_10718|giardiasis           |0.996|10064239                  |Lambliasis                     |
|DOID_7551 |gonorrhea            |0.996|10053842                  |Gianotti-Crosti syndrome       |
|DOID_7551 |gonorrhea            |0.999|10051970                  |Neisseria gonorrhoeae infection|
|DOID_10113|trypanosomiasis      |1.0  |10044710-10044707         |Trypanosomiasis                |
|DOID_13406|pulmonary sarcoidosis|1.0  |10037430                  |Pulmonary sarcoidosis          |
+----------+---------------------+-----+--------------------------+-------------------------------+
```
[meddra-doid-xref-0995-1.json.zip](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/6585922/meddra-doid-xref-0995-1.json.zip)

This is part of an emerging pipeline we are working on to integrate the different methods of automatic disease mapping into a single tool. 
The algorithm performs very well as long as it is already captured in the ontology.

Could you please examine the mappings and consider how best to include this annotation in the ontology? The SPOT team has already imported the MedDRA xrefs whose labels match an EFO/Orphanet term and are now in the process of curating the ones of less confidence. Both EFO and Open Targets would benefit a lot if you could include them similarly.

Any feedback or comments is much appreciated.

Thanks!

**Comment by lschriml** [comment]
I have added: 

giardiasis.              MEDDRA:0017536
gonorrhea             MEDDRA:10018604
trichomoniasis      MEDDRA:10044620
trypanosomiasis.  MEDDRA:10044707
pulmonary sarcoidosis     MEDDRA:10037430

Cheers,
Lynn

**Comment by ireneisdoomed** [comment]
Hi Lynn, thank you so much for checking these out!

There's a 1 to many relationship between DOID and MedDRA and this is not captured. Is the ontology constrained to having only one cross-reference to MedDRA?

**Comment by lschriml** [comment]
We can include multiple MedDRA IDs.

**Comment by linikujp** [comment]
Why do you have multiple IDs for a MedDRA term. For example :
|10018610-10018611-10018604|Gonorrhea

Also, please clarify if you are mapping PT terms only or you include other
terms as well.

Thanks,
Asiyah

**Comment by ireneisdoomed** [comment]
Hi @linikujp! Sorry for the delayed answer. We are working with a specific version of the MedDRA dictionary and as far as I understand, these 3 terms all refer to the disease Gonorrhea, which is what the column `traitName` refers to.

Given this, all three terms are mapped to the same EFO ID.

And regarding your other question, we are not restricting ourselves to a specific therapeutic area.

Many thanks!
