### ISSUE TITLE
mistake in DOID:0060350 adenine phosphoribosyltransferase deficiency?

### ISSUE THREAD

**Issue by deustp01** [DiseaseOntology/HumanDiseaseOntology#948]
The term has DOID:9252 amino acid metabolic disorder as its parent. I believe that's not true. It's a defect of purine (adenine) salvage, which makes it a  child of DOID:653 purine-pyrimidine metabolic disorder, a sibling of DOID:1919 Lesch-Nyhan syndrome. It is also a genetic disorder. All known cases show an autosomal recessive mode of inheritance, associated with loss of function mutations in the [APRT gene located on human chromosome 16](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:626). See PMID:8864750 and PMID:22700886.
Thanks
Peter D'E-

**Comment by lschriml** [comment]
Thank you Peter !!
I have made the updates, as suggested.

Cheers,
Lynn
