### ISSUE TITLE
Term requests: Ryanodine receptor-1 (RYR1) related disease terms

### ISSUE THREAD

**Issue by rankishore** [DiseaseOntology/HumanDiseaseOntology#949]
I can't seem to find any of the specific diseases that the ryanodine receptor (RYR1) is implicated in--
King-Denborough syndrome
rhabdomyolysis-myalgia syndrome
malignant hyperthermia (MH)
Minicore myopathy with external ophthalmoplegia

Central core disease is present but makes no mention of RYR1 in the definition, could be added.

References:
https://omim.org/entry/180901
PMID: 30406384

**Comment by lschriml** [comment]
Thank you for these term requests !!

**malignant hyperthermia** (DOID:8545)
OMIM:145600
--> added to definition: heterozygous mutation in the ryanodine receptor gene (RYR1) on chromosome 19q13.

**Central core disease**
     --> definition updated 

new terms: 
 **King-Denborough syndrome** (OMIM 145600)
--> added to DO
 

Minicore myopathy with external ophthalmoplegia
    OMIM:255320
  --> added to DO as:  **multiminocore disease**  

**rhabdomyolysis-myalgia syndrome**
https://pubmed.ncbi.nlm.nih.gov/30406384/

RYR1 rhabdomyolysis-myalgia syndrome
-- added to DO

Cheers,
Lynn
