### ISSUE TITLE
Add obofoundry topic to repo metadata

### ISSUE THREAD

**Issue by cthoyt** [DiseaseOntology/HumanDiseaseOntology#950]
The OBO Foundry has recently created a topics page at https://github.com/topics/obofoundry. It would be great if you could add the `obofoundry` topic to your repository, since it's currently listed as active in the OBO Foundry. If you're not sure how to do that, follow the instructions [here](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics).   The main issue for this task is at https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1538 in case you want some more context or to join the larger discussion.

**Comment by lschriml** [comment]
added
