### ISSUE TITLE
Ontology symptoms and it's updates for DIOD 

### ISSUE THREAD

**Issue by singhsaurabhaiims** [DiseaseOntology/HumanDiseaseOntology#952]
Hello, 
I am working on the ontology to get related information of the selected diseases to show in the python modules using owlready2. I am currently facing the following problems. 
1.> I can access the only subclass defined in the ontology from owl files but I require to read the definition, has_exact_synonm, and database_cross_reference in the python module. 
2.> I have updated the list of symptoms in some of the diseases on my local but I am not getting the updated list in my module when I am giving my local repository call for the load.
```
from owlready2 import *
onto_path.append("/Users/saurabhsingh/Desktop/workspace/spotcheck/HumanDiseaseOntology/src/ontology/doid-merged.owl")
onto = get_ontology("/Users/saurabhsingh/Desktop/workspace/spotcheck/HumanDiseaseOntology/src/ontology/doid-merged.owl")
onto.load()
```
Output
`get_ontology("http://purl.obolibrary.org/obo/doid/doid-merged.owl#")`
![image](https://user-images.githubusercontent.com/54199705/121648571-47f40d80-cab5-11eb-9347-8523d92c7103.png)

**Comment by lschriml** [comment]
Apologies for the delayed response. 

I'm not entirely sure what is needed to resolve your issue.
Can you provide specific examples ? 

Thank you,
Lynn

**Comment by allenbaron** [comment]
It looks like the local OWL file isn't being loaded properly. See https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/972#issuecomment-1004389156 or Owlready2's documentation on [Loading an ontology from OWL files](https://owlready2.readthedocs.io/en/v0.35/onto.html#loading-an-ontology-from-owl-files).

**Comment by allenbaron** [comment]
Closing this stale issue because there was no reply from the original poster.

Feel free to re-open this or another ticket if you still need assistance or if you'd like to request we add synonyms.
