### ISSUE TITLE
Additional parents for DOID:5810 (adenosine deaminase deficiency)?

### ISSUE THREAD

**Issue by deustp01** [DiseaseOntology/HumanDiseaseOntology#953]
This is a defect in purine metabolism caused by mutations affecting  the function of a single enzyme encoded by an autosomal gene, so it could have all of the same metabolic-disease and genetic-disease parents as DOID:0060350 adenine phosphoribosyltransferase deficiency in addition to the ones it already has. E.g., PMID: 2166947 and PMID: 2783588.

**Comment by lschriml** [comment]
Thank you for submitting this ticket !!
We will update the parentage.

Cheers,
Lynn

**Comment by lschriml** [comment]
The parentage is updated.

Cheers,
Lynn
