### ISSUE TITLE
It looks like vegetable allergy and its subclasses are not marked as IEDB slim entries?

### ISSUE THREAD

**Issue by ddooley** [DiseaseOntology/HumanDiseaseOntology#955]
I downloaded the IEDB slim but found they were missing. I presume they are content appropriate for the slim.

Cheers,

Damion

**Comment by lschriml** [comment]
Hello Damion,
  yes, they are appropriate. 
I will check with IEDB (Randi Vita) as she coordinates terms for this slim.

Cheers,
Lynn

**Comment by lschriml** [comment]
Got approval from IEDB. 
Added the terms to the IEDB slim. 

Cheers,
Lynn
