### ISSUE TITLE
reopen #829

### ISSUE THREAD

**Issue by andredekker** [DiseaseOntology/HumanDiseaseOntology#958]
I would request to reopen this [issue ](https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/829). It is a given reality that a e.g. a prostate cancer can be located in the spine. It could even be that the prostate is no longer there (e.g. because it has been removed). By including the "located_in" axiom you assume that a prostate must be there which is not true. In my opinion you should change it to a property such as the NCI thesaurus which uses has_primary_site.

**Comment by lschriml** [comment]
Thank you Andre !! 
We have revised our relation term usage, and replaced 'located in' with 'disease has location' .

In DO, with anatomical locations, we aim to describe the primary site location. 

Cheers,
Lynn

**Comment by andredekker** [comment]
thanks, to check. If i want to assert that the prostate cancer had metastasized to the seminal vesicles, i would use the following triples?

:disease1 a doid:prostate_cancer
:disease1 ro:disease_has_location :location1
:location1 a uberon:seminal_vesicle

**Comment by lschriml** [comment]
Looks good to me.
Cheers,
Lynn
