### ISSUE TITLE
DLBCL update requests

### ISSUE THREAD

**Issue by kkrysiak** [DiseaseOntology/HumanDiseaseOntology#959]
Add synonym "DLBCL" for Diffuse Large B-cell Lymphoma (DOID:0080192)

Add new DLBCL subtype terms (From the [2016 WHO guidelines for lymphoid malignancies](https://pubmed.ncbi.nlm.nih.gov/26980727/)):
1) Diffuse Large B-Cell Lymphoma Activated B-Cell Type (synonym: DLBCL ABC Type)
- https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=21.05d&ns=ncit&code=C36081
2) Diffuse Large B-Cell Lymphoma Germinal Center B-Cell Type
- https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=21.05d&ns=ncit&code=C36080

**Comment by rdmorin** [comment]
Thanks for suggesting this one. To complicate things, this revision also has a group that is defined by the presence of two or more oncogene translocations. High-grade B-cell lymphoma double-hit/triple-hit. It isn't a direct subset of DLBCL, though, and can include cases with other morphology. Any thoughts on how those could also be incorporated?

**Comment by lschriml** [comment]
Thank you KK !!
I have updated Diffuse Large B-cell Lymphoma, and added the two new subtypes.

High-grade B-cell lymphoma double-hit/triple-hit
  --> KK : what do you think ? 
      How about as a child of B-cell lymphoma ? 

Cheers,
Lynn

**Comment by rdmorin** [comment]
Thanks for this addition, Lynn. 
With regards to HGBL-DH/TH, setting it up as a child of B-cell lymphoma makes sense to me.

**Comment by lschriml** [comment]
Done :)
