### ISSUE TITLE
inclusion body myopathy with Paget disease of bone and frontotemporal dementia, has siblings

### ISSUE THREAD

**Issue by obophenotype-user** [DiseaseOntology/HumanDiseaseOntology#96]
inclusion body myopathy with Paget disease of bone and frontotemporal dementia (DOID:0050881 and OMIM:167320) is part of OMIM phenotypic series PS167320 (Inclusion body myopathy/Paget disease/frontotemporal dementia).  The original member is now Inclusion body myopathy with early-onset Paget disease and frontotemporal dementia 1; additional phenotypic series members are Inclusion body myopathy with early-onset Paget disease with or without frontotemporal dementia 2 (OMIM:615422, caused by gene HNRNPA2B1) and Inclusion body myopathy wtih early-onset Paget disease without frontotemporal dementia 3 (OMIM:615424, caused by gene HNRNPA1). (I tripped over this phenotypic series as two of the three involved genes are also ALS genes).

Reported by: gramates

Original Ticket: [diseaseontology/feature-requests/96](https://sourceforge.net/p/diseaseontology/feature-requests/96)

**Comment by lschriml** [comment]
These OMIM IDs were added to the DO term.
