### ISSUE TITLE
Add synonym to DOID:0111799

### ISSUE THREAD

**Issue by ALHoyt** [DiseaseOntology/HumanDiseaseOntology#960]
OMIM entry for Microphthalia, syndromic 1 states it was formerly Microphthalia, syndromic 4 (https://omim.org/entry/309800). OMIM considers them to be the same but MESH does not, with separate IDs for Microphthalia, syndromic 1 (mesh:C537464)and Microphthalia, syndromic 4 (mesh:C564457). DOID has no Microphthalia, syndromic 4 under Microphthalia entry(DOID:0080636). DOID synonym needed to map Microphthalia, syndromic 4 to Microphthalia, syndromic 1 and MESH remapped.

**Comment by lschriml** [comment]
Thank you Amelia !! 
DOID:0080636 - syndromic microphthalmia 1 
  -- I have added the MESH term.

Cheers,
Lynn
