### ISSUE TITLE
Ectrodactyly-cleft lip-palate syndrome remapping needed

### ISSUE THREAD

**Issue by ALHoyt** [DiseaseOntology/HumanDiseaseOntology#961]
The Ectrodactyly-cleft lip-palate syndrome (DOID:0060782) has MESH ID (MESH:C536189). The two subtypes EEC1 (DOID:0060784) and EEC3 (DOID:0060783) also reference (MESH:C536189) instead of the more accurate (MESH:C565062) for EEC1 and (MESH:C565799) for EEC3. OMIM:129900 is the reference page for MESH:C536189 and lists EEC1 as a synonym, so OMIM doesn't have a header for Ectrodactyly-cleft lip-palate syndrome without referencing the 1 or 3 types.

**Comment by lschriml** [comment]
Thank you Amelia !!
I have updated the records.

Cheers,
Lynn
