### ISSUE TITLE
Additional parents for DOID:5813 (purine nucleotide phosphorylase deficiency)?

### ISSUE THREAD

**Issue by deustp01** [DiseaseOntology/HumanDiseaseOntology#964]
(Another ticket like #953 )
This is a defect in purine metabolism caused by mutations affecting the function of a single enzyme encoded by an autosomal gene, so it could have all of the same metabolic-disease and genetic-disease parents as DOID:0060350 adenine phosphoribosyltransferase deficiency in addition to the ones it already has. E.g., PMID: 3029074, PMID: 1384322)
Thanks

**Comment by lschriml** [comment]
Thank you Peter !! @deustp01 

I have added the additional parent, as an asserted parent. 
I don't see a direct way to create an inferred parent. 

I have added the two references. 

Much appreciated,
Lynn
