### ISSUE TITLE
MESH:C567738 may need splitting

### ISSUE THREAD

**Issue by ALHoyt** [DiseaseOntology/HumanDiseaseOntology#965]
MESH:C567738 is the entry for both hereditary sensory and autonomic neuropathy type 2 A and B when those subtypes have their own entries on DOID (HSAN2A DOID:0070155 and HSAN2B DOID:0070150) and in OMIM.

**Comment by lschriml** [comment]
Hereditary Sensory and Autonomic Neuropathies
     MESH:D009477
          --> added this MeSH term to DOID:0050548

       --> and removed this MeSH ID from the 'type 2' term

    MeSH is grouping all of the subtypes of this term under the one MeSH ID.
   OMIM and the DO have split these terms into subtypes. 

There are no other changes to be made until MeSH splits the subtypes.

Cheers,
Lynn
