### ISSUE TITLE
Reference in DOID:0060681 deleted

### ISSUE THREAD

**Issue by ALHoyt** [DiseaseOntology/HumanDiseaseOntology#966]
DOID:0060681 autosomal dominant nocturnal frontal lobe epilepsy OMIM reference OMIM:PS600513 is a deleted page.

**Comment by sbello** [comment]
Odd I see an active page on the OMIM site https://www.omim.org/phenotypicSeries/PS600513

**Comment by ALHoyt** [comment]
I just checked again, on OMIM the page is there I do not know why the link from the DOID page did not open

**Comment by sbello** [comment]
Possibly it is a temporary glitch? The link from the DO page is working for me (PC using Firefox).

**Comment by ALHoyt** [comment]
The link from DOID is https://omim.org/entry/PS600513 which is probably the issue. Is the Phenotypic series something we want to be cross-referenced rather than an entry?

We probably need to mint a new prefix for OMIM's phenotypic series that's different than standard OMIM entries. @cmungall and @cthoyt have a discussion going here https://github.com/bioregistry/bioregistry/issues/64

**Comment by sbello** [comment]
I'm guessing that the DO page (on the site and I know the MGI page does this) is doing something special with these as from the DO site the link is https://www.omim.org/phenotypicSeries/PS600513 not the standard OMIM link. But I see that on OLS it is using the standard OMIM entry link that fails as you described.

**Comment by cthoyt** [comment]
`mim.ps` has now been added to the Bioregistry and is live on the site at https://bioregistry.io/registry/mim.ps

**Comment by sbello** [comment]
Thanks! Closing this ticket now.

**Comment by cthoyt** [comment]
@sbello I don't think adding the entry in the Bioregistry for the prefix is enough - I've provided an actual fix for this entry (and all others with a similar problem) in #968

**Comment by sbello** [comment]
Making that change is going to break the handling of these IDs that has been done by DO, MGI and the Alliance.

**Comment by cthoyt** [comment]
Can you elaborate a bit? I think it's worth fixing this and would be happy to try and coordinate with MGI and the Alliance

**Comment by sbello** [comment]
I know this best for MGI, we have code that picks the OMIM:PS#### out of the file and uses the phenotypic series style link for these. If the xref was suddenly OMIMPS:PS### I'm fairly certain that the MGI loader would break or at least fail to load these as the OMIMPS: prefix is not on our list to load and if the loader did load these then the link code would fail as the prefix it is looking for would no longer be present.

**Comment by cthoyt** [comment]
Do you know where the code is? I could take a look and try to provide a fix. I'm curious how MGI is handling its prefix registry in general, as well

**Comment by sbello** [comment]
MGIs code maybe available on the mgijax github site (https://github.com/mgijax) but I'm not sure. The Alliance code may also be available from the AGR github (https://github.com/alliance-genome/agr_ui). I can check with the SEs tomorrow.

**Comment by cthoyt** [comment]
I just checked the whole JAX organization as well as the AGR repo for mentions of OMIM. I made 3 pull requests in relevant places in MGI:

- https://github.com/mgijax/vocload/pull/1
- https://github.com/mgijax/fewi/pull/1
- https://github.com/mgijax/fewi/pull/2

AGR had no processing code related to OMIMPS, but perhaps I can add something

**Comment by lschriml** [comment]
Hello Charles,
  Thank you for submitting this ticket and for the active discussion.
To clarify, the DO is not going to be changing the prefix we use for the OMIM phenotypic series. 

Cheers,
Lynn
