### ISSUE TITLE
Fix child relationships of DOID:0080143

### ISSUE THREAD

**Issue by ALHoyt** [DiseaseOntology/HumanDiseaseOntology#967]
DOID:0080143 The subtypes of congenital fibrosis of the extraocular muscles are not given child relationships and instead all of the OMIM entries of the subtypes are given in the database cross reference.

**Comment by sbello** [comment]
@lschriml I'll add this to the list of priority splits

**Comment by lschriml** [comment]
Thank you @sbello 
I have added the PS # 

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Amelia, @ALHoyt 
 the subtypes have been added and will be available in our September release later this week.
Cheers,
Lynn
