### ISSUE TITLE
DOID:3765 pseudohermaphroditism linked to parent MeSH identity

### ISSUE THREAD

**Issue by ALHoyt** [DiseaseOntology/HumanDiseaseOntology#969]
MESH:D012734 (Disorders of Sex development) is linked correctly to DOID:1923 (disorder of sex development) in the database cross reference, but DOID:3765 "pseudohermaphroditism" is incorrectly also given that reference.

**Comment by lschriml** [comment]
Thank you Amelia for these updates.

Looking at the DO, I see that MESH:D012734 is also linked to DOID:3763, hermaphroditism.

MeSH has 'lumped' these three terms under the one MeSH ID. 
When MeSH splits the terms, we will be able to update these mappings.

Cheers,
Lynn
