### ISSUE TITLE
DOID:2913 linked to parent MeSH identity

### ISSUE THREAD

**Issue by ALHoyt** [DiseaseOntology/HumanDiseaseOntology#970]
MeSH:D010195 "Pancreatitis" is listed as a reference to DOID:4989 "Pancreatitis" correctly but also to a DOID:4989 child term (DOID:2913 "acute pancreatitis") incorrectly. DOID:2913 should also be split into "acute necrotizing pancreatitis" (MeSH:D019283 ) and "acute hemmorrhagic pancreatitis" (MeSH:D000081032).

**Comment by lschriml** [comment]
Good afternoon Amelia,
  Thank you for your interest in the Human Disease Ontology.
We greatly appreciate your identifying how we can improve our data representation.

Regarding MESH:D010195, in MeSH, this ID is labelled 'pancreatitis' and include 'acute pancreatitis' as one of the entry terms (synonyms). As MESH includes both terms under the same ID, the DO has assigned both terms to the same MeSH ID.

Whereas, the NCI thesaurus, for example, has split the two terms.

I have added subtypes of 'acute pancreatitis': 
     'acute necrotizing pancreatitis' 
and 'acute hemorrhagic pancreatitis'.

Cheers,
Lynn
