### ISSUE TITLE
NTR:  INTELLECTUAL DEVELOPMENTAL DISORDER WITH CARDIAC ARRHYTHMIA OMIM

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#973]
OMIM: 617173 
Definition
Intellectual developmental disorder with cardiac arrhythmia is an autosomal recessive multisystem disorder characterized by delayed psychomotor development, severe intellectual disability with poor or absent speech, and bradycardia and/or cardiac sinus arrhythmias. Additional features include visual abnormalities, seizures, hypotonia, and gastric reflux.  

Is a: monogenic disease  DOID:0050177
Is a: heart conduction disease  DOID:10273
Is a:  syndromic intellectual disability DOID:0050888

**Comment by lschriml** [comment]
Added to the DO: DOID:0081008
