### ISSUE TITLE
LEUKOENCEPHALOPATHY, CYSTIC, WITHOUT MEGALENCEPHALY (NTR)

### ISSUE THREAD

**Issue by LeylaR** [DiseaseOntology/HumanDiseaseOntology#975]
Could you please add a term to the DO to represent "infantile-onset RNASET2 deficient cystic leukoencephalopathy"?
This condition is in OMIM as "LEUKOENCEPHALOPATHY, CYSTIC, WITHOUT MEGALENCEPHALY"
https://omim.org/entry/612951

Thank you
_______________________________________________
Details:

The OMIM entry references these human disease publications (PubMed ID):
11589166
19525954
15851732
9810556

Zebrafish models of RNASET2 deficiency (PubMed ID):
21199949
**32295832**
32212285

From **32295832**:
"We previously identified biallelic loss-of-function mutations in the
RNASET2 gene to cause an early-onset cystic leukoencephalopathy
in humans (Henneke et al., 2009). This disorder follows an autosomal
recessive inheritance and manifests as psychomotor delay, spasticity,
epilepsy and normo- or microcephaly during the first year of life.
Brain magnetic resonance imaging (MRI) reveals frontal and
temporal lobe cystic lesions, multifocal white matter alterations and
cerebral atrophy. In severe cases, clinical and neuroradiological
abnormalities are already present in neonates followed by an
apparently non-progressive clinical course, indicating that the active
phase of the disease occurs during fetal brain development
(Henneke et al., 2009, 2005). The phenotypic features of human
RNASET2 deficiency are indistinguishable from the sequelae of
in utero cytomegalovirus (CMV) brain infection. Moreover, there is
a significant clinical, biochemical and neuroradiological overlap of
RNASET2-deficient cystic leukoencephalopathy with Aicardi-
Goutières syndrome (AGS) in some affected individuals (Tonduti
et al., 2016). Remarkably, AGS is also an inherited severe
neurologic condition mimicking congenital infection. AGS is
caused by mutations in genes involved in nucleotide metabolism
resulting in an abnormal immune response to endogenous nucleic
acids (Livingston and Crow, 2016). Overall, these results suggest an
involvement of the innate immune system in the disease mechanism
of human RNASET2 deficiency."

**Comment by lschriml** [comment]
Thank you for the new term  !! 
Cheers,
Lynn

**Comment by lschriml** [comment]
Added to the DO: DOID:0081007

Cheers,
Lynn
