### ISSUE TITLE
Bardet-Biedl syndrome numbers

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#976]
There was confusion in the literature with the Bardet-Biedl syndrome numbers.  We have changed some OMIM titles to mitigate the discordancy.

617119 - BARDET-BIEDL SYNDROME 22 (BBS22) due to mutations in IFT74
 	It lists BBS20 as a former title.
619471 - BARDET-BIEDL SYNDROME 20 (BBS20) due to mutations in IFT172
 	This entry is new to OMIM.

**Comment by lschriml** [comment]
Updated in the DO.
