### ISSUE TITLE
NTR for parsley allergy and dill allergy, and 2nd look at celery allergy term.

### ISSUE THREAD

**Issue by ddooley** [DiseaseOntology/HumanDiseaseOntology#978]
First, the definition and the axiom for existing celery allergen example are a bit different.  I suggest 'has allergic trigger' be applied more directly as:

`'celery` allergy' : 'has allergic trigger' some 'part of' some 'Apium graveolens'

So that whatever food product might have celery in it would elicit this? The 'celery vegetable food product' includes primarily celery plant parts - stalk, leaf, root, seed - but not anything that might have celery in it as an ingredient.  Spaghetti sauce isn't listed under that class even if it has some celery seeds in it.  There is a multi-component food product class that is evolving to cover things like that.

P.s FoodOn has a slight update on 'celery vegetable food product' -> it is now called "celery food product'.
_______________________
NTR:
label: parsley allergy
definition: A food allergy triggered by parsley (Petroselinum)
parent: food allergy [or new parent term: food plant allergy]

NTR:
label: dill allergy
definition: a food allergy triggered by dill (Anethum graveolens)
parent: food allergy [or new parent term: food plant allergy]

Note that "vegetable allergy is too narrow a parent for these probably. That's why a new term "food plant allergy" might be a better parent.

**Comment by lschriml** [comment]
Hello Damion,
Thank you for the term definitions. 
   We will review how we are building our axioms with Randi.
For now, I have added the two new terms.

parsley allergy **DOID:0081005**
       parsley food product - FOODON:00002084
dill allergy **DOID:0081006**
      dill food product - FOODON:00001811

Cheers,
Lynn
