### ISSUE TITLE
dextro-looped transposition of the great arteries

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#987]
OMIM has reclassified the dextro-looped transposition of the great arteries (DTGA) series such that types 2 and 3 are no longer in the same series and they have obsoleted the PS#.

DTGA1 is now DTGA, DTGA1 is in as DOID:0060771. The gene mentioned in the definition for DTGA1 in DO has been demoted to an association pending confirmation. 

DTGA2 is now Heterotaxy, visceral, 2, autosomal (605376) - this is currently an xref for visceral heterotaxy (DOID:0050545) along with several other OMIM IDs

DTGA3 is now Congenital heart defects, multiple types, 6 (OMIM:613854, DOID:0060772), in OMIM this includes (as implied by the title) multiple types of heart defects not just DTGA

In DO OMIM:PS608808 is an xref to DOID:0060770

DOID:0060770 also has xrefs to ICD10CM:Q20.3, ORDO:860 

DOID:0060771 also has xrefs to ICD10CM:Q20.3

ORDO:860 has xrefs to OMIM IDs 608808 and 613854

ORDO does not have separate entries for multiple types of DTGA. 

I suggest we retain DTGA1 as is, update DTGA3 to the newer understanding and remove the PS ID from DTGA. I'm torn about obsoleting DTGA1 and just retaining DTGA. If it turns out the gene association is confirmed OMIM may convert DTGA to a gene specific record without changing the title. But looking at the existing annotations in MGI, I think all of the annotations to DTGA1 should be attached to DTGA (will review to make sure and move these if I confirm). I would guess these were missed at some point in the past when OMIM changed DTGA to DTGA1. Assuming the MGI annotations are removed and the OMIM gene association is really removed then there will be nothing to distinguish DTGA from DTGA1. So we may want to obsolete DTGA1 and move the OMIM xref to DTGA.

**Comment by sbello** [comment]
All of he MGI annotations have been moved to the generic parent term

**Comment by lschriml** [comment]
updated as outlined above. 
 retain DTGA1 as is, update DTGA3 to the newer understanding
