### ISSUE TITLE
neurodegeneration review

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#994]
Hello Disease Ontology,

I am reaching out to ask if DO can be updated to include newer terms for neurodegeneration -- such as semantic dementia, primary progressive aphasia, corticobasal degeneration syndrome, and so on.

alice.tang@ucsf.edu
Tue 10/26/2021 6:32 PM

**Comment by Xenbase2** [comment]
Another term we have recently come across that relates (loosely) to this issue is : Organophosphate induced delayed neuropathy, OPIDPN

which might fit as a child of  'inflammatory and toxic neuropathy'

reference:Lotti M, Moretto A. 2005. Organophosphate-induced delayed polyneuropathy. Toxicological Reviews. 24: 37-49. PubMed ID: [16042503](https://www.ncbi.nlm.nih.gov/pubmed/16042503)

-Christna @ Xenbase

**Comment by allenbaron** [comment]
Thank you for the additional recommendation and details.

**Comment by lschriml** [comment]
Review notes, reclassification:

cognitive disorder [DOID:1561]
       dementia. [DOID:1307] 
           **frontotemporal dementia** [DOID:9255] 
           [is_a]        **primary progressive aphasia**     [ORDO:95432]
                                        logopenic variant PPA (lvPPA)/logopenic progressive aphasia (LPA)
                                                    [ORDO:250831]
                                       nonfluent agrammatic PPA (nfaPPA)/progressive non-fluent aphasia (PNFA)
                                                   [ORDO:100070]
                                       semantic variant PPA (svPPA)/**Semantic dementia** (SD)
                                                 (semantic variant of primary progressive aphasia) 
                                                   [ORDO:100069]
          corticobasal degeneration syndrome



            **Primary progressive aphasia (PPA)** is a brain condition that slowly damages parts 
                -               of the brain that control speech and language.
                              People with PPA usually have difficulty speaking, naming objects, or understanding 
                             conversations.
                   - PPA is caused by a loss of tissue (atrophy) in the area of the brain that is responsible for producing language.
                          -- characterized by the predominance and insidious onset of language impairments, and gradual deterioration of these abilities over time, associated with atrophy of the language network of the brain, including frontal, temporal, and parietal regions of the left hemisphere  
 (https://memory.ucsf.edu/sites/memory.ucsf.edu/files/wysiwyg/UCSF%20Dementia%20Patient%20Guides_svPPA_11-3-17.pdf) 

               - GARD:8541
               - https://rarediseases.info.nih.gov/diseases/8541/primary-progressive-aphasia

                        - **Primary progressive aphasia (PPA) is classified into three variants:**
                        logopenic variant PPA (lvPPA)
                        nonfluent agrammatic PPA (nfaPPA)
                          semantic variant PPA (svPPA), 
                                   based on clinical (syndromic) characteristics with support from neuroimaging 
                                   and/or underlying neuropathology
(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6993834/#:~:text=Primary%20progressive%20aphasia%20(PPA)%20is,neuroimaging%20and%2For%20underlying%20neuropathology.)

===========================================================
           
         [is_a]       **- Semantic dementia (SD)** 
                            -  designates a progressive cognitive and language deficit, primarily involving 
                             comprehension of words and related semantic processing
(https://jamanetwork.com/journals/jamaneurology/fullarticle/799806#:~:text=Semantic%20dementia%20(SD)%20designates%20a,fluency%2C%20phonology%2C%20and%20syntax.)

           -  called: semantic variant of primary progressive aphasia
           - 
           - one of the forms of frontotemporal dementia
       




=================================================
         **corticobasal degeneration syndrome**
                   (Corticobasal degeneration (corticobasal syndrome)

- Corticobasal degeneration (CBD) is a form of frontotemporal degeneration, a dementia that involves the loss of cognitive functions such as the ability to think, remember, or reason to the point that it interferes with a person's daily life and activities. 
- CBD primarily affects the cerebral cortex (the outer part of the brain) and the basal ganglia (structures deep within the brain that are involved with movement).
  (https://www.ninds.nih.gov/health-information/disorders/corticobasal-degeneration#:~:text=Corticobasal%20degeneration%20(CBD)%20is%20a,Balance)
- areas of your brain shrink and your nerve cells degenerate and die over time. The disease affects the area of the brain that processes information and brain structures that control movement. This degeneration results in growing difficulty in movement on one or both sides of your body.

- https://rarediseases.org/rare-diseases/corticobasal-degeneration/
- Corticobasal degeneration (CBD) is a rare progressive neurological disorder characterized by cell loss and deterioration of specific areas of the brain. Affected individuals often experience movement disorders initially in one limb that might spread to both the arms and legs. Symptoms include muscle rigidity and the inability to perform purposeful or voluntary movements (apraxia). 

- ORDO:454887, not in GARD
           - Corticobasal syndrome
           - A rare neurologic disease characterized by multifaceted motor system dysfunctions and cognitive defects such as asymmetric rigidity, bradykinesia, limb apraxia, and visuospatial dysfunction.


- Corticobasal degeneration and corticobasal syndrome: A review
- PMID: 34316603

=====================================================

**Comment by lschriml** [comment]
To be reviewed: 
 
Inflammatory Neuropathies. [PMC:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4575885/]

           [DOID:2537] inflammatory and toxic neuropathy
                                       Organophosphate induced delayed neuropathy, OPIDPN
reference:Lotti M, Moretto A. 2005. Organophosphate-induced delayed polyneuropathy. Toxicological Reviews. 24: 37-49. PubMed ID: [16042503](https://www.ncbi.nlm.nih.gov/pubmed/16042503)

**Comment by lschriml** [comment]
Re-classification of frontotemporal dementia [DOID:9255]
   with the addition of new terms: 
           primary progressive aphasia 
                  subtypes:  logopenic progressive aphasia, progressive non-fluent aphasia, ssemantic dementia 
 
        corticobasal degeneration syndrome

**Comment by lschriml** [comment]
Added to the DO: 

                                   Organophosphate induced delayed neuropathy 

reference:Lotti M, Moretto A. 2005. Organophosphate-induced delayed polyneuropathy. Toxicological Reviews. 24: 37-49. PubMed ID: [16042503](https://www.ncbi.nlm.nih.gov/pubmed/16042503)

Organophosphate-induced delayed polyneuropathy (OPIDP) is a rare toxicity resulting from exposure to certain organophosphorus (OP) esters. It is characterised by distal degeneration of some axons of both the peripheral and central nervous systems occurring 1-4 weeks after single or short-term exposures.


OP-induced delayed neuropathy (OPIDN) is a collection of neuropsychological symptoms associated with repeated OP pesticide exposure as well as nerve agent exposure. OPIDN symptoms can appear weeks after OP exposure and include muscle weakness, anxiety, depression, psychosis as well as cognitive and memory deficits.



Although it is usually associated with organophosphorus compounds including nerve agents, several cases have been reported that are possibly related to carbamates.  (Clark 2002; Abou-Donia 2003), is a rare, delayed neurotoxic effect, which occurs 1-5 weeks after severe toxicity from some cholinesterase inhibitors. However, it is not thought to be due to the effects on acetylcholinesterase itself.  (Jamal 1997; Clegg and van Gemert 1999; Jokanovic, Stukalov et al. 2002; Erdman 2004)


https://www.atsdr.cdc.gov/csem/cholinesterase-inhibitors/neuropathy.html

organophosphate induced delayed polyneuropathy
