### ISSUE TITLE
'physical disorder' vs 'congenital disorder'

### ISSUE THREAD

**Issue by mgiglio99** [DiseaseOntology/HumanDiseaseOntology#995]
Hi Lynn,
We are working on a DO slim for use in CFDE. In that process I was looking more closely at 'physical disorder'. I see that it is synonymous with 'congenital disorder'.  And from the history in https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/909, it looks like the term 'physical disorder' existed originally and then all of the congenital disorder terms where made children of 'physical disorder'. 
In the reading I've done, the phrase "physical disorder" seems to be used to encompass things beyond just congenital disorders. I was wondering if you considered using the term label 'congenital disorder' instead of 'physical disorder' for DOID:0080015? It seems like 'congenital disorder' would more closely represent the term as defined.
Thanks,
Michelle

**Comment by lschriml** [comment]
Hello Michelle,
     Do you have a term list so that I create your DO slim ? 
     We will then provide a synced slim file with each DO release. 

    There is a history for this term. 
There was a lengthy discussion with Barry Smith and others from 
the obo foundry regarding 'physical disorder'. 
Definition: A disease that has_material_basis_in a genetic abnormality, error with embryonic development, infection or compromised intrauterine environment.

In disease nomenclature, physical disorder is utilized to distinguish
conditions arising prior to birth, from mental health disorders. 

Our DO clinician team has also reviewed this branch and it's nomenclature, 
and agree that the branch name should be physical disorder. 

Cheers,
Lynn

**Comment by mgiglio99** [comment]
Hi Lynn,
Thanks for the background on the term. I found it confusing because In the reading I've done, physical disorder is used to distinguish things from mental health disorders across all diseases - so things like diabetes and Chrohn's disease were also referred to as physical disorders in publications and websites I was seeing. But of course the clinicians know best.

Regarding the CFDE DO slim, we haven't settled on it yet. Once we do, I'll send it to you.

Thanks,
Michelle
