### ISSUE TITLE
Spelling error in definition for achondrogenesis (DOID:0080043)

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#996]
There's a spelling error (emphasized) in this definition for [DOID:0080043](https://disease-ontology.org/?id=DOID:0080043):

An osteochondrodysplasia that has_material_basis_in deficient endochondral ossification which results_in dwarfism, short-trunk, short-limbed, anascara, **_disaprportionately_** large cranium, and a narrow chest which leads to death in utero or during early neonatal period.

**Comment by lschriml** [comment]
Thank you Allen !! 
Fixed.
